### ISSUE TITLE
"scope & closures": ch5,'Nitty Gritty' example is diffrent from chrome

### ISSUE THREAD

**Issue by cike8899** [getify/You-Dont-Know-JS#1005]
```
function foo() {
	var a = 2;

	function bar() {
		console.log( a ); // 2
	}

	bar();
}

foo();
```
Is this "closure"?

Well, technically... perhaps. But by our what-you-need-to-know definition above... not exactly. I think the most accurate way to explain bar() referencing a is via lexical scope look-up rules, and those rules are only (an important!) part of what closure is.

But I debug this code in chrome as below:

![image](https://cloud.githubusercontent.com/assets/8089971/24787109/f1e0ac8e-1b98-11e7-8618-534653eedcb7.png)

So this code is a closure?

**Comment by getify** [comment]
Academically it's called a closure... but observationally it's not different from lexical scope lookup. closure is the ability for that lexical scope to be preserved even when the function runs elsewhere. I define closure not by academic technicalities but by pragmatic observations.

**Comment by cike8899** [comment]
Thank you very much.
