### ISSUE TITLE
this And Object Prototypes / ch2.md: The bind polyfill cited from MDN will not work in case oThis is undefined

### ISSUE THREAD

**Issue by YeshaS93** [getify/You-Dont-Know-JS#1012]
The current bind polyfill cited from MDN will not work with `new` in case `oThis` is undefined or falsey. This code `this instanceof fNOP && oThis ? this: oThis` will set `this ` to `window` or `global` object when fBound is used with `new` in case` oThis` is undefined / falsey. 

The correct polyfill cited on MDN's bind page replaces this line by `this instanceof fNOP ? this: oThis`. This will work with `new` irrespective of whether `oThis` is truthy or falsey.

**Comment by getify** [comment]
Known issue for second edition.
