### ISSUE TITLE
Async & Performance Chapter 3, Promises Where does the async execution happen in a Promise?

### ISSUE THREAD

**Issue by Cerebrum2** [getify/You-Dont-Know-JS#1015]
The following code snippet is from [Async & Performance Chapter 3](https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md).

I think the comment `// start doing something that could take a while` is misleading:

```javascript
function foo(x) {
	// start doing something that could take a while

	// construct and return a promise
	return new Promise( function(resolve,reject){
		// eventually, call `resolve(..)` or `reject(..)`,
		// which are the resolution callbacks for
		// the promise.
	} );
}

```
If I understood correctly the async code should be inside the function passed to the Promise, no? So the following would be more accurate:

```javascript
function foo(x) {
	// construct and return a promise
	return new Promise( function(resolve,reject){
                // start doing something that could take a while
                // then foo returns the newly created Promise
		// eventually, call `resolve(..)` or `reject(..)`,
		// which are the resolution callbacks for
		// the promise.
	} );
}
```

**Comment by Fov6363** [comment]
you are right;
`function test_1() {
    console.log(`1`);

    return new Promise(function (resolve,reject) {
        console.log(`2`);

        return resolve(100);
    })
}

test_1().then(val => console.log(val)); // 1 2 100`

**Comment by getify** [comment]
This is entirely valid and i've done it many times:

```js
function foo() {
   ajax( "http://some. url", function(resp){
      resolve( resp );
   } );

   var resolve;

   return new Promise( function(res){
      resolve = res;
   } );
} 
```

**Comment by Cerebrum2** [comment]
@getify 
Valid yes, but I believe the following doesn't require another variable and is easier to understand:

```
function foo() {
   return new Promise( function(resolve){
       ajax( "http://some. url", function(resp){
          resolve( resp );
       } );
   } );
} 

```

**Comment by getify** [comment]
There are various reasons you want to "extract" the resolve capability as my snippet showed. I'm only pointing out that it's orthogonal/irrelevant how the actual promise resolving logic ends up getting handled.
