### ISSUE TITLE
You Don't Know JS: Scope & Closures - Chapter 5 - Closure?

### ISSUE THREAD

**Issue by chocomel1** [getify/You-Dont-Know-JS#1021]
Hi, 

Thank you for this book! I'm learning a lot. I had a question regarding closures. I look at the below part and I was wondering whether this is actually a closure? From what I understand, foo is first called, which calls the bar function and passes the baz function as a parameter. Next, baz is called inside the bar function. However, the way I understand it the foo() function has not yet returned as bar is called within the foo function. Therefore, baz would simple obtain the value of variable a from the 'normal scope chain'? I do not see how the concept of closures is needed here. 

> Of course, any of the various ways that functions can be passed around as values, and indeed invoked in other locations, are all examples of observing/exercising closure.

```
function foo() {
	var a = 2;

	function baz() {
		console.log( a ); // 2
	}

	bar( baz );
}

function bar(fn) {
	fn(); // look ma, I saw closure!
}

**Comment by booc0mtaco** [comment]
Some might be led to believe that `bar` would apply its scope to whatever function is passed in, such that calling `foo()` would produced `undefined` in the console. This example demonstrates that scope is defined where the function  `bar` is defined, so we get `2`. 

Does that sound about right?

**Comment by JonMary** [comment]
```function foo() {
	var a = 2;

	function baz() {
		console.log( a ); // 2
	}

	bar( baz );
}
foo();   // <= this is missing in that snippet
function bar(fn) {
	fn(); // look ma, I saw closure!
}
```

**Comment by lalosh** [comment]
@chocomel1 
First you have to know that **foo** or any function doesn't necessarily need to return anything,the moment **foo** called **bar** and passed the parameter **baz** it's over..**foo** finishes here
(BUT its own inner references is not dead yet because of passing **baz** to another function).

so Closure is exercised here because even after **foo** has finished ,yet a reference(**baz**) still have access to **foo** owns variables.

I can explain more through code and i made a little change to the original code to clear it to you.
```js
//another variation to the original code

let external_reference;

function foo() {
	var a = 2;

	function baz() {
		console.log( a ); // 2
	}

    //for later use
    external_reference = baz;
}

function bar(fn) {
	fn(); // look ma, I saw closure!
}

//you have to execute foo at least once 
//to make every reference inside foo living(exist)
foo();

{
    //do some work here
}
// and even here
//..
//..

// then.. whenever you want you still can access whatever was inside of foo 
//because you have a closure of foo kept available via 
//the variable `external_refernce` 
bar(external_reference);
```

**Comment by getify** [comment]
I agree with this thread, no change seems to be needed.

**Comment by chocomel1** [comment]
@lalosh 
I would say that this is a different example though. I agree that your code does include a closure. That is because foo is actually finished the moment you call bar. In my original example, foo is definitely not finished the moment bar is called. Even if there would be no closures, baz would still have access to "var a = 2" through the scope chain I would say? 

```
function foo() {
	var a = 2;

	function baz() {
		console.log( a ); // 2
	}
console.log ("Starting up bar!")
	bar( baz );
console.log("I'm foo and I am not finished yet") // this will still print because foo has not yet returned after bar is called.
}

function bar(fn) {
	fn(); // look ma, I saw closure!
}
```
