### ISSUE TITLE
JS engine parts, scope and cluser chapter 2

### ISSUE THREAD

**Issue by PouriaParhami** [getify/You-Dont-Know-JS#1032]
Hello
Tnx for your great book
God blessed you
Sorry for my poor english, but i have a question, scope and compiler is part of js engine or they are 3 Separate part one part engine one part compiler and one part scope ?
Because we have conversation between engine compiler and scope, and you say compiler one on friends engine, that mean one part of engine or compiler is separate part of engine ?

**Comment by legodude17** [comment]
AFAIK, most engines have compilers and scope trackers built in

**Comment by getify** [comment]
Collectively, all these are parts of the JS engine (like v8, SpiderMonkey, etc). They don't really have official names, per se, just informal ways to refer to different parts.
