### ISSUE TITLE
Translate to Chinese

### ISSUE THREAD

**Issue by haitaoxin** [getify/You-Dont-Know-JS#1033]
Hi Kyle,

Among a dozen of JS books I read, your series is undoubtedly the best. I would like to know if you are OK that I translate them into Chinese, and post them on github as you do. So that many many JS developers in China can also benefit from them.

Anyway, thank you so much for sharing your knowledge with us!

**Comment by getify** [comment]
Already done: https://github.com/getify/You-Dont-Know-JS/tree/1ed-zh-CN
