### ISSUE TITLE
Chapter 2 Up and Going Nested Scopes example (regarding commenting)

### ISSUE THREAD

**Issue by tchan** [getify/You-Dont-Know-JS#1036]
In the third example of Nested Scopes the comment at  the end is 
`// 5 7 9`

```
function foo() {
	var a = 1;

	if (a >= 1) {
		let b = 2;

		while (b < 5) {
			let c = b * 2;
			b++;

			console.log( a + c );
		}
	}
}

foo();
// 5 7 9
```

However, for clarity, do you think it would be better for newcomers if it was commented like this
```
// 5
// 7
// 9 
```
Which is what actually happens in the console as it runs through the loop. I think it would make more sense this way as it could not be strikingly obvious to people who are just getting started with programming. Especially since it's being introduced quite early in the series. This way, it would align more with their mental model of what happens in a while loop if they're familiar with that concept. It's a minor thing, I know, but would love to hear opinions.

**Comment by jonathanobiegba** [comment]
That's true. Commenting each output(5, 7, 9)separately will help learners appreciate them as unique iterations which they are.

**Comment by tchan** [comment]
Also for consistency as on this page has this code snippet
https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch1.md#why-this

```
function foo(num) {
	console.log( "foo: " + num );

	// keep track of how many times `foo` is called
	this.count++;
}

foo.count = 0;

var i;

for (i=0; i<10; i++) {
	if (i > 5) {
		foo( i );
	}
}
// foo: 6
// foo: 7
// foo: 8
// foo: 9

// how many times was `foo` called?
console.log( foo.count ); // 0 -- WTF?
```

**Comment by getify** [comment]
Yeah, this was really just saving space in the code snippets. Something to perhaps consider for a future update. Thanks!
