### ISSUE TITLE
Hoisting example code snippet error

### ISSUE THREAD

**Issue by tchan** [getify/You-Dont-Know-JS#1044]
https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch4.md
```foo(); // "b"

var a = true;
if (a) {
   function foo() { console.log( "a" ); }
}
else {
   function foo() { console.log( "b" ); }
}
```
I'm getting a Type error when I run this code in Chrome dev tools.

You've also written 
 `However, it's important to note that this behavior is not reliable and is subject to change in future versions of JavaScript, so it's probably best to avoid declaring functions in blocks.` 

I'm assuming this behaviour has now been changed? Would appreciate any clarification.

**Comment by nishutosh** [comment]
yes its showing error even on this
```javascript
foo();
{
   function foo() { 
    console.log( "a" ); }
}
```
i mean functions does not have block scope, then why is this happening?

**Comment by venelinpetrov** [comment]
Well, I don't get error when I paste the same code in Chrome DevTools. What exactly is the error message and which version of Chrome do you run?

**Comment by nishutosh** [comment]
hey @venelinpetrov 
i am running the latest version for windows, thats 59.0 and i get a type error

try  this out
```javascript
func(); {
    function func() {
        console.log("s")
    }
}
```
does this snippet gives error in your console?

**Comment by venelinpetrov** [comment]
Of course.

**Comment by Spike-Leung** [comment]
Hi, i read this chapter recently, also got confused by this snippet.
`foo(); //  "b"  

var a = true;
if (a) {
   function foo() { console.log( "a" ); }
}
else {
   function foo() { console.log( "b" ); }
}`
the chapter says `foo()` should output 'b', but i run the snippet, it get a Type error or if i run in strict mode , it get a Reference error.  I run in the newest chrome , and also run in node.js, get the same error.

**Comment by akshayvinchurkar** [comment]
@Spike-Leung i am getting "foo is not function error" maybe its because foo() function definition is in if block that maybe create some kind of scope because in this case function definition is dependant on condition. condition is simple but we calling foo outside of the if block not in if blockyou have to call it inside of if block.
