### ISSUE TITLE
Specify strict mode semantics in Scope and Closures Appendix C

### ISSUE THREAD

**Issue by tomkel** [getify/You-Dont-Know-JS#1050]
```
var obj = {
	id: "awesome",
	cool: function coolFn() {
		console.log( this.id );
	}
};

var id = "not awesome";

obj.cool(); // awesome

setTimeout( obj.cool, 100 ); // not awesome
```
Not awesome is printed in non-strict mode.

In strict mode, `setTimeout( obj.cool, 100 );` will print out `undefined`.

This should definitely be clarified to not confuse beginners, we don't want to teach them ES3 semantics.

Great example though, learned something new.

**Comment by getify** [comment]
The behavior of `this` for `setTimeout(..)` invoked functions is controlled by the web platform spec, not JS... and it specifies that it's always the global object, regardless of strict mode.  As such, `"not awesome"` will print regardless of strict mode. I just re-verified this myself.

**Comment by tomkel** [comment]
I see, thanks for clarifying. Maybe you could add
> the web platform spec dictates that `this` is set to the global object in `setTimeout`


Also in node, `undefined` is printed instead of `not awesome`. any idea why?

**Comment by getify** [comment]
Yes node.js, in more places than just this one, willfully diverges from the web platform spec, causing headaches for us all.
