### ISSUE TITLE
Syntax error in Scope and Closures Chapter 5

### ISSUE THREAD

**Issue by tomkel** [getify/You-Dont-Know-JS#1051]
bar.js
```
function hello(who) {
	return "Let me introduce: " + who;
}

export hello;
```
foo.js
```
import hello from "bar";
```
should be 
```
import { hello } from "bar";
```

Without the curly braces, javascript tries to import the default export of bar, of which there is none.

**Comment by getify** [comment]
This syntax changed in the spec after the time of writing, and it's already queued up for being fixed in second edition. Thanks.
