### ISSUE TITLE
object.asign copy

### ISSUE THREAD

**Issue by MAYDAY1993** [getify/You-Dont-Know-JS#1072]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).
at Object chapter 3.3.4 copy object,I run this following the book's code ,but it turned out "obj2.b===arr false",I'm wondering why,thanks
![image](https://user-images.githubusercontent.com/14831051/27679461-63e0da28-5ceb-11e7-9e30-e122840aae66.png)

**Comment by santeron** [comment]
Hey mate. You define the `var obj` twice, essentially losing the reference to the initial object `{c: true}`.

When you compare `obj2.b` with `obj`, you're actually trying to compare it with the second reference which is of course a different object.

If you use a different name for either of your assignments, your expectation will be true.

```
function func() {
}

// this object is named firstObj
var firstObj = {
    c:true
}

var arr = [];

// this object is named secondObj, which will not overwrite the firstObj reference
var secondObj = {
    a:2,
    b:firstObj,
    c:arr,
    d:func
}

var obj2 = Object.assign({}, secondObj);

obj2.b === firstObj;
true
```

**Comment by MAYDAY1993** [comment]
@santeron oh,thank you ,my naming fault😄
