### ISSUE TITLE
Korean translation suggestion

### ISSUE THREAD

**Issue by COCOLMAN** [getify/You-Dont-Know-JS#1076]
I think the contents of YDKJS are very good.

I would like to translate this content for Korean users.
I will do not claim any benefit or rights.

I just want to give more information to people using  both Korean and javascript.

If the owner agrees, and if this is possible, I would like to talk more about this.

**Comment by himaeng** [comment]
This is the thing that Thai people like me would like to do so. 
Waiting for author reply.

**Comment by COCOLMAN** [comment]
Yes.
I think it will be a great help for users who are not familiar with English and who mainly use other languages.
Thank you for asserting my opinion. I think multilingual support will be helpful for Thai people too. thanks. @himaeng

**Comment by porcokang** [comment]
👍

**Comment by getify** [comment]
Please see these threads for info on how to properly handle foreign language translations:

https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3A%22foreign%20language%20translations%22%20
