### ISSUE TITLE
Expression Side Effects -  wrong assumption regarding json and console

### ISSUE THREAD

**Issue by bumbeishvili** [getify/You-Dont-Know-JS#1081]
Right now I am reading Grammar chapter -  [contextual rules](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch5.md#contextual-rules) and It says
![assumption](https://user-images.githubusercontent.com/6873202/27858354-fb054332-6185-11e7-8ce6-317623e41dac.png)

So , I have tried in chrome console and did not got error
![result](https://user-images.githubusercontent.com/6873202/27858479-7126b79e-6186-11e7-95af-4f6907412556.png)

**Comment by Ryalian** [comment]
Not the case in Firefox though. Chrome might have changed the way it reads it.

**Comment by bumbeishvili** [comment]
I also think so

**Comment by nishutosh** [comment]
yes you are right @Ryalian. So what happens here is when you when you type
```javascript
{ a : 3 }  //or { "a" : 3 }
``` 

crome will treat it as an object but when you do

```javascript
{ a : 5 ; } //semicolen added at the end of 5
```
then crome will treat it as a js expression. So
```javascript
{ "a" : 5 ; } //error
```
thats it

**Comment by getify** [comment]
Chrome does all kinds of tricky stuff in the name of trying to be clever for developers, but mostly I just find that it makes developers who are trying to really learn JS frustrated when it doesn't quite work the same. :(
