### ISSUE TITLE
this & Object Prototypes, ch2 softBind works differently in Node.

### ISSUE THREAD

**Issue by Hobinx** [getify/You-Dont-Know-JS#1083]
```javascript
function foo() {
  console.log("name: " + this.name);
}

var obj = { name: "obj" },
    obj2 = { name: "obj2" },
    obj3 = { name: "obj3" };

obj2.foo = foo.softBind(obj);

setTimeout(obj2.foo, 10);
```
The `setTimeout` in browser outputs `name: "obj"`. However, `setTimeout` in Node bind the callback to a timer object, it outputs `name: undefined`. 
I think some explanation about it can avoid confusion and save the readers some time to track the different output.

**Comment by getify** [comment]
'softbind' works the same in any environment. Node's 'setTimeout' wilfully violates the 'this' behavior required by the web spec and thus observed in browsers.

**Comment by Hobinx** [comment]
People test this code in Node's repl just get confused result, a note about this different result will hopefully save them some time to find out the reason of it.

**Comment by getify** [comment]
It's difficult for me to accurately document node (as it changes). I understand the confusion, but really I think it's node's job to either do a better job of conforming to common expectations, or at least do a better job documenting their divergences.
