### ISSUE TITLE
Up & Going , CH2: into JavaScript (Defining variables with non-English letters)

### ISSUE THREAD

**Issue by mohamedabbasos** [getify/You-Dont-Know-JS#1087]
> An identifier must start with a-z, A-Z, $, or _. It can then contain any of those characters plus the numerals 0-9.

This is a quote form chapter 2, Up & Going book. in JavaScript we can define variables with a non-English letters.

Example: _Arabic letter_

```
var س = 5;
alert(س); 
// This will alert with a value 5
```

A lot of examples and the detailed rules will be found in this link:
[Valid JavaScript variable names in ECMAScript 5](https://mathiasbynens.be/notes/javascript-identifiers)

**Comment by getify** [comment]
Yes, I deliberately left these complications out of the discussion for the beginner book. I could have said something like "There's more rules than this" but then it just looks hand wavy and can be frustrating if a reader thinks they aren't being told the whole picture.
