### ISSUE TITLE
Variable Hoisting example within the Function Scopes section of up & going won't work 

### ISSUE THREAD

**Issue by lmuzquiz** [getify/You-Dont-Know-JS#1092]
On location 827 (kindle edition) of your up & going, you have variable hoisting example, very much like this one. But i don't think it works. I already tried running the code using ECMAScript 6 interpreter on webstorm and i get the error:  **a is not defined**

```
hoisted();
function hoisted() {
    a = 3; 
    console.log(a);
    var a;
}
```

**Comment by winar-jin** [comment]
because you have declared the variable a  in the function scope line 3, that will hoisted variable a in this function scope and make variable a a local variable  instead of a global variable. so you will get undefined error outside the function.  if you remove the line 3"var a;" that will works.

**Comment by nishutosh** [comment]
its working fine in crome browser console. I don't find any reason that it would not work. Its a correct example of hoisting.

**Comment by getify** [comment]
If you drop the whole snippet into a program (or console), it should work. If you type it in one line at a time, each line will likely be executed right away, meaning it would defeat the "hoisting" characteristics of compiling all lines of code before execution.

**Comment by lmuzquiz** [comment]
Thanks. Let me double check and ill get back to you.

**Comment by getify** [comment]
Closing for now, seems like this works fine.
