### ISSUE TITLE
typo(there should be 'a' instead of 'k')

### ISSUE THREAD

**Issue by rahulbhadhoriya** [getify/You-Dont-Know-JS#1094]
hi,
in chapter no. 5: Prototypes of this & Object Prototypes book 
there is a 3rd example like this 
var anotherObject = {
	a: 2
};

// create an object linked to `anotherObject`
var myObject = Object.create( anotherObject );

for (var k in myObject) {
	console.log("found: " + k);
}
// found: a

("a" in myObject); // true

**but it should be like**
var anotherObject = {
	a: 2
};

// create an object linked to `anotherObject`
var myObject = Object.create( anotherObject );

for (var a in myObject) {
	console.log("found: " + a);
}
// found: a

("a" in myObject); // true

**Comment by Ryalian** [comment]
I think it doesn't matter what the variable called in for loop, it's not an
typo. But using a everywhere is very massy.

In for..in loop it returns key names of the object which is 'a' in this
example.

In your code, it only change from:
      "a variable call k holds the value of 'a'"
to:
      "a variable call a holds the value of 'a'"
which a beginner reader may be confused.

Bests,

Qijun Chen

**Comment by ariyankhan** [comment]
@rahulbhadhoriya 
It doesn't matter what u named a variable, it is not any typo or any error.

**Comment by getify** [comment]
It's intentionally named `k` because that stands for "key".

**Comment by rahulbhadhoriya** [comment]
my bad !
