### ISSUE TITLE
Missing word in ch3, 'Scopes & Closures'

### ISSUE THREAD

**Issue by danedavid** [getify/You-Dont-Know-JS#1095]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).    
  In file ch3.md of 'scopes & closures', on line 444:
It is currently
>In Chapter 4, we will address hoisting,...

...could be..
>In Chapter 4, we will see address hoisting,

**Comment by getify** [comment]
address here is a verb (not a noun), meaning to deal with or discuss. not a typo to not have "see".

**Comment by danedavid** [comment]
My bad.. I thought we were gonna talk about 'address hoisting'. Sorry!
