### ISSUE TITLE
Error on evaluating the return value of logical operator &&

### ISSUE THREAD

**Issue by hijiangtao** [getify/You-Dont-Know-JS#1103]
Thanks for your great effort in contributing these great series of books for JavaScript community, I learned a lot from them. However, I was a little confused when I read the part about **# Chapter 4: Coercion** of book **You Don't Know JS: Types & Grammar**. I wrote them down and raised a PR at #1102

According to descriptions about Logical Operators in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators), we have following rules on the return value of Logical AND (&&)

> Operator: Logical AND (&&)
> Usage: expr1&&expr2
> Description: Returns expr1 if it can be converted to false; otherwise, returns expr2. Thus, when used with Boolean values, && returns true if both operands are true; otherwise, returns false.

We can get that the first `it` in desription refers to `expr1` exactly, not the expression `expr1&&expr2` itself, but the content in Chapter [Operators || and &&](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch4.md#operators--and-) describes the return value of `&&` as follows:

> Inversely, for the `&&` operator, if the test is `true`, the `&&` expression results in the value of the *second operand* (`b`). If the test is `false`, the `&&` expression results in the value of the *first operand* (`a` or `c`).

I think this may be an obvious mistake, a simple example against this is `100 && false` will return `false` as result. So the `test` in the reference should be *first operand* instead.

I first thought about modifying `test` to `first operand` only, however, I found the following sentence can express a better idea than current sentence, which is 

**Inversely, for the `&&` operator, if *first operand* can be converted to false, the `&&` expression results in the value of it (`a` or `c`). Otherwise, the `&&` expression results in the value of the *second operand* (`b`).**

instead of 

> Inversely, for the `&&` operator, if the test is `true`, the `&&` expression results in the value of the *second operand* (`b`). If the test is `false`, the `&&` expression results in the value of the *first operand* (`a` or `c`).

Best.

**Comment by hijiangtao** [comment]
The same error can be found in the chinese translation version. I can raise another PR for chinese translation version if you confirm the mistake. :-)

**Comment by getify** [comment]
Quoting from two paragraphs earlier in the text:

> Both || and && operators perform a boolean test on the first operand (a or c).

In those subsequent paragraphs, "test" clearly then is referring to "first operand".
