### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by javaherian** [getify/You-Dont-Know-JS#1104]
> Please feel free to contribute to the quality of this content by submitting PR's for improvements to code snippets, 

> submitting PR's 

> PR's

No apostrophe here.

**Comment by getify** [comment]
Eh. I like to use PR's instead of PRs.

**Comment by javaherian** [comment]
Well it's grammatically incorrect.

**Comment by getify** [comment]
Can't tell if you got the joke or not (thinking maybe not)...

But in any case, I remember way back in my schooling when it was acceptable to use ' in pluralized abbreviations. I'm aware that modern style guides recommend against it, but they also recommend an apostrophe if using periods in the abbreviation, or if it's a single character (letter, number). I find that strange that there's inconsistency there, so I have just preferred to stick to using apostrophes.

At worst, I don't think "grammatically incorrect" is entirely accurate. For one, it's merely a choice not to follow a common grammatical style recommendation, not a hard and fast rule like spelling or trailing quotation punctuation. But for another, it's just an informal README, not the book text itself.

**Comment by javaherian** [comment]
Its fine, I guess error's in readme's are acceptable nowaday's.

**Comment by javaherian** [comment]
Actually I think you might be somewhat correct: https://english.stackexchange.com/questions/55970/plurals-of-acronyms-letters-numbers-use-an-apostrophe-or-not

**Comment by javaherian** [comment]
My bad
