### ISSUE TITLE
ES6 & Beyond (Chapter 2): Clarification on strings and Iterables

### ISSUE THREAD

**Issue by awareness481** [getify/You-Dont-Know-JS#1107]
## Text from ch2:
> Recall from the "for..of Loops" section earlier in this chapter that ES6 strings have built-in iterators

This is technically false, as strings do not have built-in iterables.
## From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Distinction_between_string_primitives_and_String_objects):
> In contexts where a method is to be invoked on a primitive string or a property lookup occurs, JavaScript will automatically wrap the string primitive and call the method or perform the property lookup.

This could have been purposefully omitted to not convolute the reader with more details. However, if that's not the case then I think the text should be changed to more accurately reflect what's happening. I propose the following suggestions.

### Suggestion #.1
> Recall from the "for..of Loops" section earlier in this chapter that ES6 ~strings~ Strings have built-in iterators    

The capitalization suggests that we're talking about String objects and not string primitives. If that's not sufficient, a more verbose change could be added.

### Suggestion #.2
> Recall from the "for..of Loops" section earlier in this chapter that **invoking a method on a primitive string automatically converts the string primitive in a String object and calls the specified method. As mentioned earlier Strings are built-in iterables.**
(added text is in bold)

I'm not sure if the suggested changes are too pedantic, but I think it's worth having a discussion about whether the changes would be beneficial for the readers.

#### Helpful MDN links
* [JavaScript/Reference/Global_Objects/String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Distinction_between_string_primitives_and_String_objects)
* [JavaScript/Reference/Iteration_protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#Built-in_iterables)

**Comment by getify** [comment]
I have a whole book in the series that (in part) covers the nuance of boxing (the casting of a primitive to its object wrapper). At this point of the book series, I expect readers to have a grasp on that, so I intentionally didn't clutter the narrative here.

**Comment by awareness481** [comment]
Thanks a lot for taking the time to respond.
