### ISSUE TITLE
Vietnamese translation permission.

### ISSUE THREAD

**Issue by jarvisluong** [getify/You-Dont-Know-JS#1108]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

Hello, I'm a fan of your book and this can greatly help JS community in Vietnam. However, there is a large percentage of Vietnamese who are not able to read in English. I also noticed the license of this repo, it is CC BY-NC-ND 4.0, which I can't share my own translation version if I make one. I'd like to get a permission from you to make a Vietnamese translation of this book because I think the freedom of studying should be provided for everyone, regardless of nationalities, languages, ...

I promise the translation work will only be for the educational purpose and remain the originality from yours.

I would love to hearing from you soon!

**Comment by getify** [comment]
Please see these threads:

https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3A%22foreign%20language%20translations%22%20

Specifically: https://github.com/getify/You-Dont-Know-JS/issues/9#issuecomment-37836191

Especially look at how the current Chinese translation has been handled.
