### ISSUE TITLE
Function hoisting has changed as of chrome 49

### ISSUE THREAD

**Issue by sandrosc** [getify/You-Dont-Know-JS#1109]
In [chapter 4 of scope and closures](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch4.md) the following example (and comment) can be found:

```
foo(); // "b"

var a = true;
if (a) {
   function foo() { console.log( "a" ); }
}
else {
   function foo() { console.log( "b" ); }
}
```
> However, it's important to note that this behavior is not reliable and is subject to change in future versions of JavaScript, so it's probably best to avoid declaring functions in blocks.

Now the hoisting behavior (at least in chrome) [changed](https://stackoverflow.com/questions/36205624/hoisting-behavior-changed-between-chrome-48-and-49?noredirect=1&lq=1) and the example throws a TypeError.
The question is whether the example should be changed now.

**Comment by getify** [comment]
This is a known issue to address for second edition.
