### ISSUE TITLE
Branch 1ed-zh-CN ES6与未来 - 第二章：语法

### ISSUE THREAD

**Issue by zhaoxieluoke** [getify/You-Dont-Know-JS#1113]
First ,thank you all.
This series of books are awesome.I have already read most of them.
But I may find a problem in Branch 1ed-zh-CN / es6 & beyond / ch2.md , I think It is a conceptual problem, this
line 640-----在{ x: aa, y: bb }这一行中，x和y代表对象属性。在{ x: AA, y: BB }这一行，x和y 也 代表对象属性。-----
should change to
-----在{ x: aa, y: bb }这一行中，x和y代表对象属性。在{ x: AA, y: BB }这一行，AA和BB 也 代表对象属性。-----
we always console the target not the source (我们打印的是属性名,而不是属性值 对么? Maybe I am wrong, forgive me ,I am a tiro)

**Comment by JoeHetfield** [comment]
Please refer the comment I left in your PR
