### ISSUE TITLE
`writable:false` is used instead of `writable:true` in "this & Object Prototypes" chapter 5.

### ISSUE THREAD

**Issue by jressey** [getify/You-Dont-Know-JS#1122]
1. If a normal data accessor (see Chapter 3) property named `foo` is found anywhere higher on the `[[Prototype]]` chain, **and it's not marked as read-only (`writable:false`)** then a new property called `foo` is added directly to `myObject`, resulting in a **shadowed property**.

I believe the intention was to use `writable:true`.

**Comment by getify** [comment]
Nope. This is a known issue. Please search closed issues for explanation.
