### ISSUE TITLE
In timeoutify example when will returned function execute ?

### ISSUE THREAD

**Issue by nakshay** [getify/You-Dont-Know-JS#1123]
function timeoutify(fn,delay) {
	var intv = setTimeout( function(){
			intv = null;
			fn( new Error( "Timeout!" ) );
		}, delay )
	;

	return function() {
		// timeout hasn't happened yet?
		if (intv) {
			clearTimeout( intv );
			fn.apply( this, [ null ].concat( [].slice.call( arguments ) ) );
		}
	};}

In above example of Callbacks chapter when will the returned function will execute, I see only setTimeout will be called since there is no call made to function returned by timeoutity.
Am I missing anything, or this example is just a pseudocode.

**Comment by getify** [comment]
The returned function isn't shown to be called, but could be called if you wanted it to. If you call it before the timeout, it short-circuits to cancel the timeout and runs the function right away. If not, the function is called with an error indicating it was timed-out.

**Comment by nakshay** [comment]
Okay, makes sense. Thanks.
