### ISSUE TITLE
Labeled statements need a colon followed by a pair of curly braces

### ISSUE THREAD

**Issue by tzeikob** [getify/You-Dont-Know-JS#1124]
After reading the part [Labels](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch5.md#labels) in Types and Grammar book I'm now a little bit confused. It's written that the following syntax it is not treated by JS as a standalone object literal but instead as a labeled statement,

```
{
   foo: bar()
}
```
but I double checked it in the REPL (node.js) and the developer console and both return an object, not actually the value of the last statement within the block. Correct me if I'm wrong, but the use of a colon within a curly braces pair intended for property creation in object literals. I thing it's more appropriate to write this,

```
foo: {
   bar();
}
```
or something like this,

```
foo: bar();
```
```
{
  foo: {
   bar();
  }
}
```
As I'm new to JS community may my assumption is not accurate at all.

PS: Not to mention, you've done a great job with this series.

**Comment by getify** [comment]
The devtools console and node REPL both "fake" their parsing for common use cases like objects (and JSON)... in essence, they pre-parse to see if it's more "data" like, and if so, assume that's what you wanted.

If you just put the code in question in a JS file and run it (in browser or in node), you'll see a syntax parsing error.

**Comment by tzeikob** [comment]
I've tested the code below both in an external file as well as in an inline script tag in the latest version of chrome,
```
function bar() {
  console.log('hooray');
}

{
  foo: bar()
}
```
and neither threw any syntax or parsing error, instead only the text in question printed out. That actually doesn't prove that the second block is treated as a standalone object, as it is not possible to get the type of this code just by using the `typeof` operator. I suppose that internally the JS engine seeing this as a standalone block with a labeled statement.

**Comment by getify** [comment]
Sorry I misunderstood... I was thinking of the example of valid JSON where you have to quote the property name... THAT is invalid syntax as labels cannot be quoted.

In your case, you could "prove" it's a block and not an object by putting a semicolon after 'foo()'... valid in blocks, invalid in object literals.

**Comment by getify** [comment]
foo: bar();

**Comment by tzeikob** [comment]
Now it's pretty clear to me, either using a semicolon or adding quotes around the label proves the assumption, that is a label statement and not a standalone object literal.
