### ISSUE TITLE
Chapter 1, functions in dev tools

### ISSUE THREAD

**Issue by chrisdemars** [getify/You-Dont-Know-JS#1126]
I would like to add that when writing a function in the dev tools, the newer versions know when you are opening and closing the function, so there is no need to press `shift` + `enter` for a new line. It also indents for you as well.

**Comment by getify** [comment]
hmm that's a cool feature. thanks!

**Comment by chrisdemars** [comment]
Can I add it for chapter 1 @getify ?

**Comment by getify** [comment]
Feel free to send a PR but we'll queue it up to consider for second edition. Thanks!
