### ISSUE TITLE
Microsoft detecting history.js as Severe Trojan threat connected with Scamware

### ISSUE THREAD

**Issue by etherwar** [getify/You-Dont-Know-JS#1127]
Pretty much the title.

Here's the [link](https://virustotal.com/#/file/5cd2c5d2eb15ede6d1afbfbf86d64ef9a42b9b6470fab2034fcdcec490cfab6c/detection) to the VirusTotal summary. Seems like a false positive, but at least on my system I can't even get Microsoft Defender to leave it alone, I've added it to exclusions and it keeps disappearing. I don't know if there's a process to get this added as a false positive, or if the code itself does have issues and may need to be tweaked, but it would be nice if someone that knows more than me could chime in on what may be going on here.

My best guess is that this code was repurposed by someone with bad intentions, and the hash of the file got added to Microsoft's s--- list. However, since the code is uglified/minified and my JS is rusty (hence me having this course on my to-do list), I lack the ability to check into it myself.

Thanks for any help,
-E

**Comment by getify** [comment]
what is the reason for posting this question here?

**Comment by etherwar** [comment]
My apologies for the ommission. The file in question is history.js, which is located at:

`You-Dont-Know-JS/kickstarter-survey-site/web/js/external/history.js `

and as a part of this project, I figured it would pertain to at least those few Windows users that may clone the repo. If I'm mistaken, I apologize in advance.

**Comment by getify** [comment]
Oh I see. I'll just delete that whole directory since that site is no longer relevant.
