### ISSUE TITLE
Ch 3 - Scopes and Closures, mistake with an example

### ISSUE THREAD

**Issue by Coder-Mustafa** [getify/You-Dont-Know-JS#1130]
> var a = 2;
> (function IIFE(){
>         var a = 3;
> 	console.log( a ); // 3
> })();
> console.log( a ); // 2

There's a slight variation on the traditional IIFE form, which some prefer: (function(){ .. }()). Look closely to see the difference. In the first form, the function expression is wrapped in ( ), and then the invoking () pair is on the outside right after it. **In the second form, the invoking () pair is moved to the inside of the outer ( ) wrapping pair.**

## while reading your book which is very nice, Thank you for such a nice study material. I found one error which is a mistake w.r.t the explanation you have given  .

the example of IIFE according to your explanation must be 
>var a = 2;
> (function IIFE(){
>         var a = 3;
> 	console.log( a ); // 3
> }());
> console.log( a );//2

**Comment by AndrewLosikhin** [comment]
Both variants are possible and traditional. Where's mistake?
