### ISSUE TITLE
"scope & closures": Foreword missing

### ISSUE THREAD

**Issue by Akronix** [getify/You-Dont-Know-JS#1134]
Is there any reason of why the foreword for the second book: "scope & closures"  is missing?
Yes, I know it can be found [here](https://shanehudson.net/2014/06/03/foreword-dont-know-js/), but I'd expect a markdown file in the repo as in the rest of the books.

**Comment by getify** [comment]
It was requested by the writer of the Foreword.

**Comment by Akronix** [comment]
Oh, OK. I didn't read it anywhere, so I didn't know.
Nothing else to do here, I guess.
