### ISSUE TITLE
Link to Rick Waldron in README

### ISSUE THREAD

**Issue by ShalokShalom** [getify/You-Dont-Know-JS#1135]
redirects into the infinity here

**Comment by getify** [comment]
hmmmm... the two links I just checked on this repo (one to his bocoup page and one to his twitter) work fine. Can you point to which exact page has the broken link and/or what the link is that's bad?

**Comment by ShalokShalom** [comment]
I mixed this dir with the main: https://github.com/getify/You-Dont-Know-JS/tree/master/es6%20%26%20beyond

**Comment by getify** [comment]
The link in that page is:

https://bocoup.com/about/bocouper/rick-waldron/

And it works fine for me in my browser. Not sure what's going on for you. Can you copy-n-paste it?

**Comment by ShalokShalom** [comment]
Hnn, now its working. I got "to many redirections" before in Opera.
