### ISSUE TITLE
this & object prototypes - ch4 - building example - some misunderstanding of architect

### ISSUE THREAD

**Issue by kevinaskin** [getify/You-Dont-Know-JS#1136]
`
An architect plans out all the characteristics of a building: how wide, how tall, how many windows and in what locations, even what type of material to use for the walls and roof. She doesn't necessarily care, at this point, where the building will be built, nor does she care how many copies of that building will be built.
`

**She doesn't necessarily care, at this point, where the building will be built, nor does she care how many copies of that building will be built.**

actually, it is not right at all. For a good architect, he is supposed to be aware of THE CONTEXT of the building, including `location`, `climate`, even local `cultures`.And after fully consideration can he make a suitable solution of the BUILDING DESIGN.

**Comment by getify** [comment]
While that's likely true in the context of actual buildings I'm not sure it makes any difference to the point being made with the metaphor.

**Comment by kevinaskin** [comment]
thank you for your answer.
PS: your book is really a good guider for me on the way of javascript !
