### ISSUE TITLE
scope & closures例子无法运行(中文版p41)

### ISSUE THREAD

**Issue by 123456zzz** [getify/You-Dont-Know-JS#1138]
![j t99 m j1 lu5 q r8](https://user-images.githubusercontent.com/26499018/30247417-cfba5fdc-9646-11e7-8876-814df18016b6.png)

**Comment by 123456zzz** [comment]
![image](https://user-images.githubusercontent.com/26499018/30248236-63fd64d2-9656-11e7-8165-84ee725f98eb.png)
上面的结果说明了变量声明可以忽略条件逻辑提升，但是函数声明好像不行。

**Comment by Ryalian** [comment]
你要在纯净的js环境里面运行，console和node都是包装过的环境

**Comment by 123456zzz** [comment]
get it,thanks.

**Comment by 123456zzz** [comment]
但是怎么使用js纯净的环境

**Comment by Ryalian** [comment]
最简单的方法就像平常在网页运行JS一样，写进js文件然后放到html页里读取，这样就能保证js引擎能以正确的规则来运行

**Comment by 123456zzz** [comment]
知道了。十分感谢，这个问题卡了好几天

**Comment by 123456zzz** [comment]
刚试过你的方法，然后依然会报错（foo is not a function）.emmm,这个和环境好像没什么关系。

**Comment by JoeHetfield** [comment]
请注意后面一段话：

> 然而，重要的是要注意这种行为是不可靠的，而且是未来版本的 JavaScript 将要改变的对象，所以避免在块儿中声明函数可能是最好的做法。

首先，这种做法不是标准的，在任何情况下我们都应当避免在 if 语句内部声明函数。另外，这个例子应该是 Kyle 在 2015 年（也许更早）编写的，而 “未来版本的 JavaScript” 已经內建在你现在的浏览器中了。如果你想要看到和这个例子相同的输出，可以使用 IE，在开发者控制台中将浏览器内核的版本设置为 IE9 或更早的版本，就应该可以看到了。你也可以在设置为 IE10 或 11，看看有什么不同。

**Comment by Ryalian** [comment]
是的，原文也说这种语法是不可靠的，有可能会被改变掉

详情请看：
https://github.com/getify/You-Dont-Know-JS/blob/1ed-zh-CN/scope%20%26%20closures/ch4.md

**Comment by 123456zzz** [comment]
嗯嗯，感谢你们的解答
