### ISSUE TITLE
Google's Traceur demo URL does not work anymore

### ISSUE THREAD

**Issue by jesusabarca** [getify/You-Dont-Know-JS#1140]
Hi, thank you very much for this book series. I feel like I'm learning JS at last!

I followed the link for Google's Traceur demo in the Appendix B of the Scopes & Closures book, but the link is no longer working (http://traceur-compiler.googlecode.com/git/demo/repl.html). Seems like it has been moved to http://google.github.io/traceur-compiler/demo/repl.html

Let me know if I should create the PR :)

**Comment by cdtapay** [comment]
Go ahead good man, that's the idea :)

**Comment by cdtapay** [comment]
Just created a pull request for this: https://github.com/getify/You-Dont-Know-JS/pull/1146
