### ISSUE TITLE
this & object prototypes chapter 2

### ISSUE THREAD

**Issue by lucymonie** [getify/You-Dont-Know-JS#1145]
In the section **Implicit Binding**, you state:
>Firstly, notice the manner in which `foo()` is declared and then later added as a reference property onto `obj`. Regardless of whether `foo()` is initially declared on `obj`, or is added as a reference later (as this snippet shows), in neither case is the **function** really "owned" or "contained" by the `obj` object.

This is seems important to understanding correctly in this context, but it's easy to skim over and not quite grasp. It would be great if you could tease out this point a little more and explain how a function that is declared on an object isn't owned or contained by the object. 

It looks like this is dealt with in the next chapter - would it be worth adding a note saying there's more about it there?

**Comment by getify** [comment]
Appreciate the suggestion here. I think upon re-reading I will leave things as-is for now, but may revisit them during second edition.
