### ISSUE TITLE
async & performance - chapter 3 - Really confusing sentence

### ISSUE THREAD

**Issue by darksonic6** [getify/You-Dont-Know-JS#1153]
On section **Calling too Late**, it says:

> Similar to the previous point, a Promise's then(..) **registered observation callbacks** are automatically **scheduled** when either resolve(..) or reject(..) are **called by the Promise creation capability**. Those scheduled callbacks will predictably be fired at the next asynchronous moment (see "Jobs" in Chapter 1).

No matter how many times I read this it remains completely unfathomable to me. 

Wouldn't the _registered observation callbacks_ be the `resolve(..)` and `reject(..)` callbacks themselves? Are they called at the same time they're scheduled? If so, how does this explain anything? If not, what would these _registered observation callbacks_ be?  Also, what are they scheduled to do? Finally, what exactly the phrase _promise creation capability_ refers to?

It's the fourth time I'm reading this chapter, so either that sentence is indeed impenetrable or I am really dense.

**Comment by getify** [comment]
"registered observation callbacks" are the function(s) you pass to a then() method.

**Comment by getify** [comment]
"promise creation capability" refers to the promise constructor function that receives the resolve/reject functions.

**Comment by getify** [comment]
The resolve/reject functions, when called in the promise constructor, schedule any registered observers (that were passed to then() calls) to be executed on the next tick/job queue.

**Comment by kricketune** [comment]
> The resolve/reject functions, when called in the promise constructor, schedule any registered observers

While I'm grateful you answered my questions, I cannot comprehend what you said above.

For instance:

```javascript
function foo(x) {
	return new Promise(function (resolve, reject) {
		resolve(x);
	});
}

var p = foo(42);

p.then(function (v) {
	console.log(v);   // 42
});

// At least according to my interpretation, `function (v) { ... } gets assigned to the
// variable of name `resolve`.
```

The function passed to `then()` gets assigned to `resolve`. However, according to you, resolve calls the function passed to `then()`. Is `resolve` calling itself or am I missing something?

**Comment by getify** [comment]
No that is not correct. The promise constructor runs right away, having created the resolve/reject callbacks for you right at the beginning. That all happens long before you ever call then(..) and give it a callback.

**Comment by kricketune** [comment]
What part of the book tells us that?

**Comment by getify** [comment]
In this section: https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md#promise-events

The second note in that section reads:

    The pattern shown with `new Promise( function(..){ .. } )` is generally called the "revealing constructor". The function passed in is executed immediately (not async deferred, as callbacks to then(..) are), and it's provided two parameters, which in this case we've named `resolve` and `reject`. These are the resolution functions for the promise. `resolve(..)` generally signals fulfillment, and `reject(..)` signals rejection.

**Comment by kricketune** [comment]
Thank you. You're really helpful. I will read this once more and I will certainly pay more attention.
Again, thank you very much.
