### ISSUE TITLE
Release a digital copy of the books

### ISSUE THREAD

**Issue by yvan-sraka** [getify/You-Dont-Know-JS#1154]
Hello,

What do you think of making available a digital copy of the books, for example in `.epub`, `.mobi` or even `.pdf` format for download in [the release section of this GitHub repository](https://github.com/getify/You-Dont-Know-JS/releases)?

Thank you in advance,

**Comment by getify** [comment]
O'Reilly maintains the sole license to distribute the books in ebook form (for sale). The only form I can distribute them in is markdown in this repo.
