### ISSUE TITLE
this & object prototypes - chapter 2 - example code seems wrong

### ISSUE THREAD

**Issue by MostafaNasiri** [getify/You-Dont-Know-JS#1156]
When I run the code below:
`
function foo() {
    console.log(this.a);
}
var a = 2;
foo(); // 2
`
I get "undefined" in my console but the book says it should print 2.
Where is the problem?

**Comment by getify** [comment]
I dunno...

![screen shot 2017-09-30 at 7 09 56 am](https://user-images.githubusercontent.com/150330/31045296-6f8bf568-a5ae-11e7-9666-b6f02ed5535c.png)

**Comment by MostafaNasiri** [comment]
Weird! When I run this code in chrome's web console it gives me the correct output but when I run it with nodejs compiler then I get "undefined" instead of 2!

**Comment by getify** [comment]
Node's "global scope" is not a purely standard JS environment and cannot be trusted to give you accurate JS behavior like this.

**Comment by bmeck** [comment]
CommonJS wraps `.js` files in a boilerplate function. See https://nodejs.org/api/modules.html#modules_the_module_wrapper

**Comment by MostafaNasiri** [comment]
I didn't know that. Thanks guys!

**Comment by getify** [comment]
@bmeck on that topic, I've always wondered why Node has to do that for the main .js file it's executing, as opposed to only doing it for any modules you load?

**Comment by bmeck** [comment]
@getify to inject things like `require` and `module` (`process.mainModule === module`) for people to use. Also prevents various differences like allowing top level `return` depending on how a module is loaded.

Node is also deciding to register this file type as a separate MIME : https://github.com/nodejs/TSC/issues/371

**Comment by getify** [comment]
@bmeck doesn't node care that their deviations confuse JS devs? :)

IIRC the v8 API provides a way to inject identifiers into scope without having to wrap code in an IIFE, no?

**Comment by bmeck** [comment]
@getify doesn't have files be wrapped/not wrapped depending on how they are loaded just add to the confusion?

**Comment by bmeck** [comment]
it should be noted that injecting variables isn't sufficient, grammar/this value also changes

**Comment by getify** [comment]
grammar/this should never have been changed, that's my point, it perpetually confuses developers, like in this thread.

**Comment by bmeck** [comment]
That ship has long since passed and I was just explaining things.
