### ISSUE TITLE
MINOR: NaN is the only reflexive property in JS, but there might be an exception

### ISSUE THREAD

**Issue by electriccode** [getify/You-Dont-Know-JS#1163]
While reading [Javascript equality comparison matrix](https://dorey.github.io/JavaScript-Equality-Table/) I started wondering one thing.
We know that NaN !== NaN and so is object type.
i.e. `{} !== {}`, `[] !== []`, `/a/ !== /a/`, `(function(){}) !== (function(){})`all returns true.
I think it's because they are allocated new memory each time they are initialized and === operator maybe checks for the memory address.
So while this works perfectly fine
```javascript
var a = {};
a !== a; // false
```

this doesn't
```javascript
var a = {};
var b = {};
a !== b; // true
```

Same goes for Array, Regex and function.

I think it might be a good idea to add this as a tip/note in either NaN discussion i.e. "Types & Grammer, Ch2" or in `===` discussion in "Types & Grammer Ch4". Or maybe add an appendix to the Volume if there are more corner cases.

I have read the book couple of months back and now I am re-reading it. This might have been already added to the book. If so, please feel free to close this.

**Comment by getify** [comment]
The "reflexive" property only refers to an actual value being equal to itself, not about two things that look identical (`{}` and `{}`) being equal to each other. The object and array literals here are totally different values, so of course they're not equal. That's entirely different from `NaN` and `NaN`, which in this case is presented to the JS program as both being strictly the same value, but yet it's a value that doesn't hold the reflexive property.
