### ISSUE TITLE
when we will see the 2nd edition of the books

### ISSUE THREAD

**Issue by ahmedvip2008** [getify/You-Dont-Know-JS#1166]
hi
I want to ask
when will we see the 2nd edition of the books?

thanks

**Comment by getify** [comment]
I am hoping maybe to start working on the edits (there are lots of them) sometime by end of this year. I would expect it to take ~6 months of work for all the books to get their second editions completed.

**Comment by ahmedvip2008** [comment]
Thanks for your effort

Wish you more success and happiness

**Comment by srinivasank** [comment]
Thanks
