### ISSUE TITLE
Translate books to Brazilian Portuguese

### ISSUE THREAD

**Issue by svjp** [getify/You-Dont-Know-JS#1172]
Hi there,

I have noticed that this is such a huge repository and yet, you do not have support for other languages but english, therefore, I would like to know if is possible to start translating it?

**Comment by getify** [comment]
Actually, this topic has been discussed a lot, and there are multiple translations. Please see the following threads for more info:

https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3A%22foreign%20language%20translations%22

In particular, there's already a Brazilian Portugese translation project mentioned therein.
