### ISSUE TITLE
this & Object Prototypes chapter 2 - function returns undefined rather than 2

### ISSUE THREAD

**Issue by maecapozzi** [getify/You-Dont-Know-JS#1174]
You write: 

```
function foo() {
	console.log( this.a );
}

var a = 2;

foo();
```

When I run this code in the chrome developer console and from my terminal, I get `undefined`.

**Comment by JoeHetfield** [comment]
Maybe what you referring is this?

![dingtalk20171101092421](https://user-images.githubusercontent.com/4022524/32255875-844f4a7a-be79-11e7-89ce-cf8a15908229.png)

look one line above, it prints "2"
