### ISSUE TITLE
"this & Object Prototypes" Chapter 2: Is the 'a' parameter in the lexical this example needed?

### ISSUE THREAD

**Issue by enumjorge** [getify/You-Dont-Know-JS#1177]
The first example illustrating arrow function lexical scope starts off like this:
```
function foo() {
	// return an arrow function
	return (a) => {
		// `this` here is lexically adopted from `foo()`
		console.log( this.a );
	};
}
```

The arrow function that foo returns takes a parameter called 'a'. Unless I'm missing something, I don't see that parameter being used anywhere in the example or the discussion that follows. What's the purpose of that parameter?

**Comment by getify** [comment]
The `a` is only there to emphasize that `this.a` is not a lexical reference to a local variable `a`, but rather a property on the `this` object context.

**Comment by a-ogilvie** [comment]
I don't think this carries the point very well. In this example, a is assigned to an object which contains its own a property - it's unnecessarily confusing.
