### ISSUE TITLE
this and object prototypes: ch1 - "there is no bridge"

### ISSUE THREAD

**Issue by vinay30** [getify/You-Dont-Know-JS#1194]
Here:
https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch1.md

You have this on line 263:
Every time you feel yourself trying to mix lexical scope look-ups with this, remind yourself: there is no bridge.

In keeping with the Matrix references throughout, perhaps this instead for the 2nd edition:

Every time you feel yourself trying to mix lexical scope look-ups with this, remind yourself: there is no ~~spoon~~ bridge.

**Comment by getify** [comment]
:)
