### ISSUE TITLE
Scope and Closures

### ISSUE THREAD

**Issue by rajatvijay** [getify/You-Dont-Know-JS#1198]
Hey @getify 
In the **Scope and Closure** book, you said that in the compilation phase, all variables are declared and initialized if they have been declared using `var`.

**Consider the code below**
```javascript
function foo(i) {
    setTimeout(function callback() {
      console.log(i);
    }, 1000);
  }

for(var i =0; i < 5; i++) {  
  foo(i);
}
```

My question is when do those buckets are created. Since if the compilation phase only creates the buckets then all calls for a `function` should share the same bucket and the below code should print: 
```
5
5
5
5
5
```

But this is not the case. It rather prints: 
```
0
1
2
3
4
```

Which means the buckets are created at runtime and a different bucket(aka scope) is created for different calls for the same function.
**Is this right?**

**Comment by code-atom** [comment]
@rajatvijay, it creates a new scope per iteration, 
```
for (let i=1; i<=5; i++) {
	setTimeout( function timer(){
		console.log( i );
	}, i*1000 );
}
```
let keyword also create new scope per iteration, because the variable will be declared not just once for the loop, but each iteration.
reference link [https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch5.md](url) **(Block Scoping Revisited)**

**Comment by rajatvijay** [comment]
The function `foo` created a new scope per iterations?

So whenever a new scope is created the same 3 phases are run again? 
Since we have a new scope manager, the compiler has to run again and declare and initialize variables in the scope?

**Comment by code-atom** [comment]
[http://latentflip.com/loupe/?code=ZnVuY3Rpb24gZm9vKGkpIHsNCiAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uIGNhbGxiYWNrKCkgew0KICAgICAgY29uc29sZS5sb2coaSk7DQogICAgfSwgMTAwMCk7DQogIH0NCg0KZm9yKHZhciBpID0wOyBpIDwgNTsgaSsrKSB7ICANCiAgZm9vKGkpOw0KfQ%3D%3D!!!PGJ1dHRvbj5DbGljayBtZSE8L2J1dHRvbj4%3D](url)
Check out this, here you will know how each time new scope is create in js

**Comment by getify** [comment]
The compiler parses the code and sets up a plan for a lexical environment to represent each scope (aka function... or block), but JS doesn't technically create that lexical environment (scope) until it's time for that scope to execute during runtime.

So, a single function represents not just a single scope itself, but a blueprint for a scope that will be created whenever that function is called. If the function is called once, then only one lexical environment (scope) is created. If it's executed 10 times, 10 "instances" of that scope are created, each as separate from the others.

**Comment by code-atom** [comment]
Thanks, @getify, That means 10 times compilation phase and runtime phase executed when we call a function inside a loop?

**Comment by getify** [comment]
no... it means one time compilation, always, no matter where the function is. compilation sets up what kind of environment each scope would need, and then runtime is when that blueprint is instantiated.

**Comment by rajatvijay** [comment]
Thanks @getify 

I think this makes a good point to be added to the book. (Maybe this edition or the second one)
