### ISSUE TITLE
Global variables are "not" automatically properties of the global object

### ISSUE THREAD

**Issue by sudharsan81** [getify/You-Dont-Know-JS#1199]
**Knowledge Source URL**
https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch2.md

**Area Under Study**
Look-ups

**Documentation Snippet under discussion**
`Note: Global variables are also automatically properties of the global object (window in browsers, etc.), so it is possible to reference a global variable not directly by its lexical name, but instead indirectly as a property reference of the global object.`

**Actuals**
Trial01
Code
`
global_var = 100;
function boo(){
  console.log('gloabl_var = ' + global.global_var);
}
(boo)();
`
Output
`
global.gloabl_var = 100
`

Trial02
Now, I declared global_var using "var".
Code
`
var global_var = 100;
function boo(){
  console.log('gloabl_var = ' + global.global_var);
}
(boo)();
`

Output
`
global.gloabl_var = undefined
`

**_Trial02 makes me to beleive not all global vars become properties of "global"_**

I printed global object in both the above trials. (not mentioned here for brevity) I see that If I declare a global variable using either {let|var|const} then I do not see them. But If I declare without using {let|var|const}, then I see them.

I am learning nodeJS from scratch and I will have to form opinions about global variable declarations Vs Look-ups.

Can you please help me to understand this Material.

Thanks in advance.

**Comment by getify** [comment]
Node.js is not a pure JS environment, and thus you cannot take its behavior as reflective of accuracy of the teachings. Node wraps all code in a "module", so your "global" var isn't really a global at all, but a variable inside that module. Even sites like jsbin/etc can't be trusted in this respect.

The only true way to test something like this is to put the code in a .js file and load it into a .html file and test it in a browser.

**Comment by sudharsan81** [comment]
Thanks so much @getify for this explanation. I will ponder more on "module" scope and give a try embedding .js in .html and see the result.

You are my inspiration in JS.
