### ISSUE TITLE
ES2018 & above

### ISSUE THREAD

**Issue by MatthD** [getify/You-Dont-Know-JS#1200]
Hi,

ES2018 is 100% supported by Node.js 9, it implement many new usefull things (import...).
Will you release a new ebook/book for all those new functionalities ?

Regards

**Comment by getify** [comment]
There's a second edition coming, but no specifics yet on when I'll have time to get to that work. The "new" stuff in JS since ES6 will be covered as chapters in "ES6 & Beyond".

**Comment by politologu** [comment]
@getify a quick question,  to get started with React, must I first learn with ECMAScript?

**Comment by getify** [comment]
React is very heavily ES6.
