### ISSUE TITLE
Replace folder name

### ISSUE THREAD

**Issue by KBPsystem777** [getify/You-Dont-Know-JS#1206]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

Replacing the folder filenames like`up & going` will not be recognize as a valid directory when you `cd` into terminal. Suggestion:  `up_and_going`
Same goes to other folders that has special char names and spacing. Thanks

**Comment by getify** [comment]
thanks, but at this point there's far too many cross-links to these books that I don't want to go changing directory structure or naming conventions and break things for people.
