### ISSUE TITLE
Add Async ans Await on top of Promises?

### ISSUE THREAD

**Issue by laoshaw** [getify/You-Dont-Know-JS#1214]
Will Async and Await be added to the "Async" book some day?

**Comment by getify** [comment]
yes, in the second edition.

**Comment by laoshaw** [comment]
when will be 'second edition' ready? Thanks!

**Comment by getify** [comment]
Haven't started them yet... so, hard to predict. Hoping to start them by mid-year. Should then take 6-9 months to get all six books updated.
