### ISSUE TITLE
Resources for further training on behavior delegation

### ISSUE THREAD

**Issue by blachawk** [getify/You-Dont-Know-JS#1216]
This is more of a request rather than an issue.  First, excellent job on the online book.  I have read through all the books on "You Don't Know JS" and feel super inspired in coding JavaScript they way its intended (without the lies).  

What additional resources, authors, or web sites should I look into to further my training in behavior delegation of objects through JavaScript?  Bottom line - the more examples I can learn from, the closer to the truth I can begin to apply in my projects.

If the answer is "come back here" - I dig it 👍 

Thanks!

**Comment by jameshiggins** [comment]
Maybe eloquent Javascript?

**Comment by getify** [comment]
As far as I'm aware, I'm about the only one out there particularly advocating for (though many claim to like) object delegation. I don't really have a lot of resources to point to. Maybe this old blog 3-part post series I wrote (though it's much the same as the book): https://davidwalsh.name/javascript-objects
