### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by ismailbayram** [getify/You-Dont-Know-JS#1222]
Hello, I would like to translate this e-book to Turkish. May I with refer to reference of you?

**Comment by getify** [comment]
Yes! Please see these threads for more info: https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=label%3A%22foreign+language+translations%22

Specifically, https://github.com/getify/You-Dont-Know-JS/issues/9#issuecomment-152142890 and #900
