### ISSUE TITLE
Object.create in the (Prototypical) Inheritance section

### ISSUE THREAD

**Issue by ithacasnowman** [getify/You-Dont-Know-JS#1229]
In the section [(Prototypical) Inheritance](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch5.md#prototypal-inheritance), an example of "typical 'prototype-style' code" is provided that includes following lines:

`// here, we make a new Bar.prototype`
`// linked to Foo.prototype`
`Bar.prototype = Object.create( Foo.prototype );`

When I read the example for the first time, the call to `Object.create` was surprising. It doesn't seem to entirely clear at this point why we're creating an entirely new object when all that this example intended to illustrate was "linkage". 

Later on in the section, you do mention how:

> "Prior to ES6, there's a non-standard and not fully-cross-browser way, via the .__proto__ property, which is settable. ES6 adds a Object.setPrototypeOf(..) helper utility, which does the trick in a standard and predictable way."

It may be because I'm new to JS, but "setting" the `__proto__` property seems far more natural. It makes sense to modify the `__proto__` property of `Bar.prototype` to point to `Foo.prototype` instead of creating an entirely new object just so that we can get an object whose `__proto__` property is `Foo.prototype`. And even then the new object isn't quite "right" because `Bar.prototype.constructor` is now Foo. 

Perhaps you could move that `Object.setPrototypeOf` section up before the example, and sort of derive your way into why `Object.create` is really the preferred way to do this. Actually, it's still not clear to me that it is the best/preferred way to do this, or if there are other ways to accomplish the same thing.

In the same section, you also mention that:

> "Ignoring the slight performance disadvantage (throwing away an object that's later garbage collected) of the Object.create(..) approach, it's a little bit shorter and may be perhaps a little easier to read than the ES6+ approach. But it's probably a syntactic wash either way."

As a reader it's not clear if the creation of the object itself also makes that approach less performant. Does `Object.setPrototypeOf` do anything other than set the `__proto__` property to the desired prototype? If not, why isn't that approach recommended?

My apologies if this seems like I'm splitting hairs, but the section really did confuse me.

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

**Comment by ithacasnowman** [comment]
I should add here that later in the section you make the following points:

> .__proto__ is also a settable property, just like using ES6's Object.setPrototypeOf(..) shown earlier. However, generally you should not change the [[Prototype]] of an existing object.

> The only other narrow exception (as mentioned earlier) would be setting the [[Prototype]] of a default function's .prototype object to reference some other object (besides Object.prototype). That would avoid replacing that default object entirely with a new linked object. Otherwise, it's best to treat object [[Prototype]] linkage as a read-only characteristic for ease of reading your code later.

**Comment by getify** [comment]
Using Object.create() is the classic standard way of doing this **prior to ES6**. That's the perspective the book takes.

Also, note that neither __proto__ nor setPrototypeOf are polyfillable or transpilable to non-supporting environments (IE <= 10) so they're really not an option for some section of developers who still have to support those environments.
