### ISSUE TITLE
Object.create() Polyfilled

### ISSUE THREAD

**Issue by ithacasnowman** [getify/You-Dont-Know-JS#1230]
A simple implementation of [Object.create() Polyfilled](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch5.md#objectcreate-polyfilled) is given as this:

```
if (!Object.create) {
	Object.create = function(o) {
		function F(){}
		F.prototype = o;
		return new F();
	};
}
```

I was a bit surprised by this implementation. Wouldn't it be easier to do this:

```
if (!Object.create) {
	Object.create = function(o) {
		return Object.setPrototypeOf({}, o); // <-- no, that only works ES6+. so let's polyfill below
                var newObject = {};
                newObject.__proto__ = o;
                return newObject;
	};
}
```

Perhaps I'm mistaken and those are not equivalent. If they are, isn't it more costly to define F (which in turn creates a F.prototype object), and then modify _that_ prototype object, and then garbage collect both that object and the function object later? 

My apologies if this is outside the scope of discussion in the book (and better suited for a forum discussion). 

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

**Comment by ithacasnowman** [comment]
I noticed something you mentioned about `.__proto__`:

> Prior to ES6, there's a non-standard and not fully-cross-browser way, via the .__proto__ property, which is settable.

Are these the reasons for not choosing the implementation above?

**Comment by getify** [comment]
Neither `__proto__` nor `setPrototypeOf(..)` can work in pre-ES6 environments, nor can they be polyfilled. The book was written to show the ES5 equivalent of `Object.create(..)`, since that's the version of JS where `Object.create(..)` was added.
