### ISSUE TITLE
Scope and Closures, chapter 1 - building metaphor

### ISSUE THREAD

**Issue by amosonn** [getify/You-Dont-Know-JS#1231]
I would suggest turning the building in the metaphor over on its head, meaning to have the global scope as the entrance floor and the current scope the floor on which you're one. A few advantages to this:
- This clearly demonstrates the "staticness" of the global scope. Other scopes come and go, including the one in which you're in, the global stays on the ground - whereas in the current model it can change floors depending on how deeply nested you're gone.
- At least with the picture currently used, it also suggests the singleness of the global scope, due to the large door on the ground floor as opposed to the many windows in the others.
- It seems like a more complete story while passing through scopes. You enter the building at the ground floor (global scope), then ascend to higher floors (scopes) and come back down through the ground floor. It also somehow suggests that scopes are "built on top of each other", which is the reason why you can ask a lower scope when you lack the answer yourself.
- It resembles the classic representation of the call stack, where new functions are "pushed on top" and the calling scope is "lower", which is of course related, and might make it easier for programmers switching over from lower-level languages to make the connection. It is true though that stack-traces are sometimes displayed in reverse; well, we can't win them all.

**Comment by aladdine** [comment]
That's an interesting point but the current metaphor has one key aspect: the "find the correct scope" operation starts at the lowest level scope and goes towards the global scope (highest level). 
Doing it the way you suggested may be confusing because it may suggest that the search starts at the global scope which is incorrect. An upside down building is also not an obvious metaphor.

**Comment by getify** [comment]
Metaphors are rarely completely encompassing of all aspects of a topic. They generally focus on a certain angle. In this case, the building metaphor is, as @aladdine points out, focused on the "lookup" part, as in if you walked into a new building looking for someone's office. It would be awfully strange (and a bit inefficient) to suggest a person go all the way to the top floor to start their search, moving down each floor one at a time.

The notion of scopes being added is indeed a "stack" (aka, an upside down building), but scopes are not added at runtime (where this lookup is happening, generally); for the purpose of a lookup and this metaphor, the scopes available to search in are already fixed -- as in, a building that's already built.

Were we talking about scopes being added / removed, I would agree the building metaphor is inappropriate and a stack is the more logical choice.

**Comment by amosonn** [comment]
Of course turning it upside down was only a turn of speech, it should remain a normal right-side-up building.

My point was that if you reverse the order of floors, you can use one building for the entire code - there is only one global scope through which you enter, and during the running of the program you go up and down in different scopes. With the current metaphor, you need a "new building" for each time you're scope checking, with no obvious compatibility between them, which is confusing because most of these scopes are actually the same.

This is also the solution to the concern about the person going up to start their search. They don't need to go up, they're already there - they climbed there when they called all these functions. Now they're just peering down when they're missing something, only to resume their business in their current floor. I feel this also captures better the logic behind the idea of scope resolution - you're not arbitrarily asking other places, you're going back to the places you've been through, maybe you've "forgotten" something there. In other words, this maintains the bond between code flow and scope resolution.

**Comment by getify** [comment]
Thanks for the feedback.
