### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by chicooou** [getify/You-Dont-Know-JS#1242]
Hello, are you planning on doing an English-Spanish translation of the book? I can be of great help for this : D.

**Comment by getify** [comment]
Please see these issues for more info on translations: https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=label%3A%22foreign+language+translations%22

**Comment by EstebanMarin** [comment]
There is an active repo for that, please check this thread
https://github.com/getify/You-Dont-Know-JS/pull/1378
