### ISSUE TITLE
Potential mistake discussing coercion on up&going ch2

### ISSUE THREAD

**Issue by silicakes** [getify/You-Dont-Know-JS#1243]
Hi,
While browsing the following:
https://github.com/getify/You-Dont-Know-JS/blob/master/up%20%26%20going/ch2.md

i came a cross this paragraph:

> The difference between == and === is usually characterized that == checks for value equality and === checks for both value and type equality. However, this is inaccurate. **The proper way to characterize them is that == checks for value equality with coercion allowed, and === checks for value equality without allowing coercion**;

I took a look at the recent implementation of strictEqual on v8:
```

Type* OperationTyper::StrictEqual(Type* lhs, Type* rhs) {
  if (!JSType(lhs)->Maybe(JSType(rhs))) return singleton_false();
  if (lhs->Is(Type::NaN()) || rhs->Is(Type::NaN())) return singleton_false();
  if (lhs->Is(Type::Number()) && rhs->Is(Type::Number()) &&
      (lhs->Max() < rhs->Min() || lhs->Min() > rhs->Max())) {
    return singleton_false();
  }
  if ((lhs->Is(Type::Hole()) || rhs->Is(Type::Hole())) && !lhs->Maybe(rhs)) {
    return singleton_false();
  }
  if (lhs->IsHeapConstant() && rhs->Is(lhs)) {
    // Types are equal and are inhabited only by a single semantic value,
    // which is not nan due to the earlier check.
    return singleton_true();
  }
  return Type::Boolean();
}
```
As you can see, the [first line](https://github.com/v8/v8/blob/7ff1aa63d93fc4497729a3c4880764d567887340/src/compiler/operation-typer.cc#L1116) clearly does type checking rather than coercing into something.
The implementation of JSType is just a switch statement (implemented with ifs).

Am I missing something? If so, mind you point me to the reference you've used?

**Comment by getify** [comment]
I think maybe you're misreading what I wrote, because what you're asserting backs me up.

**Comment by silicakes** [comment]
You're right - my bad, I mixed up the two in my head and referred to the other one,
Sorry about that!

**Comment by getify** [comment]
np. :)

For posterity sake, the relevant sections of the spec:

* [`==`, aka "Abstract Equality Comparison"](http://www.ecma-international.org/ecma-262/8.0/#sec-abstract-equality-comparison)

* [`===`, aka "Strict Equality Comparison"](http://www.ecma-international.org/ecma-262/8.0/#sec-strict-equality-comparison)
