### ISSUE TITLE
Async & Performance - Promise Scheduling Quirks - result not match in Chrome 

### ISSUE THREAD

**Issue by lordisback** [getify/You-Dont-Know-JS#1244]
Hello
`var p3 = new Promise( function(resolve,reject){
	resolve( "B" );
} );

var p1 = new Promise( function(resolve,reject){
	resolve( p3 );
} );

var p2 = new Promise( function(resolve,reject){
	resolve( "A" );
} );

p1.then( function(v){
	console.log( v );
} );

p2.then( function(v){
	console.log( v );
} );`
I run the code both in node v6.9.5 and Chrome55, and the result is 'A B' and 'B A' respectively, which seems the exc order is depend on the implementation of Promise. 

Thank you!

**Comment by getify** [comment]
The execution order IS implementation-dependent (not guaranteed by the spec), and that's why this section strongly suggests not relying on that inter-promise scheduling.
