### ISSUE TITLE
ES6 and beyond - Chapter 3 - Dead links to blog.getify.com

### ISSUE THREAD

**Issue by Aravamudhan** [getify/You-Dont-Know-JS#1249]
- When talking about [custom iterators](https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch3.md#custom-iteratorsl) there are couple of links @getify points to know more about them. They are http://blog.getify.com/iterating-es6-numbers/ and http://blog.getify.com/iterating-es6-numbers/comment-page-1/#comment-535294
- Those two links not seem to be available. @getify Is there an alternative to those two links or should they be removed ? Seems like the domain itself is not available.

**Comment by getify** [comment]
The site's been down for almost 2 years. However, those blog posts should be findable (with a bit of poking around) on archive.org.
