### ISSUE TITLE
Closure - Reference to the entire scope or just required variables?

### ISSUE THREAD

**Issue by ross-weir** [getify/You-Dont-Know-JS#1250]
Hi I have some questions about the Closure section of the series (amazing series btw).

 In the early section of [Scope & Closures chapter 5, nitty gritty](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch5.md#nitty-gritty) when you're explaining closure you explain it as a reference to the scope.

> bar() still has a reference to that scope, and that reference is called closure.

When I am experimenting with chrome devtools, the output I'm getting seems to indicate that closure isn't a reference to the entire scope, but just the variables/resources required by the inner scope. 

Is this just devtools simplifying things for me?

For example, consider the following:

```
function outer() {
	var a = 'a';
	var b = 'b';

	function inner() {
		console.log(a);
        }

	return inner;
}

let x = outer();

console.dir(x);
```

When I check the closure that devtools is reporting I am only seeing `a`. If closure was preserving the entire scope reference as I would expect after reading the chapter, I would expect to see `a` and `b` because they both belong to that particular scope.

So is closure really about preserving a reference to the entire scope or just preserving the resources required? Or is there something more to this? Is devtools simplifying things?

Thank you sir.

**Comment by ross-weir** [comment]
To clarify:

I wasn't using devtools. I was using `console.dir` in chrome to view the closure.

**Comment by getify** [comment]
I'm not sure what you mean by using console.dir on the closure? Not aware of any way to reveal from code or console what's in the closure.

My advice is to think about closure over the whole scope and not just a single variable. It's hard to predict whether any engine might close over individual vars or not.

**Comment by ross-weir** [comment]
Thanks for your reply.

[Here's a screenshot to try and explain what I mean](https://i.imgur.com/ysu4Vzs.png). It's only showing the variable `a` in the `Closure` field. It seems only the chrome browser has the support for showing the `[[Scopes]]` field and thus `Closures` (granted I didn't try many browsers).

My first thought was maybe there has been some optimization done recently to the engines to 'create closure' over certain variables? 

Ok, thank you. It certainly seems better/more consistent to just think of closure as the whole scope.

**Comment by harsh2602** [comment]
Not a 100% sure about whether I am correct, but to answer the specific question related to the screenshot, I think that's a V8 compiler optimization where it realized that variable 'b' isn't needed after function outer is popped of the call stack i.e executed. Do remember that the language spec is one thing but how the browser vendor implement things is totally dependent  on them. According to language spec, it should have both variables 'a' and 'b' under the [[Scopes]] property.

**Comment by getify** [comment]
AFAICT, the spec neither requires nor disallows "closure culling", which is to strip out variables from a closed-over scope that aren't specifically referenced. It's purely an optimization.

I think the only way you could hope to observe if it happened would be to use `eval(..)` inside a closure, but I'm pretty sure engines won't cull if they see an `eval(..)` present so you probably wouldn't actually observe it.

In theory engines can cull their closures, but in practice I think it turns out to be difficult and costly and generally found not to be worth the effort. So whether any engine does so, and under what conditions, would be a difficult target to lock down.

That's why I suggest just always thinking of it as the whole scope being closed over.
