### ISSUE TITLE
Up & Going - Chapter 2: Into JavaScript - Minor typo on "behavior delegation" reference

### ISSUE THREAD

**Issue by mstred** [getify/You-Dont-Know-JS#1252]
I couldn't find something related in the existing issues (both open and closed).

I understand that [typos aren't a big deal](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md#typos), but then I wanted to make this acknowledged by others, in order to be fixed in a further major typo-related PR.

The actual problem refers to a mistyped comma inside the "behavior delegation" quote definition in the ["Prototypes" section](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20%26%20going/ch2.md#prototypes):

```md
...a pattern called "behavior delegation," where you intentionally design...
```
Which should be like this:
```md
...a pattern called "behavior delegation", where you intentionally design...
```

**Comment by getify** [comment]
Not a typo... that's how the writing style guide expects.

**Comment by mstred** [comment]
Sorry @getify, but as a foreigner, I didn't know about that... I took a time to look up on this and it's correct for en-US. Thanks!

Here are some sources for those who want to know a little bit more on that:
* http://blog.apastyle.org/apastyle/2011/08/punctuating-around-quotation-marks.html
* https://www.grammarbook.com/punctuation/quotes.asp
