### ISSUE TITLE
Bug in -- You Don't Know JS: Async & Performance Ch3 Promises

### ISSUE THREAD

**Issue by metasong** [getify/You-Dont-Know-JS#1253]
https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md#what-is-a-promise

```js
var p1 = Promise.resolve( 42 );

var p2 = Promise.resolve( p1 );

p1 === p2; // true
```
it's **false** now, in chrome  64.0.3282.186

**Comment by JamieMaple** [comment]
I think it's not a bug exactly, you can see [ecma262](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-promise.resolve)

> The resolve function returns either a new promise resolved with the passed argument, or the argument itself if the argument is a promise produced by this constructor.

**Comment by andreaschrist27** [comment]
it's **true** for me. my chrome version 64.0.3282.186

**Comment by Nirajn2311** [comment]
Its **true** for me also and my chrome version is **64.0.3282.186**
@metasong are you able to reproduce it again? If yes, could you post a screenshot

**Comment by getify** [comment]
The spec requires the behavior I describe: http://www.ecma-international.org/ecma-262/8.0/#sec-promise.resolve

So any example of Chrome not doing that would be a spec violation, not a bug in my book. :)
