### ISSUE TITLE
Up&Going chapter 1, functions section. Declaring both functions, second function maybe with an error

### ISSUE THREAD

**Issue by Jopepato** [getify/You-Dont-Know-JS#1256]
Hi!
While reading this chapter I encounter a bit of a problem while understanding the functions you declared in this chaper.

```
function printAmount(amt) {
    console.log(amt.toFixed( 2));
}
function formatAmount(){
    return "$" + amount.toFixed( 2))
}
```

As we can see in the second function, it is accesing the amount variable without passing it as a parameter. This, as explained later on this chapter in the scope can be posible. However, while reading this section there is no reference to it, so the reader can be quite confused. Or maybe the parameter is missing if i missed the point of the explanation

**Comment by getify** [comment]
The sentence immediately after that snippet indicates the purpose of this approach:

> The function printAmount(..) takes a parameter that we call amt. The function formatAmount() returns a value. Of course, you can also combine those two techniques in the same function.

In other words, I'm isolating concepts in those two functions; one has the parameter but no return, the other has the return but no parameter. Then the sentence suggests these two concepts can be put together into a single function.

As you said, the idea of scope happens later, I don't want the reader to get too overwhelmed here with that detail.
