### ISSUE TITLE
[Question] Can I fork this repository and host it myself?

### ISSUE THREAD

**Issue by bauripalash** [getify/You-Dont-Know-JS#1265]
I've seen the License and I'm aware that i can only share your work.
I'm thinking of making a open source online library of free books.
The Site will be totally non-profit and free to everyone.
Can i add your book?

**Comment by getify** [comment]
Depends on how (in what format) people would be accessing the books. People can fork the repo as much as they want, and display digitally in the rendered-markdown as github does. But it's against my license with O'Reilly for people to create a digital ebook (PDF, etc) for distribution.

**Comment by bauripalash** [comment]
No, it would be shown as a rendered markdown. Markdown will converted into html and then it'll be shown to people.
