### ISSUE TITLE
Wording indicates future, but book already exists

### ISSUE THREAD

**Issue by wojonet** [getify/You-Dont-Know-JS#1278]
In Chapter 6 of `this` & Object Prototypes, this sentence appears under the section: *Simpler Design*

> **Note:** We don't cover Promises here, but we will cover them in a future title of the *"You Don't Know JS"* series.

Since that book does exist now, I propose changing that to:

> **Note:** We don't cover Promises here, but we do in a another title of the *"You Don't Know JS"* series: *Async & Performance*.

**Comment by getify** [comment]
This is already on tap to address in the second editions. Thanks.

**Comment by wojonet** [comment]
Gotcha. In retrospect, I probably should have realized that in the first place. Thank you!
