### ISSUE TITLE
while(true) in generators

### ISSUE THREAD

**Issue by subhranshudas** [getify/You-Dont-Know-JS#1292]
i have a generator function, which has a while(true) loop inside it. And i am running the generator using gen.next() from outside, based on some events happening. These events can be like 100 in a minute.

Now is it good practice to run the generator like that, or should i avoid while(true). How does it impact the performance.?

**Comment by getify** [comment]
The `while..true` idiom inside a generator is basically how you keep a generator alive indefinitely. I use that pattern regularly. Should be totally safe.

**Comment by subhranshudas** [comment]
@getify ah.. i see...so its an "indefinite" loop instead of an "infinite" one....as long as the "calling" code is run in a safe manner, this pattern should be completely fine. Thank you Sir!
