### ISSUE TITLE
why is IIFE needed to create a new scope?

### ISSUE THREAD

**Issue by ags799** [getify/You-Dont-Know-JS#1296]
From this section: https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch5.md#loops--closure

I've asked a StackOverflow question about this https://stackoverflow.com/questions/50615610/why-is-iife-needed-to-create-a-new-scope

Would appreciate any help.

**Comment by getify** [comment]
This is the correct answer: https://stackoverflow.com/a/50615634/228852?stw=2

The function has to run to create a scope closure.

**Comment by ags799** [comment]
yep thank you! 😊
