### ISSUE TITLE
Async & Performance. Chapter 3.  Broken Trust.

### ISSUE THREAD

**Issue by LxPvlv** [getify/You-Dont-Know-JS#1302]
If a *thenable* calls at first (or only) reject? We can't trust a *thenable*?

```javascript
var p = {
	then: function(cb,errcb) {
		errcb( "evil laugh" );
 		cb( 42 );
	}
};


Promise.resolve( p )
.then(
	function fulfilled(val){
		console.log( val ); // 42
	},
	function rejected(err){
		// oops, shouldn't have run
		console.log( err ); // evil laugh
	}
);
```
Resolved promise calls reject.

**Comment by getify** [comment]
No, by definition you cannot trust thenables, only legit promises.

**Comment by LxPvlv** [comment]
Yes, you wrote:

> This p is a thenable but it's not so well behaved of a promise. Is it malicious? Or is it just ignorant of how Promises should work? It doesn't really matter, to be honest. In either case, it's not trustable as is.

But this words make me confuse:

> Nonetheless, we can pass either of these versions of p to Promise.resolve(..), and we'll get the normalized, safe result we'd expect:

and then:

> Promise.resolve(..) will accept any thenable, and will unwrap it to its non-thenable value. But you get back from Promise.resolve(..) a real, genuine Promise in its place, **one that you can trust**. ...

Thank you for answer!

**Comment by getify** [comment]
Right so you can trust a promise but you can't trust a thenable that may be used to create a promise.
