### ISSUE TITLE
将中文版迁移到雨雀

### ISSUE THREAD

**Issue by uv-w** [getify/You-Dont-Know-JS#1303]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).
将中文版本迁移到了雨雀，便于中国程序员学习，谢谢。
[https://yuque.com/uv-w/you-dont-know-js](https://yuque.com/uv-w/you-dont-know-js)

**Comment by JoeHetfield** [comment]
Thanks for the help
