### ISSUE TITLE
One book instead of a series

### ISSUE THREAD

**Issue by amfische** [getify/You-Dont-Know-JS#1304]
I thought it would be nice to have all of this content in one book instead of having to purchase 6 books. It'd provide a better reading experience and maybe save some trees. Anyhow, thank you for creating this content, really good stuff.

**Comment by getify** [comment]
Appreciate your feedback. I understand the convenience (and cost) considerations you're voicing. However, such a combined book would be over 1100 pages in length, and probably would cost $90 or more. That strategy would cause much of the content to be less accessible to a broader audience, many of whom have only purchased a few of the books that focus on things they're most interested in.
