### ISSUE TITLE
an example used in "Scope & Closures"

### ISSUE THREAD

**Issue by whitemuu** [getify/You-Dont-Know-JS#1306]
an example from chapter 5
```
function wait(message) {
    setTimeout( function timer(){
        console.log( message );
    }, 1000 );
}

wait( "Hello, closure!" );
```
I doubt if it's a closure, since 'setTimeout' is call right inside 'wait'. So I tried something similar in Perl
```
sub foo() {
    local $a = 2;
    sub baz() {
        print $a;
    }
    bar(\&baz);
    return \&baz;
}

sub bar {
    my $baz = shift;
    &$baz();
}

local $a = 1;
my $baka = foo();  #call baz in foo, but with bar whose body is outside foo, print 2
&$baka; #call baz outside, print 1
```
It turns out even with dynamic scope, the `bar(\&baz);` ,which is similar to the setTimeout's invocation, references to the $a within `foo`

**Comment by getify** [comment]
> I doubt if it's a closure, since 'setTimeout' is call right inside 'wait'.

It's definitely a closure, 100%. `setTimeout(..)` is called right away, but the `timer()` function is not invoked until later, and yet it still has lexical access to `message`.

I'm not sure what's going on with your perl code (my perl skills are very old and rusty), but I can say that the JS snippet is definitely closure.

**Comment by whitemuu** [comment]
Thanks for your rapid reply.

It definitely has lexical access to message. My confusion is whether it is invoked inside or outside `wait`. It is invoked within `setTimeout`'s declaration body, but `setTimeout` itself is invoked with `wait`(the call stack begins there). So I mimic the code with Perl, which could be dynamic scoped. And here the free reference `$a` in `baz` can also grab the the `$a` binding in `foo`, even it's dynamic(which can be proofed by in last line). Thus, back to the JS example, if I say the `timer` function is invoked in `wait`(then it's not a closure, right?), the knowledge describing two mechanism(describing dynamic and lexical among the two language) will be consistent and unified.

I also replicated the situation in elisp, same behavior.

```
(setq a "global")

(defun foo ()
  (let ((a "let"))
    (bar (lambda () (message a)))))

(defun bar (func)
  (funcall func))

(foo) ;=> "let"
```

**Comment by whitemuu** [comment]
sorry I did miss something.
I shouldn't use a global variable as a comparing object, which in either scope will be the last binding to consult.

```
(setq a "global")

(defun foo ()
  (let ((a "let"))
    (bar (lambda () (message a)))))

(defun bar (func)
  (let ((a "bar"))
    (funcall func)))

(foo) ;=> "bar"
```
