### ISSUE TITLE
Two's complement

### ISSUE THREAD

**Issue by mohamedatef98** [getify/You-Dont-Know-JS#1310]
"So, let's turn our attention back to ~. The ~ operator first "coerces" to a 32-bit number value, and then performs a bitwise negation (flipping each bit's parity)."

"Another way of thinking about the definition of ~ comes from old-school computer science/discrete Mathematics: ~ performs two's-complement. Great, thanks, that's totally clearer!"

Only flipping the bits is the one's complement.
The two's complement is ths one's complement and adding one.

**Comment by getify** [comment]
Known issue: https://github.com/getify/You-Dont-Know-JS/issues/616
