### ISSUE TITLE
Writable should be true instead of false

### ISSUE THREAD

**Issue by ap0404** [getify/You-Dont-Know-JS#1312]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

In this & object prototypes ch.5 has below line:

> If a normal data accessor (see Chapter 3) property named foo is found anywhere higher on the [[Prototype]] chain, and it's not marked as read-only (writable:false) then a new property called foo is added directly to myObject, resulting in a shadowed property.

I think it's a typo & writable should be true here.

**Comment by getify** [comment]
Please search existing issues.
