### ISSUE TITLE
Async and Performance Chapter 1

### ISSUE THREAD

**Issue by DawoodShahat** [getify/You-Dont-Know-JS#1318]
`var a = 20;

function foo() {
	a = a + 1;
}

function bar() {
	a = a * 2;
}

// ajax(..) is some arbitrary Ajax function given by a library
ajax( "http://some.url.1", foo );
ajax( "http://some.url.2", bar );`

In JavaScript's single-threaded behavior, if foo() runs before bar(), the result is that a has 42, but if bar() runs before foo() the result in a will be 41.

**from the explanation above the value of a should be 40.**

**Comment by getify** [comment]
If `foo()` runs first, `a` becomes `21`, then `bar()` runs and it becomes `42`.

If `bar()` runs first, `a` becomes `40`, then `foo()` runs and it becomes `41`.
