### ISSUE TITLE
The word "hijacks" in Chapter 3 Seems out of place - Let's Discuss

### ISSUE THREAD

**Issue by JustAnotherG** [getify/You-Dont-Know-JS#1319]
I've just finished reading Chapter 3 of the book on "Scopes" and I see the word "hijacks" used when explaining the new let keyword in ECMAScript 6. Isn't it really just hiding any other variables having the same identifier in the current scope?

Is hijacks just a more dramatic synonym for hiding? I'm just curious if there is a difference between the two.

**Comment by getify** [comment]
The term hijack in my usage is meant to point out that the `let` keyword takes over an otherwise normal block (like an `if`) and turns it also into a block of scope. Any block without a `let` is not a scope, but as soon as there's even one `let` anywhere in the block, all of a sudden it's a scope.
