### ISSUE TITLE
Is the following code really asynchronous?

### ISSUE THREAD

**Issue by stavalfi** [getify/You-Dont-Know-JS#1320]
I think you have a second (and entirely not equal) definition for asynchronous operations compared to [Wikipedia](https://en.wikipedia.org/wiki/Asynchrony_(computer_programming)). To be sure that I'm not wrong before creating an issue here, I opened a post in [StackOverflow](https://stackoverflow.com/questions/51451279/is-the-following-code-asynchronous).

 In case I'm not wrong than the connection between `Generators` and `Async` is not clear from the parts I mentioned in your book.

Due to the absence of any response or answer, I may request your attention to this subject.

Thanks for your time.

**Comment by getify** [comment]
Answered: https://stackoverflow.com/a/51471659/228852

**Comment by stavalfi** [comment]
Thank you for the quick answer. It was extremely helpful.

I was __so sure__ about my conclusions that I didn't try to print something after:
```javascript
var it = main();

// start it all up!
it.next();
console.log("will it be printed first?") // yes :)
```
to see what will be the result.

It's indeed a confusing example full of surprises.
