### ISSUE TITLE
Piece of advice

### ISSUE THREAD

**Issue by mohamedatef98** [getify/You-Dont-Know-JS#1323]
```
var gimmeSomething = (function(){
	var nextVal;

	return function(){
		if (nextVal === undefined) {
			nextVal = 1;
		}
		else {
			nextVal = (3 * nextVal) + 6;
		}

		return nextVal;
	};
})();
```

I believe the if.. else isn't necessary.
the if could be removed and nextVal should be initialized by 1

**Comment by sandrosc** [comment]
@mohamedatef98 then the value the function returns first would change, from 1 to 9.

**Comment by njnygaard** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4606342/44489577-b15ab700-a610-11e8-939f-fdf65c5f06f2.png">

**Comment by carlsmith** [comment]
Hey @mohamedatef98. The title of a new issue should ideally summarize the issue. Just a piece of advice `:)`
