### ISSUE TITLE
Types & Grammar Ch. 3 - Sparse array serialization in Chrome now uses 'empty'

### ISSUE THREAD

**Issue by rydash** [getify/You-Dont-Know-JS#1335]
[_Types & Grammar_, Chapter 3: Natives](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch3.md#array) contains a few references to the Chrome Developer Tools' behavior when dealing with sparse arrays. Specifically, it laments that a snippet like the following produces `undefined`:
```
var a = new Array( 3 );

a.length; // 3
a;
```

In Chrome 68 and later, the output is no longer `[undefined x 3]`, but instead `[empty x 3]`, properly identifying the sparseness of the array.

I haven't checked if Firefox has made similar improvements. I'd motion that these areas of that chapter are re-checked, and those callouts are either removed, or presented in a more historical context.

I also understand that the intent of those sections is to say "it is up to the browser to determine how to serialize and represent sparse arrays." I hope not to lose that message's intent with any changes.

**Comment by getify** [comment]
These are all things that will be re-visited during second edition. Thanks!
