### ISSUE TITLE
scope & closures/apB.md - Dynamic scope code sample needs to be rectified. 

### ISSUE THREAD

**Issue by ajit555db** [getify/You-Dont-Know-JS#1342]
https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/apA.md

```
function foo() {
	console.log( a ); // 3  (not 2!)
}

function bar() {
	var a = 3;
	foo();
}

var a = 2;

bar();
```

Above example returns 2, not 3. Can you please rectify it.

**Comment by animeshk874** [comment]
That section explains dynamic scoping. It's not an error. For more details: https://github.com/getify/You-Dont-Know-JS/issues/702

**Comment by ajit555db** [comment]
Oh, thanks. Got it.
