### ISSUE TITLE
Logical OR and Grouping Question

### ISSUE THREAD

**Issue by lsycxyj** [getify/You-Dont-Know-JS#1353]
Grouping should have higher priority than logical operator, but I tried to run the following code it didn't throw an error. And the "Selector" section didn't answer it.
Should it throw an error or shouldn't it? And why?
```javascript
const a = false;
const b = undefined;
console.log(a && (b.a || b.c));
```

**Comment by lopatnov** [comment]
It shouldn't, because the first result returns false, so the next logic of && operator not important.

**Comment by lsycxyj** [comment]
@lopatnov But grouping should have higher priority.

**Comment by lopatnov** [comment]
Yes, and what? You know that the group is (b.a || b.c). Do you need the result of group? No, you have the result of the "a" variable.
Group and the result of it are different things.

**Comment by lsycxyj** [comment]
@lopatnov The problem is Grouping has the highest priority. Maybe somebody wants to do something when they use the logical operators (eg. assign a value to some variables). Shouldn't the grouping operator be respected? Or should the meaning of priority of grouping be redefined?

**Comment by lsycxyj** [comment]
Ooops, I found the answer. Close this issue.
https://github.com/getify/You-Dont-Know-JS/blob/f0d591b6502c080b92e18fc470432af8144db610/types%20%26%20grammar/ch5.md

**Comment by getify** [comment]
For posterity, this note (and its preceding referred to example) spells it out:

> Note: If hypothetically && was right-associative, it would be processed the same as if you manually used ( ) to create grouping like a && (b && c). But that still doesn't mean that c would be processed before b. Right-associativity does not mean right-to-left evaluation, it means right-to-left grouping. Either way, regardless of the grouping/associativity, the strict ordering of evaluation will be a, then b, then c (aka left-to-right).

In other words, while the ( ) set will indeed override precedence and even potentially associativity, it will not change left-to-right operation.
