### ISSUE TITLE
Wrong function name 

### ISSUE THREAD

**Issue by dimachernov** [getify/You-Dont-Know-JS#1354]
https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch2.md

Was going through the chapter and noticed the function name should be foo instead of bar in this explanation.

>Whoa! bar is hard-bound against obj1, but new bar(3) did not change obj1.a to be 3 as we would have expected. Instead, the hard bound (to obj1) call to
```diff
+ foo(..) 
- bar(..) 
```
>is able to be overridden with new. Since new was applied, we got the newly created object back, which we named baz, and we see in fact that baz.a has the value 3.

**Comment by getify** [comment]
Quoting myself from the related PR:

> The text is correct as-is. As with other mentions of "bar" in that paragraph, the reference in question is to the call-site that looks like "bar()" and "new bar()", not to the underlying "foo" function that actually gets called.
