### ISSUE TITLE
Is there a need for HTML & PDF versions ?

### ISSUE THREAD

**Issue by rajmayank** [getify/You-Dont-Know-JS#1363]
I have a fork of the project [here](https://github.com/rajmayank/You-Dont-Know-JS) wherein each markdown is also available as HTML & PDF.
HTML files are generated by passing the markdowns through github markdown API and PDF conversion is dome via chromium browser.
I personally needed this so that I could print the chapters. 
Is there a need of a PR, or maybe setup of a simple pipeline so that they are available in this repo itself ?

**Comment by getify** [comment]
PDF distribution (even on github) is not allowed, per my publishing agreement with oreilly. I request you take it down.

**Comment by getify** [comment]
if you want printed copies of the books, you should buy them, that's why their on sale.

**Comment by rajmayank** [comment]
I have taken down all the PDF's.
My motivation behind putting them up were a few typos that I found in the books that are fixed in this repo. I'm sure there would be no major update to the content of this repo from the book as I see a lot of issues under "second edition" label but updated content is all I was after.

**Comment by getify** [comment]
Second edition updates will happen eventually. Trying to work that out.
