### ISSUE TITLE
Code example "isThisCool" in Ch3 "Types and Grammar", "Native Prototypes" throws error

### ISSUE THREAD

**Issue by komali2** [getify/You-Dont-Know-JS#1366]
Link: https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch3.md#native-prototypes

The code example is as follows:

```
function isThisCool(vals, fn, rx) {
    vals = vals || Array.prototype;
    fn = fn || Function.prototype;
    rx = rx || RegExp.prototype;

    return rx.test(
        vals.map(fn).join("")
    );
}

isThisCool();		// true

isThisCool(
    ["a", "b", "c"],
    function (v) { return v.toUpperCase(); },
    /D/
);
```

In node (latest version) and chrome (latest version), I get this error from the above code:

```
    return rx.test(
              ^

TypeError: Method RegExp.prototype.exec called on incompatible receiver [object Object]
    at Object.exec (<anonymous>)
    at Object.test (<anonymous>)
    at isThisCool (/home/calebjay/Documents/personal/test.js:6:15)
    at Object.<anonymous> (/home/calebjay/Documents/personal/test.js:11:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

**Comment by getify** [comment]
https://twitter.com/awbjs/status/1054960260186804224

**Comment by qwhatevera** [comment]
@getify For some reason，I can't access twitter，Could you tell me the reason please?

**Comment by getify** [comment]
Quoting his tweets:

> Starting with ES2015 RegExp.prototype is an ordinary object rather than an RegExp instance.  This is the case for most built-in prototypes except where we found significant compat issues. I think yours is the 1st RegExp proto issues I've heard of.
> 
> See step 3 https://tc39.es/ecma262/#sec-regexp.prototype.exec
