### ISSUE TITLE
Extending Object with Object.defineProperty - Setting & Shadowing Properties

### ISSUE THREAD

**Issue by basheerOct** [getify/You-Dont-Know-JS#1393]
I would like to thank you for your time and effort.

I just tested the following code on all major browsers `chrome, firefox, opera` and they did return the same result.

```
var a = {};
Object.defineProperty(a, 'team', {writeable: true, enumerable: true, value: 'AUS'});

let b = Object.create(a);

b.team = 'PK'
```
According to the first rule quoted below it should Shadow the `team` property onto `b` object as `a`
has property `team` with `writeable:true` but that's not the case. The property `team` isn't being shadowed onto `b`.

```
console.log(a) // Object { team: "AUS" }
console.log(b) // Object {  }
```
So any property defined through `Object.defineProperty` aren't being shadowed while it's contrary to when we define through `{}`.

```
var a = {team: 'awesome'};

let b = Object.create(a);

b.team = 'PK'

console.log(a) // Object { team: "awesome" }
console.log(b) // Object { team: "PK" }
```

> 1. If a normal data accessor (see Chapter 3) property named foo is found anywhere higher on the [[Prototype]] chain, and it's not marked as read-only (writable:false) then a new property called foo is added directly to myObject, resulting in a shadowed property.
>2. If a foo is found higher on the [[Prototype]] chain, but it's marked as read-only (writable:false), then both the setting of that existing property as well as the creation of the shadowed property on myObject are disallowed. If the code is running in strict mode, an error will be thrown. Otherwise, the setting of the property value will silently be ignored. Either way, no shadowing occurs.
>3. If a foo is found higher on the [[Prototype]] chain and it's a setter (see Chapter 3), then the setter will always be called. No foo will be added to (aka, shadowed on) myObject, nor will the foo setter be redefined.

**Regards,
Basheer A**

**Comment by CoolRice** [comment]
I have the same question.

**Comment by teksaver** [comment]
Hi,

IMHO it is due to rule 3: ObjectProperty defines a setter, so rule 3 applies.

> If a foo is found higher on the [[Prototype]] chain and it's a setter (see Chapter 3), then the setter will always be called.

Source : [https://javascriptplayground.com/es5-getters-setters/](https://javascriptplayground.com/es5-getters-setters/l)

**Comment by teksaver** [comment]
Hi,
 ```
> var a = {};
> Object.defineProperty(a, 'team', {writeable: true, enumerable: true, value: 'AUS'});
 ```
There is a typo in the example - **writeable** should be **writable**
