### ISSUE TITLE
Elipses ...

### ISSUE THREAD

**Issue by landonsanders** [getify/You-Dont-Know-JS#1406]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

Hey, Man! Thanks for You Don't Know JS's. They are the best things in life! 

Your elipses all have two dots. An elipsis is three dots,

**Comment by getify** [comment]
I intentionally use `..` in code/comments instead of a full a `...` because the `...` is an actual operator as of ES6 and I don't want there to be confusion.
