### ISSUE TITLE
This & Object Prototypes Ch6 - De-class-ified

### ISSUE THREAD

**Issue by web-man** [getify/You-Dont-Know-JS#1412]
Hi guys,

In [this](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch6.md#de-class-ified) part of the book you said: Delegation is simpler because we don't need Controller class or object. That doesn't make sense because when AuthControler fails we will get message: "Login invalid: Auth failed: " + err. So we need Controller object if we want custom fail message for AuthController.

Thanks,
Igor

**Comment by getify** [comment]
Are you referring to this section?

> We didn't need a base Controller class to "share" behavior between the two, because delegation is a powerful enough mechanism to give us the functionality we need. We also, as noted before, don't need to instantiate our classes to work with them, because there are no classes, just the objects themselves. Furthermore, there's no need for composition as delegation gives the two objects the ability to cooperate differentially as needed.

**Comment by web-man** [comment]
@getify Yes

**Comment by getify** [comment]
Well...

> We didn't need a base Controller class...
> We also... don't need to instantiate our classes... just the objects themselves.

So I think you may be mis-reading. I'm not saying we don't need objects, **we do**. I'm only saying we don't need classes to **get** those objects.

**Comment by web-man** [comment]
Hmm, I understand that.

You said:

> The main takeaway from this second code listing is that we only have two entities (LoginController and AuthController), not three as before.

So I thought that you wanted to get the same output like the output from previous example. In the previous example when AuthController fails the output is "Auth failed: " + err, but in the second you get ""Login invalid: Auth failed: " + err, because there is no Controller object.

**Comment by web-man** [comment]
Oh, thank you for clarifying. Sorry for interrupting.
