### ISSUE TITLE
Cheat sheet for every chapter

### ISSUE THREAD

**Issue by harshitjuneja** [getify/You-Dont-Know-JS#1419]
Do you think adding cheat sheet (one per chapter) with just the bullets and one-liners would add additional value for people who have read the book in the past and just want to get a very quick glimpse of content they learned for that particular topic? I am happy to begin such a contribution.

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)**

**Comment by npoku** [comment]
I thought the reviews at the end of each chapter does a good job. But I did create flash-cards on my end just to help me extract items in better detail than maybe the review does. It will be good to see others thoughts. I will be willing to help make it possible if needed.

**Comment by getify** [comment]
I think these sorts of resources are great but not quite appropriate in the book itself. I encourage additional resources outside and around the book. Many have done similar things, and I think it's great. :)
