### ISSUE TITLE
types & grammar - ch3 - Natives as Constructors - Array: FF example outdated

### ISSUE THREAD

**Issue by ilya-k-v** [getify/You-Dont-Know-JS#1422]
Example of console output with empty sloted array in recent Firefox is outdated.

> Worse than that, at the time of writing, Firefox reports [ , , , ] for a and c. ...

Actual console output:
`Array(3) [ <3 empty slots> ]`

**Comment by ryanhaining** [comment]
The chrome examples are outdated as well.

> The serialization of a in Chrome is (at the time of writing): `[ undefined x 3 ]`. This is really unfortunate.

What I see is `(3) [empty × 3]`

A bit lower:

> For `b` (in Chrome, currently), you'll find `[ undefined, undefined, undefined ]` as the serialization, as opposed to `[ undefined x 3 ]` for `a` and `c`.

But I again see `[empty × 3]` in the chrome console for `a` and `c`

**Comment by getify** [comment]
Both browsers' devtools finally fixed what I spent several years trying to convince them to do. :)
