### ISSUE TITLE
"chapter 6: this & Object Prototypes": error occurs on example code #5 when trying to invoke 'super' on non 'constructor' method

### ISSUE THREAD

**Issue by huangc28** [getify/You-Dont-Know-JS#1423]
I ran into error when trying to execute example code #5 counting from the top to bottom on jest:

```js
class C extends P {
  foo() {
    super()
  }
}

var c1.foo()
c1.foo()
```

the error states:

```
super() is only valid inside a class constructor. Make sure the method name is spelled exactly as 'constructor'.
```
the above code is ran after being transpiled by `@babel/plugin-transform-classes`

I am wondering if the example code tend to be: 

```js

class C extends P {
  foo () {
    super.foo()
  }
}
```

then `c1.foo()` can then be found via `super` binding 1 level higher the than the current position in the prototype type chain, that is,  `class P`.
Should this content be fixed to avoid error popping?

**Comment by getify** [comment]
Known issue: #586
