### ISSUE TITLE
{} + []gives the same as [] + {}, but book reports differently

### ISSUE THREAD

**Issue by vineetpanwar** [getify/You-Dont-Know-JS#1445]
Hi, i was going through the types and Grammer , Chapter 5. I found this wrong while executing as a   code.
{} + [] gives the same as [] + {} which is "[object Object]", but book reports differently to both the cases.
![image](https://user-images.githubusercontent.com/26851334/55212335-5c6dc780-5215-11e9-8b1a-cfeede783932.png)

**Comment by KirankumarAmbati** [comment]
**Chrome console returned this:**

![js-twik](https://user-images.githubusercontent.com/9110567/55227247-f39a4580-523c-11e9-8a88-8d41cd72ced8.PNG)

**Comment by getify** [comment]
You put both into a console.log() statement, which makes both of them expressions, so yes they will be the same.

The point of the book section in question is when they're in statement positions (as shown by @KirankumarAmbati), the `{} ` is taken as a separate block statement when it's at the beginning.

**Comment by vineetpanwar** [comment]
hey @getify , thanks for clearing the confusion.@Kiran thanks for the timely response. It is correct
