### ISSUE TITLE
this & Object Prototypes Ch: 2

### ISSUE THREAD

**Issue by p-brighenti** [getify/You-Dont-Know-JS#1451]
Hello! First of all, thanks for taking the initiative on writing these books, they're amazing!

I hope this is the correct issue category as it's not really an error in the code per say (as in, not in any of the snippets), but rather a potential issue with one of the explanations given.

The sentence I'm referring to is the following:

> When a function is invoked with new in front of it, otherwise known as a constructor call, the following things are done automatically:

Maybe I'm misinterpreting this line, but wouldn't it be more correct to say:

> When a function is invoked with new **preceding it**, otherwise known as a constructor call, the following things are done automatically:

If so, please let me know and I'll open a PR.

Thanks in advance!

**Comment by getify** [comment]
What do you mean by "more correct"? The phrase "in front of" and the word "preceding" mean the same thing in this context, as far as I can tell.

**Comment by p-brighenti** [comment]
Then it turns out it's just my interpretation. By saying in front I associate it with the word being written after the mentioned word. Maybe it's due to my native tongue and I always thought in english "in front" (in this context) was associated with "after".

Nevermind then and thanks for taking some time to answer!
