### ISSUE TITLE
'this' and 'use strict' output in Firefox scratchpad

### ISSUE THREAD

**Issue by induratized** [getify/You-Dont-Know-JS#1454]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

In [ch2 - this & Object Prototypes](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch2.md#default-binding)

- the 'use strict' example say 

>  the strict mode state of the call-site of foo() is irrelevant.

but in the the example below (with 'use strict enabled on **call-site**) gives following result in Firefox (v64.0) scratchpad

```javascript

function foo() {
  console.log('this.a = '  + this.a);
}

var a  = 'a';

(function() {
  'use strict';
  foo();
})();

// OUTPUT
/*
Exception: TypeError: "a" is not a function
@Scratchpad/1:17:10
*/
```

Can you explain this behavior ?

Thanks.

**Comment by getify** [comment]
I don't understand that error, and I don't get that when I run it in Firefox (or Chrome):

<img width="392" alt="Screen Shot 2019-04-15 at 11 47 12 AM" src="https://user-images.githubusercontent.com/150330/56150332-4af62080-5f74-11e9-93da-fb05464f4aaa.png">

**Comment by induratized** [comment]
Yes indeed. I retried and got the positive result. 
It wasn't giving me this result yesterday. 

Thanks for your time and such amazing JS content

Closing the issue !
