### ISSUE TITLE
this & Object Prototypes Ch: 3

### ISSUE THREAD

**Issue by StevenYuysy** [getify/You-Dont-Know-JS#1455]
> Error objects are rarely created explicitly in code, but usually created automatically when exceptions are thrown. They can be created with the constructed form new Error(..), but it's often unnecessary.

I can not understand why using `throw new Error('..')` is often unnecessary. I use it a lot while writing code, for `new Error` can provide message, error code stack, and I think it is very helpful for debug and error handling.

Is there any one can explain how to understand `They can be created with the constructed form new Error(..), but it's often unnecessary.`?

Thanks for answering.

**Comment by AminHadei** [comment]
The `throw expression;` generates an exception with the value of expression. it could be string, numeric, boolean (also any other kind of custom types for user-defined exception) or an instance of Error objects.
I think this quote means:

> the throw can generate an exception from an instance of Error objects, but it's often unnecessary.

and I think this picture below almost show you the difference between these two kind of throwing exceptions:

<img width="306" alt="Screen Shot 2019-04-27 at 10 48 08" src="https://user-images.githubusercontent.com/7405886/56845854-baf19880-68dc-11e9-8704-cd854fdc75e7.png">

**Comment by StevenYuysy** [comment]
Thx @AminHadei
