### ISSUE TITLE
Chapter 1: What is Scope? - Poor wording

### ISSUE THREAD

**Issue by JPritchard9518** [getify/You-Dont-Know-JS#1459]
In the "Back & Forth" section within the 2 points where it describes how the compiler will proceed. The compiler point contained the sentence "The code Engine runs will first ask..." which sounds and feels  grammatically wrong. I think it reads better as "When the code Engine runs, it first asks...". I may be reading the original text wrong, but wanted to throw this out there just in case it improved the flow of reading.

**Comment by getify** [comment]
I believe the original text means "The code *that* Engine runs will first ask..."

**Comment by JPritchard9518** [comment]
Ah yes, that makes sense! Definitely read it wrong. Thanks!
