### ISSUE TITLE
question: why doesn't Javascript have optional static typing ? 

### ISSUE THREAD

**Issue by catastrop** [getify/You-Dont-Know-JS#1478]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by askirmas** [comment]
```<flood>```
1. [PHP has](https://www.php.net/manual/en/control-structures.declare.php)
```php
declare(strict_types=1);
```
while things are that PHP tries to repeat destructing, common to ```object```&&```array``` syntax to access properties||keys and etc. Once JS repeat PHP, PHP will try to repeat it and the situation will becomes like PHP repeats PHP - or infinite loop, or Pandora's box. I prefer not to know what really will happen.
2. Microsoft will disappear. 
3. Add TS as git submodule
4. Add TS as production dependency - dev count will be obviously less
5. ~Write you're own~ Just copy their repo content to your projects
6. Less bugs - less threshold - less salary
7. Nobody will say but engines also tired to be straight
```</flood>```
