### ISSUE TITLE
ReDoS

### ISSUE THREAD

**Issue by inf3rno** [getify/You-Dont-Know-JS#1490]
In my opinion at least mentioning [ReDoS ](https://en.wikipedia.org/wiki/ReDoS) and catastrophic backtracking vulnerability by regex should have been a part of the performance book. I tried to find any mentioning of these, but found nothing. I am not sure if I can send a "feature request" like this, since the book is complete according to the readme.

**Comment by getify** [comment]
It's an interesting topic, and tangentially related to why TC39 hasn't updated regexes for a very long time until recently (ES2018) -- they wanted to make sure not to change regexes in a way that made them more susceptible to this problem.

But it's not clear to me why it's particularly relevant to JS developers, especially from the performance perspective?

Are you suggesting that JS devs need to be more careful in the regexes they create? That's not really DOS, though. If they write a really bad regex accidentally, that's just them making mistakes. AFAICT, these attacks are really only troublesome if the user provides regular expressions that the program runs. That's pretty rare in JS land.

**Comment by inf3rno** [comment]
@getify It is very easy to write an evil regex if the developer does not know anything about this problem, it doesn't have to be user input. Before reading about this vulnerability I expected regex to always run at most in 10-20 msec, not for minutes or hours. I think most of the devs never heard of this vulnerability. It does not just cause DoS if there is an attacker, but a badly designed regex can slow down writing even by accident. So I think it is a performance issue too.

**Comment by getify** [comment]
Do you have an example of a regex that a JS dev might "accidentally" write which would suffer from this performance problem?

**Comment by getify** [comment]
This is interesting on the topic: https://medium.com/@erik_68861/regexp-backtracking-in-loops-and-how-we-can-optimize-it-away-ef3b2590f87e

It seems that current JS engine regexp implementations are attempting to optimize away many/most of these issues.

**Comment by inf3rno** [comment]
The most simple example is `(a+)+`. There are many real life examples in several articles in the topic...

```js
var Benchmark = require('benchmark');

var evilRegex = /^(a+)+$/g;
var harmlessRegex = /^a+$/g;

var a5 = "aaaaa";
var x = "x";
var string5 = a5 + x;
var string10 = a5 + a5 + x;
var string15 = a5 + a5 + a5 + x;

var suite = new Benchmark.Suite();
suite.add("Evil regex 5", function () {
    evilRegex.lastIndex = 0;
    evilRegex.test(string5);
});
suite.add("Evil regex 10", function () {
    evilRegex.lastIndex = 0;
    evilRegex.test(string10);
});
suite.add("Evil regex 15", function () {
    evilRegex.lastIndex = 0;
    evilRegex.test(string15);
});
suite.add("Harmless regex 5", function () {
    harmlessRegex.lastIndex = 0;
    harmlessRegex.test(string5);
});
suite.add("Harmless regex 10", function () {
    harmlessRegex.lastIndex = 0;
    harmlessRegex.test(string10);
});
suite.add("Harmless regex 15", function () {
    harmlessRegex.lastIndex = 0;
    harmlessRegex.test(string15);
});

suite.on("cycle", function (event) {
    console.log(String(event.target));
});
suite.on("complete", function () {
    console.log('Fastest is ' + this.filter('fastest').map('name'));
});
suite.run({"async": true});

/*
    Evil regex 5 x 4,624,465 ops/sec +0.28% (96 runs sampled)
    Evil regex 10 x 152,530 ops/sec +0.13% (95 runs sampled)
    Evil regex 15 x 4,835 ops/sec +0.38% (96 runs sampled)
    Harmless regex 5 x 38,511,774 ops/sec +0.14% (98 runs sampled)
    Harmless regex 10 x 29,270,877 ops/sec +0.12% (96 runs sampled)
    Harmless regex 15 x 20,685,704 ops/sec +0.29% (92 runs sampled)
*/
```

**Comment by inf3rno** [comment]
I checked with a "string30", so 30 "a" and 1 "x" at the end too, I just did not want to include it in the example.

```js
// Evil regex 30 x 0.13 ops/sec +14.73% (5 runs sampled)
```

**Comment by getify** [comment]
Well it's interesting and I've definitely learned something. Appreciate you calling it out.

But this is a ridiculously niche topic. I don't think it's appropriate for a general book on JS. It's also not really a "performance" issue as much as it is a regex issue. It belongs in a book on regexes, which is not something I'm remotely qualified to write.

Thanks again for bringing it up!

**Comment by inf3rno** [comment]
Okay, no problem. I appreciate your link, it is something I was looking for. You can read here about the topic in details: https://www.regular-expressions.info/catastrophic.html I really like this site, I remember learning regex from here ages ago. I think it is the best site in the topic.

What I find interesting that you can solve this backtracking issue with atomic groups in many cases. Sadly JS does not support those, but I just found an old article about how to polyfill atomic groups: http://blog.stevenlevithan.com/archives/mimic-atomic-groups I think that is at least a partial solution in the topic. I tried it out and this atomic grouped version was even faster on my PC than the harmless one: `/^(?=((a+)+))\1$/g`.

I am working on a regex generator library that uses OOP to describe patterns in a more readable way and after that the regex will be automagically generated. It would be a nice feature to generate only harmless regex, so I try to solve this. It appears to be a very hard problem, at least I don't feel I fully understand it even after reading many articles.
