### ISSUE TITLE
On Understanding of new keyword

### ISSUE THREAD

**Issue by itzfyp** [getify/You-Dont-Know-JS#1499]
Hi Kyle,

There is a confusion on understanding of new keyword.

**Class**
```
class Test{
	constructor(){
		this.name = 'kyle'
	}
	
	show() {
		console.log('displaying name:', this.name);
	}
}
```

then we are calling Test class with new keyword like

> var withCallingBrackets = new Test();

> var withOutCallingBrackets = new Test;

Both are returning Object with same properties / methods which has. 
Accessing of both object props / methods are displaying same result.

As of my understanding calling a function /  class with new key word, below things are happening

> When a function is invoked with new in front of it, otherwise known as a constructor call, the following things are done automatically:
> 
> a brand new object is created (aka, constructed) out of thin air
> the newly constructed object is [[Prototype]]-linked
> the newly constructed object is set as the this binding for that function call
> unless the function returns its own alternate object, the new-invoked function call will automatically return the newly constructed object.

My Questions :

1.  Is the second approach ( withOutCallingBrackets ) also following above procedure to create new object and injected with this
2. Are both objects same or have subtle internal difference. 

Please give us some input on this.

Thanks in advance.

**Comment by getify** [comment]
JS has a strange syntactic affordance which is that, for `new` only, if there is no arguments to pass, you can drop the `( )` on the end of the call. I think this is a really bad idea because it will confuse readers, but it is legal in that case, and yes it does the same thing as if they were present.

**Comment by itzfyp** [comment]
Thanks Kyle.

It will be grate for YDK JS readers if this differentiation added as hint in NEW binding section or Object creation section.
