### ISSUE TITLE
Hoisting With Compiler & ScopeManager Conversation

### ISSUE THREAD

**Issue by muradsofiyev** [getify/You-Dont-Know-JS#1501]
```
var foo;
function foo() {
    console.log( foo );
}
console.log(foo);
```

Compiler: Hey scope do your hear foo identifier

Scope: No I Declare Variable

Compiler: Hey scope do your hear foo identifier

Scope: Yes I declare foo a second ago

Compiler: Okay skip this declaration

This process don't run like this but we say before if Scope found any declaration skip next declaration. In there function declaration can override variable declaration. 
Is that mean functionDeclaration declare first in scope at compiler time? If you answer yes. Why? Why we need to first declare functionDeclaration in scope?

**Comment by getify** [comment]
Skipping a duplicate identifier declaration (which happens) is not the same thing as skipping a function itself (which does not happen).

**Comment by muradsofiyev** [comment]
And I also read Ecma Spesification  http://www.ecma-international.org/ecma-262/5.1/#sec-10.5 in there functions are given higher priority than var statements. Why function declaration happens before than var?  Do you know reason this? Thank You It was my last stupid question for you )))

**Comment by getify** [comment]
> Do you know reason this?

I sure don't. Sorry!

**Comment by muradsofiyev** [comment]
Thank you for great book, great video content in Frontend Masters and Answers :)
