### ISSUE TITLE
EcmaScript new version  ES5 (and higher) don't use "activation object" longer

### ISSUE THREAD

**Issue by muradsofiyev** [getify/You-Dont-Know-JS#1506]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**

**Edition:** (1st or 2nd)
 YDKJS 1st edition 
**Book Title:**
   this & Object Prototypes
**Chapter:**
   this Or That?
**Section Title:**
   What's this?
**Problem:**
 In there you use "Activation Object" terminology but I think you must be use Lexical Environment termin.
Because ES5 (and higher) added "Lexical Environment" termin and "Activation Object" is old termin.
Also I think You must be talk Lexical Environment, Environment Record in 2nd Edition Scope & Closure book and people good undertstand what is going here.

**Comment by muradsofiyev** [comment]
http://dmitrysoshnikov.com/ecmascript/es5-chapter-3-2-lexical-environments-ecmascript-implementation/

**Comment by getify** [comment]
I'll take it under consideration for second edition.
