### ISSUE TITLE
Clarify top/last in Implicit Binding

### ISSUE THREAD

**Issue by stcalica** [getify/You-Dont-Know-JS#1516]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**
I already searched for this issue. 

**Edition:** 2nd (1st or 2nd)

**Book Title:** `this` & Object Prototypes

**Chapter:** 2,  `this` All Makes Sense Now!

**Section Title:** Implicit Binding

**Problem:**

You state this: 

> Only the top/last level of an _object property reference chain_ matters to the call-site. For instance:

And obj1 would be the top level but you returned from obj2? 
Is that right? 
When you mean top-level did you mean the last one right before or the one starting the call? 

I think adding top is confusing me. I believe stating the last of the _object property reference chain_ would clarify this better than "top/last". 

```
function foo() {
	console.log( this.a );
}

var obj2 = {
	a: 42,
	foo: foo
};

var obj1 = {
	a: 2,
	obj2: obj2
};

obj1.obj2.foo(); // 42
```

https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/this-object-prototypes/ch2.md#implicit-binding

**Comment by getify** [comment]
Thank you for the suggestion, I'll take it into consideration.
