### ISSUE TITLE
Implicitly Lost With "Indirect Call"

### ISSUE THREAD

**Issue by muradsofiyev** [getify/You-Dont-Know-JS#1517]
Hello @getify .

I read about Implicit binding from your book and in there you talk about "Implicitly Lost". I think I understand your examples in book. 
For example I can explain why "Implicitly Lost" happening in bellow example. 
```
var bar = obj.foo;
bar();
```
But I saw some another "Implicitly Lost" versions.
1. Call "method" with comma operator (aka Indirect Call) - (0, obj.foo)()
2. Call "method" with logical operators - (true && obj.foo)();

In above examples I really don't understand why "Implicitly Lost" happened and what is difference above examples with **(obj.foo)().**

Actually I have some estimates but I don't know there are true or not.

One of my estimate is in compile time Engine know which operator can create "Implicitly Lost" but this is only estimate.

Second estimate is "Implicitly Lost" reason is **GetValue** internal method.

I think I need someone's help.
Thank you.

**Comment by getify** [comment]
A direct invocation is where the `(..)` part is immediately and directly attached to the function it's invoking. Anything that's not a direct invocation is indirect.

In both the `,` and `&&` cases you cited, the function's reference value is the result of the of the expression, so when it's then "later" invoked, it's an indirect invocation.

**Comment by muradsofiyev** [comment]
Thanks for response. 
Does compiler know function call type (direct or indirect) before run time?
