### ISSUE TITLE
Translate into Ukrainian

### ISSUE THREAD

**Issue by Croftyland** [getify/You-Dont-Know-JS#1520]
Hi @getify, 

I've read the Contributions Guidelines, checked issues and clearly understand that should wait for your 2nd edition. 
Is it a good idea to start to translate the works that you have done or better to wait for a green light?

Look forward to your reply

**Comment by getify** [comment]
I would recommend waiting until the 2nd edition books are done before starting translation.

**Comment by Croftyland** [comment]
Is it going to be soon?

**Comment by getify** [comment]
I expect by early-to-mid Q1.

**Comment by Croftyland** [comment]
Thank you so much for the information! 
Good luck
