### ISSUE TITLE
Context in Generators

### ISSUE THREAD

**Issue by muradsofiyev** [getify/You-Dont-Know-JS#1527]
When we talk about context we say we have 4 type to check what is this (context) referenced in function. But what about Generators? In generators also have **this** and you don't talk about Generators in "this & Object Prototypes" book.

**Comment by getify** [comment]
It's less common to use `this`-aware generators. Not unheard of, though. However, there's nothing particularly different from the discussion of normal functions, with respect to how `this` works. The `this` is determined at the initial invocation of the generator, and remains the same throughout its entire lifetime.
