### ISSUE TITLE
globalThis.undefined is not reassignable in modern environments

### ISSUE THREAD

**Issue by CertainPerformance** [getify/You-Dont-Know-JS#1532]
I already searched for this issue:

**Edition:** 2nd

**Book Title:** You Don't Know JS Yet: Types & Grammar

**Chapter:** 2: Values

**Section Title:** Special Values/[Undefined](https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/types-grammar/ch2.md#undefined)

In environments which are compliant with ES5 (which includes the vast majority of browsers and Node), the `undefined` property of the global object is not reassignable, because its property descriptor is not writable. Rather, in sloppy mode, the assignment will fail silently - the global `undefined` identifier will continue to contain `undefined`. It's not so much a "really bad idea" (though it is) as much as it doesn't do anything at all (at least in the vast majority of environments nowadays).

One option is to tweak the section so that it's more inline with ES5+. On the other hand, one might consider the silent failure to be more *interesting trivia* than *essential information* nowadays. It may not be important enough to be worth mentioning here - another option would be to remove that part completely, and only keep the part that warns against creating a local variable named `undefined`.

**Comment by getify** [comment]
Did you see this note near the top of that chapter?

| NOTE: |
| :--- |
| Everything below here is previous text from 1st edition, and is only here for reference while 2nd edition work is underway. **Please ignore this stuff.** |

Also, quoting this section of the [CONTRIBUTING.md](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md):

## Editions

The current edition (*work in progress*) of the books is the 2nd edition. While these 2nd edition books are in progress, contributions are OK, but **there's no need to jump the gun early** while I'm still working on stuff. That's what "work in progress" means. :)

| NOTE: |
| :--- |
| **ALSO**, please note that while a book is in progress, the previous 1st edition text may be included at the bottom of each file, and marked as such. Please ignore this text, as contributions there are not relevant. |

I **am not accepting any contributions** for 1st edition books.
