### ISSUE TITLE
Youtube video translation to slovak

### ISSUE THREAD

**Issue by cundamic** [getify/You-Dont-Know-JS#1533]
I will  "audiotranslate" YDKJSY to Slovak  using YouTube. Is it OK?

**Comment by getify** [comment]
Isn't audio pretty difficult to convey code snippets?

**Comment by cundamic** [comment]
I show original text source on video and translate it live to Slovak.

**Comment by getify** [comment]
Could you post a 5 minute sample so I could get an idea?

**Comment by getify** [comment]
Closing for now, let me know if you get a sample for me to review.
