### ISSUE TITLE
Get Started, Ch. 2: Function Parameter Declaration

### ISSUE THREAD

**Issue by glitchassassin** [getify/You-Dont-Know-JS#1537]
**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** (1st or 2nd) 2nd

**Book Title:** You Don't Know JS Yet: Get Started

**Chapter:** 2

**Section Title:** Variables

**Problem:** The following explanation is given for function and parameter identifiers:

> Here, the identifier hello is created in the outer scope, and it's also automatically associated so that it references the function. But the named parameter name is created only inside the function, and thus is only accessible inside that function's scope.
> 
> Both hello and name act generally as if they were declared with var.

But because the parameter is only accessible inside the function's scope, doesn't that mean that `name` acts generally as if it was declared with `let`? 

If there is a substantive difference that I'm missing, could you elaborate on it?

Thanks!

**Comment by getify** [comment]
'var' has always scoped variables to functions, that's why it's the closest match for describing the scope of a parameter.

'let' adds variables to a local block (if, for, etc) that is a subset of a function scope.

**Comment by glitchassassin** [comment]
Aha! I was looking at the previous example of block scoping, where `var` was accessible outside the block, and confused the two in my mind. But var doesn't break out of functions:

```
function test() {
    var name = "Kyle";
}
test();
console.log(name) // Error!

if (true) {
    var age = 39;
}
console.log(age) // 39
```

Thanks, that clears up my confusion!

**Comment by lynus** [comment]
I had the same confuse when I first encounter the example in the text. I suggest the author considering adding a footnote to further explain that 'var' always scope variables to functions
