### ISSUE TITLE
"Types & Grammar": language type names need to be uppercase or lowercase?

### ISSUE THREAD

**Issue by dragonishare** [getify/You-Dont-Know-JS#1538]
**Chapter1: Types**
At the beginning of the chapter, the language type name is uppercase; in the Built-in Types section, it is lowercase. as follows：

“The ECMAScript language types are  **Undefined, Null, Boolean, String, Number, and Object**.”

**Built-in Types**
JavaScript defines seven built-in types:

null
undefined
boolean
number
string
object
symbol -- added in ES6!
Note: All of these types except object are called "primitives".

I am confused

**Comment by getify** [comment]
This book has not yet been worked on in second edition. Please hold off on issues for books until they've actually been written.

**Comment by dragonishare** [comment]
> This book has not yet been worked on in second edition. Please hold off on issues for books until they've actually been written.

I mentioned above in the first edition。Does it have some errors? 

I refer to some information and found that the first letter of the language type is capitalized. such as 
《Professional JavaScript for Web Developers 3rd》、[JavaScript data types and data structures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) and [ES5.1 specification](http://www.ecma-international.org/ecma-262/5.1/#sec-4.3.1)
