### ISSUE TITLE
Foreword (by Brian Holt) wrongly redirects to Becky Holt

### ISSUE THREAD

**Issue by tsphoenix** [getify/You-Dont-Know-JS#1541]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**
I already searched for this issue
**Edition:** (1st or 2nd)
2nd
**Book Title:**
You Don't Know JS Yet: Get Started - 2nd Edition
**Chapter:**
Table of Contents
**Section Title:**
Foreword (by Brian Holt)
**Problem:**
Foreword (by Brian Holt) hyperlink wrongly redirects to Becky Holt:
https://twitter.com/btholt
It should be:
https://twitter.com/holtbt

**Comment by getify** [comment]
thx
