### ISSUE TITLE
Function Declaration With Block Scope

### ISSUE THREAD

**Issue by muradsofiyev** [getify/You-Dont-Know-JS#1544]
If you remember you talked about Function Declarations in Hoisting Chapter and you said "However, it's important to note that this behavior is not reliable and is subject to change in future versions of JavaScript"
Today I saw function declaration not hoisted to outer function scope. But interesting part we can access inner function identifier from outer scope but it's result undefined. Is this meaning in there have LHS? Because compiler/parsing time **test** is declared in outer scope but value assigned when interpretor arrive block scope :/ 
```
(function main() {
    console.log(test);
    if(true) {
        function test() {

        }
    }
})();
```

**Comment by getify** [comment]
This has been addressed in the second edition work.
