### ISSUE TITLE
Editorial Review - Get Started, Chapter 2

### ISSUE THREAD

**Issue by simonstl** [getify/You-Dont-Know-JS#1545]
Editorial review, not a searchable issue.

**Edition:** (1st or 2nd)  2nd

**Book Title: Get Started**

**Chapter: 2**

In some ways, this is the hardest chapter in the entire series.  It covers a vast amount of terrain in a mere 20-ish pages, isn't really allowed to focus, and has to set expectations for a lot of people who come from other places.

I have one concern about the overall chapter organization.  Objects need more emphasis, especially on informal use without full-on class declarations. This is the heart of the programming language, and especially the zone that confuses people coming from other approaches.  Consider giving objects their own section - right now, they hide in "Values".  Also, important to note that objects can also contain functions, even in the absence of classes.

If, as I hope, you reorganize this, I will want to take another pass over the chapter afterward.

**Intro:**

The first paragraph - "there's no substitute" - is weirdly static.  Can we make this one explicitly welcoming?  Something like: "

> The best way to learn JavaScript is to write JavaScript.  You don't need to know a lot to get started on that, but you do need a core set of foundations.  Much of this may seem familiar if you've programmed in other languages, but it's worth the review to set your JavaScript expectations.  Take your time, and try things out."

In general, I strongly recommend reviewing the first paragraphs of every chapter when you're done writing the rest, and a pass over them at the very end of the process, so this will probably be a repeating theme. (Readers love chapter breaks because they feel they completed something, but also often drop off at the start of a new chapter, so motivation is especially important here.)

**Files As Programs:**

I'm wondering if "Each File is a Program" would be a better headline than "Files As Programs".  Make it more of a statement, more of a challenge. It might also make sense to mention that tools often combine all of the JavaScript into one file for delivery.

**Values:**

The values section is difficult, critically important, and feels to me like it has too much in one section.  

I mentioned that objects need more visibility in the chapter organization, but I also get a bit lost with leaping into arrays right after numbers, and mixing in the while loop.  Especially given the complicated conversations around JS arrays, I'm thinking that it would be cleaner to have a section on literal values (and bring typeof forward to that!), then go to variables, and then go to fancier variable tricks.  Interpolation, arrays, functions, etc.  

After those foundations are set, I'd go to how these things get clustered into objects, probably as a separate Objects section, maybe after Variables.  (It's okay to mention that variables can contain objects while leaving objects to a later section.)

**Variables:**

The Variables section is more about declaring variables than using them. I think that's fine, but it would flow better if it appeared right after literal values per the discussion above.

**Functions:**

I'm pretty sure that "in the good ol' days of JS," we typically only used function declarations, the "one way to declare a function", but function expressions were always around. (If I'm reading 15.3.2 of https://ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%201st%20edition,%20June%201997.pdf correctly, anyway.)  I think this may be more of a change in use than a change in the language.  

Function expressions remain a surprise to people who come from languages that don't support them.  If you can pause for a moment and talk about the concept of storing a function in a variable (or object property), you might do them a lot of good.

Also, I'd expand the IIFE acronym in the JS comment that shows them to Immediately-Invoked Function Expression, or explain them, or maybe include the alternative description Self-Executing Anonymous Function.  I've given and received a lot of blank looks on that topic.  (I know this is quicksand. Expanding the acronym might be the easiest way to clarify without getting stuck.)

**Comparisons:**

This covers a lot of ground, some of JavaScript's most criticized ground. I love that you include comparisons in conditional expressions, something that often sneaks by. 

I'm thinking it might help to build some simple lists of the different kinds of equality testing, so people can see them in one place.  Also, coercion is defined in a Note, and a lot of people skip Notes.  I'd move that to main body text. (Maybe emphasize coercion in the section above on typeof, too?) 

**Code Organization:**

"Code Organization" doesn't seem like quite the right description for this section to me.  It's more "Tools for Organizing Code", and tools often only get used when code has reached a certain scale or needs to be shared in particular ways.  Classes, in addition to being new, often just aren't used at all.  Modules are, well, their  own excitement.  Maybe turn:

> "These patterns are not mutually exclusive; many programs can and do use both."

Into:

> "These patterns are not mutually exclusive; many programs can and do use both.  Some programs use one or neither."

I also suspect that you will have a subset of readers who assume that they already know all there is to know about variables and leap ahead to classes.  I'm not sure there's much you can do about it, but emphasizing that classes are optional might get them to look around more, especially at objects.

**Modules:**

I recommend turning the note on AMD, UMD, etc. into body text.  It's the first time you define those things, and then you use them later in the text.

"modules can utilize classic modules" -> "modules can use classic modules".  Unless you have a reason to go explicitly for "utilize", typically for variation or contrast with "use", just stick to the shorter and less bureaucratic "use".  (It's okay and easy to sort this with a search at the end of the writing process.)

**Before You Go On:**

I like this call to action - 

> "carefully consider and ensure you are comfortable with. I suggest re-reading this chapter, maybe a few times."

I wonder if that call could echo throughout the chapter - after some of the trickier code examples, encourage readers to try the code, and create their own variations?  Acknowledge in some of the more surprising points that they may want to read through things (and try them) a couple of times, to make sure they have it?  I think it's okay to say (maybe at the beginning of the chapter) that this is a compressed highlights version of content explored across the series, but focusing here will make things easier throughout.

I hope this helps! Let me know if you need more, less, or different.

**Comment by getify** [comment]
**Note:** These revisions included moving some content to a new Appendix A, called "Exploring Further" -- covering some of the deepest dives on the topics. "Practice" was moved to Appendix B.
