### ISSUE TITLE
Editorial Review, Get Started, Chapter 4

### ISSUE THREAD

**Issue by simonstl** [getify/You-Dont-Know-JS#1553]
Editorial review, not a searchable issue.

**Edition:** (1st or 2nd)  2nd

**Book Title: Get Started**

**Chapter: 4**

**Title** 

When I saw "The Rest", I expected a list of spare parts and interesting asides, not pillars and pathways.  Maybe rename this "The JavaScript Journey" or something like that?

**Opening**

The opening section does a much better job of telling the story than the title does, but it's still kind of... flat.  Congratulate readers on having seen what they've seen earlier in the book, invite them on the journeys (books) to come, and then get into the advice about pausing to explore and build.

**Pillars, Generally**

I like your three pillars, both as an organizational concept and for their content.  I'm a little confused by the function of the sections here. On the one hand, you're telling a broad story about how these tools provide the base of successful work in JavaScript.  On the other, you're getting into details about var and classes without really being able to provide the full context.

The scope of Pillar 3 seems most balanced to me.  It outlines why types and coercions are important, and points out the high points of controversy.  It doesn't, though, go into the case for a particular approach, instead setting up the reader to succeed with the more focused book.

**Pillar 1: Scope and Closure**

This section works well until you get to the Note.  I don't think you should have a note with that level of technical information in this kind of section (or chapter).  Worse, readers really have to read the note to understand the next paragraph.  It isn't an aside.

For this section, I don't think you need to point out people who claim that JavaScript isn't lexically scoped.  Instead, I recommend proceeding with your claim that it is, and alerting readers that they will want to pay close attention to hoisting, function scoping, and the "temporal dead zone", which reminds me too much of a Christopher Walken movie.  The details should come in the later book, where you have room to explore rather than just assert them.

**Pillar 2: Prototypes**

This section flows better than Pillar 1, but still tries to explain too much.  I'd emphasize that prototypes are a different approach to establishing cooperation and sharing among objects, and let behavior delegation hold the spotlight.  Note that prototypal inheritance and classes both build on this, but aren't excuses to avoid knowing the foundations, and even the strictest of functional programmers will still have to know how this works.  Emphasize the learner's need of this knowledge.

(Full disclosure, probably not surprising - I consistently recommend that everything be structured as FP as possible, while recognizing the structures JavaScript works are best centered on prototypes.)

**Pillar 3: Types and Coercion**

This section is broadly in great shape.  The only thing I'd suggest is rephrasing some of the warnings and general "don't" messaging to show more positively what JavaScript can do.  I don't generally claim that you need to accentuate the positive.  However, since the primary goal here is to get readers to continue into the later books, I think that approach will work better.

**In Order**

I think I'd move this to the end of the chapter, and move *With the Grain* ahead of it.  You're pretty much handing out paths away from this book here, but then readers find there's another section in the way of the end.  I might renumber the 1-6 list as 0-5, partly as a nod to JavaScript numbering, and partly because readers are at least theoretically through the first item at this point.

From my perspective, _Sync & Async_ is the heart of applying JavaScript skillfully, and I like the way you emphasize a complete understanding of the pillars before leaping into it.

Steal the last paragraph from *With the Grain*. Emphasizing practice and pointing into the appendix is exactly the right way to end the chapter.

**With the Grain**

As noted above, I think this should come before *In Order*, but the final paragraph should stay the final paragraph.

With my woodworking hat on, I ask that you point out that this is not grain like wheat, where you can move through a flow of kernels any way you want, but grain like wood.  If you plane wood from the wrong direction, you tear out the grain and make a mess.  It's kind of like the response you get if you pet a cat against the direction of its fur.  

The tone here is slightly cranky, but it's very appropriate to a warning section, so I don't recommend shifting it toward positivity.

**Comment by getify** [comment]
👍

**Comment by getify** [comment]
....and with that revision, the book is edit-complete! All that should be left it final polishes and any copy-editing.

@simonstl Please feel free to scan over the edited book (especially the new Appendix A) and share any additional thoughts you may have.
