### ISSUE TITLE
variables scope

### ISSUE THREAD

**Issue by parid0kht** [getify/You-Dont-Know-JS#1556]
2-end edition, get-started, ch2.md
under the **Variables** title

```
function hello(name) {
    console.log(`Hello, ${name}.`);
}
hello("Kyle");
// Hello, Kyle.
```
it is being said
> Both hello and name act generally as if they were declared with var.

I think this sentence is a bit confusing (for me at least), because the scope for hello and name are not exactly the same, the `name` acts like a declared var _within the function_. but they are mentioned together in the sentence.

**Comment by getify** [comment]
> as if they were declared with var

That doesn't mean "declared in the same scope" it means "the manner in which each is declared (in whatever scope) is like it was done with the 'var' keyword."
