### ISSUE TITLE
Appendix A: Comparison assignment - my Solution

### ISSUE THREAD

**Issue by BerendKemper** [getify/You-Dont-Know-JS#1562]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**

**Edition: 2nd** (1st or 2nd)

**Book Title: Get Started**

**Chapter: Appendix A**

**Section Title: Comparison assignment**

**Question: Which solution would you prefer?**

'use strict';

const dt = new Date();
const [year, month, day] = [dt.getFullYear(), dt.getMonth(), dt.getDate(),];
const dayStart = "07:30";
const dayStartDt = new Date(year, month, day, ...dayStart.split(':'));
const dayEnd = "17:45";
const dayEndDt = new Date(year, month, day, ...dayEnd.split(':'));

function scheduleMeeting(startTime, durationMinutes) {
    const scheduleStartDt = new Date(year, month, day, ...startTime.split(':'));
    const scheduleEndDt = new Date(Number(scheduleStartDt) + 1000 * 60 * durationMinutes);
    if (scheduleStartDt < dayStartDt)
        return console.log(false);
    if (scheduleEndDt > dayEndDt)
        return console.log(false);
    return console.log(true);
}

console.log('yMongol...');

scheduleMeeting("7:00", 15);     // false
scheduleMeeting("07:15", 30);    // false
scheduleMeeting("7:30", 30);     // true
scheduleMeeting("11:30", 60);    // true
scheduleMeeting("17:00", 45);    // true
scheduleMeeting("17:30", 30);    // false
scheduleMeeting("18:00", 15);    // false

**Comment by BerendKemper** [comment]
I even tested the time performance, these tests show that working with the "new Date()" is faster and more readable (to me).

**Comment by getify** [comment]
OK, there's plenty of ways to solve any task. But I like how I've presented it.
