### ISSUE TITLE
Can't find PDF of the current book

### ISSUE THREAD

**Issue by louiscb** [getify/You-Dont-Know-JS#1568]
I'd like an eBook or PDF of this current version of the repository. Online I can only find versions which are several years old. I've read the contribution guidelines on here and they say not to post these types of questions but I don't know where else to look as when I attempt to load the official website (https://t.co/LQR6WQLYTJ) I get a timeout error. I don't mind paying for it but I just simply can't find a place to do so.

**Comment by Celebes** [comment]
You can create it yourself using tool like https://pandoc.org/. That's what I am about to do right now.

**Comment by getify** [comment]
Which "current version" (edition 1 or 2) are we talking about, and which book in the series?

This repo doesn't provide PDFs and never has. PDFs (and other ebook formats) are made available for purchase on other sites. However, as we switch from 1st ed to 2nd, the 1st ed ebooks are no longer for sale, and the 2nd ed books are still being written.

**Comment by louiscb** [comment]
@Celebes ah thanks! If you have the PDF created anyway could you send it to me? It would be much appreciated.

**Comment by Celebes** [comment]
@louiscb well I started doing it, but during that I found out that 2nd edition is still being written and 1st edition is outdated, so I decided to pick another book (Professional JavaScript for Web Developers, 4th edition) in the meantime and wait for YDKJS 2nd edition to finish.

**Comment by louiscb** [comment]
@getify do you recommend waiting for this current edition of the book to be finished and released as an ebook then?

**Comment by getify** [comment]
yep :)
