### ISSUE TITLE
Function scoping statement is possibly wrong in 2nd Ed

### ISSUE THREAD

**Issue by kwccoin** [getify/You-Dont-Know-JS#1573]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**I already searched for this issue

**Edition:** (1st or 2nd) 2nd

**Book Title:** You do not know Javascript

**Chapter:** 2

**Section Title:** Declaring and Using Variables

**Question:** "Both hello and name act generally as if they were declared with var." is not right.  name is a function parameter and should be considered like "let/const".

**Comment by getify** [comment]
Duplicate: #1556 #1537
