### ISSUE TITLE
Add a .epub and a .pdf build, for those who want to read using an e-reader whilst offline

### ISSUE THREAD

**Issue by GeorgeWL** [getify/You-Dont-Know-JS#1588]
Markdown is a great format, but it's not readable by many e-readers, and I personally would love that as an option.

**Comment by getify** [comment]
From the contribution guide: https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/CONTRIBUTING.md#reading-experience-chaptersection-links-etc

**Comment by GeorgeWL** [comment]
@getify you mention paid for ebooks? I'd totally pay for one of those instead, but can't see a link to one on the readme. (I may just accidentally being blind)

**Comment by getify** [comment]
Currently the first edition books are "out of print" meaning oreilly removed them from being sold. I am writing the second edition books, and once each is published, it'll be available for purchase from (at least) leanpub (ebook/pdf) and amazon (kindle). Print form should also be available on amazon eventually, as well as hopefully some other retail channels.
