### ISSUE TITLE
Ch1: don't use terms like "JS6" or "ES8"

### ISSUE THREAD

**Issue by TJZXG** [getify/You-Dont-Know-JS#1594]
In chapter 1, **What's With That Name**, there is this note:
Don't use terms like "JS6" or "ES8" to refer to the language. Some do, but those terms only serve to perpetuate confusion. "ES20xx" or just "JS" are what you should stick to.

However the rest of the text uses exclusively ES6 instead of ES2015 in direct contradiction to this note. Suggest either editing the note or changing references of ES6 to ES2015.

**Comment by getify** [comment]
The note is about current references to the language name, not historical ones.

Up until only a few months before ES2015 shipped, it had been referred to, even officially, as ES6. The attempted change by TC39 at that late a moment didn't stick, as far as I'm concerned. Some of us had even published books with "ES6" in the title, so... ES6 is the name, as was ES5 and ES3.

Starting with the next revision, though, the naming change took effect, meaning from ES2016 forward, that's the name. Some kept trying to say "ES7" or "ES8", but those are inaccurate.
