### ISSUE TITLE
TDZ - let and const hoisting issue

### ISSUE THREAD

**Issue by ratneshmurugesangale** [getify/You-Dont-Know-JS#1611]
**Edition:** (2nd)

**Book Title:**  You-Dont-Know-JS

**Chapter:** Chapter 5

**Section Title:** Scope-closures -> Uninitialized Variables (aka, TDZ)

**Problem:**

Declared variable **studentName** inside block-scope is not hoisted to top of section and below error has been raised.

**Error Info:** Uncaught ReferenceError: Cannot access 'studentName' before initialization at <anonymous>:4:17

var studentName = "Kyle";
{
    console.log(studentName);
    // ???
    // ..
    let studentName = "Suzy";
    console.log(studentName);
    // Suzy
}
<img width="1676" alt="TDZ-let-const-hoisting-issue" src="https://user-images.githubusercontent.com/51107885/75133892-7607df80-5702-11ea-9bbd-2187c84e577d.png">

**Comment by getify** [comment]
> Declared variable studentName inside block-scope is not hoisted to top of section and below error has been raised.

Yes it *is* hoisted, that's the whole point of this code and the following 3-4 paragraphs explain exactly that.
