### ISSUE TITLE
Don't used parameter

### ISSUE THREAD

**Issue by YaroslavTER** [getify/You-Dont-Know-JS#1662]
Does this `a` parameter have a sense in this case?
Because it looks redundant.

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** 1st

**Book Title:** this & object prototypes

**Chapter:** 2nd

**Section Title:** Lexical this

**Problem:** unused parametr `a`
```javascript
function foo() {
	// return an arrow function
	return (a) => {
		// `this` here is lexically adopted from `foo()`
		console.log( this.a );
	};
```

**Comment by getify** [comment]
Asked several times before, please search existing issues.
