### ISSUE TITLE
Scope-Closures chapter 7 typo

### ISSUE THREAD

**Issue by xiangshang** [getify/You-Dont-Know-JS#1666]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** (1st or 2nd) 2nd

**Book Title:**Scope-Closures

**Chapter:** 7

**Section Title:**Live Link, Not a Snapshot

**Problem:** In the first code example in this section, 'function ' is missing.

**Comment by getify** [comment]
![Screenshot_20200509-075804](https://user-images.githubusercontent.com/150330/81474417-f64ec480-91ca-11ea-9be0-8dcd3659def4.jpg)

this one? looks fine to me.

**Comment by xiangshang** [comment]
@getify,  I'm so sorry.  It's my fault. The code that I downloaded is out of date. This typo existed in an old version, i.e. 680703646a53d47ab2a88e796b76253d0e32dbfc. 
![image](https://user-images.githubusercontent.com/4658590/81520118-e8897280-9375-11ea-9bb7-2661c5e59ac8.png)
