### ISSUE TITLE
scope & closures Ch.4

### ISSUE THREAD

**Issue by spencer17x** [getify/You-Dont-Know-JS#1677]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**

**Edition:** (1st or 2nd) 1st

**Book Title:** Scope & Closures

**Chapter:** Chapter 4: Hoisting 

**Section Title:** Functions First

**Question:** 

```js
foo(); // "b"
var a = true;
if (a) {
   function foo() { console.log( "a" ); }
} else {
   function foo() { console.log( "b" ); }
}
```
in chrome, Why is this code wrong, it will be throwing a TypeError。Is it because of a browser update？

```js
var a = 0;
if(true){
    a = 1;
    function a(){}
    a = 21;
    console.log("inner",a); // 21
}
console.log("outer",a); // 1
```
And how do I understand this code, the outer output 1, Is the function hoisted to block-level scope?

**Comment by getify** [comment]
See this section in the second-edition of this book:

https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/scope-closures/ch6.md#function-declarations-in-blocks-fib

**Comment by spencer17x** [comment]
@getify I read it, it means that I don’t have to dig into it, but try to avoid it?

**Comment by getify** [comment]
The best sense I can make of it is... yeah, just don't put function declarations inside of blocks.

**Comment by spencer17x** [comment]
Thank you very much for your answers.
