### ISSUE TITLE
Different log 

### ISSUE THREAD

**Issue by OmarioHassan** [getify/You-Dont-Know-JS#1679]
**Edition:** (1st or 2nd)  1st

**Book Title:** Scope & Clousers

**Chapter:** Lexical Scope

**Section Title:** eval

**Problem:**

I've tried this code to see the error `// ReferenceError: a is not defined` 

![image](https://user-images.githubusercontent.com/8146344/87819508-a0eaff80-c86c-11ea-82ee-ab4f49e9362b.png)

But it generates a circle instead

![image](https://user-images.githubusercontent.com/8146344/87819417-7b5df600-c86c-11ea-9e08-0ab5074fe4fb.png)

**Comment by getify** [comment]
WFM...

<img width="362" alt="Annotation 2020-07-17 144534" src="https://user-images.githubusercontent.com/150330/87825166-39b55700-c83c-11ea-909e-0473f26e47cc.png">

Dunno, you must have some strange situation going on there.

**Comment by OmarioHassan** [comment]
Sorry you're right
it was a global variable in the youtube tab

![image](https://user-images.githubusercontent.com/8146344/87826837-e2ce7280-c879-11ea-81e0-2d8c76417cdd.png)

And it works well thanks @getify 

![image](https://user-images.githubusercontent.com/8146344/87826864-ecf07100-c879-11ea-8137-5466fc2da699.png)
