### ISSUE TITLE
Dead link in Foreword

### ISSUE THREAD

**Issue by minimalsm** [getify/You-Dont-Know-JS#1693]
**Please type "I already searched for this issue":**
I already searched for this issue
**Edition:** (1st or 2nd)
1st
**Book Title:**
Up and Going
**Chapter:**
Foreword
**Section Title:**
Foreward
**Problem:**
jennlukas.com seems to be no longer used (checked Jenn's twitter and she doesn't seem to be linking to it herself either)

**Comment by getify** [comment]
Not accepting changes to the first edition books, per contributions guidelines.
