### ISSUE TITLE
Can we add string with space as a truthy value in the example?

### ISSUE THREAD

**Issue by vnoitkumar** [getify/You-Dont-Know-JS#1702]
**Edition:** 1st

**Book Title:** You Don't Know JS: Up & Going

**Chapter:** Chapter 2: Into JavaScript

**Section Title:** Truthy & Falsy

**Question:** I was confused that what is an "empty string", I thought String with space is also an empty string, so maybe if we have this line `" "` (string with space) in the truthy section it will be more helpful.

Spec: If argument is the empty String (its length is zero), return false; otherwise return true.

https://ecma-international.org/ecma-262/11.0/index.html#sec-toboolean

**Comment by getify** [comment]
Appreciate the question, but this book has been out for 5+ years already, and has subsequently been replaced (earlier this year) by the second edition "Get Started" title, so we're not making any further updates to it.
