### ISSUE TITLE
IIFE scope is not empty

### ISSUE THREAD

**Issue by ghost** [getify/You-Dont-Know-JS#1708]
**Edition:** 1st

**Book Title:** Scope & Closures

**Chapter:** 5

**Section Title:** Loops + Closure

**Problem:**
I ran this snippet of code in my browser, Google Chrome, and it works just fine.

```js
for (var i=1; i<=5; i++) {
	(function(){
		setTimeout( function timer(){
			console.log( i );
		}, i*1000 );
	})();
}
```

apparently, the scope is not empty!!

I'm confused 🤔

**Comment by JaykeyGuo** [comment]
```js
for (var i=1; i<=5; i++) {
	(function(i){
		setTimeout( function timer(){
			console.log( i );
		}, i*1000 );
	})(i);
}
```

You need take `i` into IIFE

**Comment by getify** [comment]
@osaimi if you run your snippet, you'll get this result:

<img width="316" alt="for-loop-1" src="https://user-images.githubusercontent.com/150330/98831540-111c2300-2412-11eb-9149-6213c60f3804.png">

It doesn't fail, but it's not *right* either, as the "expected" outcome is this (from @JaykeyGuo's snippet illustrates):

<img width="310" alt="for-loop-2" src="https://user-images.githubusercontent.com/150330/98831595-26914d00-2412-11eb-81b2-3b4a6f89080a.png">

**Comment by ghost** [comment]
But it shouldn't even work because IIFE creates a new scope that doesn't have 'i'.

Am I missing something here?

**Comment by ghost** [comment]
I changed var to let for the sake of experiment and if behaved as expected!!

![Capture](https://user-images.githubusercontent.com/26454240/98852390-a813ca00-2468-11eb-9f7b-5a3bac36a76f.JPG)

**Comment by getify** [comment]
Creating an IIFE that has no declared variables in it is a no-op... it has no effect... as your initial snippet showed. If you removed the IIFE, nothing would change.

Using `let` creates a different kind of binding (block scoping) per iteration, so again the IIFE is completely irrelevant... take it out or leave it, makes no difference. An empty scope is no different than no scope at all, in this respect.

**Comment by ghost** [comment]
It makes sense now. 
Thank you @getify
