### ISSUE TITLE
Setting and shadowing properties in chapter 5 prototypes

### ISSUE THREAD

**Issue by anurag001** [getify/You-Dont-Know-JS#1710]
**Edition:** 1st

**Book Title:** this and Object Prototypes

**Chapter:** 5 - Prototypes

**Section Title:** Setting and shadowing properties

**Problem:**
**Writable** should be **true** in the 1st point, when foo is not already on myObject, but it is at a higher level of the prototype chain. It's written as marked as read-only then, it writable should be true. Its typo I guess.

**Comment by getify** [comment]
Dupe.
