### ISSUE TITLE
Error link at chapter 6

### ISSUE THREAD

**Issue by vanpipy** [getify/You-Dont-Know-JS#1715]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**

**Edition:** 1st

**Book Title:** You-Dont-Know-JS

**Chapter:** ch6

**Section Title:** Benchmark.js

**Problem:** [Error link](https://github.com/getify/You-Dont-Know-JS/blob/1ed-zh-CN/async%20%26%20performance/ch6.md#benchmarkjs)

**Comment by vanpipy** [comment]
All right, it looks the problem is the Github document itself. Close it.

**Comment by riverfreudenrich** [comment]
Thanks! River
