### ISSUE TITLE
Chinese translation of 2nd edition book1

### ISSUE THREAD

**Issue by qiweiii** [getify/You-Dont-Know-JS#1729]
Hi, Kyle, I am working on Chinese translation of the 2nd edition in [this fork](https://github.com/qiweiii/You-Dont-Know-JS), now i have finished translating and reviewing book 1. Would you like to include it in this main repo?

**Comment by getify** [comment]
@JoeHetfield since you did the whole 1st-ed chinese translation, would you mind taking a look at this forked translation of 2nd-ed and advising if it's ready to bring over? Thanks!

**Comment by JoeHetfield** [comment]
Hi, Kyle

No problem，actually I’m preparing my translation of the first two books of 2nd edition. I’ll send request when it’s done (maybe in  two weeks), of course I’ll look at @qiweiii 's work, to see if that PR ready. please give some time.

Thanks

**Comment by Coder-hrl** [comment]
你们能说汉语吗，我英语看不懂

**Comment by Wangjinqian** [comment]
Nice,Cant wait to see it sooner!
