### ISSUE TITLE
2021

### ISSUE THREAD

**Issue by icecream17** [getify/You-Dont-Know-JS#1730]
**Please type "I already searched for this issue":**  I already searched for this issue

**Edition:** *2nd*

**Book Title:** Get Started - (but really the main Readme)

**Chapter:** 1

**Section Title:** What's with that name?

**Question:** It's 2021 now

I noticed this because of the "As of this time" sentence:
____
![image](https://user-images.githubusercontent.com/58114641/114926093-92c71100-9df5-11eb-9110-ccb320b573ee.png)
____

Perfectly fine, but because of this I noticed the Readme copyright year is outdated too, so that's what this is about

**Comment by getify** [comment]
Books get published at a certain date. That date, for these two 2nd edition books, was Jan of 2020. The books were in part written in 2019. Hence the copyright of 2019-2020.

Copyrights don't have to be updated if the content they apply to hasn't been changed. This is a common misconception wherein everyone rushes to update the copyrights on all their sites (assuming that all sites are updated!) each Jan 1. You don't need to do so, and in fact, doing so is redundant and confusing to posterity, who may then wonder what was changed.

If I made substantive changes to either book in 2021, I would update the copyright. However, that is unlikely.
