### ISSUE TITLE
Get Started - Chapter 2 - Declaring and Using Variables - Example

### ISSUE THREAD

**Issue by samcareelmont** [getify/You-Dont-Know-JS#1733]
I already searched for this issue

**Edition:** 2nd

**Book Title:** Get Started

**Chapter:** Chapter 2: Surveying JS

**Section Title:** Declaring and Using Variables

**Question:** 

> Besides var / let / const, there are other syntactic forms that declare identifiers (variables) in various scopes. For example:
> 
> ```
> function hello(myName) {
>     console.log(`Hello, ${ myName }.`);
> }
> 
> hello("Kyle");
> // Hello, Kyle.
> ```
> 
> The identifier hello is created in the outer scope, and it's also automatically associated so that it references the function. But the named parameter myName is created only inside the function, and thus is only accessible inside that function's scope. **hello and myName generally behave as var-declared.**

It seems to me that myName behaves more like a let-declared variable than like a var-declared variable.

**Comment by getify** [comment]
why?

**Comment by samcareelmont** [comment]
I've read the section a few times more and the question has disappeared. Sorry for the bother and thanks for writing this book! 

(I got myself confused because a function looks like a block since it's also defined using curly brackets.)
