### ISSUE TITLE
Adding Contents In The Beginning Of Every Chapter

### ISSUE THREAD

**Issue by alexjavascript** [getify/You-Dont-Know-JS#1742]
Hi, Kyle! 🤓 Every time when I start reading your book I've got to scroll down till the place I finished before, wouldn't it better to add contents in the beginning of every chapter to jump to a needed place more quickly, just as you did with README.md of every particular book 👀

**Comment by getify** [comment]
https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/CONTRIBUTING.md#reading-experience-chaptersection-links-etc

**Comment by alexjavascript** [comment]
Oh, Okay
