### ISSUE TITLE
Illustrations disappear in Dark Mode

### ISSUE THREAD

**Issue by ColemanTO** [getify/You-Dont-Know-JS#1757]
In dark mode, the SVG illustrations are on a transparent (dark) background, making the dark lines on a dark background almost invisible.

**Comment by getify** [comment]
yes this is unfortunate... I can't really fix this with markdown alone, since I can't use custom CSS or even JS to control things.

**Comment by ColemanTO** [comment]
Not with just the markdown, but I think you could apply a color to the background in the SVGs - they're just text. 
There is also a very good free open source SVG editor called Inkscape: <https://inkscape.org/release/inkscape-1.1/> 
Adobe Illustrator (not free) also supports SVG.

**Comment by ColemanTO** [comment]
It looks like you also have some PNG files you could swap for the SVGs...

**Comment by getify** [comment]
Before there was a dark mode on github, the images had white backgrounds. Then dark mode came out, and people said the white backgrounds were too jarring, especially for some e-readers (not just github). So I removed them (which lets some e-readers apparently automatically detect the dark-on-dark and change it to light-on-dark). But that has the unfortunate downside of making it hard to see them in dark mode on github. There's no way to please everyone. The best solution would be if I could have light-on-dark and dark-on-light versions of the images, and have the markdown/CSS auto-select it. But that doesn't seem to be possible.

**Comment by ColemanTO** [comment]
True. Closing the issue. Thanks for your responses.

**Comment by ColemanTO** [comment]
What if the background was 50 or 60% transparent? That way, it would be gray in dark mode.

**Comment by getify** [comment]
So black-on-gray? I think that might violate/harm accessibility.

**Comment by ColemanTO** [comment]
It would conform to WCAG 2.1 Level AA if it had a contrast ratio of 4.5:1 or greater.

**Comment by ColemanTO** [comment]
It's for sure not conforming now ;)

**Comment by ColemanTO** [comment]
Text needs 4.5:1, graphics need only 3:1

**Comment by getify** [comment]
Are you referring to the first edition books or second edition books? I already fixed this for the second edition books.

<img width="652" alt="Screenshot 2021-08-15 085754" src="https://user-images.githubusercontent.com/150330/129480980-04ed9c99-fab0-4a3d-b0f9-f39e56a0f8a9.png">

**Comment by ColemanTO** [comment]
It's possible I was looking at the wrong edition - sorry!
