### ISSUE TITLE
[Question][Scope & Closure] Modules Pattern in Chapter 5

### ISSUE THREAD

**Issue by bangedorrunt** [getify/You-Dont-Know-JS#176]
Hi guys,
I'm trying to get my head round at this pattern:

``` javascript
var MyModules = (function Manager() {
    var modules = {};

    function define(name, deps, impl) {
        for (var i = 0; i < deps.length; i++) {
            deps[i] = modules[deps[i]];
        }
        //modules[name] = impl.apply(impl, deps); <~~ This WORK!
        modules[name] = impl(deps); <~~ This NOT WORK!
    }

    function get(name) {
        return modules[name];
    }

    return {
        define: define,
        get: get
    };
})();
```

If I modify this `modules[name] = impl.apply(impl, deps);` to `modules[name]=impl(deps);`, I trip up `TypeError: Object [object Object] has no method 'hello'`

Can you explain **carefully** to me why this happen?

**Comment by HaveF** [comment]
@getify :innocent:
Can you explain why you use
```javascript
modules[name] = impl.apply(impl, deps)
```
instead of
```javascript
modules[name] = impl.apply(null, deps)
```
Does that has some special meaning? Thanks

**Comment by getify** [comment]
no, no special meaning other than to bind the 'this' for that call to the public API instance itself. Perhaps more predictable and thus safer.

**Comment by HaveF** [comment]
@getify thanks for your explanation.:smile:

**Comment by ischurov** [comment]
Just wanted to mention that I wondered what the second `impl` in `impl.apply(impl, deps)` do and tried exactly the same alternative (`impl.apply(null, deps)`) as @HaveF. So maybe it worth to add some comments to the book in this place. (And probably to explain what `.apply` do?)
