### ISSUE TITLE
website for this repo

### ISSUE THREAD

**Issue by Utkarsh1504** [getify/You-Dont-Know-JS#1765]
Hey @getify, First of all, thank you for doing open-source all the You Don't Know JS book series. I think now we should make a website for the same, It would be great if the markdown files under this repo get converted into HTML pages similar to this site https://btholt.github.io/intro-to-web-dev-v2/
Thank you.

**Comment by getify** [comment]
Appreciate the suggestion but I'm not interested in that approach for now.
