### ISSUE TITLE
Typo in Chapter 5 of this & object prototypes

### ISSUE THREAD

**Issue by iamsharzil** [getify/You-Dont-Know-JS#1768]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**

**Edition:** (1st or 2nd)
1st

**Book Title:**
this & Object Prototypes

**Chapter:**
5

**Section Title:**
Setting & Shadowing Properties

**Problem:**

> If a normal data accessor (see Chapter 3) property named foo is found anywhere higher on the [[Prototype]] chain, and it's not marked as read-only (writable:false) then a new property called foo is added directly to myObject, resulting in a shadowed property

here "writable" should be true instead of false.

**Comment by getify** [comment]
Please search closed issues for explanation.

**Comment by iamsharzil** [comment]
@getify Apologies! 
I should have checked the closed issues before raising one.
