### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mbledkowski** [getify/You-Dont-Know-JS#1780]
Hi, is it ok to create own translation of the book, and upload it on Github?

**Comment by getify** [comment]
Check this out: https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/.github/ISSUE_TEMPLATE/foreign-translation-request.md

**Comment by mbledkowski** [comment]
Ok, so I want to make it clear. Can I create my own translation on GitHub, of this book? 
Temporary repository: [mbledkowski/You-Dont-Know-JS-PL](https://github.com/mbledkowski/You-Dont-Know-JS-PL)

**Comment by getify** [comment]
The link I provided above explains what you need to know generally about translating the works and making the text available **FOR FREE** here on GitHub. Assuming you abide by those provisions, I'm OK with foreign translations.

----

However, for Polish language in particular, there's already an official published translation of the second edition books into Polish. Indeed, those books are already available for sale, as can be seen here: https://thepolishbookstore.com/p/637384/ptitle.html

Technically, that [publisher (PWN)](https://www.pwn.pl/) holds "exclusive rights" to Polish translations of the books. I'm sure they wouldn't allow any commercial sale of your translations as it would be competitive to them.

However, I'm not sure whether they're OK with you doing your own Polish translation for free consumption. I would imagine they're probably OK with it, but I would strongly recommend contacting them first. I wouldn't want your translation efforts to be interrupted/wasted later if they weren't OK with it.

**Comment by getify** [comment]
Closing for now. Feel free to add further discussion if you see fit.
