### ISSUE TITLE
Function name capitalization throws error.

### ISSUE THREAD

**Issue by adamyala** [getify/You-Dont-Know-JS#1784]
I already searched for this issue.

**Edition:** 2nd

**Book Title:** Scope & Closures

**Chapter:** Appendix A: Exploring Further

**Section Title:** Are Synchronous Callbacks Still Closures?

**Problem:** Function name capitalization throws error. `document.getElementByID` should be `document.getElementById`, note the lowercase `d` at the end. `document.createELement` should be `document.createElement`, note the lowercase `l`.

Link to file: https://github.com/getify/You-Dont-Know-JS/blob/fcbd9b8d965f9c97508906c5739d4e919b067b0d/scope-closures/apA.md#synchronous-closure

Would a PR be welcome to adjust the capitalization? I saw https://github.com/getify/You-Dont-Know-JS/pull/416 from long ago. If a PR is welcome, I'm happy to make one.

As always, thank you for creating an amazing resource to learn from. Reading it has been a joy.

**Comment by getify** [comment]
Yes PR welcome for those fixes. Thanks!
