### ISSUE TITLE
A concern about the "only whitespace and comments are allowed before the use-strict pragma" part

### ISSUE THREAD

**Issue by SiarheiBobryk** [getify/You-Dont-Know-JS#1786]
"I already searched for this issue"

**Edition:** 2nd

**Book Title:** You Don't Know JS Yet: Get Started

**Chapter:** 1

**Section Title:** Strictly Speaking

**Question:**

The "Strictly Speaking" section says that

```js
// only whitespace and comments are allowed
// before the use-strict pragma
"use strict";
// the rest of the file runs in strict mode
```

However, I'm able to run the following code without any errors/crushes in my Node.js (v16) and in Chrome as well:

```js
// only whitespace and comments are allowed
// before the use-strict pragma
console.error('error');
const test = '';
function foo() { };
"use strict";
// the rest of the file runs in strict mode
console.info('works!');
```

So I have a concern about the "only whitespace and comments are allowed before the use-strict pragma" part. If that is true, why am I able to run the example above? Maybe am I missing something? Also, what is the expected behaviour if I violate the "only whitespace and comments are allowed" rule?

**Comment by getify** [comment]
> If that is true, why am I able to run the example above? ... what is the expected behaviour if I violate the "only whitespace and comments are allowed" rule?

By "allowed"  I meant "is effective". IOW, `"use strict"` only does something relevant if it appears at the "top" of a function or global scope, where "top" means "nothing before it except for optional whitespace or comments".

If it's not in that "top" position, it's *ONLY* seen as a trivial string value expression. That means it doesn't do *anything*. It doesn't turn on strict mode for that program/scope. But it also doesn't cause any exceptions. It's just processed, does nothing of any importance, and moves on.

Here's two screenshots to illustrate. In the first snippet, strict mode is switched on, and the program throws a syntax error on the duplicate parameters.

<img width="546" alt="1" src="https://user-images.githubusercontent.com/150330/159551057-7f9cc82c-a5c8-44ee-9cbb-1d92a5bc0b60.png">

In this second snippet, strict mode does *NOT* get switched on, so the `"use strict"` just gets processed as a string value that has no other purpose or effect on the program (but is valid and legal).

<img width="502" alt="2" src="https://user-images.githubusercontent.com/150330/159551060-c427fdb0-1017-4222-9a27-3893a00658e2.png">

**Comment by SiarheiBobryk** [comment]
Thanks for the detailed explanation @getify!
And a BIG thanks for your great books ❤️
