### ISSUE TITLE
"scope & closures": one more eval example

### ISSUE THREAD

**Issue by frontenddeveloping** [getify/You-Dont-Know-JS#179]
You have a good examples in `Cheating Lexical` part with `eval`. But I want to add one example here which can make a one more cheating with `eval` in `strict mode`:

```
function foo(str) {
   "use strict";
   var e = eval;
   e( str );
   console.log( a );// will write 2
}
foo( "var a = 2" );
```

There is no `ReferenceError` here. The reason is in [section 10.4.2](http://www.ecma-international.org/ecma-262/5.1/#sec-10.4.2) of ECMAScript 5.1 specification, which says how we "entering" on `eval` code:

> The following steps are performed when control enters the execution context for eval code:
> If there is no calling context or if the eval code is not being evaluated by a direct call (15.1.2.1.1) to the eval function then,
> Initialise the execution context as if it was a global execution context using the eval code as C as described in 10.4.1.1.

May be it can be useful for `Cheating Lexical` section.

**Comment by getify** [comment]
Closing now that this text has been re-written in the second edition book, so this issue no longer applies.
