### ISSUE TITLE
Objects & Classes - 2nd Edition - Ch. 4 - point.init(...) is not a constructor

### ISSUE THREAD

**Issue by BigKamil5** [getify/You-Dont-Know-JS#1801]
**Please type "I already searched for this issue":**
I already searched for this issue.

**Edition:** (1st or 2nd)
2nd

**Book Title:**
Objects & Classes

**Chapter:**
Chapter 4: This Works

**Section Title:**
New Context Invocation

**Problem:**

> var anotherPoint = new point.init(3,4);

This line of code throws an error. 
`point.init(...) is not a constructor`

**Comment by getify** [comment]
Thanks, there's a bit of nuance I hadn't explained, but I addressed it now.
