### ISSUE TITLE
Meaning of web globals 

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [getify/You-Dont-Know-JS#1804]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":** I already searched for this issue

**Edition:**  2nd

**Book Title:** Scope & Closures

**Chapter:** 4

**Section Title:** [ES Modules(ESM)](https://github.com/getify/You-Dont-Know-JS/blob/8861041133f496edce0d03885e2e998d50c3414a/scope-closures/ch4.md#es-modules-esm)

**Question:**
I'm not sure of the meaning of `web globals` in this sentence. Could you elaborate more? 

```
However, as noted earlier, there are still plenty of JS and web globals that you will continue to access from the global scope, whether you realize it or not!
```

**Comment by getify** [comment]
`window`, `location`, `navigator`, etc

**Comment by Violet-Bora-Lee** [comment]
Gotcha!

Thanks 👍
