### ISSUE TITLE
Reflection of mechanics how execution contexts and Lexical Environment objects work

### ISSUE THREAD

**Issue by dimau** [getify/You-Dont-Know-JS#1809]
The book does not reflect the fundamental concepts related to the implementation of scopes in JS — mechanics of how execution contexts and Lexical Environment objects work. Here is an article on stackoverflow, which gives a fundamental understanding of this mechanic, I supposed to see something like this in this book - https://stackoverflow.com/questions/12599965/lexical-environment-and-function-scope

----

**Edition:** 2nd

**Book Title:**

**Chapter:**

**Section Title:**

**Problem:**
The book completely does not reflect the fundamental concepts related to the implementation of scopes in JS. I mean the mechanics of how execution contexts and Lexical Environment objects work. Here is an article on stackoverflow, which gives a fundamental understanding of this mechanics, I supposed to see something like this in this book - https://stackoverflow.com/questions/12599965/lexical-environment-and-function-scope

**Comment by getify** [comment]
If you'd rather read stackoverflow posts than my book, I wish you the best of luck.
