### ISSUE TITLE
Add simplified Chinese translation to the 2ed

### ISSUE THREAD

**Issue by liunnn1994** [getify/You-Dont-Know-JS#1831]
Hi, Kyle

I am a Front-end developer, and also helping MDN Web Docs with localized translations in spare time.I have spent some time and have completed the [Chinese translation](https://github.com/liunnn1994/You-Dont-Know-JS-zh-CN) of the book 1. Can you create a new branch with the name  **2ed-zh-CN**, so I can new a PR to it?

Looking forward to your reply.

**Comment by getify** [comment]
Thanks! Done!

**Comment by liunnn1994** [comment]
Already create a PR #1832.

By the way,
I noticed that author @JoeHetfield of the 1ed is already inactive. If possible, you can give me access to both the 1 and 2 ed. So I can help deal with some typos issues on the 1ed.

**Comment by getify** [comment]
@liunnn1994 on your js.org site where you're hosting the translation, can you add a note stating that it's a community translation of the text and not the official text? thanks!

**Comment by liunnn1994** [comment]
@getify I've configured the title of each page to add a reminder that this is a community edition, and added this [repository](https://github.com/getify/You-Dont-Know-JS) address to the index page along with the License & Copyright.

**Comment by yahiaalloucha13** [comment]
@getify
