### ISSUE TITLE
I think the condition in the if statement should be "(new.target === Point2d)" now it is "(new.target === Point2)"

### ISSUE THREAD

**Issue by todordiklich** [getify/You-Dont-Know-JS#1839]
https://github.com/getify/You-Dont-Know-JS/blame/85b2e6c5fa03b95d044015d6e44b72b8beb6a53b/objects-classes/ch3.md#L569

**Comment by getify** [comment]
yep, minor typo, thx

**Comment by naveenprasad07** [comment]
I solved the issue
