### ISSUE TITLE
Unable to see images on generated epub

### ISSUE THREAD

**Issue by hmassareli** [getify/You-Dont-Know-JS#1840]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":**
I already searched for this issue

**Edition: ** 2 edition

**Book Title:** get started

**Chapter:**

**Section Title:**

**Question:**

I would like to say that images are not present when you generate the epub version of the ebooks

**Comment by 0888960852** [comment]
![Uploading 0C050DE2-059D-4D68-BB9B-2F45DF6E9338.jpeg…](g fg)

**Comment by hmassareli** [comment]
> ![Uploading 0C050DE2-059D-4D68-BB9B-2F45DF6E9338.jpeg…](g fg)
> 

what?

**Comment by getify** [comment]
This repository does not officially support any methods for self-conversion to other digital formats (such as epub).

In fact, the epub version of these books (where applicable) is *sold* as an ebook on LeanPub: https://leanpub.com/p/getipub
