### ISSUE TITLE
Reordering of "Why Closure?" and "An Alternative Perspective" in the toc

### ISSUE THREAD

**Issue by liunnn1994** [getify/You-Dont-Know-JS#1844]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** 2nd Edition

**Book Title:** scope-closures

**Chapter:** Chapter 7: Using Closures

**Section Title:** Why Closure?

**Question:** Reordering of "Why Closure?" and "An Alternative Perspective" in the toc

In the course of translation I noticed that "[An Alternative Perspective](https://github.com/getify/You-Dont-Know-JS/blob/85b2e6c5fa03b95d044015d6e44b72b8beb6a53b/scope-closures/ch7.md?plain=1#L649)" in the toc should precede "[Why Closure?](https://github.com/getify/You-Dont-Know-JS/blob/85b2e6c5fa03b95d044015d6e44b72b8beb6a53b/scope-closures/ch7.md?plain=1#L715)"

**Comment by Salemi01** [comment]
Please type "I already searched for this issue": I already searched for this issue

Edition: 2nd Edition

Book Title: scope-closures

Chapter: Chapter 7: Using Closures

Section Title: Why Closure?

Question: Reordering of "Why Closure?" and "An Alternative Perspective" in the toc

In the course of translation I noticed that "[An Alternative Perspective](https://github.com/getify/You-Dont-Know-JS/blob/85b2e6c5fa03b95d044015d6e44b72b8beb6a53b/scope-closures/ch7.md?plain=1#L649)" in the toc should precede "[Why Closure?](https://github.com/getify/You-Dont-Know-JS/blob/85b2e6c5fa03b95d044015d6e44b72b8beb6a53b/scope-closures/ch7.md?plain=1#L715)"
