### ISSUE TITLE
Copy right policy about teaching your book

### ISSUE THREAD

**Issue by HamedSiaban** [getify/You-Dont-Know-JS#1853]
Hello.

I'm a frontend developer trying to get better everyday.
I love your books and I think all frontend developers should read and learn it.

I was thinking as I learn each chapter, may be I could introduce your book, translate and teach it in a simpler version to other people in my youtube channel. 
I won't show content of the book to people, Only teaching what I learned from it in my own way, according to the table of the contents. Like a classroom.
But I'm not very informed about copy right issues and etc.

So can you enlighten me about the possibility of this? 
Thanks.

**Comment by getify** [comment]
You can absolutely teach JS with your own content, and if you so choose, *inspired* by the content of my book. I look forward to seeing what you provide!

I would ask that:

1. don't not show literal text or code in more than a few bits at a time... like don't just show a huge chunk of a chapter or whatever. It's better if you adapt the concepts and make your own code examples (that's better for your learning, if nothing else!).

2. don't name your teaching/content in a way that's confusing to folks as if it being from me/YDKJS.

**Comment by HamedSiaban** [comment]
Thanks for the response.
Sure, I will stick to the guidelines you stated.
:pray:
