### ISSUE TITLE
`add10To` vs `addTo10`

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [getify/You-Dont-Know-JS#1855]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** 2nd

**Book Title:** Scope and Closures

**Chapter:** 7

**Section Title:** [An Alternative Perspective](https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/scope-closures/ch7.md#an-alternative-perspective)

**Problem:**

Hello, my name is Bora Lee, and I am currently finalizing the translation work for a Korean text. I'm reaching out because I've noticed some discrepancies between the code, the text, and the images. 

```js
function adder(num1) {
    return function addTo(num2){
        return num1 + num2;
    };
}

var add10To = adder(10);
var add42To = adder(42);

add10To(15);    // 25 
add42To(9);     // 51 
```
In the code, the instances created by the inner function calls are named `add10To` and `add42To`, but in the accompanying images and descriptions, they are referred to as `addTo10` and `addTo42`. I'm contacting you to clarify this as I might be misunderstanding something. Could you please confirm if the text and images provided are correct?

![image](https://github.com/getify/You-Dont-Know-JS/assets/6451384/30a6f136-a638-41e9-9024-5ee899f5a1fa)

![image](https://github.com/getify/You-Dont-Know-JS/assets/6451384/8b99203b-e59a-4641-8fa8-f2714053c547)

**Comment by getify** [comment]
It's a minor typo discrepancy. The code snippet should use names that match the images and surrounding text.

**Comment by Violet-Bora-Lee** [comment]
Ah, I see. I personally find `add10To(15)` more intuitive and to my liking, but I will convey your words to the publisher as well. 

Thank you for your prompt response, especially during the holiday season. 🎄
