### ISSUE TITLE
First Edition Vs Second Edition

### ISSUE THREAD

**Issue by arimtiaz** [getify/You-Dont-Know-JS#1865]
Do i read the second series or the first one?

**Comment by getify** [comment]
both :)

read books 1-4 of the second edition, then read books 5-6 of the first edition.

**Comment by StigNygaard** [comment]
Are there plans to sell books 3-4 from second edition on print soon(ish)?
I greatly prefer print (yeah, I'm a bit old). Plus of course I support your work that way 🙂
I see 3rd book is in "draft stable".

**Comment by getify** [comment]
I have no active plans to publish books 3 and 4 officially. There's a ton of work involved, and book sales (globally) of tech books is so low that it makes it too much to justify.

**Comment by StigNygaard** [comment]
> I have no active plans to publish books 3 and 4 officially. There's a ton of work involved, and book sales (globally) of tech books is so low that it makes it too much to justify.

Thanks. Good to know, so I doesn't keep waiting forever 😊

**Comment by StigNygaard** [comment]
> I have no active plans to publish books 3 and 4 officially. There's a ton of work involved, and book sales (globally) of tech books is so low that it makes it too much to justify.

What if I want to print book 3 and 4 myself? Are there anyway to get a pdf or other printable ebook format from the repository or somewhere else (would love to pay for it!)? Or some smart way to generate from repository content? Looked around, but cannot find any hints in that direction? :-/ ...

**Comment by getify** [comment]
People are free to print their own personal copies as they see fit, just not distribute/sell them to others.

A number of people have used various tools for converting markdown to PDF, for example tools like this: https://pypi.org/project/markdown-pdf/ You might just try a few of them and see what the results look like to you.

**Comment by StigNygaard** [comment]
Thanks @getify . I'll try that.
