### ISSUE TITLE
"(Primitive) Values are copied on assignment" (or not)

### ISSUE THREAD

**Issue by swombat** [getify/You-Dont-Know-JS#1887]
----

**Please type "I already searched for this issue":**
I already searched for this issue and found no other issues about values and references.

**Edition:** (1st or 2nd)
2nd

**Book Title:**
YDKJS: Get Started

**Chapter:**
Appendix A

**Section Title:**
Values vs. References

**Problem:**
So, I love the preciseness of the book so far, and therefore as someone who started coding in BASIC on a C64 and then in Pascal and finally C, and learned about pointers all the way back then, something bugged me about the explanation:

> If you assign/pass a value itself, the value is copied. For example:
>
> ```
> var myName = "Kyle";
> 
> var yourName = myName;
> ```
> 
> Here, the yourName variable has a separate copy of the "Kyle" string from the value that's stored in myName. That's because the value is a primitive, and primitive values are always assigned/passed as value copies.

That didn't sound quite right. 

I did a bit of poking around (some of it talking to my pal 4o to check my understanding), and I thought my hunch was right that something wasn't quite accurate here.

At first, my instinct was that what was actually happening here is that all primitives in JS are immutable. And "variables" (or rather variable names) are, as in C, really pointers. So `var myName = "Kyle"` creates a pointer to the immutable string `"Kyle"`. And `var yourName = myName` gets yourName's pointer to point to the same bit of memory.

Then in the next example:

> ```
> var myName = "Kyle";
> 
> var yourName = myName;
> 
> myName = "Frank";
> 
> console.log(myName);
> // Frank
> 
> console.log(yourName);
> // Kyle
> ```

What would then really be happening is that when you run `myName = "Frank";"`, the `myName` pointer is repointed to a new immutable string, which of course doesn't change the immutable string that `yourName` was already pointing at.

Except... of course reality is even more complicated, and we're both right.

According to [this MDN link](https://developer.mozilla.org/en-US/docs/Glossary/Primitive?retiredLocale=de) all Primitives are indeed immutable. But that's not specified in the [ECMAScript specs](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-data-types-and-values) afaict. So then I found more useful info in [this StackExchange post](https://softwareengineering.stackexchange.com/questions/445028/ecmascript-primitives-immutability-vs-value-type#:~:text=Whereas%20Reference%20Types%20store%20a,is%2C%20they%20cannot%20be%20altered.):

> For example, ECMAScript does not specify whether values are stored on heap or stack and whether they are stored as pointers or direct values. The implementation can choose the most appropriate strategy, and may even change strategy at runtime.
>
> Mutability is significant because it affects what strategy is appropriate. For an immutable value, there is no observable difference between copying a pointer to the value or copying the value, so the implementation may choose a strategy based on performance. For mutable values, however, the implementation is basically required to use pointers when assigning, since changes to a mutable value should be observable through all variables the value is assigned to.

So, really, what's happening is, under the hood, we don't know what the JS VM is doing to optimise things to within an inch of their life, but in practice, it looks the same whether primitives are copied by value, or whether they are pointers to immutable values.

But it is not 100% correct, I think, to say:

> If you assign/pass a value itself, the value is copied.

Instead, a more correct statement, I think, would be something like:

> If you assign/pass a primitive, then either the value is copied, or a new pointer is created that points to the same immutable primitive, depending on the internal optimisation details of your JS VM. Either way, the ECMAScript spec demands that it looks exactly the same as if the value was copied. For all intents and purposes, primitive variables behave as if values were copied on assignemnt.

I totally realise this is a rather insane level of nitpicky... but then this book is so delightfully precise, I couldn't help myself when I saw this incredibly tiny imprecision!...

Thanks for this awesome book either way! I hope this helps.

**Comment by getify** [comment]
I appreciate your feedback/thoughts. However, the assertions I'm making about "value copying"/etc are intended:

a) for a more beginner JS dev audience (since this is the Get Started intro book of the series); AND
b) intended to describe (i.e., create a useful mental model) the ergonomics and observable behaviors of JS as the developer experiences, NOT to describe what the internals of one engine may do or not.

It's not that your suggested text is *wrong* per se, but I think it's *wrong for this book/audience* in that sense, as it creates distraction and highlights detail that is not particularly useful to the JS developer.

FWIW, I rarely in my books/teachings cover engine internal implementation details, in part because of that principle, but also because these things are subject to change over time, so you can't really create *timeless* information on such topics.

**Comment by swombat** [comment]
Thanks for taking the time to respond and explain your thinking!
