### ISSUE TITLE
Exercise issue

### ISSUE THREAD

**Issue by mikeewazowski** [getify/You-Dont-Know-JS#1889]
Hey Mr. Kyle! 

**I have already searched for this issue**

**1st edition**

**UP& Going**

**Chapter 1**

**Practice:**

"Exercise code has the same result every time I run it even with different bank_balance values. I consider an approach to change _while (amount < bank_balance)_ to _while (amount + PHONE_PRICE < bank_balance)_ and _if (amount < SPENDING_THRESHOLD)_  to _if (amount + ACCESORY_PRICE < SPENDING_THRESHOLD)_ " 

Good luck. Mahdi

**Comment by getify** [comment]
I understand the code is not particularly "real world". I deliberately simplified the logic since it's for a beginner audience. Moreover, this book was published about 10 years ago, so it's not subject to change (per [Contributions guidelines](CONTRIBUTING.md)).
