### ISSUE TITLE
"scope & closures": another scope/hoisting oddity

### ISSUE THREAD

**Issue by getify** [getify/You-Dont-Know-JS#199]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Scope_Cheatsheet#function_oddities

For example: https://github.com/jsbin/jsbin/issues/1948#issuecomment-56298790

**Comment by MJGwater** [comment]
In case browser implementations matter, function declarations do hoist when declared inside a child block in Safari.

**Comment by doubleOrt** [comment]
@MattGoldwater This example results in a "TypeError" in Chrome version 58.

**Comment by phavor** [comment]
The code says foo is not a function on Firefox nihhtly

**Comment by phavor** [comment]
The code says foo is not a function on Firefox nightly

**Comment by 928m** [comment]
This code doesn't work on Chrome 78.

**Comment by getify** [comment]
Closing now that this text has been re-written in the second edition book, so this issue no longer applies.
