### ISSUE TITLE
"types & grammar": a note about code example

### ISSUE THREAD

**Issue by severyanov** [getify/You-Dont-Know-JS#206]
In the section `Implicitly: Booleans --> Numbers` of chapter 4 there are two versions of function `onlyOne`. The first one returns `true` if only one of the arguments is truthy, and the second is considered to work in the same way using implicit to-Number coercion. But it doesn't work exactly the same. In the first version of `onlyOne` you can pass any falsy value as a parameter and it will be always treated as `false`, but in second version you cannot pass `NaN` or `undefined` hoping to get the same result, since those values convert to `NaN` and hence `sum` becomes `NaN` and the function returns `false` even if there is only one truthy argument.

**Comment by ruichao-factual** [comment]
I am a little confused by this fix. 

If I pass some truthy string or number, like `4`, `'4'`, to the first `onlyOne` function, it will fail.

I think your previous version is much more meaningful. (only need to change `sum += arguments[i]` to `sum += !!arguments[i]`)

**Comment by getify** [comment]
@ruichao-factual

I understand your point, and I kinda agree. Can you open a separate issue (referencing this one) and I can tag it to address in second edition? :)

**Comment by ruichao-factual** [comment]
Sure thing. Created.
