### ISSUE TITLE
"scope & closures": IIFE benefits in minification

### ISSUE THREAD

**Issue by grabbou** [getify/You-Dont-Know-JS#211]
In the book (which is great, just reading on my Kindle, thanks!!), there's a sentence about wrapping global objects inside IIFEE

``` js
(function doSomething(globalReference, whatever){
   ...
})(window, MyApp.modules.whatever)
```

> This is mostly just stylistic choice.

Although your book is not describing patterns and other javascript aspects that much as scope and stuff, maybe we should consider a note about code minification that will fail to rename globals otherwise so it's considered as a good practice for optimising code size? Just to make it clearer for those who are unfamiliar with that behaviour.

**Comment by getify** [comment]
Closing now that this text has been re-written in the second edition book, so this issue no longer applies.
