### ISSUE TITLE
"scope & closures": hoisting of let

### ISSUE THREAD

**Issue by sAbakumoff** [getify/You-Dont-Know-JS#215]
The text says:

> However, declarations made with let will not hoist to the entire scope of the block they appear in. Such declarations will not observably "exist" in the block until the declaration statement.

```
{
   console.log( bar ); // ReferenceError!
   let bar = 2;
}
```

That does not seem to be correct, actually this code will display "undefined".

**Comment by jinbeomhong** [comment]
For record, see his recent answer from here https://github.com/getify/You-Dont-Know-JS/issues/767
