### ISSUE TITLE
"scope & closures": explain immutable binding of function-expression name

### ISSUE THREAD

**Issue by sAbakumoff** [getify/You-Dont-Know-JS#223]
I really love you-dont-know-js series. After reading "scope & closures" I started playing with scope feature and found out strange behavior which even can't be explained in SO:
http://stackoverflow.com/questions/26670116/javascript-function-scope-behavior
Consider the following code:

```
'use strict';

// no error
function f1(n){
    (function a(k){
        a = 5;
        console.log(a);
        if(k<n)
            a(++k);
    })(1);
}

// error!!
function f2(n){
    function a(k){
        a = 5;
        console.log(a);
        if(k<n)
            a(++k);
    };
    a(1);
}

//no error
function f3(n){
    var a = function a(k){
        a = 5;
        console.log(a);
        if(k<n)
        a(++k);
```

f2(3) invocation produces the error on a(++k) line that says number is not a function which is expected because value of a is set to number just one line earlier. However, f1(3) and f3(3) does not show any errors and prints the function's toString result in the console! I found it strange because the code is executed in strict mode and if variable a was not declared then the code would produce the error like a is not defined. So a is defined, and of course it's the reference to function itself, but somehow setting its value has no effect in f1 and f3 code!
My only guess is that the answer is the way the function expression keeps and exposes reference to itself, but how it's done is not quite clear..Function declaration does not use this way because it keeps the reference to itself right in the scope it's declared.
Maybe it's worth to add a couple of words about it to the excellent book to make it more..awesomer..if it's a word)

**Comment by web20opensource** [comment]
@getify  Excuse me, what's the answer for the last @sAbakumoff's question? Can you help us to figure out what happened?

**Comment by getify** [comment]
Closing now that this text has been re-written in the second edition book, so this issue no longer applies.
