### ISSUE TITLE
"async & performance" - ljharb

### ISSUE THREAD

**Issue by ljharb** [getify/You-Dont-Know-JS#248]
Preface:
 - I still prefer "ham : hamburger" rather than "car : carnival" :-p

Chapter 1:
 - Async Console: "serializing it to a string" - technically serializing it to any primitive will work. not sure if it's worth mentioning
 - I find your code spacing to be really weird - ie `data.map( function(val){` instead of the more common `data.map(function (val) {`, and the spaces inside the parens for the `ajax` calls. Is that intentional? Even if it's your preferred style, and if it's consistent, you still may want to consider using more common whitespacing forms to avoid reader confusion.
 - I see that you're intentionally using `splice`, but that's one of the most confusing Array methods, and mutates the array. Is there another way of writing that code that doesn't use splice, or mutation? I think it would read much more clearly.
 - Is it worth noting that the HTML5 spec means that `setTimeout` can't possibly schedule any sooner than 4ms, and prior to HTML5 it was like 20ms?

Chapter 2:
 - "node style" - this is worth a note explaining that it's because that's the convention used in node.js, otherwise there's no context
 - this was excellently written, btw. it re-convinced me of what i already knew, thoroughly.

Chapter 3:
 - the "immediately" note is good, but perhaps another word or phrase instead would be better? "immediately" is pretty tightly coupled conceptually to "synchronously" in my head.
 - i like the receipt, and it's a better example than "go to a mall restaurant, you get a pager, when it buzzes your table is ready" but it fits better in my head. no changes necessary, just thinking out loud.
 - s/methaphorically/metaphorically
 - any note about `.catch` in ES6?
 - your ducktyping thenable code could be much simplified - `if (p && typeof p.then === 'function')` - which also would cover a primitive if i'd set up `Number.prototype.then`, for example (not that that would be a good idea)
 - the emphasis on "completion"/"continuation" seems strange; i've never really heard them used before - and the term "event" is pretty overloaded. This could stand to be reworded to avoid conflation with other topics, or to avoid placing emphasis on terms that aren't actually commonplace. The `.on` notation is jquery/backbone/etc standard, but isn't part of the language or the DOM, so it might not be helpful.
 - "// A B  <-- not  B A  as you might expect" - i see "p3" is sync resolved (1 on microtask queue), "p1" is sync resolved and synchronously assumes (or should, as i understand it) the internal state of "p3" (so, 2 on microtask queue), "p2" is sync resolved (3 on microtask queue). p1's "then" will execute at microtask 2, p2's "then" at microtask 3. Thus, the microtasks will execute as 1,2,3, which means p1's "then" (B) and then after, p1's "then" (A). I agree (running the code) that it outputs A B, but obviously I'm missing something. This is not well explained, and I still don't understand what's going on. I assume it's some nuance of the spec, but fully talking out the algorithm may be helpful.
 - more explanation of `Promise.race` (like you did with `Promise.all`) would be helpful here
 - the place where you talk about an error in the first arg of "then" not firing the second arg of "then" is why `Promise#catch` is so useful - it would be great for it to have been introduced above.
 - finally got to "catch" :-) but i still think sooner is better.
 - glad to see you came around on "resolve" vs "fulfill" ;-)
 - you may want to link to `"The point of promises is to give us back functional composition and error bubbling in the async world." https://gist.github.com/3889970` somewhere, it's awesome
 - holy crap, `Promise.race()` rejects but `Promise.race([])` stays pending forever. i'm not on board with the error throwing stuff you believe, but this one i agree is utterly insane.
 - I'm really not a fan of the casual way your code examples modify globals. Is that really necessary to illustrate the point? (`Promise.map`, for example). That stuff is widely considered a horrible practice, and with no immediate notes every time you do it advising that it may be a bad idea, people *will* copy it, to their detriment.
 - no link to the `es6-shim`? :-)
 - "splitting values": `foo` doesn't return two values, it returns one, an array. that there's two things inside it is irrelevant. i think you're blurring the line here a bit too much.
 - worth talking about the ES6 `...` spread operator vs a `spread` method, and vs destructuring?
 - `Observables` are proposed for ES7, might be worth mentioning https://github.com/jhusain/asyncgenerator
 - sigh, Promise.wrap. another global mutation. That one explicitly assumes a node-style callback. That's not going to work on everything.

Chapter 4:
 - coming soon

**Comment by ljharb** [comment]
Thanks, I'll add here when I do, but don't wait on me :-)

**Comment by getify** [comment]
last call on editorial comments. :)

**Comment by ljharb** [comment]
I'm not going to have time before you get this published :-) thanks for listening to the comments on the first 3 chapters!

**Comment by getify** [comment]
<3 thanks for the help!!! :)
