### ISSUE TITLE
"async & performance"

### ISSUE THREAD

**Issue by rwaldron** [getify/You-Dont-Know-JS#261]
I was asked to review chap 1-6, turns out this work is pretty nice to review since it's all already correct and _very_ thorough. 

## ch1 
- LGTM

## ch2
- LGTM

## ch3
- The overly negative editorial content towards the end of **Thenable Duck-Typing** (just before and including the **Note**) came out of left field and seems inappropriate. Until this point, the book has been really good at presenting facts with strong examples and explanations—as well as being _correct_ (impressive!)—but this part of the chapter reads as bitter or even resentful (though I don't think it actually is), which cheapens the author's expert voice and loses the momentum from the first two chapters.

## ch4

... only about half way through, but so far so good.

**Comment by getify** [comment]
last call on editorial comments. :)
