### ISSUE TITLE
"scope & closures": declaring functions in blocks under strict mode will throw error

### ISSUE THREAD

**Issue by rayshan** [getify/You-Dont-Know-JS#270]
May be nice to mention this.

Book location: end of https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch4.md#functions-first

Reference: http://stackoverflow.com/a/10069457/2152076

**Comment by getify** [comment]
Closing now that this text has been re-written in the second edition book, so this issue no longer applies.
