### ISSUE TITLE
Conditionals example

### ISSUE THREAD

**Issue by nickbalestra** [getify/You-Dont-Know-JS#283]
On the [conditionals example](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20&%20going/ch1.md#conditionals) doesn't make more sense something like:

`if ( (amount + ACCESSORY_PRICE) < BANK_BALANCE ) {...`

instead of

`if ( amount < BANK_BALANCE ) {...`

**Comment by getify** [comment]
In reality, yes.

but in terms of introducing programming concepts, i felt like having math inside the conditional test expression was too much detail and would obscure the point. The point is not about creating a sound financial software system for making store purchases. :)

**Comment by nickbalestra** [comment]
Agree, in that scenario math and the added () inside the conditional test will definitely obscure the point.

**Comment by getify** [comment]
cheers! thanks for the suggestions. keep 'em coming. :)
