### ISSUE TITLE
Up & Going sentence change?

### ISSUE THREAD

**Issue by pertrai1** [getify/You-Dont-Know-JS#285]
Would this be better written from 

In a computer language, a group of these words, numbers, and operators **forms** a statement, which is a set of instructions to the computer to perform some task. For example:

to:

In a computer language, a group of these words, numbers, and operators **form** a statement, which is a set of instructions to the computer to perform some task. For example:

**Comment by Charlotteis** [comment]
Your change reads much smoother to me!

**Comment by getify** [comment]
Thanks for the suggestion. Tweaked a bit.
