### ISSUE TITLE
"up & running": Ch. 2 - Conditional !! ?

### ISSUE THREAD

**Issue by pertrai1** [getify/You-Dont-Know-JS#291]
Is it worth giving an idea of what `!!` does in the conditional section of chapter 2?

**Comment by getify** [comment]
That topic is more complex than this book plans to get into. It's fully covered in detail in [Chapter 4 of the "Types & Grammar" book](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20&%20grammar/ch4.md#explicitly-----boolean).
