### ISSUE TITLE
"up & going": A couple thoughts on chapter 1

### ISSUE THREAD

**Issue by KellyHitchcock** [getify/You-Dont-Know-JS#292]
Overall, I thought it was a very good introduction with a good deal of concrete examples to tie these abstract concepts to. It felt to me like the section on scopes and closures needed more concrete examples. 

Like with scope, I've always understood it as the boundaries in which a certain function can be performed. With the buying a phone example, maybe the employee can only help you with a purchase at one particular location. 

Maybe it was because closures was at the end of the chapter, but I was feeling overloaded when I got there and my brain could not process the information. Anything you can do to make this section less intimidating would be a positive change. 

My only other comment is that I think the quotation marks are overused when introducing terms, particularly given that " " means something different in code itself. Maybe italics instead? Just a thought. Great job and good luck!

**Comment by getify** [comment]
Thanks so much! Great feedback!

**Comment by getify** [comment]
Maybe on "scope" I can extend the phone store metaphor to talking about how the employee only has access to the phones they have in stock at that location, and that they can't get phones from other stores. :)

I am thinking I may move "closure" entirely out of chapter 1 and leave it only in chapter 2. It's too much for chapter 1 I think.

**Comment by getify** [comment]
Check out: https://github.com/getify/You-Dont-Know-JS/commit/647693729521b491e3919cd7a6a9e5bdb93c3d3b#diff-76156755825f17e9d885b1c8c90b030aR529
