### ISSUE TITLE
"up & running": ch.3, ambiguous/confusing wording

### ISSUE THREAD

**Issue by pertrai1** [getify/You-Dont-Know-JS#294]
This did not make sense to me when reading it as a sentence:

> which acts as a sort of property look-up chain (not totally unlike the lexical scope chain, actually)

Possibly better:

> which acts similar to the property look-up chain (not totally unlike the lexical scope chain, actually)

**Comment by getify** [comment]
it's not "similar to", it IS.

but agreed that the wording here is hedged unnecessarily. I'll revise.
