### ISSUE TITLE
"up & running": ch.3, s/ire/frustrating/g

### ISSUE THREAD

**Issue by pertrai1** [getify/You-Dont-Know-JS#295]
I believe that `ire` could be better used as was done in previous issue where you used `frustration` instead.

> No topic in JavaScript raises more **ire** from developers than when you talk about the confusions surrounding implicit coercion.

**Comment by cliffordfajardo** [comment]
I second @pertrai1. I feel that the word "frustration" encapsulates what you were trying to convey to the reader 'more' visually than 'ire', if that makes any sense. petrai1 makes a good point about consistency as that is one of the main reasons why I love your "YDKJS" series.

**Comment by getify** [comment]
s/ire/frustration/g
