### ISSUE TITLE
"async & performance": ch.1, break long sentence

### ISSUE THREAD

**Issue by pertrai1** [getify/You-Dont-Know-JS#298]
This long running paragraph could probably be changed for easier and understandable reading:

> But as JS continues to grow in both scope and complexity, to meet the ever widening demands of a first-class programming language that runs in browsers and servers and every conceivable device in between, the pains by which we manage asynchrony are becoming increasingly crippling, and they cry out for approaches that are both more capable and more reason-able.

Possibly:

> As JS continues to grow in both scope and complexity, meeting the demands of a first-class programming language that runs in browsers and servers, as well as  every conceivable device in between is ever widening . The pains by which we manage asynchrony are becoming increasingly crippling, and they cry out for approaches that are both more capable and more reason-able.

**Comment by gikfi** [comment]
Those long Marcel Proust style sentences look good to me as long as are not part of the key concept intensive sections.

**Comment by pertrai1** [comment]
I think "pains" is a key concept :-)

**Comment by getify** [comment]
I like it the way it is. But thanks for the suggestion.
