### ISSUE TITLE
"async & performance": ch.1, understanding of 10m

### ISSUE THREAD

**Issue by pertrai1** [getify/You-Dont-Know-JS#301]
In this sentence, is `m` supposed to stand for million?

> But if it's say 10m records, that can take awhile to run (several seconds on a powerful laptop, much longer on a mobile device, etc).

**Comment by getify** [comment]
yes.

[not a lot of agreement here](http://arstechnica.com/civis/viewtopic.php?t=1144032) on proper way to abbreviate, so I just use lowercase "m" because I like it. :)

**Comment by getify** [comment]
fixed
