### ISSUE TITLE
"types & grammar": ch1, Test for a null value

### ISSUE THREAD

**Issue by okadurin** [getify/You-Dont-Know-JS#302]
/types & grammar/ch1.md Built-in Types:

If you want to test for a null value using its type, you need a compound condition: 
```javascript
var a = null;
(!a && typeof a === "object"); // true
```
================

Hi, any reason why I might want to test for a null value using _its type_? If we don't need to test for a null value using _its type_ is it ok to compare as follows:
```javascript
var a = null;
(a === null) // true
```
Thanks!

**Comment by getify** [comment]
> any reason why I might want to test for a null value using its type?

Not particularly, unless your goal is to teach about the `typeof null` bug while writing a book about types. :)

> is it ok to compare as follows: `(a === null)`

Yep. It's also OK (and I think better) to test with `(a == null)`. But I cover those details in Chapter 4 when we talk about coercion. Here in Chapter 1, we're only talking about types and in particular, the `typeof` operator and its behavior. :)

**Comment by okadurin** [comment]
Thanks a lot! 
And I want to say that I realy like your book series! :)

**Comment by getify** [comment]
Awesome, good to hear! :)
