### ISSUE TITLE
"async & performance" ch.2: so or say?

### ISSUE THREAD

**Issue by pertrai1** [getify/You-Dont-Know-JS#303]
Was not sure if I was reading this wrong, so I will put it here for review:

> "I need to go to the store, but on the way I'm sure I'll get a phone call, **so** 'Hi Mom', and while she starts talking, I'll be looking up the store address on GPS, but that'll take a second to load, so I'll turn down the radio so I can hear mom better, then I'll realize I forgot to put on a jacket and it's cold outside, but no matter, keep driving and talking to mom, and then the seatbelt ding reminds me to buckle up, **so** 'Yes mom, I am wearing my seatbelt, I always do!'. Ah, finally the GPS got the directions, now..."

Should that be say instead of so? Just did not read right to me the first time

> "I need to go to the store, but on the way I'm sure I'll get a phone call, **say** 'Hi Mom', and while she starts talking, I'll be looking up the store address on GPS, but that'll take a second to load, so I'll turn down the radio so I can hear mom better, then I'll realize I forgot to put on a jacket and it's cold outside, but no matter, keep driving and talking to mom, and then the seatbelt ding reminds me to buckle up, **say** 'Yes mom, I am wearing my seatbelt, I always do!'. Ah, finally the GPS got the directions, now..."

**Comment by getify** [comment]
it's informal like if you were abbreviating while speaking (since the point is kind of stream of consciousness).
