### ISSUE TITLE
"up & going": Chapter 1

### ISSUE THREAD

**Issue by shelleyp** [getify/You-Dont-Know-JS#304]
"Typing that code into the console in Chrome would look something like this|"

Might need to touch on what the console is, and how does one open it in chrome

**Comment by pertrai1** [comment]
Possibly a good place for these instructions would be in an appendix possibly?

**Comment by mallowigi** [comment]
Or in Firefox, and, most importantly, IE.

**Comment by shelleyp** [comment]
Definitely, all browsers. And yes, it does sound like good Appendix material. That, and pointing out the code sites, like jsBin and jsFiddle.

**Comment by getify** [comment]
all good points. thanks!

**Comment by getify** [comment]
Addressed in this commit: https://github.com/getify/You-Dont-Know-JS/commit/1213e9aef60e3ae5e0fece1e7e849d5483ac43ec
