### ISSUE TITLE
In Scope&Closures AppendixB let-er seems not added at end of chapter?

### ISSUE THREAD

**Issue by transedward** [getify/You-Dont-Know-JS#315]
In [Implicit vs. Explicit Blocks](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/apB.md#implicit-vs-explicit-blocks),
I saw the ^note-let_er in content but didn't see the link at the end of the AppendixB,
which seems like a good practice of this series of books.
[let-er](https://github.com/getify/let-er)
and maybe more example and how you implemented let-er added in context would be
more comprehensible (like try-catch you mentioned)?

**Comment by getify** [comment]
If you look at the [raw form of the markdown source](https://raw.githubusercontent.com/getify/You-Dont-Know-JS/master/scope%20&%20closures/apB.md), you'll see the footnote **is** there for *let-er*, but for some reason github's rendering isn't showing it. Weird. Seems like a bug with github.
