### ISSUE TITLE
this & Object Prototypes: what would be the solution to the end code on chapter 2

### ISSUE THREAD

**Issue by Cmdv** [getify/You-Dont-Know-JS#321]
Not sure if I'm being idiotic but I can't seem to work out how you would imply "bind" on the last code section in chapter2 to replace the use of self = this: 

```
function foo() {
    var self = this; // lexical capture of `this`
    setTimeout( function(){
        console.log( self.a );
    }, 100 );
}

var obj = {
    a: 2
};

foo.call( obj ); // 2
```

Hopefully I'm not being a total tool be good to know what your implementation would be in this situation :)

**Comment by getify** [comment]
Pretty straightforward, I believe:

```js
function foo() {
    setTimeout( function(){
        console.log( this.a );
    }.bind(this), 100 );
}

var obj = {
    a: 2
};

foo.call( obj ); // 2
```

And, in ES6, the fat arrow `=>` (which I definitely do not like, but...) would be:

```js
function foo() {
    setTimeout( () => {
        console.log( this.a );
    }, 100 );
}

var obj = {
    a: 2
};

foo.call( obj ); // 2
```

That works because ES6 arrow functions have lexical `this`, which means they're essentially doing the `var self = this` thing for you. :)

**Comment by Cmdv** [comment]
Superb, thanks a lot. would you say this is acceptable too if I happen to need to call a function within a function and bind "this" :

```
function foo(){
  (function bar(e){
    console.log(e.a);
  })(this);
}

var obj = {
  a: 2
};
foo.call( obj ); // 2
```

Really been enjoying all of your books such a great way to learn Javascript, I started your course on Frontendmasters then just kept going. Thanks for all your effort it's appreciated :)

**Comment by benjamingr** [comment]
@Cmdv this would also work - you see it more commonly without an IIFE as:

```js
function foo() {
   var that = this; 
   setTimeout( function(){
        console.log( that.a );
    }, 100 );
}
```

That said, in my personal opinion both alternatives suggested by Kyle are cleaner.

**Comment by Cmdv** [comment]
@benjamingr 

Thanks for your input but if you read the end of chapter 2 it says:

```
While self = this and arrow-functions both seem like good "solutions" to not wanting to use bind(..), they are essentially fleeing from this instead of understanding and embracing it.
```
