### ISSUE TITLE
"up & going": Code Sample Clarity

### ISSUE THREAD

**Issue by Jenn** [getify/You-Dont-Know-JS#325]
Often when following along with code samples, students will read and type exactly from top to bottom instead of looking ahead. Two areas this might be confusing in chapter 1:

**I would move the tip before the code sample so readers know how to move from line to line and don't worry about not knowing how to do so** 

Now, type this code and see how it runs:
a = 21;

b = a * 2;

console.log( b );
Tip: To type multiple lines into the console at once, use <shift> + <enter> to move to the next new line. Once you hit<enter> by itself, the console will run everything you've just typed.

**In the next sample, it sounds like we are about to see an example of a multiline comment with */ in it. Perhaps move that line after the code sample.**

It can also appear anywhere on a line, even in the middle of a line, since the */ ends it. The only thing that cannot appear inside a multiline comment is a */, since that would be interpreted to end the comment. For example:

var a = /* arbitrary value */ 42;

console.log( a );   // 42

**Comment by getify** [comment]
great feedback, thanks so much! :)

**Comment by getify** [comment]
If you have any other editorial suggestions, please feel free to re-open. Thanks!
