### ISSUE TITLE
"scope & closures" and "this & Object Prototypes": editorial comments

### ISSUE THREAD

**Issue by getify** [getify/You-Dont-Know-JS#335]
For second editions of these books, sift through the condescension here to see if there's any useful feedback to improve the content:

https://news.ycombinator.com/item?id=9058533

> Your opening paragraph of chapter 1 makes several debatable claims. For example, your characterisation of mutable variables as fundamental to nearly all programming languages immediately ignores alternatives such as purely functional or logic languages. That is perhaps an unfortunate choice given the current trends in JS libraries and frameworks, which in many cases are moving in that more declarative direction.
> You then seem to conflate various concepts of scope, storage and lifetime throughout the book, and similarly do not seem to distinguish clearly and consistently between the concepts of identifiers, variables and values. In a language where closures and references to functions are used routinely and where you have some types passed by value but others effectively passed by reference, these kinds of distinctions matter, particularly to someone who has learned by osmosis or perhaps come from a background working with other programming languages, which seems to be a lot of your target audience here.
> More generally, your terminology tends to drift away from the ECMAScript spec quite a lot, again making it less precise. Another example would be the opening paragraph of chapter 1 of "this & Object Prototypes", where you describe this as being a "special identifier keyword". By definition (in the spec) an identifier can't be a keyword, because an identifier is precisely an identifier name that is not a reserved word.
> The most vague section of those I read was probably when you discuss closures in the final chapter, where I'm sorry to say you come across as rather unfamiliar with the concept yourself. Your usage is somewhat casual, unidiomatic even, not least in your definition of the term itself. Your explanation for where closures come from ("Closures happen as a result of writing code that relies on lexical scope. They just happen.") is just plain wrong, as evidenced by the fact that numerous languages with lexical scope do not provide closures as a language feature at all.

Most of this feedback is ignorant of the intent to make technical details more accessible to those not steeped in traditional academic terms and processes. But nonetheless, accuracy is also an important goal. Some clarity in the content wording may stem from these points.

**Comment by getify** [comment]
[ hijacking the rest of this thread for further second edition revisions ]

"scope & closures", ch5

> that anonymous function still has closure over that scope.

In fact, it's not an anonymous function, it's a function expression called `timer`.

**Comment by benjamingr** [comment]
Meh, most of the criticism is bs, I'm going to try to read some of the chapters and leave comments about stuff that can be ambiguous or divisive.

**Comment by getify** [comment]
need to update end of chapter 5 "scope & closures" to use the final ES6 module syntax

**Comment by bronickstone** [comment]
well im really glad i helped in some way was only really wanted to know the truth and learn a bit and i never wanted to hurt any companie that did work on my software, u just doing your jobs made my mind up to sign up to them as i thought that ment i was never going to cause probs but as usal i hit the wrong button u should know im only upset with two people no one else ? a bit of help would be nice if u get the odd min as going to try and learn a bit more and chouse life thank you

**Comment by getify** [comment]
No longer relevant to the 2nd-ed book, so closing.
