### ISSUE TITLE
"scope & closure": "loops + closure" alternative closure solution

### ISSUE THREAD

**Issue by pdawyndt** [getify/You-Dont-Know-JS#350]
Another variation on binding the loop variable to the callback is to "close" the callback itself with an IIFE rather than the entire call to `setTimeout`. The end result looks like this:

```
for (var i = 1; i <= 5; ++i) {
    setTimeout(
    	(function(j){ 
    		return function timer(){ 
    			console.log(j); 
    		};
    	})(i), 
    	i * 1000
    );
}
```

**Comment by getify** [comment]
That's true, but you then have to do the `return function...` whereas in the previous version, there's no need to `return` anything. I think this version is a tiny bit more confusing, TBH.
