### ISSUE TITLE
"types & grammar": explicitly: parsing numeric strings

### ISSUE THREAD

**Issue by kemar** [getify/You-Dont-Know-JS#373]
Hi,

The last sentence of this chapter (kudos, great book btw!) can be somewhat misleading:

> As of ES5, `parseInt(..)` no longer guesses. Unless you say otherwise, it assumes base-10. That's much nicer. Just be careful if your code has to run in pre-ES5 environments, in which case you still need to pass `10` for the radix.

The radix of 16 is still assumed in [ES5](http://www.ecma-international.org/ecma-262/5.1/#sec-15.1.2.2) and [ES6](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-parseint-string-radix) in some cases:

> If *radix* is **undefined** or 0, it is assumed to be 10 except when the number begins with the character pairs **0x** or **0X**, in which case a radix of 16 is assumed.

**Comment by getify** [comment]
Interesting. Did not know that `"0x"` was still being parsed into hex. Thanks.
