### ISSUE TITLE
"scope & closures": clear up misleading wording

### ISSUE THREAD

**Issue by getify** [getify/You-Dont-Know-JS#379]
"Collision Avoidance":

``` js
function foo() {
    function bar(a) {
        i = 3; // changing the `i` in the enclosing scope's for-loop
        console.log( a + i );
    }

    for (var i=0; i<10; i++) {
        bar( i * 2 ); // oops, infinite loop ahead!
    }
}

foo();
```

The `i = 3` assignment inside of `bar(..)` overwrites, unexpectedly, the `i` that was declared in `foo(..)` at the for-loop. In this case, it will result in an infinite loop, because `i` is set to a fixed value of `3` and that will forever remain `< 10`.

---

Actually, `i` is not really a "fixed value" of `3`.. it's set to `3` each loop, and then the `i++` updates it to `4` before the next iteration sets it back to `4`. Clear up the misleading wording in that paragraph.

**Comment by nitink4472** [comment]
I would like to contribute but tell me that what are the values that you want to console?Is it 3,5,7,9,11,13,15,17,19,21 and then terminate?

**Comment by getify** [comment]
This issue is now moot as the text has been re-written in second edition. Closing.
