### ISSUE TITLE
"types & grammar": Value vs. Reference

### ISSUE THREAD

**Issue by kemar** [getify/You-Dont-Know-JS#387]
In case you're interested, I read that some people use "Call by sharing" when talking about the JavaScript evaluation strategy.

    var a = b = {'foo': 1};

`a` and `b` are sharing the same `{'foo': 1}` object.

From Wikipedia:

> "Call by sharing" 
> Also known as "call by object" or "call by object-sharing" is an evaluation strategy first named by Barbara Liskov et al. for the language CLU in 1974.

From the CLU documentation (p.14 http://publications.csail.mit.edu/lcs/pubs/pdf/MIT-LCS-TR-225.pdf):

> Argument passing is defined in terms of assignment; the formal arguments of a routine are considered to be local variables of the routine and are initialized, by assignment, to the objects resulting from the evaluation of the argument expressions. We call the argument passing technique *call by sharing*, because the argument objects are shared between the caller and the called routine. The technique does not correspond to most traditional argument passing techniques (it is similar to argument passing in LISP). In particular **it is not call by value** because mutations of arguments performed by the called routine will be visible to the caller. And **it is not call by reference** because access is not given to the variables of the caller, but merely to certain objects.

- http://dmitrysoshnikov.com/ecmascript/chapter-8-evaluation-strategy/#call-by-sharing
- http://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_sharing
- https://learntofish.wordpress.com/2012/01/09/call-by-object-reference-call-by-sharing/

**Comment by getify** [comment]
Appreciate the links and formal information. Not sure if there's anything actionable here for changing/clarifying anything in the book. Closing for now, but if you have any specific suggestions, please feel free to re-open. :)
