### ISSUE TITLE
"up & going": Chapter 1 console.log coercion

### ISSUE THREAD

**Issue by piperswe** [getify/You-Dont-Know-JS#395]
`console.log` doesn't coerce values, it can take any data type and displays it as such.

![Imgur](http://i.imgur.com/JLkpA58.png)

Notice the color difference between the `Number` and `String` values, `console.log` interpreted them differently, the only changing of data types happens in the engine's implementation of `console.log` (most likely native code).

**Comment by getify** [comment]
Yes, you're technically correct. I'm not sure it terribly affects the overall message either way. But I could clarify this a bit better in a second edition.

**Comment by ladmerc** [comment]
Would be better to fix this in this current edition. Kinda misleading to people who would 100% trust the contents of your material.

**Comment by getify** [comment]
Closing since "Up & Going" was replaced with the new "Get Started" book for second edition, so this issue is no longer applicable.
