### ISSUE TITLE
Module resolution

### ISSUE THREAD

**Issue by mallowigi** [getify/You-Dont-Know-JS#405]
Hi, I have a question regarding modules in ES6.

As a regular of CommonJS, I find it quite odd that when importing modules, we don't specify the full path (or relative) of the module.

```js
import x from "foo";
```

How is the module resolver able to determine where is the foo? If I have two files declaring foo, which one would he take?

I tried using browserify to leverate ES6 modules, and I got this problem. Is it an issue with Browserify not completely simulating the module resolver or is it an error in the book?

Thanks :)

**Comment by getify** [comment]
The ModuleSpecifier is not controlled by ES6, you have to put a normal path in there (either file system path for local server loading like in node, or URL for browsers).

**Comment by getify** [comment]
Closing for now. Reopen if there's more to answer.
