### ISSUE TITLE
Is it okay to translate YDKJS?

### ISSUE THREAD

**Issue by ramesaliyev** [getify/You-Dont-Know-JS#413]
Hello,

We want to translate these awesome books into our language :) But license is not quite clear about it, or we dont understand very well. So is it okay or not? 

Thanks.

**Comment by nesrinkalender** [comment]
+1

**Comment by AlanCezarAraujo** [comment]
+1

**Comment by zhongsp** [comment]
You could find the answer [here](https://github.com/getify/You-Dont-Know-JS/issues/9#issuecomment-37836191)  :)

**Comment by hwclass** [comment]
+1

**Comment by getify** [comment]
answered via email.
