### ISSUE TITLE
Default value syntax trick

### ISSUE THREAD

**Issue by JohnGurin** [getify/You-Dont-Know-JS#421]
Don't know if this were mentioned earlier, but I think the better "default value syntax trick" would be
`vals || (vals = ..)`
instead of 
`vals = vals || ..`

Spotted this tip in *Types & Grammar - Chapter 3: Natives - Prototypes As Defaults*

**Comment by getify** [comment]
can you define "better"?

alternate form, for sure. but IMO not as good.

**Comment by IanVS** [comment]
The second makes a lot more intuitive sense to me. Just my two cents.

**Comment by JohnGurin** [comment]
There is no redundant assignment. As far as I understand, int the usual way of default value trick, `vals` is evaluated firstly then assigned to the same variable.

**Comment by getify** [comment]
argument in favor of `val || (val = ..)`: http://webreflection.blogspot.co.uk/2011/08/please-stop-reassigning-for-no-reason.html

argument in favor of `val = val || ..`: https://twitter.com/wesleytodd/status/591957479082356738

> There is no redundant assignment.

Naively speaking, `val = val || ..` would always assign `val`, even if the thing it's assigning is just the current `val` value. But I would hope engines are intelligent enough to see `val = val` and skip it in those cases.

**Comment by benjamingr** [comment]
> But I would hope engines are intelligent enough to see val = val and skip it in those cases.

I don't think engines make that assumption. It does sound reasonable though.

**Comment by getify** [comment]
I don't see convincing enough evidence to warrant a change here. Please reopen if there's more to consider.
