### ISSUE TITLE
"es6 and beyond": remarks on destructuring

### ISSUE THREAD

**Issue by angus-c** [getify/You-Dont-Know-JS#425]
incredibly thorough - very cool

Just 2 things:

* After the first (non es6) example you say: *This pattern is widely called array destructuring assignment*.

Technically the manual assignment is a destructuring assignment , but using that term in the context of a chapter about es6 destructure assignment invites confusion IMO.

* you could explicitly call out destructuring's succinct options syntax

```js
// es6
const fn = ({a,b,c}={}) => console.log(a,b,c);

// es5
var fn = function(options) {
  options || (options = {});
  console.log(options.a, options.b, options.c)
}
```

**Comment by getify** [comment]
> you could explicitly call out destructuring's succinct options syntax

Hmmm... quoting the chapter (beginning of the "Object Property Assignment Pattern" section):

> If the property name being matched is the same as the variable you want to declare, you can actually shorten the syntax:
> 
> `var { x, y, z } = bar();`

**Comment by getify** [comment]
> using that term in the context of a chapter about es6 destructure assignment invites confusion IMO.

Actually, I see exactly what you mean. I think this might have been an artifact of some reordering of content and missing this point. Excellent catch, thanks! :)

**Comment by getify** [comment]
See 0e6f58b, does that clear up the terminology confusion? :)

**Comment by getify** [comment]
Closing for now, reopen if you have further feedback. Thanks! :)
