### ISSUE TITLE
ToBoolean in comparison operators

### ISSUE THREAD

**Issue by matt-e-king** [getify/You-Dont-Know-JS#435]
Hey Kyle! First off, this series is great, my understanding for the Javascript language is much much deeper thanks to you - hopefully I can put it into practice :)

I was hoping for clarification on something...

If I am understanding correctly, the ToBoolean abstract operation is never used during the ``==`` and ``===`` comparison operations. According to the spec (http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3), it appears only the ToNumber and ToPrimitive are the abstract operations used, respective to the types being compared. Am I understanding that correctly? 

AirBnB recently pushed out their new style guide with ES6 in mind and in this section https://github.com/airbnb/javascript#comparison-operators--equality:
> Comparison operators are evaluated using coercion with the ToBoolean method and always follow these simple rules

Is that correct? Is the ToBoolean ever used with the comparison operators? Any clarification would be appreciated. Thanks!

**Comment by getify** [comment]
There is absolutely **no** `ToBoolean` coercion that occurs with the coercible comparison operators `==` and `!=`. The spec is plain and clear on that, as you've already read.

I'd like to be generous and give some clarifying explanation for their explanation, but having read it now several times, I can't come up with any way to spin that besides: wrong/misleading. It's probably just an innocent mistake or confused wording.

You might want to file an issue with them withjyour concern to clarify. Feel free to point them at the book or this thread if they'd like more info. ;-)

**Comment by matt-e-king** [comment]
Thanks, Kyle! https://github.com/airbnb/javascript/issues/336
