### ISSUE TITLE
es6: ch2: "const declarations", GC admonition may be inaccurate

### ISSUE THREAD

**Issue by chrisdickinson** [getify/You-Dont-Know-JS#437]
Per [the text](https://github.com/getify/You-Dont-Know-JS/blob/e49c289219dd88e9552c9c3de0c3174af6e38554/es6%20%26%20beyond/ch2.md#const-declarations):

> **Warning:** Assigning an object or array as a constant means that value will never be able to be garbage collected, since the reference to the value can never be unset. That may be desirable, but be careful if it's not your intent!

I don't believe this is so – GC works as usual on objects pointed to by these references. If they can't be reached by walking the graph from a retaining object, they'll be GC'd like any other object. The distinction is that global constant values will *always* be reachable from a retaining object – the global object – so constants at that level may never be garbage collected.

As an example, just to illustrate:

```javascript
// will never be GC'd in this program, since each of these create
// a reference reachable from the global object:
var globalValue = {}
const constantGlobalValue = {}
let blockScopedGlobalValue = {}

{
  const someOtherObject = {}
}
// at this point someOtherObject is a viable candidate for GC, since it
// can no longer be reached by a retaining object.
```

**Comment by getify** [comment]
Sounds like I need to amend the sentence:

"Assigning an object or array as a constant means that value will never be able to be garbage collected **until that constant's lexical scope goes away**, since the reference to the value can never be unset."

This was my original intent, but I was not specific. Better?

**Comment by chrisdickinson** [comment]
Yep! I might amend "never" to "not" in the above, since front-loading "never" in front of a caveat reads a bit oddly:

"Assigning an object or array as a constant means that value will ~~never~~ not be able to be garbage collected until that constant's lexical scope goes away, since the reference to the value can never be unset."

**Comment by getify** [comment]
+1. care to submit a PR? ;-)

**Comment by chrisdickinson** [comment]
Will do :) Thanks for the prompt reply!
