### ISSUE TITLE
https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch7.md#review

### ISSUE THREAD

**Issue by dingnan** [getify/You-Dont-Know-JS#448]
it's time to start leveraging these powerfu meta programming capabilities to push the language further!

should read

it's time to start leveraging these powerful meta programming capabilities to push the language further!

**Comment by mleah** [comment]
I updated this and submitted a pull request.

**Comment by getify** [comment]
fixed.
