### ISSUE TITLE
Idea: Using a plus sign instead of parentheses at the start of an IIFE.

### ISSUE THREAD

**Issue by illourr** [getify/You-Dont-Know-JS#453]
I don't think I've seen this referenced within the You Don't Know JS series, and thought it may be useful if you could find a place to put it.
```javascript
+function ($) {
  'use strict';
  var version = $.fn.jquery.split(' ')[0].split('.')
  if ((version[0] < 2 && version[1] < 19) || (version[0] == 1 && version[1] == 9 && version[2] < 1)) {
    throw new Error('Bootstrap\'s JavaScript requires jQuery version 1.9.1 or higher');
  }
}(jQuery);
```
In the bootstrap.js source code I ran across this at the very beginning of the file.  I got curious about what was happening here because this function will return `NaN` instead of `undefined` if the exception is not thrown, because it is being coerced to a `Number`.

It is a Immediately invoked function expression, but with something a little different about it.  It's prefixed with a `+` sign instead of it having an opening an closing parens.

`+`, `-`, `!`, `~` before the function keyword can be used in replacement to a opening closing parens on the IIFE.

Source: http://stackoverflow.com/questions/13341698/javascript-plus-sign-in-front-of-function-name

**Comment by getify** [comment]
There's quite a few ways to make a function into an expression using unary operators. I've mused about this on twitter many times, but never really had a place to put it into the books. My favorite:

```js
void function foo(x){ .. }();
```

The `+` and `!` operators are pretty commonly used by minifiers, but I don't think most people author with them.

**Comment by illourr** [comment]
It's also worth noting that using one of these unary operators will have different side effects on the functions return value.

For example:
```javascript
void function foo(x) { 
  return 1;
}();
// returns undefined

+function foo(x) { 
  return 1;
}();
// returns 1
```

**Comment by getify** [comment]
There's no need for the unary operator to turn the function into an expression if the return value is cared about, as this will always be using the function in an already-expression position, such as:

```js
var a = function(..) { .. }();  // <-- execute the expression, assign return to `a`

foo( function(..) { .. } () ); // <-- execute the expression, pass return into `foo(..)`
```

**Comment by illourr** [comment]
Good point. Thanks.

**Comment by getify** [comment]
I'll keep this around for second edition to consider adding a little note about other unary operator options. :)
