### ISSUE TITLE
"up & going": Ch1 Practice. Purchase is always unaffordable

### ISSUE THREAD

**Issue by mvg73** [getify/You-Dont-Know-JS#456]
Can you improve on the Ch 1 practice? Because despite any changes to the constants in the Ch 1 Practice solution, the purchase is always unaffordable. That is it always comes back with "You can't afford this purchase. :("
I tested this by copy/pasting the very text from the digital book into my console. I did it again and again using different values in the constants for the threshold, prices, bank balance, etc... Always You can't afford this purchase. :("

**Comment by getify** [comment]
I may look into tweaking the logic for second edition. Thanks.

**Comment by michelrossier** [comment]
What about changing it to:
```
// keep buying phones while you still have money
while (amount + PHONE_PRICE < bank_balance) {
```

As the loop is intended to buy phones only if there is enough money left.

**Comment by bautistaI** [comment]
agree! is always problematic when you try to solve the problem on your own just to find out the "answer" doesn't really work. This is what makes things hard for beginners.

**Comment by jcohlmeyer** [comment]
There is also a larger issue in the fact that you are adding the tax after you decide how many phones to purchase. For a more reliable calculation you should add the tax before you calculate how many phones you can afford.

**Comment by getify** [comment]
The point of the snippet was to show simple if-then logic, not to have a completely accurate adding program. I understand the points being made here, but really, can we just lighten up, it's not a cash register that was being programmed. The text is for beginner programmers.

**Comment by petrpacas** [comment]
I know this issue is closed, but I'd just like to add my input:

Disclaimer: I'm not a _complete_ beginner programmer, but not very skilled either.

I found the description of the pratical task pretty confusing. I got stuck at it for a couple of minutes and then decided to make a similar narrative that made more sense to me (`bankBalance` vs. `spendingTreshold`).

Then, tinkering with the sample solution and the (expected) inability to achieve the positive outcome was somewhat frustrating to me.

I believe that modifying the practical exercise would lead to more newbie happiness.

**Comment by shhhpark** [comment]
for some reason even when i copy and paste your exercise answer i'm receiving errors like Uncaught SyntaxError: Identifier 'ACCESSOR_PRICE' has already been delared.  Am I missing something very obvious..

**Comment by legodude17** [comment]
It is because `ACCESSOR_PRICE` is a `const`, so you can't redeclare it.

**Comment by shhhpark** [comment]
it's giving me the error on line 1 though and I wasnt re declaring it anywhere further down

**Comment by legodude17** [comment]
Where are you running it?

**Comment by shhhpark** [comment]
in a blank page's console in chrome

**Comment by legodude17** [comment]
Did you run it more than once? That would be why if you did.

**Comment by shhhpark** [comment]
That must be why...thought clearing out the console would be enough instead of opening a new instance.  Much aprpeciated!

**Comment by pratechnic** [comment]
I implemented it as I understood it from the text maybe the wording for the problem itself can be clearer & better. I ended up coding this:
`
const TAX_RATE = 0.8;
const PHONE_PRICE = 100;
const ACCESSORY_PRICE = 50;
const SPENDING_THRESHOLD = 200;

var bank_balance = 3459;

//Function to calculate tax amount
function calculate_tax(amount){
	return amount * TAX_RATE;
}

//Function to make the amount presentable
function format_amount(amount) {
	return "$"+amount.toFixed(2);
}

var amount = 0;
var accessory_amount = 0;

//Keep buying phones until you can't any more
while(bank_balance > 0) {
	amount += PHONE_PRICE;

	//Keep buying accessories as long as you are in the threshold amount
	while (accessory_amount < SPENDING_THRESHOLD) {
		accessory_amount += ACCESSORY_PRICE;
	}
	amount += accessory_amount;

	//Reduce that from the bank balance
	bank_balance -= amount;
}

//Calculate tax, format the amount & Print final bill
amount = amount + calculate_tax(amount);
final_amount = format_amount(amount);
console.log("Your Final bill is for:"+final_amount);
`

**Comment by pratechnic** [comment]
The wording to the problem itself can be better, as I ended up coding this from my understanding of it:

```
const TAX_RATE = 0.8;
const PHONE_PRICE = 100;
const ACCESSORY_PRICE = 50;
const SPENDING_THRESHOLD = 200;

var bank_balance = 3459;

//Function to calculate tax amount
function calculate_tax(amount){
	return amount * TAX_RATE;
}

//Function to make the amount presentable
function format_amount(amount) {
	return "$"+amount.toFixed(2);
}

var amount = 0;
var accessory_amount = 0;

//Keep buying phones until you can't any more
while(bank_balance > 0) {
	amount += PHONE_PRICE;

	//Keep buying accessories as long as you are in the threshold amount
	while (accessory_amount < SPENDING_THRESHOLD) {
		accessory_amount += ACCESSORY_PRICE;
	}
	amount += accessory_amount;

	//Reduce that from the bank balance
	bank_balance -= amount;
}

//Calculate tax, format the amount & Print final bill
amount = amount + calculate_tax(amount);
final_amount = format_amount(amount);
console.log("Your Final bill is for:"+final_amount);
```

**Comment by zeckdude** [comment]
Below is my take on the solution for the problem @getify  described in Chapter 1. I agree that the directions are confusing, but not impossible. Definitely too hard for a Chapter 1 exercise, but a good challenge nonetheless. 

Here's a pen of it in action: https://codepen.io/zeckdude/pen/zdOPva

```
const PHONE_PRICE = 99.99;
const ACCESSORY_PRICE = 9.99;
const SPENDING_THRESHOLD = 200;

const TAX_PERCENTAGE = 8;
var bankAccountBalance = 303.91;

function calculateTax(amount) {
  return amount * (TAX_PERCENTAGE/100);
}

function formatAmount(amount) {
  return '$' + amount.toFixed(2);
}

function countPurchasedItems(purchasedItems) {
  return purchasedItems.phones + purchasedItems.accessories;
}

function calculatePurchaseAmount(bankAccountBalance) {
  var total = 0;
  var purchaseAmount;
  var totalTax;
  var purchasedItems = {
    phones: 0,
    accessories: 0
  };
  
  // Is there still enough money in the bank account for at least one phone?
  while(bankAccountBalance >= PHONE_PRICE) {
    purchaseAmount = 0;
    
    // Add the phone price to the purchase amount
    purchaseAmount += PHONE_PRICE;
    purchasedItems.phones++;

    // If the total of all purchases isn't over the spending threshold yet, then add the accessory
    if (total <= SPENDING_THRESHOLD) {
      purchaseAmount += ACCESSORY_PRICE;
      purchasedItems.accessories++;
    }
    
    // If the bank account balance can still cover the price for the new item(s) in the loop when added to the overall taxes, then add the new items(s) amounts to the overall total
    if ((purchaseAmount + calculateTax(total)) < bankAccountBalance) {
      // Add the determined purchase amount to the running total
      total += purchaseAmount;
      
      // Deduct the purchase amount from the bank account balance
      bankAccountBalance -= purchaseAmount;
    }
  }
  
  // Add the tax to the subtotal
  totalTax = calculateTax(total);
  total += totalTax;
  
  console.log('PURCHASE SUMMARY');
  console.log('Total Number of Items Purchased:', countPurchasedItems(purchasedItems));
  console.log('Phones Purchased:', purchasedItems.phones);
  console.log('Accessories Purchased:', purchasedItems.accessories);
  console.log('Subtotal:', formatAmount(purchasedItems.phones * PHONE_PRICE + purchasedItems.accessories * ACCESSORY_PRICE));
  console.log('Tax:', formatAmount(totalTax));
  console.log('Total:', formatAmount(total));
}

calculatePurchaseAmount(bankAccountBalance);
```

**Comment by SobiszeK** [comment]
I think we should not muddle this program too much, since it is for beginners, only change that should be made is description of task. We should just add what  @getify has said "It's not a cash register that is being programmed" and note that the result should always be the same.

**Comment by getify** [comment]
Closing since "Up & Going" was replaced with the new "Get Started" book for second edition, so this issue is no longer applicable.
