### ISSUE TITLE
"this & Object Prototypes": Ch6 - using Object.assign for consistency?

### ISSUE THREAD

**Issue by muffypl** [getify/You-Dont-Know-JS#464]
I really like this **OLOO style code**. It's kinda odd that you are using two styles for defining methods, eg:
```javascript
var Widget = {
  init: function () {}
};
// and
var Button = Object.create(Widget);
Button.setup = function () {};
```
How do you feel about using Object.assign? It looks like there is no difference and code is more consistent.
```javascript
var Button = Object.assign(Object.create(Widget), {
  setup: function () {}
});
```
Please correct me if I'm wrong.

**Comment by getify** [comment]
`Object.assign(..)` is an ES6 feature, so to advocate using it requires either ES6 browser support or a polyfill. Also, there's a subtle/minor drawback performance wise: The `{ .. }` object you declare is only temporarily used and then thrown away (creating potential extra GC) and also each of the properties has to be copied over to the actual target object. OLOO object creation is already slower than `new Fn(..)` constructor-form creation, so making it even slower is not something I would necessarily prefer to recommend as general best practice.

Recommending `Object.assign(..)` along with OLOO produces shorter/nicer code examples for sure, but it comes along with that baggage, and at the time of writing (over a year ago) was not something I was fully ready to recommend. I may amend that stance for the second edition, however. :)

**Comment by muffypl** [comment]
Thank you for your response and clarification. :)

**Comment by getify** [comment]
Cheers! :)
