### ISSUE TITLE
"Async & Performance": Ch6 - typo: justifcation  -> justification

### ISSUE THREAD

**Issue by mectest1** [getify/You-Dont-Know-JS#465]
Section: <strong>Not All Engines Are Alike</strong>

//<em>Original:</em>
But it's troublesome to suggest that just one browser's trouble with performance is justifcation for using a code approach that quite possibly could be sub-optimial in all other browsers. ...

//<em>Modified:</em>

justifcation  -> justification

PS: Sorry for the fuzz. The "this & prototype" book helped me a lot, and I really liked the way you clarify some nuances (aka my headaches) in it. Hope you have a nice day. :P

**Comment by getify** [comment]
Thanks so much! :)
