### ISSUE TITLE
Promises chapter. Gate vs Barrier.

### ISSUE THREAD

**Issue by sharov-am** [getify/You-Dont-Know-JS#468]
Hi.
Thank you for great books!

I found some questions related to terminology:

*In classic programming terminology, a "gate" is a mechanism that waits on two or more parallel/concurrent tasks to complete before continuing.*

Wouldn't be it more appropriate to use barrier (https://en.wikipedia.org/wiki/Barrier_%28computer_science%29)  instead of gate?

**Comment by getify** [comment]
I learned it as "gate", similar to how it's described here (in comparison to "barrier"):

https://blog.affien.com/archives/2006/03/02/locks/
