### ISSUE TITLE
"up & going": Chapter 2, pg 38; "by reference"

### ISSUE THREAD

**Issue by TashasEv** [getify/You-Dont-Know-JS#472]
Hello Sir @getify,
As requested, here is my issue for my confusion in regards to the usage of the phrase "by reference" to explain why two arrays containing the same values will test as false when compared using even a non-strict comparison. The explanation states, <I>"Because those values are actually held by reference, both == and === comparisons will simply check whether the references match, not anything about the underlying values." </I>

Since I feel this book is geared towards people like me, the code-curious but untaught, I wanted to let you know that I did not understand this explanation and was fortunate to have a friend who could break it down into further n00bese for me. Otherwise, I am _greatly_ appreciative of the work you are doing here to make JS a friendlier space for people like me. Thanks!

**Comment by getify** [comment]
Closing since "Up & Going" was replaced with the new "Get Started" book for second edition, so this issue is no longer applicable.
