### ISSUE TITLE
Up and Going: Chapter 2 - Values and Types, return values of typeof operator

### ISSUE THREAD

**Issue by bidhan-a** [getify/You-Dont-Know-JS#477]
It is mentioned that 

> The return value from the typeof operator is always one of six (seven as of ES6!) string values.

Besides string, number, boolean, undefined and object, what is the other one? I'm assuming the other one is null, but typeof what would return null? Since typeof null will return an object, I can't seem to find out what would return null in this case. Or is the sixth return value something else? Thanks for any help.

**Comment by zhongsp** [comment]
It's callable object type `function`.

``` js
var foo = function() {}
typeof foo;  // "function"
```

**Comment by getify** [comment]
yep, `"function"`. And in ES6, `"symbol"` makes 7.
