### ISSUE TITLE
static

### ISSUE THREAD

**Issue by stebru** [getify/You-Dont-Know-JS#486]
In the code example here: https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch3.md#static, wouldn't the call to `b.cool()` also fail, since it too is declared as `static`)?

**Comment by getify** [comment]
You're correct, that's a mistake. But actually, this whole discussion is flawed. I was using outdated information when that was written. I'll rework the section for accuracy. Thanks!
