### ISSUE TITLE
Object#assign & symbols

### ISSUE THREAD

**Issue by stebru** [getify/You-Dont-Know-JS#487]
I guess this was changed? https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch6.md#objectassign-static-function

Seems symbols *are* copied when using `Object.assign()`.

**Comment by getify** [comment]
Yeah, [apparently there's been a fair bit of confusion](https://github.com/zloirock/core-js/issues/45) about this. I'm fairly certain symbols were non-enumerable by default at one point, but I guess they're enumerable by default now. Also, the [official MDN polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) for `Object.assign(..)` doesn't support symbols, which is further confusing. That's probably where I got my incorrect info originally.
