### ISSUE TITLE
Niggling comment re: "promisory"

### ISSUE THREAD

**Issue by richb-hanover** [getify/You-Dont-Know-JS#498]
I know that you derived the term "promisory" from "promise factory", but the real word you refer to in Chapter 3 - "conveying or implying a promise" is spelled with two "s" - promissory.

Not sure what you want to do about it, but I thought I should mention it.

BTW: This is a spectacular exposition of async topics, promises, generators, etc. Thank you!

**Comment by getify** [comment]
The two s's would be a typo. :)

**Comment by getify** [comment]
Sorry, looking closer at this issue. I see your point. Not really sure what to do about it though. Changing it breaks the naming convention consistency, and explaining the divergence is probably just distracting. I think we'll just leave it alone. But appreciate you pointing it out. :)

**Comment by richb-hanover** [comment]
Yes, I agree to leave it as-is.
