### ISSUE TITLE
"Loops + Closure": ch5, First value is random

### ISSUE THREAD

**Issue by CodingFree** [getify/You-Dont-Know-JS#506]
Link: https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch5.md#loops--closure

When using the first snippet, It returns a random value at first:
![why](https://cloud.githubusercontent.com/assets/4342359/9113779/b653d4c0-3c56-11e5-9588-3cffdbaa084c.PNG)
 
Why?

**Comment by Manest** [comment]
The 12 is the return value of setTimeout. 
"setTimeout - Return Value: A Number, representing the ID value of the timer that is set. Use this value with the clearTimeout() method to cancel the timer"

**Comment by getify** [comment]
+1. :)
