### ISSUE TITLE
Default parameters & TDZ

### ISSUE THREAD

**Issue by creeperyang** [getify/You-Dont-Know-JS#512]
[You Don't Know JS: Types & Grammar#TDZ](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20&%20grammar/ch5.md#function-arguments):

In **Function Arguments** section:

```js
var b = 3;

function foo( a = 42, b = a + b + 5 ) {
    console.log(a, b);
}

foo(); // 42 NaN
```

When run `foo()`, **no errors throwed!** It's a little confusing. So, any more details?

```js
browser: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0"
```

**Comment by alexeysmorkalov** [comment]
As a paramenter b in a different scope here. It can be calculated as NaN, why you would expect error here?

**Comment by getify** [comment]
Pretty sure the spec calls this a TDZ error, as [confirmed by babel](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=true&playground=false&code=var%20a%20%3D%2010%3B%0Afunction%20foo(a%20%3D%20a)%20%7B%7D%0Afoo()%3B). I think various browsers are just not fully ES6 compliant yet.

**Comment by creeperyang** [comment]
Get it. :grin:
