### ISSUE TITLE
Recommend trying gitbook.com

### ISSUE THREAD

**Issue by binoculars** [getify/You-Dont-Know-JS#524]
https://www.gitbook.com/ is much easier than trying to navigate a GitHub repo full of mardown files.

**Comment by getify** [comment]
Thank you, I am aware of gitbook. It doesn't work for my needs, but it's a great project.

**Comment by Siilwyn** [comment]
@binoculars Found it on gitbook, it's indeed much easier to read: https://www.gitbook.com/book/ydkjs/you-don-t-know-js/details

**Comment by getify** [comment]
It's not supposed to be on there.

**Comment by binoculars** [comment]
@Siilwyn I like it--much easier to navigate and read.

@getify Isn't releasing under CC license make it so that anyone is free to "copy and redistribute the material in any medium or format"

**Comment by getify** [comment]
not if it conflicts with the commercial sale of ebook forms of the book, no.

**Comment by binoculars** [comment]
I don't think that's how it works.

>3. License Grant. Subject to the terms and conditions of this License, Licensor hereby grants You a worldwide, royalty-free, non-exclusive, perpetual (for the duration of the applicable copyright) license to exercise the rights in the Work as stated below:

>to Reproduce the Work, to incorporate the Work into one or more Collections, and to Reproduce the Work as incorporated in the Collections; and,
>to Distribute and Publicly Perform the Work including as incorporated in Collections.
>The above rights may be exercised in all media and formats whether now known or hereafter devised. The above rights include the right to make such modifications as are technically necessary to exercise the rights in other media and formats, but otherwise you have no rights to make Adaptations. Subject to 8(f), all rights not expressly granted by Licensor are hereby reserved, including but not limited to the rights set forth in Section 4(d).

**Comment by Siilwyn** [comment]
This is an interesting discussion since the book is also open source. The book on gitbook is free and it seems like it can not be purchased.
