### ISSUE TITLE
Lexical scope created by catch()

### ISSUE THREAD

**Issue by bl4de** [getify/You-Dont-Know-JS#528]
This is just some of my thoughts, please delete this issue if it's not appropriate :)

I was thinking about try...catch:

> It's a very little known fact that JavaScript in ES3 specified the variable declaration in the catch clause of a try/catch to be block-scoped to the catch block.

(https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch3.md#trycatch)

catch() looks to me as regular, named function call here (apart of that I know it's the part of try..catch statement). We can pass argument(s) to it as in your example.
Even when we take a quick look at ECMA spec - catch() seems to me like function call (or sort-of).
http://www.ecma-international.org/ecma-262/6.0/#sec-try-statement

Is it scope created inside catch() some 'natural' here?

I am wondering, how it's implemented in JavaScript engines.

**Comment by getify** [comment]
1. I do not know how it's implemented in the engines. I would imagine it's similar to how they're now enabling `let` / `const` to create block-scoped declarations in `{ .. }` blocks.
2. I don't think it's natural or appropriate to think about `catch(..)` as a function. Here's why:
   - you can't put a `var` inside the `catch` block and have it scoped to the `catch`; instead it hoists to the function
   - if you call `return` from inside the `catch`, that's a `return` from whatever the surrounding function is
   - the outer function's `this` and `arguments` are still in effect -- in this way, you could sorta think of `catch` as an ES6 arrow function. but again, it's not a function!

**Comment by bl4de** [comment]
Thank you for your answer, you're right, I did not think about in this way. I've missed these obvious differences between catch(...) and regular function.

Wouldn't be much less confusing here, if the syntax of try..catch looks for example something like this?:

```javascript
try {

} catch err {    // we don't use brackets here to point that catch is for sure not a function call :)
     console.log(err);
}
```

I know this is some kind of syntax detail that, for sure, 99,999% of JS devs don't even think about.

**Comment by getify** [comment]
Shrugs. I dunno why the chose the grammar they way they did. But probably because most other `try..catch`es in other languages uses the `( )` too.
