### ISSUE TITLE
"scope & closures": Block Scoping Revisited - clarification of scope created by let (question)

### ISSUE THREAD

**Issue by bl4de** [getify/You-Dont-Know-JS#529]
Hi,

I've got a question about scope created by _let_.

We've got an example (similar as in YDKJS):

```javascript
"use strict";

for (let a = 1; a < 10; a++) {
    setTimeout( function() {
        console.log(a);
    }, 0);
}
```

Works perfect, closure in setTimeout() has access to valid _a_ in each iteration as is defined inside scope created by _let_.

But let's do something like this:

```javascript
"use strict";
function foo() {
    {
        let b = 10;
        for (let a = 1; a < 10; a++) 
        {
            console.log("in loop: ", a);
            fn();
        }
    }
}
    
foo();

console.log(a);  // undefined
console.log(b);  // Uncaught ReferenceError: b is not defined

function fn() {
    console.log("in fn(): ", a);
}
```

I define fn() *outside* of scope created by _let_ (in _for_ statement). Also there's one more block scope created by outside brackets. _a_ should not be visible, right? And everything is enclosed in foo() which is created yet another scope.

And the result is:
> in loop:  1
closure2.js:20 in fn():  10
closure2.js:7 in loop:  2
closure2.js:20 in fn():  10
closure2.js:7 in loop:  3
closure2.js:20 in fn():  10
closure2.js:7 in loop:  4
closure2.js:20 in fn():  10
closure2.js:7 in loop:  5
closure2.js:20 in fn():  10
closure2.js:7 in loop:  6
closure2.js:20 in fn():  10
closure2.js:7 in loop:  7
closure2.js:20 in fn():  10
closure2.js:7 in loop:  8
closure2.js:20 in fn():  10
closure2.js:7 in loop:  9
closure2.js:20 in fn():  10
closure2.js:15 10
closure2.js:16 Uncaught ReferenceError: b is not defined

_fn()_ has an access to _a_ as is called inside the scope, where _a_ is defined (right?). But how _a_ might be accessible outside of all scopes which surround it? (this line with console.log(a), where there's _undefined_ - as I was expecting Reference Error, the same as for _b_)

And why _a_ in each iteration, printed by _fn()_, behaves as if _fn()_ was declared as closure, similar as in your example from "Loops + Closure" chapter?

Is there's something I didn't I understand from scopes?

**Comment by getify** [comment]
IIUC the only explanation for this is that in whatever environment you're trying this in, there's already an `a` in the outer scope, diff from the `a` in the loop. Or whatever implementation you're running in has a massive bug. `a` most definitely should not be accessible in that scope.

**Comment by bl4de** [comment]
This is totally insane, but you're correct as usual.

I've tried code above in my Chrome Dev Tools (created some small snippet for this). Yeah, and there was an _a_ in Chrome Dev Tools console defined an hour or two earlier today :/
I am sorry for this issue, I should check this before I've created one.

**Comment by getify** [comment]
No worries. :) Happens all the time, actually.
