### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by cez-aug** [getify/You-Dont-Know-JS#535]
Hey Kyle, 

I'm interested in translating the series to Brazilian Portuguese. I think you did an incredible job with the books and way more people could be benefit from your work (Brazil hosts the world's biggest JS conference). 

However, since the books are published under the helm of O'Reilly, is there any implications of doing it? Please, I have no commercial intent to redistribute, sell, share-alike or anything, it's just for the sake of the knowledge.

Thank you!

**Comment by Coladela** [comment]
Cezar, I could help you when it's necessary....

**Comment by getify** [comment]
Please see this:

https://github.com/getify/You-Dont-Know-JS/issues/9#issuecomment-37836191

**Comment by Coladela** [comment]
OK Kyle, I think I got it, the concept is clear for me....maybe would be better help people in Brazil to improve their english, when it´s necessary...so, tk´s for your amazing job here!

**Comment by cez-aug** [comment]
Thank you Kyle, I'll get in touch with you.
@Coladela thanks, it would be great.

**Comment by joelwallis** [comment]
Hi @cez-aug! Nice initiative! Did you proceed with the task of translating the book? I'm interesting - and willing in working on the translation of YDKJ to pt-BR. :-)

**Comment by cez-aug** [comment]
Hi @joelwallis. Yes, I'm currently making the translation and would be great if you could help me on it! You can check it here: https://github.com/cez-aug/You-Dont-Know-JS

Let me know when you're ready so I could include you in the contributor list! :muscle:

**Comment by joelwallis** [comment]
@cez-aug awesome! I just forked the repo. I'll take some time to organize a weekly routine to use on this project. This translation is a great contribution to the Brazilian JS community! \o/

**Comment by joelwallis** [comment]
Hey @cez-aug, can you please enable the issue tracker of your repo? I tried to start working on the pt-BR translation last week but I was unable to setup an organization logic for our work. Also, we'll need to discuss things related to content and/or metacontent (like documentation for accepting contribution in `CONTRIBUTING.md`, moving credits to `CONTRIBUTORS.md`, how/why/when do things, etc.).

Also, I don't have any sort of contact information about you. What's your Twitter @?

**Comment by cez-aug** [comment]
Hi @joelwallis, yes, it's kind of weird now. Let's make it better: @cez_aug. Thanks!

**Comment by gabsprates** [comment]
great! :+1:
