### ISSUE TITLE
Port it to gitbook

### ISSUE THREAD

**Issue by kirtangajjar** [getify/You-Dont-Know-JS#537]
I was really impressed by the content of this books. 

Why not port this to gitbooks?

It will be easier to read and easier for author to publish!

Here's how a gitbook looks like - https://samypesse.gitbooks.io/how-to-create-an-operating-system/content/

**Comment by getify** [comment]
I appreciate the suggestion. It's already been discussed before, but it's not quite appropriate for this project.
