### ISSUE TITLE
"scope & closures": ch3,'const' example seems wrong in chrome

### ISSUE THREAD

**Issue by DophinL** [getify/You-Dont-Know-JS#540]
```javascript
var foo = true;

if (foo) {
    var a = 2;
    const b = 3; // block-scoped to the containing `if`

    a = 3; // just fine!
    b = 4; // error!
}

console.log( a ); // 3
console.log( b ); // ReferenceError!
```

This is the source code in ch3 for const above.
But I ran it in chrome and output different result as '3 3' instead of '3 ReferenceError'.

**Comment by bl4de** [comment]
You have to add "use strict", because for now Chrome does not handle block scope without strict mode :)
http://caniuse.com/#search=const

**Comment by getify** [comment]
Yep, @bl4de is correct! :)

**Comment by DophinL** [comment]
Thank u so much:)
