### ISSUE TITLE
types & grammar / Coercion

### ISSUE THREAD

**Issue by sAbakumoff** [getify/You-Dont-Know-JS#541]
> Built-in primitive values have natural stringification: null becomes "null", undefined becomes "undefined" and true becomes "true"

That's not possible to explicitly invoke toString function for null and undefined values, however, the code that implies stringification
```javascript
console.log(null + ''); // 'null'
```
works just fine. I guess it's somehow handled by JS engine.
It might be worth to mention in "ToString" abstract operation description

**Comment by getify** [comment]
I think `ToString` is sufficiently covered in other parts of the chapter.
