### ISSUE TITLE
"this & object prototypes": ch2 explain 'this'-style code

### ISSUE THREAD

**Issue by gszabo** [getify/You-Dont-Know-JS#572]
At the end of chapter 2 you give the advice to:
> Embrace this-style mechanisms completely, including using `bind(..)` where necessary, and try to avoid `self = this` and arrow-function "lexical this" tricks.

Can you explain what you mean by `this`-style code? Let's assume I'd like to follow this advice and embrace `this` (rather than escape with self and arrow). Could you give a real world example that turns the 'difficulties'/characteristics of `this` (described in the whole chapter) into some benefit and greatness?

Maybe the cause is that I come from a class-based background, but given the style of code I write, it seems to me that if want to use `this` instead of self or arrow, my code is going to need a lot of `obj.fn.bind(obj)` statements, and that doesn't seem to be healthy either. I'd write roughly the same number of `bind` statements than I'd write 'self'-s (because that's when I lose the implicit binding), and I'd rarely if ever use `call` or `apply`. 

I feel the need for some kind of example here because the examples in the chapter only demonstrate how the context is bound to a function with little code, but the bigger picture where this behaviour is an advantage is missing.

**Comment by getify** [comment]
> the bigger picture where this behaviour is an advantage is missing.

The rest of the book explains why you want to use the `this` keyword... which is to take advantage of the `[[Prototype]]` chain.

"`this`-style code" broadly just refers to any usage of the `this` keyword in functions, for any of a variety of purposes. It can be simple stuff like:

```js
var obj = {
   id: 42
   foo: function(){ 
      console.log( this.id );
   }
};

obj.foo();  // 42
```

Or it can be more complicated stuff like classes/OO emulation (ch4), or it can be more straightforward like OLOO (ch6). For example:

```js
var util = {
   doubleVal: function(){
      this.val *= 2;
      return this.val;
   }
};

var thing1 = Object.create(util),
   thing2 = Object.create(util),
   thing3 = Object.create(util);

thing1.val = 21;
thing2.val = 100;
thing3.val = 57;

thing1.doubleVal();  // 42
thing2.doubleVal();  // 200
thing3.doubleVal();  // 114
```

In that snippet, `thing1`, `thing2`, and `thing3` all delegate up their `[[Prototype]]` chains, respectively, to the `util` object, to use its `doubleVal(..)` function, which is `this`-aware. The implicit binding rule at those 3 call sites makes sure `doubleVal(..)` is called in the context of each of those 3 objects. That's using one function in multiple contexts based on `this`-binding rules.

**Comment by gszabo** [comment]
Thank you for the answer. It is true that I haven't read the other chapters
yet.
