### ISSUE TITLE
ES6 & Beyond Chapter 4: Async Flow Control - Promise.race example

### ISSUE THREAD

**Issue by guyonroche** [getify/You-Dont-Know-JS#576]
I noticed the Promise.race example is incorrect: since race completes on the first resolution, you will see the 42 value, not the rejection...

```javascript
Promise.race( [p2,p1,v3,p4] )
.then(
    function fulfilled(val){
        console.log(val);                     // 42
    },
    function rejected(reason){
        // never gets here
    }
);
```

**Comment by getify** [comment]
The value `43` is what would print. Good "catch", thanks!

**Comment by getify** [comment]
I changed the example so it shows the rejection as intended.
