### ISSUE TITLE
Async & Performance - Ch5 - one to one relationship?

### ISSUE THREAD

**Issue by xDaizu** [getify/You-Dont-Know-JS#581]
> Here's how to listen for events (actually, the fixed "message" event):
>
>w1.addEventListener( "message", function(evt){
>    // evt.data
>} );
>And you can send the "message" event to the Worker:
>
>w1.postMessage( "something cool to say" );
>Inside the Worker, the messaging is totally symmetrical:
>
>// "mycoolworker.js"
>
>addEventListener( "message", function(evt){
>    // evt.data
>} );
>
>postMessage( "a really cool reply" );
>Notice that a dedicated Worker is in a **one-to-one relationship** with the program that created it. That >is, the "message" event doesn't need any disambiguation here, because we're sure that it could >only have come from this one-to-one relationship -- either it came from the Worker or the main >page.

Would'nt be more accurate to say the worker is on a **many-to-one relationship** with the program? That's why it's unambiguous on the worker's side: 
>postMessage( "a really cool reply" );

but need disambiguation in the program's side:
>w1.postMessage( "something cool to say" );

**Comment by getify** [comment]
The worker itself is one-to-one, because a worker can only be in one JS program at a time. If two JS programs tried to open the dedicated worker, you'd get two separate instances. That's the main difference from shared workers.

More broadly speaking, there's a "many-to-one" relationship between a JS program and all its web workers. But for a single worker, it's definitely one-to-one.

**Comment by xDaizu** [comment]
*"But for a single worker, it's definitely one-to-one."* Sorry to object but that sentence doesn't make any sense to me, neither does *"The worker itself is one-to-one, because a worker can only be in one JS program at a time."* because, if I understand correctly your argument, the same could be said for pretty much any many-to-one relationship. 

Please, correct me if I am wrong:

One-to-one: "Person" and "ID card" Every person only has one card, every card only corresponds to one person.
Many-to-one: "Person" and "phone number" (I know, loose example): One person has many phone numbers, a phone number can only be had by one person.
Many-to-many: "Person" and "address": One person may have many addresses that can themselves be had by other persons.

When you say 
*"The worker itself is one-to-one, because a worker can only be in one JS program at a time. If two JS programs tried to open the dedicated worker, you'd get two separate instances."* 
it sounds to me like it falls in the Person-PhoneNumber situation, because if the workers could be shared, we would have a Person-Address (many-to-many) situation, wouldn't we?

**Comment by getify** [comment]
What I was trying to get across in the earlier answer is that what kind of relationship you have is not absolute but depending on perspective and on abstraction.

In a ["one to one" relationship](http://www.databaseprimer.com/pages/relationship_1to1/) between X and Y, there's only one X for each Y, and conversely only one Y for each X.

So, to discuss dedicated web workers:

1. there is a **one-to-one** relationship between the **web worker instance** and a **page instance**.
   - If **one page instance** opens the same web worker file two or more times, you get **two separate worker instances** of the one worker file. So I'd say you'd have two separate **one-to-one** relationships.
   - If **two separate page instances** try to open the same web worker file, you'll get **two separate worker instances**, meaning that you'll again have two separate **one-to-one** relationships.
2. If **one page instance** has two or more instances of a different web worker files in it, that's a **one-to-many** relationship between the **one page instance** and **web worker files** (not specific instances).
   - If **two separate page instances** open the same web worker file, you **don't** get a shared worker instance (unless it's a shared -- not dedicated -- worker!), so you don't have a **many-to-one** relationship. However, **shared worker instances** absolutely have a **many-to-one** relationship with their hosting page instances -- by definition.
   - If **multiple page instances** open the same sets of multiple web worker files as instances, you'd have a **many-to-many** relationship between the **worker files** and the **page instances**. Or, you could think of that as many **one-to-one** relationships between **worker instances** and **page instances**.

To relate this all back to your Person-Card, Person-PhoneNum, Person-Address:

1. page instances and worker instances are: Person-Card
2. page instances and worker files are: Person-PhoneNum
3. pages and worker instances are: Person-Address

Does that help at all?

**Comment by xDaizu** [comment]
Barely. I mean, yes, I understand everything you said (even better tan before, granted :smile_cat:   ) but I'm sorry, maybe I'm thick, but I still don't get this part:

>If one page instance opens the same web worker file two or more times, you get two separate worker instances of the one worker file. So I'd say you'd have two separate one-to-one relationships.

I wouldn't say that. If the same page instance opens two worker instances that's a one-to-many relationship, isn't it?

I mean, maybe I'm not understanding it correctly (I'm new to the worker concepts, that's why I'm struggling to map it to my mind), but... let's say: page A, instance 32 (A-32) opens web worker Z twice.

So we would have:
**A-32** <-> **Z-1**
**A-32** <-> **Z-2**

But since it's the SAME page instance, A-32 (instead of an A-33) it would be one-to-many, wouldn't it? Because there's not  *only one X for each Y*
