### ISSUE TITLE
Constant is not a variable

### ISSUE THREAD

**Issue by DmitryAuine** [getify/You-Dont-Know-JS#582]
https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch2.md#const-declarations

In the const explanation section of the chapter 2, we have some text about constants. And in the second listing (example of code) we have declaration of the constant <code>a</code>.
Next to it there is explanation of code - "The a variable", which i think is wrong because variable !== constant.

**Comment by KrisSiegel** [comment]
Constants are simply immutable variables. If you take a look at the ECMAScript 6 specification (section 13.3.1) the language there also refers to them as variables. If further clarity is necessary (which, in my opinion, it isn't) then simply add "constant" to the existing phrase.

**Comment by oliverbenns** [comment]
Constants are variables, it's simply another way to define it.

@KrisSiegel isn't correct in saying they are immutable, as you can still push to arrays and add new object key/vals that are originally defined with `const`.

**Comment by getify** [comment]
I see no reason for change here. Thanks for the feedback.

**Comment by KrisSiegel** [comment]
@oliverbenns pushing to a const array or modifying a const object doesn't change the original identifier (which cannot be reassigned). The identifier is immutable when declared with const. Put another way: the value of a reference is not immutable but the reference itself is.

**Comment by oliverbenns** [comment]
@KrisSiegel Gotcha! Thanks :)
