### ISSUE TITLE
delegation direction reverse?

### ISSUE THREAD

**Issue by wewea** [getify/You-Dont-Know-JS#585]
In <this & Object prototype>  ch6 ###De-class-ified
it say:
> With behavior delegation, AuthController and LoginController are just objects, horizontal peers of each other, and are not arranged or related as parents and children in class-orientation. We somewhat arbitrarily chose to have AuthController delegate to LoginController -- it would have been just as valid for the delegation to go the reverse direction.

1. why `AuthController` and `LoginController` is horizontal peer? i can't understand, isn't they in a chain, just follow one direction.  

2. why they can delegate in reverse direction? i see `AuthController` has call `this.validateEntry` in its   `checkAuth` property.  if they reverse, how could it find the property in the chain?

here is my test code, it can't find foo if they delegate reverse
```javascript
var Foo = {
  foo() {
    console.log('here is foo');
  }
};

var Bar = {
  bar() {
    this.foo();
  }
}

// Object.setPrototypeOf(Bar, Foo);
Object.setPrototypeOf(Foo, Bar);
Bar.bar();
```

**Comment by getify** [comment]
> it would have been just as valid for the delegation to go the reverse direction.

That statement does not imply that the reversal wouldn't require extra changes to the design of the objects -- it would. but you could design their behavior differently to suit having the delegation go in the opposite direction.
