### ISSUE TITLE
Results Are Same But The Book Says They Are Different

### ISSUE THREAD

**Issue by theleancoder** [getify/You-Dont-Know-JS#600]
Code block 1:
```
a = 2;

var a;

console.log( a );
```
Code block 2:
```
console.log( a );

var a = 2;
```
When executing both the code blocks in chrome dev console, the output is same for both the block i.e., 2 while the book says that output of fisrt one is 2 and that of second one is ```undefined```.

**Comment by huei90** [comment]
You should separately test both code blocks.

**Comment by theleancoder** [comment]
I did the same.

**Comment by huei90** [comment]
The second block should return `undefined`.
You can share your screenshot of your code.

**Comment by theleancoder** [comment]
I've already shared.

**Comment by huei90** [comment]
![screen shot 2015-12-07 at 10 51 31 am](https://cloud.githubusercontent.com/assets/2560096/11617924/ca164f18-9ccf-11e5-940c-2b973a14476c.png)

I have the different result from the console.

What I have done?
After the first code block, i refresh the page, and try the second one.

**Comment by theleancoder** [comment]
Gotcha. Thanks!

**Comment by huei90** [comment]
:+1:

**Comment by getify** [comment]
Yes, you have to refresh your environment between each test.
