### ISSUE TITLE
"This & Object Prototypes" Chapter 5, "Constructor or Call?": Unexpected results in testing

### ISSUE THREAD

**Issue by Kyune** [getify/You-Dont-Know-JS#609]
I recently started reading through the series of books in order to learn Javascript.  I come from a primarily OOP background (Java, C#, etc), and while re-reading the section of the material referenced in the title of this issue, I thought to test out the behavior of the "function-object" returned by a call of this nature.

```javascript

function itemA() {
    console.log(itemA.id); // 2
}

itemA.prototype.id = "1";
itemA.id="2";

var itemB = Object.create(itemA);
var itemC = new itemA();
var itemD = itemA();

itemA.id // 2
itemB.id // 2
itemC.id // 1
itemA.isPrototypeOf(itemB); // true
itemA.isPrototypeOf(itemC); // false
itemA.prototype.isPrototypeOf(itemB); // false
itemA.prototype.isPrototypeOf(itemC); // true

itemA.prototype // itemA {id: "1"} (Should report as Object due to previously mentioned bug, right?)
itemA.__proto__ // function (){}
itemB.prototype // itemA {id: "1"}
itemB.__proto__ // function itemA(){...}
itemC.prototype // undefined
itemC.__proto__ // itemA {id: "1"}
itemC.__proto__.prototype // undefined
itemC.__proto__.__proto__ // Object {}

itemD // undefined

```

Instinctively I was expecting that objects B and C would be functionally identical, where prototype links to A would resolve the "id" property.  The main difference I expected to see was just that B would be created without the overhead of the function call to ItemA().

I can reason out what's going on with A,B, and D, but what's going on with C? It has an undefined "prototype" property, but through __proto__ it is linked to the prototype object of itemA.  There is no reference to the function aspect of A, either.  My best guess is that the behavior of the new operator in conjunction with a function that doesn't return a value is as undefined as the straight function call to itemA(), and what I am seeing is simply Chrome's interpretation of the issue, though it seems somehow incomplete.

I expect the appropriate response to this dilemma is to not use objects that weren't explicitly returned from function calls, but perhaps there is some way the results of this experiment could be incorporated into the material, or at the very least a concrete explanation for what's happening here?

**Comment by getify** [comment]
The problem in your example is that you keep trying to reason about `itemA` as if it's an object in the prototype chain... it's not -- it's a function. `itemA.prototype` is the object in the prototype chain that you care about.

So...

```js
var itemB = Object.create(itemA.prototype);
var itemC = new itemA();

// itemB and itemC will "behave identically" now
```

**Comment by getify** [comment]
Closing for now. Feel free to respond if there's remaining questions on this topic.
