### ISSUE TITLE
JS: Scope & Closures - Chapter 3: Function vs. Block Scope - No difference in syntax ( IIFE function style)

### ISSUE THREAD

**Issue by Jiantastic** [getify/You-Dont-Know-JS#610]
Hello,

I have been reading chapter 3 of Scope & Closures and noticed a misordering of parentheses comparing IIFE function styles  => https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch3.md#invoking-function-expressions-immediately

Comparison between the 2 styles

Style 1

```js
var a = 2;

(function foo(){

	var a = 3;
	console.log( a ); // 3

})();  // parentheses style 1

console.log( a ); // 2
```

and Style 2

```js
var a = 2;

(function IIFE(){

	var a = 3;
	console.log( a ); // 3

})();  // parentheses style same as above? Should probably be }());

console.log( a ); // 2
```

Thanks! Appreciate the work you've done.

**Comment by getify** [comment]
I mentioned in the paragraph text immediately following that snippet that there's a stylistic difference, but I don't repeat a full code snippet with the `}())` vs `})()` ending.

**Comment by Jiantastic** [comment]
Alright sure. Just found it fairly confusing when I was comparing the two code snippets. Thanks for the reply.
