### ISSUE TITLE
Create a GitHub Pahge for reading this repo.

### ISSUE THREAD

**Issue by gautamkrishnar** [getify/You-Dont-Know-JS#611]
Github page that felicitate html for interface reading this repo. 
If you can create the gh-pages branch then i can help you on creating the site

**Comment by getify** [comment]
I like the GH repo the way it is. Each chapter is its own markdown file, which makes for easy reading. The Chapter List is clickable for each chapter, such as:

https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/README.md

**Comment by gautamkrishnar** [comment]
Oh ok then. Thanks.. :)
