### ISSUE TITLE
Why this is false

### ISSUE THREAD

**Issue by elkebirmed** [getify/You-Dont-Know-JS#612]
```javascript
if (true == []) { // true && [] works
  console.log('Yup!');
} else {
  console.log('Nop!');
}
```

**Comment by getify** [comment]
the steps in the spec algorithm for == in your example will be:

true == []
true == ""    (ToPrimitive, toString) 
"true"  == ""

**Comment by elkebirmed** [comment]
Wow! dirty coercion...
Thank you for explaining @getify

**Comment by huei90** [comment]
Then why

```
if ([]) {
  console.log('Yup!');
} else {
  console.log('Nop!');
}
```

is `Yup!`?

**Comment by getify** [comment]
because in that case, there's no `==` algorithm involved, just the `if (..)` statement, which does a `ToBoolean` coercion... since `[]` is not on the falsy list, it's truthy, so it coerces to `true`.

**Comment by huei90** [comment]
Thank you @getify
