### ISSUE TITLE
This & Object Prototypes: Chp 5 - Objects: Typo

### ISSUE THREAD

**Issue by TimoorKurdi** [getify/You-Dont-Know-JS#615]
Hello! First of all, thank you for the series of books, I'm a junior dev trying to enhance my JS knowledge and these books have been wonderful!

In **Chp 5** under **Setting & Shadowing Properties** I noticed what may be a typo?

1. If a normal data accessor (see Chapter 3) property named foo is found anywhere higher on the [[Prototype]] chain, and it's not marked as read-only **(writable:false)** then a new property called foo is added directly to myObject, resulting in a shadowed property.

Did you mean to say **(writable:true)**, as that would imply it isn't read-only? Or am I confused and not understanding this correctly.

P.S. - I'm new at open source contributions so please pardon any incorrect attempts to contribute.

**Comment by getify** [comment]
Please see: https://github.com/getify/You-Dont-Know-JS/pull/466

> I'm new at open source contributions so please pardon any incorrect attempts to contribute.

No worries, thanks for caring enough to contribute! :)
