### ISSUE TITLE
missing 'return' in hard bindings section?

### ISSUE THREAD

**Issue by dare05** [getify/You-Dont-Know-JS#617]
Here:
https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch2.md

You have:

var bar = function() {
    foo.call( obj );
};

Should you add "return" in the body of the statement?

**Comment by getify** [comment]
Since we don't care about the return value, it's not necessary. The general `bind(..)` utility pattern would indeed use a `return`, but it would also use `apply(..)` to pass along any arguments sent to `bar(..)` into `foo(..)`.
