### ISSUE TITLE
this & prototypes, chapter 5 #Setting & Shadowing Properties

### ISSUE THREAD

**Issue by xiekw2010** [getify/You-Dont-Know-JS#618]
1. If a normal data accessor (see Chapter 3) property named `foo` is found anywhere higher on the `[[Prototype]]` chain, **and it's not marked as read-only (`writable:false`)** then a new property called `foo` is added directly to `myObject`, resulting in a **shadowed property**.

**and it's not marked as read-only (`writable:false`)** => writable:true

**Comment by getify** [comment]
Duplicate. Please see: https://github.com/getify/You-Dont-Know-JS/pull/466

**Comment by getify** [comment]
...context: https://github.com/getify/You-Dont-Know-JS/pull/186
