### ISSUE TITLE
Double negation - is it safe?

### ISSUE THREAD

**Issue by m-camilleri** [getify/You-Dont-Know-JS#620]
Just how safe is it to use !! to coerce a value to a Boolean? Does the ES standard guarantee that an optimizing compiler won't optimize !! away?

**Comment by getify** [comment]
By "optimizing compiler", do you mean a JS engine? I am quite certain that they all know that the coercion of `!` makes it not isomorphic, so the `!!` isn't a no-op. That much is definitely guaranteed by the spec. So it's totally safe in mainstream JS engines.

But that's not to say that some other sub-par "optimizing compiler" tool might not make the mistake of missing the coercion detail and incorrectly remove it.

**Comment by getify** [comment]
Closing for now, reopen if more clarification needed.
