### ISSUE TITLE
"this & Object Prototypes" chapter 5:Prototypes [[Prototype]] section

### ISSUE THREAD

**Issue by MehdiRaash** [getify/You-Dont-Know-JS#621]
As I was figuring out about how [[Get]] in **myObject.a** works(=process continues until chain ends), everything was allright!
   
    var anotherObject = {
        a: 2
    };

    // create an object linked to `anotherObject`
    var myObject = Object.create( anotherObject );

    myObject.a; // 2

but I came up with a question which is "what will happen if no prototype was set, How does getter work in this situation":

     var myObject = Object.create(null);
     myObject.a = 7;
     myObject.toString(); //Uncaught TypeError: myObject.toString is not a function

so look-up fails cause there's no link, beside that no [[Get]] should be found.

     myObject.a; // 7

but this works fine... how?! : 

but I feel there should be a notice for that in this section.

**Comment by MehdiRaash** [comment]
Please somebody help me to the question!

**Comment by donvadicastro** [comment]
By default, when you are using classic object creation var a = {}, you are creating new object which is inherited by base Object object. It is the same as to write:
```
Object.create(Object.prototype)
```  

So using this syntax you are free to use base Object methods and properties, like .toString(), from your inherited object.

Using prototype-less object creation (Object.create(null)) - you are creating object which is not inherited from base Object class so you can't access Object specific methods, like .toString(), but you are free still to use getters and setters, which aligns to language specifications, so are accessible from any valid object.

**Comment by MehdiRaash** [comment]
Thanks.

**Comment by getify** [comment]
Just to be clear... `[[Get]]` and `[[Put]]` are inherent (not inherited) to every object, so the lack of `[[Prototype]]` linkage up to `Object.prototype` doesn't prevent an object from having properties added to and read from.

**Comment by MehdiRaash** [comment]
Thanks for the clarification, hence ~~[[Get]]~~ and ~~[[Put]]~~ are inherent to every object.

**Comment by MehdiRaash** [comment]
Thanks for the clarification, so only `[[Get]]` and `[[Put]]` are inherent to every object.

**Comment by getify** [comment]
not **only**, no. See [section 9.1](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots) of the ES6 spec for more details.

**Comment by MehdiRaash** [comment]
Thanks.
