### ISSUE TITLE
json-safe about deep copy

### ISSUE THREAD

**Issue by SimplyY** [getify/You-Dont-Know-JS#624]
Json.prase(Json.stringify(someobj))  in your book.It is very useful

in book  https://github.com/getify/You-Dont-Know-JS/blob/master/this%20&%20object%20prototypes/ch3.md#duplicating-objects
> var newObj = JSON.parse( JSON.stringify( someObj ) );
Of course, that requires you to ensure your object is JSON safe. For some situations, that's trivial. For others, it's insufficient.

but, read it.I still dont know when I can use it.

after I test,I find when object has function, the object is not safe-json.

so,is It only way for unsafe json?

If it is,that, for deep copy, when object is unsafe-json, after  var newObj = JSON.parse( JSON.stringify( someObj ) );,   and  then do function copy

**Comment by getify** [comment]
"JSON unsafe" is an object containing any value type that is not representable in standard JSON. For example:

* function
* regex
* typed object (like `String`, `Number`)
* reference (circular reference, for example)

**Comment by MehdiRaash** [comment]
Could we check an object for being safe or unsafe for sure?
is it doable 100% programmatically?

**Comment by SimplyY** [comment]
@getify  thanks very much。

@MehdiRaash  maybe, need write function. But I think js will be es6,es2016,es2017,,so, new grammer will destory old function

**Comment by getify** [comment]
@MehdiRaash writing such a function would require traversing the entire object and inspecting every single property, keeping track of circular refs, etc. That's exactly what `JSON.stringify(..)` already does, so there'd be no good reason to re-implement all that logic separately.

The better (brute force) way is:

```js
var newObj = (function(){
   try { return JSON.parse(JSON.stringify(obj)); }
   catch (err) { return obj; }
})();
```

IOW, you just try to clone it, but wrap in a `try..catch` in case it fails, and then pick some other option if you detect that it wasn't JSON safe.

**Comment by MehdiRaash** [comment]
Thanks.
