### ISSUE TITLE
Ch 4 Functions First is a little confusing

### ISSUE THREAD

**Issue by davidbkemp** [getify/You-Dont-Know-JS#63]
You state that functions are hoisted before variables, and yet these functions can refer to variables defined in the same scope. Is it simply the case that the variables will be defined by the time the function is actually called, or is it that all the variable and function names are hoisted together, then the functions defined, and then the remainder of the code executed?

**Comment by muradsofiyev** [comment]
```
function foo() {
    console.log( foo );
}
var foo;


foo()
```
But what is happened in there? If  functions are hoisted first and then variables we can't call foo like function but we can
