### ISSUE TITLE
Have you thought of using GitBook?

### ISSUE THREAD

**Issue by MattMcFarland** [getify/You-Dont-Know-JS#635]
I think GitBook would be perfect for this project. https://www.gitbook.com it easily translates your md files and allows for easy creation of ebooks, pdfs, static sites, also makes it easy to sell the book as well.

**Comment by getify** [comment]
Yes, please see: https://github.com/getify/You-Dont-Know-JS/issues?q=is%3Aissue+gitbook+is%3Aclosed

**Comment by getify** [comment]
FTR: gitbook approached me a long time ago. I considered it, but they didn't offer the ability to only have online reading without PDF export. It's the ebook export that's unacceptable, which is what keeps me from using gitbook.

**Comment by MattMcFarland** [comment]
Ok thanks for the quick response, sorry to bring up something already brought up.  I'll make sure to search closed issues next time.

**Comment by getify** [comment]
No worries. Cheers. :)
