### ISSUE TITLE
es6 export keyword correction

### ISSUE THREAD

**Issue by craescu** [getify/You-Dont-Know-JS#636]
Hi,

On chapter [Scope & Closures / Chapter 5: Scope Closure](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch5.md) at the end you have few code examples regarding es6 modules (bar.js, foo.js):

**bar.js**
```javascript
function hello(who) {
    return "Let me introduce: " + who;
}

export hello; // compile error 
```

Accordingly to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export), `export hello;` should be `export { hello };` or `export default hello;`
**bar.js**
```javascript
function hello(who) {
    return "Let me introduce: " + who;
}

export default hello; 
```

Thank you for the book!

**Comment by getify** [comment]
Yes, this is a planned update for second edition. Thanks!
