### ISSUE TITLE
this & object prototypes - ch4 - DNA metaphor

### ISSUE THREAD

**Issue by edoardo849** [getify/You-Dont-Know-JS#639]
In chapter 4, sub-chapter "Class Inheritance":

> It's important to remember that we're talking about parent and child classes, which aren't physical things. This is where the metaphor of parent and child gets a little confusing, because we actually should say that a parent class is like a parent's DNA and a child class is like a child's DNA. We have to make (aka "instantiate") a person out of each set of DNA to actually have a physical person to have a conversation with.

I find this metaphor confusing because while saying "parent" and "child" you are implying a relationship with a certain order (1. parent -> 2. child) and so it seems to emphasize the error that the child "Child" Class "inherits" from the parent "Parent" Class. 

If this is the intent, the implication is that a "new" human could, theoretically, build new methods (fly, breathe under-water): if you use the DNA metaphor, then wouldn't be better to say that both (human-child and human-parent) have a similar DNA of class "human" and that both inherits from the class "living being" (or animal...). In this way the generalization is "human-DNA" and "human-parent" or "human-child" are just different "instantiations".

Also it could be highlighted the role of the constructor by saying that in order to instantiate a new class of type "human", the constructor must include at least 2 arguments, both of class "human" but of opposite gender.

P.s: kudos for your books, they are really interesting to say the least

**Comment by getify** [comment]
> so it seems to emphasize the error that the child "Child" Class "inherits" from the parent "Parent" Class.

I do not understand this assertion. I don't think I am claiming that, but I'm not sure even what you're saying?

> Also it could be highlighted the role of the constructor by saying

This seems like stretching the metaphor way too far. I don't think that would add any clarity to the discussion. Metaphors are only useful in so far as they are limited to exactly what's being discussed. Stretching them or taking them too literally is problematic.

**Comment by getify** [comment]
Closing for now, feel free to reopen if more can be clarified.
