### ISSUE TITLE
Scope & Closures - LHS look-ups

### ISSUE THREAD

**Issue by rphuber** [getify/You-Dont-Know-JS#641]
function foo(a) {
    var b = a;
    return a + b;
}

var c = foo( 2 );
Identify all the LHS look-ups (there are 3!).

Why would this not include the function declaration as an LHS?

**Comment by getify** [comment]
Because the function declaration also includes the value (aka, sorta assignment), it's in its own special category in my mind. There really is not left and right, or even source and target.. it's all in one. It's not exactly the same thing as thinking of:

`var foo = function ...`

**Comment by rphuber** [comment]
Thanks!
