### ISSUE TITLE
es6 & beyond: ch4 - are examples from promises + generators equivalent?

### ISSUE THREAD

**Issue by Podlas29** [getify/You-Dont-Know-JS#645]
Hi.
I am reading es6 book and enjoying it very much. I learned a lot, however I have some doubts. Either it is real issue or I have some misconceptions about the topic.

You present two version of code, that gives impression this examples are equivalent: 

```javascript
step1()
.then(
    step2,
    step2Failed
)
.then(
    function step3(msg) {
        return Promise.all( [
            step3a( msg ),
            step3b( msg ),
            step3c( msg )
        ] )
    }
)
.then(step4);
```
```javascript
function *main() {
    var ret = yield step1();

    try {
        ret = yield step2( ret );
    }
    catch (err) {
        ret = yield step2Failed( err );
    }

    // step 3
    ret = yield Promise.all( [
        step3a( ret ),
        step3b( ret ),
        step3c( ret )
    ] );

    yield step4( ret );
}
```
But after some tries and tests I don't believe that to be true. When `step2Failed` function will be called in both examples?

In the first example (promise chain), `step2Failed` will be called if `step1` will be rejected. If `step1` is resolved to some value, `step2` function will start, but no matter what the result of `step2` will be (rejected or resolved), `step2Failed` will never be called.

This is different is second example (generator). Since call to `step1` is not even in try block, when runner throws for this promise an error, it will not be caught in catch block and `step2Failed` will not be called. It will be however called if `step2` promise is rejected. 

Thus in promise chain `step2Failed` is called when `step1` fails, while in generator when `step2` fails. These semantics are different. Having this two examples seeming to be equivalent code will have people confused about either how rejected promises or throwing in generators work.

If I am wrong however, I would be grateful for clarifications.
Best regards.

**Comment by Podlas29** [comment]
Hi. Any reason why there is still no answer here? I don't mean to be pushy, just curious. :)

**Comment by getify** [comment]
You are correct, the snippets were intended to be the same but they were not equivalent. Corrected. Thanks!
