### ISSUE TITLE
"up & going": Chapter 2: introducing the concept of methods

### ISSUE THREAD

**Issue by adactio** [getify/You-Dont-Know-JS#647]
[This is the first time that the word "method" is used in the book](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20&%20going/ch2.md#built-in-type-methods).

It would be good to introduce the concept of what a method is. Properties are introduced in Chapter 1, but methods aren't.

A sentence or two (either here or in the first chapter) would be helpful for someone unfamiliar with the terminology.

Hope that helps.

**Comment by getify** [comment]
Thanks, good suggestion!

**Comment by getify** [comment]
Closing since "Up & Going" was replaced with the new "Get Started" book for second edition, so this issue is no longer applicable.
