### ISSUE TITLE
"this & Object Prototypes" - Chapter 5 (Setting & Shadowing Properties)

### ISSUE THREAD

**Issue by dgwyer** [getify/You-Dont-Know-JS#649]
In the "Setting & Shadowing Properties" section on the three scenarios for the myObject.foo = "bar", should 'writable:false' in scenario 1 be 'writable:true'? In scenario 1 and 2 'writable' is shown to be false in both cases, where it should actually be true in one of them?

I also found the sentence on the first scenario more readable if the first fragment in bold was:

**and it's marked as writable**

rather than

**and it's not marked as read-only**

but that's just my personal impression when reading through it for the first time. :)

**Comment by getify** [comment]
Duplicate. Please see #466 and #186.
