### ISSUE TITLE
"Scope & Closures": Chapter 3: `let`

### ISSUE THREAD

**Issue by czytelny** [getify/You-Dont-Know-JS#654]
Hi, first of all - brillant series, great job & thank you! :) 

I'm wondering about below sentence from Chapter 3: 

> However, declarations made with `let` will not hoist to the entire scope of the block they appear in. Such declarations will not observably "exist" in the block until the declaration statement.
```
{
   console.log( bar ); // ReferenceError!
   let bar = 2;
}
```

I understand that Babel and Traceur are just transpillers nevertheless they behave like actually hoisting for `let` exists. So in above example `console.log` prints undefined, not ReferenceError.
Can you please explain is it issue with transpillers implementation of `let` mechanism ?

**Comment by getify** [comment]
Yeah, transpilers jump through all kinds hoops to do their magic, and part of that involves static analysis of your code and code optimizations based on what it actually does. You can't look at their generated code and derive ES6 semantics, b/c their code cuts whatever corners are not applicable to your code.

In the case of `let` and non-hoisting, if you're using "high compliancy" mode (in their online repl) and [you have code like](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=true&playground=false&code=if%20(true)%20%7B%0A%20%20console.log(a)%3B%0A%20%20let%20a%20%3D%202%3B%0A%7D):

```js
if (true) {
   console.log(a);
   let a = 2;
}
```

...they generate code like this:

```js
"use strict";

var _temporalUndefined = {};

function _temporalAssertDefined(val, name, undef) { if (val === undef) { throw new ReferenceError(name + " is not defined - temporal dead zone"); } return true; }

if (true) {
  var a = _temporalUndefined;

  console.log(_temporalAssertDefined(a, "a", _temporalUndefined) && a);
  a = 2;
}
```

You'll notice that they are emulating the fact that the `a` in `console.log(..)` should produce a reference error by first setting it to a special value they can detect and manually throw an error, but then relying on the fact that if your code is actually written correctly, your `a = 2` would have overwritten that. It's a neat trick.

But the point is, generated code is hard to always analyze to see actual spec semantics. In other cases besides `let`, the generated code will be significantly more divergent from expected semantics based on special cases it can detect in your actual code.

**Comment by getify** [comment]
Closing for now, reopen if more clarification is needed.
