### ISSUE TITLE
'Scopes & Closures': Appendix C - discussion of this using fat arrow

### ISSUE THREAD

**Issue by michael-reeves** [getify/You-Dont-Know-JS#655]
The discussion of the context of `this` when using the ES6 fat arrow is rather confusing, because you switch contexts when discussing how the function is defined.  You switch where the `setTimeout` is being executed.

First example

```
var obj = {
  id: 'awesome',
  cool: function coolFn() {
    console.log(this.id)       // this binds to obj or main depending
                               // on how it is called
  }
}

var id = 'not awesome'
obj.cool()  // awesome
setTimeout( obj.cool, 100 )    // not awesome
setTimeout( obj.cool(), 100 )  // awesome
```

But then use:

```
var obj = {
    count: 0,
    cool: function coolFn() {
        if (this.count < 1) {
            setTimeout( () => { // arrow-function ftw?
                this.count++;
                console.log( "awesome?" );
            }, 100 );
        }
    }
};

obj.cool(); // awesome?
```

to talk about `this` and `=>`.  So the `setTimeout` is being executed from within the scope of the `obj`, instead of outside like the previous example. 

Perhaps the following example could make things a bit clearer?

```
var obj = {
  id: 'awesome',
  cool: () => { console.log( this.id ) }
}
var id = 'not awesome'

obj.cool()           // not awesome
setTimeout( obj.cool, 1000)   // not awesome
setTimeout( obj.cool(), 1000) // not awesome
```

It seems that `this` is always in the scope of the call, instead of the `obj`....unless I'm missing something entirely.  BTW, the last line works in Node, but blows up in Chrome.

Or perhaps you could make the first example more like the second, to illustrate your point.

**Comment by getify** [comment]
I understand the confusion here. Will address with changes in upcoming second edition.

**Comment by getify** [comment]
This is no longer part of the (2nd edition) book, so closing.
