### ISSUE TITLE
types & grammar ch3 > Object Wrapper Gotchas

### ISSUE THREAD

**Issue by MehdiRaash** [getify/You-Dont-Know-JS#658]
> If you want to manually box a primitive value, you can use the
> Object(..) function (no new keyword):
>    var a = "abc";
>    var b = new String( a );
>    var c = Object( a );

It is clear why it's not recommended not using of **Object warpper**, but you do encourage(or suggest) if it's about to use Object Wrapper it's better to use `Object()`function (no new keyword), so What's the reason behind of your encouragement?
Is there any optimised stuff behind it?

**Comment by getify** [comment]
Nope, just mentioning it for completeness sake. I don't recommend it.

**Comment by MehdiRaash** [comment]
Okay, sorry, I misunderstood.

**Comment by getify** [comment]
Cheers!

**Comment by doubleOrt** [comment]
@getify  Why without `new` keyword ? If a constructor call returns an object (like `Object(10)` and `Object("hello")` do), that object will be returned, even if `new` is used with that constructor call.
