### ISSUE TITLE
"this & Object Prototypes" - Seal section - Minor grammatical error

### ISSUE THREAD

**Issue by RachelMinto** [getify/You-Dont-Know-JS#660]
A minor change: "anymore" should be "any more":

> So, not only can you not add **anymore** properties, but you also cannot reconfigure or delete any existing properties (though you can still modify their values).

Revised:
> So, not only can you not add **any more** properties, but you also cannot reconfigure or delete any existing properties (though you can still modify their values).

Thanks for the great series!

**Comment by getify** [comment]
Thanks!
