### ISSUE TITLE
"Scopes & closures": ch5, Future modules - Wrong keyword

### ISSUE THREAD

**Issue by vlindhol** [getify/You-Dont-Know-JS#664]
In the final example in the `Future modules` subheading, the modules are imported with the following code:

```javascript
// import the entire "foo" and "bar" modules
module foo from "foo";
module bar from "bar";
```

Shouldn't it be `import` rather than `module`? I tried googling the `module` keyword and didn't find it in the ES6 grammar definition. Or have I misunderstood something?

**Comment by getify** [comment]
This is more than 2 year old text... `module` was the keyword at the time, but it was subsequently consolidated with `import`. This issue will be addressed in the second edition updates. Thanks! :)
