### ISSUE TITLE
IIFE's namespace?

### ISSUE THREAD

**Issue by subaochen** [getify/You-Dont-Know-JS#671]
Thanks for the great books first!

In "Functions as scopes" of ch3 of  book "Scope & Closures", you say:

Compare the previous two snippets. In the first snippet, the name foo is bound in the enclosing scope, and we call it directly with foo(). In the second snippet, the name foo is not bound in the enclosing scope, but instead is bound only inside of its own function.

But I have tried code below:

`
(foo = function (){
  var a = 10;
  console.log(a);
})();

console.log(foo);

(foo = function (){
  var b = 20;
  console.log(b);
})();

console.log(foo);
`

and console.log(foo) output [Function], is that mean foo is belongs to global scope? I think is the function created scope, but not () pair, is that right?

**Comment by getify** [comment]
`(foo = function...` is not a traditional IIFE form. The named IIFE looks like `(function foo...`. That form will not bind a `foo` identifier into the enclosing scope. Also make sure you're starting with a clean state each time.
