### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [getify/You-Dont-Know-JS#680]
Hi there! This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because may you get some extra support for this hard work, but there is no donate button o something like that.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like You-Dont-know-js. 
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work man!

**Comment by conorcussell** [comment]
You could buy the books, or in the readme there is this section outlining this https://github.com/getify/You-Dont-Know-JS/blob/master/README.md#publishing
