### ISSUE TITLE
May I publish a translated version of these books on other blogs? (Of course it will link back to this repo)

### ISSUE THREAD

**Issue by JoeHetfield** [getify/You-Dont-Know-JS#681]
Just as the issue title. I love this series, btw.

**Comment by saadshahd** [comment]
:+1:

**Comment by getify** [comment]
Please see [these issues](https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=is%3Aissue+translate) for more information.

Specifically, you can translate but under the condition that it needs to only be hosted on github (in your own repo).
