### ISSUE TITLE
Scope & Closures

### ISSUE THREAD

**Issue by itmitica** [getify/You-Dont-Know-JS#682]
Hi. I'd like to submit these for your review. 

* A closure is a function **expression** executed outside its declaration scope. Is this formulation clearer perhaps?

* On hoisting, you specify **functions first**, but you declare **var** before **function** in your demo code. Why?

* On `setTimeout()`, the inline function name is `timer()`, whereas the purpose, behaviour and code is `print()`.

* First declare a function like `timer()` and then use it in `setTimeout()`: the stack is identical, `timer()` is local to the `wait()` function, the positive difference is on debug and on compile.
``` javascript
function wait(message) {

  function timer() { // function print()
    console.log(message);
  } 

  setTimeout(timer, 1000);
}
wait('Hello, closure!')
```

* Nitty Gritty 3rd example is all declarations, no function call, maybe add a `foo()`?
``` javascript
function foo() {
   var a = 2;

    function baz() {
        console.log( a ); // 2
    }

    bar( baz );
}

function bar(fn) {
    fn(); // look ma, I saw closure!
}

foo();
```

**Comment by getify** [comment]
> A closure is a function expression

Nope, it's a function value/reference, regardless of whether it came from an expression or declaration originally.

> On setTimeout(), the inline function name is timer(), whereas the purpose, behaviour and code is print()

Shrugs. I don't think naming it "print" would make the code any clearer. That's bikeshedding at that point.

> First declare a function like 

The illustrations in the book are shortened to keep code snippets manageable. Not every snippet is intended to illustrate all possible best practices around code. Besides, single line functions as inline expressions makes more sense than as declarations. After about 3-4 lines, that's where I start considering it as declarations.

**Comment by getify** [comment]
Doesn't seem like any change is necessitated for this. Closing for now.
