### ISSUE TITLE
Loops & Closures

### ISSUE THREAD

**Issue by itmitica** [getify/You-Dont-Know-JS#683]
Your approach, `let` not considered, is to create a IIFE inside a loop. 
``` javascript
for (var i=1; i<=5; i++) {
    (function(){
        var j = i;
        setTimeout( function timer(){
            console.log( j );
        }, j*1000 );
    })();
}
```
Supposedly, this code breaks a few "laws": anonymous functions (the IIFE), polluting the namespace (the `i` var), "smart" code (a recognizable pattern only after a while).

Why not move the loop inside a IIFE? Why not this?
``` javascript
(function IIFE() {
    function closure(j) {               // IIFE.declarative {
        function printc() {                     // closure.declarative {
            console.log(j);
        }                                       // }
        setTimeout(printc, j*1000);             // closure.live {}
    }
    var i;                              // }
    for (i = 1; i <= 5; i++) {          // IIFE.live {
        closure(i);
    };                                  // }
})()
```
Is this moving inside a IIFE instead, maybe a pattern for simulating the block scope in general: for `if`, `switch` and so on? Additionally, is this code too explicit?

**Comment by getify** [comment]
I think your version obscures the main point of the text around this example which is that what we need, most simply, is a new scope *per iteration*. That's the root of the problem, and the solution.

**Comment by getify** [comment]
Thanks for the suggestion, but I think we'll leave as-is.
