### ISSUE TITLE
Distinguish declaration vs. expression functions.

### ISSUE THREAD

**Issue by oldergod** [getify/You-Dont-Know-JS#686]
The book says at the [third chapter](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch3.md#functions-as-scopes) of _Scope and Closures_:

> **Note**: The easiest way to distinguish declaration vs. expression is the position of the word "function" in the statement (not just a line, but a distinct statement). If "function" is the very first thing in the statement, then it's a function declaration. Otherwise, it's a function expression.

But on [MDN#functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions#Examples) it is said that "_[if a function declaration is a nested] statement in the script or a function body[, then it is a function expression]_" which would be a exception of the rule in the book from above.

**Comment by getify** [comment]
MDN is incorrect. function declarations inside blocks are still declarations.

**Comment by oldergod** [comment]
Probably why I did not find anything about this in the spec. Thank you.
