### ISSUE TITLE
Chapter 4: Hoisting changes across javascript engine

### ISSUE THREAD

**Issue by cliffordfajardo** [getify/You-Dont-Know-JS#689]
For the last example in Chapter 4 of hoisting I ran into interesting problems concerning the following statement: 
- *Function declarations that appear inside of normal blocks typically hoist to the enclosing scope, rather than being conditional as this code implies:*

```js
foo(); // "b"

var a = true;
if (a) {
   function foo() { console.log( "a" ); }
}
else {
   function foo() { console.log( "b" ); }
}
```
The following logs different values across browsers (I'm using OSX El Capitan):
- Safari(9.03 latest): logs 'b'
- Chromium(41.0.2272.76 Linux): logs 'b'
 - I knew Chrome in the past was doing the same behavior as Safari's latest version & just so happened to have my Ubuntu laptop which I hadn't used in a while to test my assumptions.
- Chrome(49.0.2623.87 latest consumer): returns a `TypeError: foo is not a function(...)`
  - Chrome a few updates (not versions) ago was logging 'b' as well. I remember this because I was writing a blog post on hoisting recently.
- Firefox(45 latest consumer): foo is not defined 
- Firefox Developer Edition (47.0A2): foo is not a function

To close the chapter (at the end of the above-mentioned example) you note:

- *However, it's important to note that this behavior is not reliable and is subject to change in future versions of JavaScript, so it's probably best to avoid declaring functions in blocks.*

Just curious about what you meant about this behavior. Were you referring to ES2015+?

**Comment by getify** [comment]
ES6 changed this behavior (after this book's first edition had been published). And even post-ES6, there's been some discussions of whether or not the changes in ES6 are actually implementable without breaking too much of the web. I think this is still in flux, especially as your test results illustrate.

**Comment by getify** [comment]
Closing for now. Will revisit if this settles.
