### ISSUE TITLE
`arguments` spoken as if it was an array

### ISSUE THREAD

**Issue by oldergod** [getify/You-Dont-Know-JS#701]
In _[Types & Grammar / Chapter 5: Grammar](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20&%20grammar/ch5.md)_, `arguments` is refered many times as being the "`arguments` array" while it is, as I am sure you know, an object.

Would it not be better to say clearly `object` or at least `array-like`?

**Comment by getify** [comment]
Shrugs. I don't think it's terribly important at those parts of the text to introduce distraction around "things that look like arrays but aren't." the "arguments array" is wording i've heard in common usage before.
