### ISSUE TITLE
"Scopes & closures": apA, Dynamic Scope example goes wrong!

### ISSUE THREAD

**Issue by xiekw2010** [getify/You-Dont-Know-JS#702]
```js
function foo() {
	console.log( a ); // 2
}

function bar() {
	var a = 3;
	foo();
}

var a = 2;

bar();
```

As `bar()` runs, get the result `2` which dynamic scope expect `3`.

I tested it in chrome's console.

**Comment by getify** [comment]
The example you cite is explained in the surrounding text as illustrating how lexical (non-dynamic) scope actually works. Yes, in lexical scope, the value is `2`. There is no such thing as dynamic scope in JS. This appendix is pointing out how dynamic scope would work if it existed, which it doesn't.

**Comment by xiekw2010** [comment]
Ok, I got it, thanks!

**Comment by HaveF** [comment]
@getify 
```
function foo() {
    console.log( a ); 
}

function bar() {
    var a = 3;
    foo();
}

var a = 2;

bar();
```
I understand this, but have another question to ask:

If I do not modify the position of `foo`, but only modify the `bar` function, could it possible to get `3` as a result?

**Comment by EirikBirkeland** [comment]
@HaveF Just my 2 cents:

You didn't explicitly prohibit against altering `foo`, so, you could just pass `a` into `foo`:

`function foo( a ) {
    console.log( a ); 
}

function bar() {
    var a = 3;
    foo( a );
}

var a = 2;`

I can't seem to do this in any other way without breaking your criteria (e.g. could just put `foo` inside `bar`.)

Anything I missed ... ? I hope so!

**Comment by HaveF** [comment]
@EirikBirkeland 
:joy: Ok, then I explicitly prohibit against altering `foo`, and also can not put the `foo` inside of `bar`.

I just curiosity about "Could it possible only change `bar` to get the result `3`"

```
function bar() {
    var a = 3;
    __.....__

}
```
Anyway, thanks for your reply:blush:

**Comment by EirikBirkeland** [comment]
This works fine since the bottom `var a = 2` in the outer scope is roughly equivalent to `window.a = 2` (depending on browser):

`function foo() {
	console.log(a);
}

function bar() {
	window.a = 3;
	foo();
}

var a = 2;

bar();`

Would not work if run in some environments, like Chrome extensions, where  the module would be wrapped somehow.

**Comment by HaveF** [comment]
@EirikBirkeland 
:grin:could it possible do not to change the `global a` ?

**Comment by HaveF** [comment]
Find answer in [Look-ups](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch2.md#look-ups):

> However, non-global shadowed variables cannot be accessed.
