### ISSUE TITLE
"up & going": Chapter 2: Truthy & Falsy

### ISSUE THREAD

**Issue by ptMcGit** [getify/You-Dont-Know-JS#704]
Using Firefox 45.0.1 empty arrays seem to be falsy

```javascript
[ ] == false;   // evaluates to true
```
My mistake. You can get the actual true/false value with 

```javascript
console.log(!![ ] == false);  // evaluates to false
``` 

See http://stackoverflow.com/questions/33567147/empty-array-is-falsy-yet-0-1-evaluates-to-0

**Comment by getify** [comment]
Covered here: https://github.com/getify/You-Dont-Know-JS/blob/master/types%20&%20grammar/ch4.md#the-crazy-ones

**Comment by ptMcGit** [comment]
Thanks.

Great work by the way.
