### ISSUE TITLE
You program with primitives like objects, because of the dot operator ...

### ISSUE THREAD

**Issue by landonsanders** [getify/You-Dont-Know-JS#706]
You program, explicitly, with type conversion, with the dot operator, when you use a primitive like an object. In other words, when one of the operands of the dot operator is a primitive and the other operand is an object, the first, primitive operand is converted to an object, with a wrapper. The operation is done. The expression evaluates to the result of the computation. 

The point is that dot is an operator.

**Comment by getify** [comment]
Not sure what the point of your comment is. Are you asking a question, or disagreeing with something in the text? Can you clarify.

That said, I have a couple of observations about your statement:

1. I wouldn't call `"abc".toUpperCase()` an *explicit* coercion, but an *implicit* coercion. But yes, it's a coercion, a special kind called "boxing", where the primitive `"abc"` becomes the object wrapper equivalent (`new String("abc")`).
2. "...and the other operand is an object..." eh, no. `"abc".c` does a coercion to make `"abc"` an object, regardless of `c` being an object or not. If `c` is a property, it doesn't matter what type of value it holds, it's a property, and properties only exist on objects.

**Comment by landonsanders** [comment]
I meant to say when the other operand is a function ...


I am saying that coercion in this case is explicit, because primitives are not objects. In other words, you have to use the dot operator to program with a property and/or method or method, with a primitive value. In other words, implicit coercion is a feature. You can explicitly use the feature to program with primitives like object with the dot. Behind the scenes, we know that the primitive is wrapped, but that is a detail of the operation, not the operation, itself.


 From the view that an operation is what it is -- an operation. As a thing in itself, I am saying, when one of the operands to the dot operator is a not-an-object-primitive and the other is a function or rather method an operation takes place. The operation is explicit because the first operand is not an object. All. "Properties on exist on objects" -- Kyle Simpson: I agree, in other words. That is what makes coercion explicit.


You write great books, man. 


Enjoy your day,
Landon Sanders

--------------------------------------------
On Thu, 3/31/16, Kyle Simpson <notifications@github.com> wrote:

 Subject: Re: [getify/You-Dont-Know-JS] You program with primitives like objects, because of the dot operator ... (#706)
 To: "getify/You-Dont-Know-JS" <You-Dont-Know-JS@noreply.github.com>
 Cc: "Landon Sanders" <mr.landonsanders@yahoo.com>
 Date: Thursday, March 31, 2016, 11:31 AM
 
 Not sure what the point of your
 comment is. Are you asking a question, or disagreeing with
 something in the text? Can you clarify.
 
 That said, I have a couple of observations about your
 statement:
 
 
 I wouldn't call
 "abc".toUpperCase() an
 explicit coercion, but an implicit
 coercion. But yes, it's a coercion, a special kind
 called "boxing", where the primitive
 "abc" becomes the object wrapper
 equivalent (new String("abc")).
 "...and the other operand is an object..." eh,
 no. "abc".c does a coercion to make
 "abc" an object, regardless of
 c being an object or not. If c is
 a property, it doesn't matter what type of value it
 holds, it's a property, and properties only exist on
 objects.
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly or view
 it on GitHub

**Comment by landonsanders** [comment]
An aside -- I think that truthy and falsy values extend the boolean type with more values. In other words, I love Javascript. Don't mind me, guys. Error-Driven Development ... :)

--------------------------------------------
On Thu, 3/31/16, Kyle Simpson <notifications@github.com> wrote:

 Subject: Re: [getify/You-Dont-Know-JS] You program with primitives like objects, because of the dot operator ... (#706)
 To: "getify/You-Dont-Know-JS" <You-Dont-Know-JS@noreply.github.com>
 Cc: "Landon Sanders" <mr.landonsanders@yahoo.com>
 Date: Thursday, March 31, 2016, 11:31 AM
 
 Not sure what the point of your
 comment is. Are you asking a question, or disagreeing with
 something in the text? Can you clarify.
 
 That said, I have a couple of observations about your
 statement:
 
 
 I wouldn't call
 "abc".toUpperCase() an
 explicit coercion, but an implicit
 coercion. But yes, it's a coercion, a special kind
 called "boxing", where the primitive
 "abc" becomes the object wrapper
 equivalent (new String("abc")).
 "...and the other operand is an object..." eh,
 no. "abc".c does a coercion to make
 "abc" an object, regardless of
 c being an object or not. If c is
 a property, it doesn't matter what type of value it
 holds, it's a property, and properties only exist on
 objects.
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly or view
 it on GitHub

**Comment by landonsanders** [comment]
When the other operand is a property, I meant. Sorry about the bad email etiquette man. You ought to unblock me on twitter. That way I can follow you. I am, totally, not a leader of men.

--------------------------------------------
On Thu, 3/31/16, Kyle Simpson <notifications@github.com> wrote:

 Subject: Re: [getify/You-Dont-Know-JS] You program with primitives like objects, because of the dot operator ... (#706)
 To: "getify/You-Dont-Know-JS" <You-Dont-Know-JS@noreply.github.com>
 Cc: "Landon Sanders" <mr.landonsanders@yahoo.com>
 Date: Thursday, March 31, 2016, 11:31 AM
 
 Not sure what the point of your
 comment is. Are you asking a question, or disagreeing with
 something in the text? Can you clarify.
 
 That said, I have a couple of observations about your
 statement:
 
 
 I wouldn't call
 "abc".toUpperCase() an
 explicit coercion, but an implicit
 coercion. But yes, it's a coercion, a special kind
 called "boxing", where the primitive
 "abc" becomes the object wrapper
 equivalent (new String("abc")).
 "...and the other operand is an object..." eh,
 no. "abc".c does a coercion to make
 "abc" an object, regardless of
 c being an object or not. If c is
 a property, it doesn't matter what type of value it
 holds, it's a property, and properties only exist on
 objects.
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly or view
 it on GitHub

**Comment by getify** [comment]
OK, thanks for your thoughts.

**Comment by landonsanders** [comment]
Thanks for your response, man. Means something.
