### ISSUE TITLE
Is this series had some authorized translation version?

### ISSUE THREAD

**Issue by JoeHetfield** [getify/You-Dont-Know-JS#719]
My Chinese translation is in progress. I suddenly reminded to check if I am the only one doing this. I searched around and found this: (https://www.amazon.cn/%E5%9B%BE%E4%B9%A6/dp/B00W34DZ8K).

This one looks like a O'Reilly official edition. but I didn't fond any repo of it on github.

Am I doing a job which is already done? 

if there is anything different between that and mine, is I will host mine on github and maintain in the fashion of community, I think.

**Comment by getify** [comment]
There's already a Chinese company that has done a translation of at least some of the books in the series. Not sure who they are, though, just seen it done.

**Comment by JoeHetfield** [comment]
Oops. Thank you @getify 

Is this mean my work will be meaningless if keep going? Actually I'm planning a big PR to you after 2 months (if everything goes fine). 

any suggestions?

**Comment by getify** [comment]
I'd recommend looking around for the information about the official Chinese translated books before proceeding. It might mean you wouldn't need to keep your translation going. But that's not my call, it's yours.

**Comment by JoeHetfield** [comment]
yes, you're right. I will check on that version. it may lead a tough decision, though.
thanks for help.

**Comment by davidpelayo** [comment]
Do you know, by the way, if there is any translation to spanish done? I've quickly checked and haven't found anything.

**Comment by JoeHetfield** [comment]
@davidpelayo sorry, I don't know, but I found the Chinese translation version on amazon China. maybe you could try amazon Spain?

**Comment by davidpelayo** [comment]
Not found it. That's why ask.

**Comment by JoeHetfield** [comment]
@davidpelayo Then I think you got a opportunity to do this.

**Comment by getify** [comment]
Closing for now.
