### ISSUE TITLE
"this & object prototypes": ch2, Could it possible to avoid using self and arrow-function here?

### ISSUE THREAD

**Issue by HaveF** [getify/You-Dont-Know-JS#721]
In ch2 this part: [Lexical this](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes%2Fch2.md#lexical-this)

It said at last:

>Embrace this-style mechanisms completely, including using bind(..) where necessary, and try to avoid self = this and arrow-function "lexical this" tricks.

Could it possible to avoid using `self=this` and arrow-function in the example which is illustrated?

```js
function foo() {
    setTimeout(() => {
        // `this` here is lexically adopted from `foo()`
        console.log( this.a );
    },100);
}

var obj = {
    a: 2
};

foo.call( obj ); // 2
```

**Comment by getify** [comment]
> Could it possible to avoid using self=this and arrow-function

Yes:

```js
function foo() {
    setTimeout(function() {
        // `this` here is lexically adopted from `foo()`
        console.log( this.a );
    }.bind(this),100);
}

var obj = {
    a: 2
};

foo.call( obj ); // 2
```

**Comment by HaveF** [comment]
@getify beautiful:heart:
