### ISSUE TITLE
Human brain has been always worked asynch.

### ISSUE THREAD

**Issue by imanghafoori1** [getify/You-Dont-Know-JS#723]
ُSounds strange ?!
Hi,Uncle Kyle
You are by far the best javascript teacher I ever had.
I hear you mention in a lot of your talks that Human brain works synchronously.
I believed in it too for a year and always thought about that fact.
But I recently realized that although human brain is absolutely single threaded...
It does not work synchronous at all.
of course, It can only think about one and only one think at a given moment but it never likes staying blocked for an answer of a question like synchronous languages block for a result of a database call.

A real life example of that is:
Consider me, emailing this fact to you, After typing and sending the mail for you, I (as a human) never stay "Blocked" behind my PC , and do nothing except waiting for your response to come.(like PHP does in case a of database call)
I immediately start my other tasks after sending the email, leaving the email response to come later.
(like javascript does in case of sending an ajax call,it goes for executing the rest of the code.)
And when it is answered by you, I come back to read it and do some think based on your response (equivalent of executing a call back).

In fact human beings always hate being blocked.
If I go to a restaurant and order food, I have to wait for 20 minutes. for the food to get ready.
A synchronous human only waits in that 20 minute and does nothing.
But people hate waiting.They immediately bring their smart phone out of their pockets and start to work with it, They "tend" to do something to get the most out of their time.

That tendency is what makes humans Asynchronous creatures.
But any way we all are "single threaded"

**Comment by imanghafoori1** [comment]
But Why Asynchronous Programming Is So Difficult ?!
I think it is because we are dealing with an extra more dimension and that is "Time".
which Albert Enestien called the 4th dimension.
The callbacks, functions passed into the .then(func) and etc... are all going to be executed later in future.
I think any Asynchronous javascript program can be divided into multiple synchronous block of codes which are going to be executed (synchronously) at different times, one after the other.
This a what makes producing animation harder that painting on a wall.
since any animation (or .mp4 file) can be splitted into static frames.

**Comment by getify** [comment]
I never said the human brain works synchronously. What I said is that it operates sequentially (which it does) and that we plan (cognitively, consciously) in a fundamentally synchronous way. In fact, numerous times I've claimed our brains are a lot like JS engines (concurrent event loops), in terms of how we react to stimuli. But the part that matters for the discussion is how we plan, because that's how we architect our code. We plan in a "do this, then that, then that, then that" sort of matter, which is synchronous and blocking in nature. Which is why I claim we should write code that way.

**Comment by imanghafoori1** [comment]
https://www.youtube.com/watch?v=Qg1SvpIau6U 
at 16:00-16:30
Maybe I did not get what you really meant in there.
Any way your javascript tutorials are earth shattering , thank you.

**Comment by getify** [comment]
thanks.
