### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by Isocles** [getify/You-Dont-Know-JS#730]
Hello,
I notice that the concept of garbage collection is never formally explained in Up & Going, and while Scope & Closure touches it (very lightly in chapter 3 and more directly in chapter 5) perhaps a formal definition would be useful to add, as the aforementioned chapters seem to assume one is already familiar with garbage collection in JS. 

Note that I've only just finished Scope & Closures, so if there's another book which goes more in-depth on it I have yet to read it. If that is the case, a specification of this fact  in the parts where garbage collection is mentioned in Scopes & Closures would be great to add. 

Thank you.

EDIT: Spelling

**Comment by getify** [comment]
Interesting point. It's pretty complicated to explain accurately, and it's only an implementation detail, not controlled by the spec, so you can only talk generally and not specifically (which harms accuracy). Not really sure if it would muddy the waters to add or not.

**Comment by brad-decker** [comment]
Personally garbage collection has always been a fuzzy topic for me, so even if does end up being very imprecise having a general knowledge about the subject could be greatly beneficial.
