### ISSUE TITLE
How many phones can I afford Practice solution has a logic issue.

### ISSUE THREAD

**Issue by muxica** [getify/You-Dont-Know-JS#733]
After getting my version of the practice done, I checked it with the solution and found a glaring issue with the first While loop.
`while (amount < bank_balance) {
    // buy a new phone!
    amount = amount + PHONE_PRICE;

    // can we afford the accessory?
    if (amount < SPENDING_THRESHOLD) {
        amount = amount + ACCESSORY_PRICE;
    }
}
`
Specifically, this part: `while(amount < bank_balance)`
It occurs to me that this will run the loop until there are insufficient funds in the bank_account no matter the amount you have input. I think that the while loop should be checking against the `SPENDING_THRESHOLD` both times. So it should look like this: 

`while (amount < SPENDING_THRESHOLD) {
    // buy a new phone!
    amount = amount + PHONE_PRICE;

    // can we afford the accessory?
    if (amount < SPENDING_THRESHOLD) {
        amount = amount + ACCESSORY_PRICE;
    }
}
`

**Comment by getify** [comment]
Known issue:

https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=is%3Aissue+phone+afford

Thanks.
