### ISSUE TITLE
"Async & Performance", ch3, Promise.race([ .. ]) -> Not clear about reject status

### ISSUE THREAD

**Issue by JoeHetfield** [getify/You-Dont-Know-JS#737]
Hi, Kyle.

In the "Async & Performance", chapter 3 , "Promise.race([ .. ])" section. Line 1362. you said:

> Similar to `Promise.all([ .. ])`, `Promise.race([ .. ])` will fulfill if and when any Promise resolution is a fulfillment, and it will reject if and when any Promise resolution is a rejection.

Say I have `Promise.race([ p1, p2 ])`, if p1 finished first and got reject, what you said above is OK. What if p1 finished after p2 and p2 is fulfilled but p1 got rejected? will the Promise.race([ .. ]) be rejected because of p1? if so, is this mean Promise.race([ .. ]) are waiting all of it's sub promise, and lost the meaning of "Race"?

Or, which I think is more accurate, Promise.race([ .. ]) will be rejected if the first finished promise is rejected. then I think the statement above should be:

> Similar to `Promise.all([ .. ])`, `Promise.race([ .. ])` will fulfill when the first finished Promise resolution is a fulfillment, and it will reject when the first finished Promise resolution is a rejection.

I haven't try this by myself, but I think this issue should be explained.

**Comment by getify** [comment]
For `Promise.race([p1,p2])`, whichever one finishes (`p1` or `p2`) first, whatever its completion is, that's the result. If the first one is a rejection, it's rejected. If the first one is fulfilled, it's fulfilled. It's simple: it's purely a race for whichever promise has some sort of completion first.
