### ISSUE TITLE
"this & Object Prototypes", ch2, default binding example

### ISSUE THREAD

**Issue by zcserei** [getify/You-Dont-Know-JS#738]
Hello!

I am finally trying to get my head around `this` - the whole thing really is the way you described: been using JS for years, didn't really understand `this` at all. Thanks for this amazing series, it was due time I upgraded myself.

However, in chapter two of this & Object Prototypes, the default binding example does not seem to work. Below is the code in question:
```
function foo() {
    console.log( this.a );
}

var a = 2;

foo(); // 2
```

I am running example code using Node, the code above just returns undefined. When using strict mode, instead of just stating that there is a TypeError because `this` is undefined, it elaborates: `TypeError: Cannot read property 'a' of undefined`.

I think I do understand the strict mode error, however... can you please clarify why it is returning `undefined` in non-strict mode?

Thanks

**Comment by getify** [comment]
As strange as it sounds, running code inside of Node is not actually running in a true JS environment. Node wraps all code, even the main program, in these pseudo-modules (wrapper functions). The `var a = 2` in a node program isn't actually creating a global the way it would in a browser.

The console in your dev tools has other weird tricks it plays which sometimes violates the rules of JS, too.

So, if you want to actually test in a real, non-altered JS env, use an actual full program in a browser. That's the only way to correctly test.

**Comment by zcserei** [comment]
Hi Kyle!

Thanks for the clarification! Just assuming that it's the same engine that is under Chrome's hood, I've been using the `node` command to test a bunch of my scripts previously.

**Comment by getify** [comment]
It is the same engine (v8), but the environment is more than that.

**Comment by lancelot-koh** [comment]
same in nodejs runtime and chrome console
