### ISSUE TITLE
this & object prototypes/ch5.md

### ISSUE THREAD

**Issue by ivanberry** [getify/You-Dont-Know-JS#742]
*Setting Shadowing Properties*
>2. If a foo is found higher on the [[Prototype]] chain, but it's marked as read-only (writable:false), then both >the setting of that existing property as well as the creation of the shadowed property on myObject are >disallowed. If the code is running in strict mode, an error will be thrown. Otherwise, the setting of the >property value will silently be ignored. Either way, no shadowing occurs. 

Yeah, once we are in strict mode , the console will throw the error, while, we are not, I can re-assign the property of one's [[property]] have the property and not allowed writable(writable: false), is this a error or something else?

![shadow property](https://cloud.githubusercontent.com/assets/13112910/15524731/7c316310-2257-11e6-84db-a88ba83417f5.gif)
test on Chrome version  50.0.2661.102 (64-bit)

**Comment by getify** [comment]
In strict mode, you get an error. In non-strict mode, it silently fails.
