### ISSUE TITLE
ES 6 & beyond, Temporal dead zone

### ISSUE THREAD

**Issue by anirudh-modi** [getify/You-Dont-Know-JS#743]
I was trying to replicate the TDZ error mentioned in ES6, however I could not replicate the effect using the code Babel...

````
console.log(a); 
let a;
````
but I could not get the reference error. it never prints any output, nor throws any error, am I doing anything wrong?

https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015&code=%0A%20%20console.log(a)%3B%0A%20%20%0A%20%20const%20a%3D1%3B

**Comment by anirudh-modi** [comment]
I guess this is because babel transpiles to ES5, which prevents the issue.

**Comment by DiglidiDudeNG** [comment]
Maybe don't have `'use strict';` at the beginning of your js file. Try it with that.

**Comment by getify** [comment]
you need to turn on the strict spec compliance optio  with babel

**Comment by anirudh-modi** [comment]
Seems like a babel issue, because my strict mode is on, i have selected es 2015 from presets..
Thanks for response..

**Comment by getify** [comment]
not strict mode, strict spec compliance
