### ISSUE TITLE
When synchronous is trustable?

### ISSUE THREAD

**Issue by calamarino** [getify/You-Dont-Know-JS#744]
In chapter 3 this is clearly not trustable
```
var x, y = 2;
console.log( x + y ); // NaN <-- because `x` isn't set yet
```

Question:
How trustable is the following case? (because hoisting, the variables should have already been defined before getting to `console.log`)
- Would it be better to write it using Promises to make it bulletproof? (one could end with an insane amount of Promises in a rather simple program, right?).
```
console.log( x + y );
var x = 2;
var y = 1;
```

**Comment by getify** [comment]
> How trustable is the following case?

Depends on what you mean by "trustable". The variables will definitely be in scope, but they absolutely will both be `undefined` at the point of the `console.log(..)` statement.

**Comment by calamarino** [comment]
Sorry for asking back late.  I'm thinking on this.
- Is it because of hoisting that the evaluation is correct? 
- How can I determine **conceptually** which is the correct sequence of evaluation of this snippet ? (without using tools)
```
"use strict";
function sum(x1, y1) {
    "use strict";
    return function () {
        console.log(x1 + y1)
    }
}
var funcSum = sum(x, y);
funcSum();
var x = 2;
var y = 4;
```

**Comment by getify** [comment]
I think you should (re)read this chapter:

https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch1.md
