### ISSUE TITLE
Using setPrototypeOf to change super

### ISSUE THREAD

**Issue by gotoprototype** [getify/You-Dont-Know-JS#746]
Hello,
I enjoyed your talk [What the... JavaScript?](https://www.youtube.com/watch?v=2pL28CcEijU).
I played a little bit around and found it weird that you can't change **super** via `setPrototypeOf` as mentioned in the presentation at [36:54](https://www.youtube.com/watch?v=2pL28CcEijU&feature=youtu.be&t=36m54s) and on [slide 75](https://speakerdeck.com/getify/what-the-javascript?slide=75).
Turns out you can change **super** via `setPrototypeOf` and it works as aspected, with the obvious downside that you have to manually switch it back.

```
class Px {
  another() { console.log('Px.another'); }
}
class Cx extends Px {
  something() { console.log('Cx.something'); }
  another() { this.something(); super.another(); }
}

class Py {
  another() { console.log('Py.another'); }
}
class Cy extends Py {
  something() { console.log('Cy.something'); }
  another() { this.something(); super.another(); }
}


Object.setPrototypeOf(Cy.prototype, Px.prototype);
var x = new Cx();
var y = new Cy();

y.another.call(x);
// "Cx.something"
// "Px.another"

// obviously, this also changes super for y itself:
y.another();
// "Cy.something"
// "Px.another" <-- because of Object.setPrototypeOf(Cy.prototype, Px.prototype);
```

I know that your presentation was in Mar '15 and ES6 was standardized in June '15, so it's possible that it was changed just before that. But I couldn't find anything to this in [ES6 & Beyond > Organization > There Be super Dragons](https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch3.md#there-be-super-dragons). To be honest I didn't dig to much into the books, maybe I can't find the spot or I just missunterstood something. Maybe it changed before standardization.

Just wanted to point it out. 😊

**Comment by getify** [comment]
The content of the talk may have been misleading, but this repo is about the book content. I believe the books are accurate in their discussion of how `super` works (and doesn't).
