### ISSUE TITLE
Small grammatical error

### ISSUE THREAD

**Issue by Isocles** [getify/You-Dont-Know-JS#747]
Hello,
not 100% sure if this really worth submitting a new issue or not, but I believe "mathematic" cannot be used as an adjective, like you do in Chp 2 of Types & Grammar:

> Any mathematic operation

Here: https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch2.md#the-not-number-number

I think this would be more correct:

>Any mathematical operation

Thank you.

EDIT: Forgot a word.

**Comment by Isocles** [comment]
I created a pull request here:

#753

**Comment by getify** [comment]
Both "mathematic" and "mathematical" are acceptable adjective forms:

http://www.dictionary.com/browse/mathematic
