### ISSUE TITLE
Blocked scoped function

### ISSUE THREAD

**Issue by anirudh-modi** [getify/You-Dont-Know-JS#754]
https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch2.md#block-scoped-functions

In the blocked scoped function it was mentioned that the code below prior to ES6 would give an output of 2, no matter what the value of something be.

````
if (something) {
    function foo() {
        console.log( "1" );
    }
}
else {
    function foo() {
        console.log( "2" );
    }
}

foo();
````

However, When I tried this out, if the value of something was a truthy value, it was printing 1, else it was printing 2.

But if I tried executing foo, before the if loop, then it was giving foo is not a function.

I tried in JSBIN.

**Comment by getify** [comment]
First, you can't rely on the behavior of such things in JS emulation environments like JSBin. Secondly, this block-scoped functions thing is in flux, so YMMV in diff browsers.

**Comment by anirudh-modi** [comment]
Ok, I also tried in the console of the chrome and firefox, i was getting the same result..
But as mentioned it may vary in different browsers...

Thanks for the info.
