### ISSUE TITLE
Wrong comment in es6 & beyond.

### ISSUE THREAD

**Issue by krave1986** [getify/You-Dont-Know-JS#756]
The comments of the code in `Custom Change Events` section of es6 & beyond are wrong, I think.
Check [here](https://github.com/getify/You-Dont-Know-JS/blob/cc82d7c8f4872ceee87a5c3b193ee846c6ab0ecc/es6%20%26%20beyond/ch8.md#custom-change-events)
```
function observer(changes){
    for (var change of changes) {
        if (change.type == "recalc") {
            change.object.c =
                change.object.oldValue +
                change.object.a +
                change.object.b;
        }
    }
}

function changeObj(a,b) {
    var notifier = Object.getNotifier( obj );

    obj.a = a * 2;
    obj.b = b * 3;

    // queue up change events into a set
    notifier.notify( {
        type: "recalc",
        name: "c",
        oldValue: obj.c
    } );
}

var obj = { a: 1, b: 2, c: 3 };

Object.observe(
    obj,
    observer,
    ["recalc"]
);

changeObj( 3, 11 );

obj.a;          // 12
obj.b;          // 30
obj.c;          // 3
```
The comment of the last three lines should be 
```
obj.a;          // 6
obj.b;          // 33
obj.c;          // 3
```
or the arguments of changeObj(..) should have been 6 and 10 as calling changeObj( 6, 10 ) to see
the comment as it is if the comments indicate what the value of those properties are.

**Comment by getify** [comment]
`Object.observe(..)` has been abandoned so I can't verify it anymore. The topic will be removed entirely from the book in the second edition.
