### ISSUE TITLE
samples of  "regexp sticky position" are broken

### ISSUE THREAD

**Issue by xiechao06** [getify/You-Dont-Know-JS#757]
in the chapter  https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch2.md#sticky-positioning, there's a code sample:

```js
var re = /f../y,
    str = "foo       far       fad";

str.match( re );        // ["foo"]

re.lastIndex = 10;
str.match( re );        // ["far"]

re.lastIndex = 20;
str.match( re );        // ["fad"]
```

but when I run this snippet (both in chrome Version 50.0.2661.86 dev, and node 6.2.1), I find out that "str.match(re)" always gives ["foo"], it seems that sticky flag only works to "RegExp.prototype.test" rather than "RegExp.prototype.match".

**Comment by getify** [comment]
This is what I get in Chrome:

![screen shot 2016-06-10 at 7 18 22 am](https://cloud.githubusercontent.com/assets/150330/15964000/b3ffef06-2edb-11e6-892b-117f9ba8a0e2.png)

**Comment by xiechao06** [comment]
![image](https://cloud.githubusercontent.com/assets/2888536/15983621/a888810a-2fe0-11e6-8117-949a7af72dd2.png)

![image](https://cloud.githubusercontent.com/assets/2888536/15983616/9cc3c096-2fe0-11e6-907e-a1868005b426.png)

Ah , it seems a bug in my chrome version( 50.0.2661.86) and node(version 6.2.1). It seems we should use this new feature more carefully.
@getify may I know your chrome version?

**Comment by getify** [comment]
I just retested in Chrome Canary 53.
