### ISSUE TITLE
Dynamic typing vs Weak typing

### ISSUE THREAD

**Issue by rustyworks** [getify/You-Dont-Know-JS#759]
https://github.com/getify/You-Dont-Know-JS/blob/master/up%20&%20going/ch1.md#variables
"Weak typing, otherwise known as dynamic typing, allows a variable to hold any type of value at any time"

I think it is wrong, because weak typing means that you can do operation between two different type variable.
For example: 1 + "1" // This is ok in weak typing but not ok in strong typing

The dynamic typing is that a variable can be inserted without declaring the type
For example: var a = 1; a = "a" // This is ok in dynamic typing but not ok in static typing.

I hope you reconsider the terms. Thank you.

**Comment by getify** [comment]
In an intro book, I don't think those fine distinctions matter that much. Explaining it fully would be way beyond a beginner, but not talking about it at all does a disservice to the learner.

Weak typing is about whether coercion can happen implicitly, and dynamic typing is about whether values of different types can go in a variable. Those are not that far off conceptually, especially for the beginning programmer.

**Comment by rustyworks** [comment]
I think because the reader is beginner, the book shouldn't mislead the reader. Well, I don't know. :confused:

**Comment by getify** [comment]
> the book shouldn't mislead the reader.

No, it shouldn't actively/intentionally mislead. But there's necessarily tons of details left out of a beginner book.

Ask yourself: what mistake would a beginner make if they had the misimpression that weak typing and dynamic typing were basically two sides of the same concept? That's important detail, but only once you're much more seasoned and evaluating multiple languages and stuff like that.

**Comment by rustyworks** [comment]
No fatal things happened, but this misleading can be continuous. Just like in my case in teaching for math the PI value is 3.1415... and some teacher teach that PI value is 22/7.

Well overall the content is good, and the analogy is very clear, I would recommend this book for pedagogy. Well please don't take this too personally.

Thanks anyway.

**Comment by oskarkv** [comment]
@getify I just wanna say that I agree with the original poster. Why say something that isn't true? Isn't that actively misleading? What's the point of keeping it the way it is? I can't see any point to including false statements. Can you? There is difference between leaving out details and stating falsehoods.

> and dynamic typing is about whether values of different types can go in a variable

No actually, it's not. Dynamic typing means that type checks happens at runtime, and static means that they happen before runtime, typically at compile time (just as "static analysis" means analysis done without running the code).
