### ISSUE TITLE
Generators yield in finally

### ISSUE THREAD

**Issue by LukaszBrygala** [getify/You-Dont-Know-JS#760]
I'm wondering if putting yield inside finally block is really always a terrible idea. What about a generator yielding promises, which gonna be used in a bluebird's Promise.coroutine? Let's say, that in such generator we would like to clean up some resources asynchronously (no matter if all went ok or exception was thrown), using method returning a Promise, and we yield that result. 

Why it would be a bad thing?

**Comment by getify** [comment]
In my opinion it's a bad idea because it violates the expectation that when you call `return()` on an iterator, you expect it to immediately quit, not keep going.
