### ISSUE TITLE
ES6 & Beyond - Chapter 5: Collections - time complexity of Map & Set operations?

### ISSUE THREAD

**Issue by rayshan** [getify/You-Dont-Know-JS#762]
https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch5.md

Hi, it may be good to discuss the algorithm complexity of operations, which is a key consideration of deciding what data structure to use. My understanding is both insertion / lookup is O(1), as both Map and Set are backed by hash tables. Please correct me if I'm wrong.

Reference:
http://www.ecma-international.org/ecma-262/6.0/index.html#sec-set-objects
https://codereview.chromium.org/220293002/

**Comment by getify** [comment]
I think it might be an open question, not a guarantee, as to how these data structures are actually implemented, and what that might mean for performance. I also expect the first implementations of these features may be naive and then performance/optimization will come over time.

**Comment by rayshan** [comment]
Good points. Spec only says "hash tables or other mechanisms that, on average, provide access times that are sublinear on the number of elements in the collection".

Feel free to close this issue if you think it's too open ended.

**Comment by getify** [comment]
Closing for now. Reopen if more info comes to light on this that should be brought to attention of end-developers.
