### ISSUE TITLE
this & Object Prototypes chapter 2

### ISSUE THREAD

**Issue by ShengYun** [getify/You-Dont-Know-JS#766]
I read the code which is demonstrating arrow functions and `this`
```
function foo() {
    // return an arrow function
    return (a) => {
        // `this` here is lexically adopted from `foo()`
        console.log( this.a );
    };
}

var obj1 = {
    a: 2
};

var obj2 = {
    a: 3
};

var bar = foo.call( obj1 );
bar.call( obj2 ); // 2, not 3!
```

why does the arrow function have a parameter `a`? was it a typo? in my understanding this was not used in the snippet.

**Comment by getify** [comment]
it is not used.

**Comment by ShengYun** [comment]
Should it be removed? to make the snippet cleaner for newbies like me?

**Comment by getify** [comment]
Eh. It has a slight point which is to make the reader think about that the lexical `a` is not the same thing as the `a` in `this.a`. There's a perpetual confusion among developers that `this` can somehow refer to a function's own lexical scope, which it never can. Other places in the text refer to this confusion.

**Comment by ShengYun** [comment]
Got it:) Thanks for the great book. Also it would be great if you can add a link to the `arrow function lexical this` part, pointing to your blog post which clarifies that it does not have any `this` at all.

**Comment by getify** [comment]
yeah there's lots of improvements coming to all the books whenever i get time for a second edition.
