### ISSUE TITLE
Es6 & Beyond, template literal

### ISSUE THREAD

**Issue by anirudh-modi** [getify/You-Dont-Know-JS#771]
Hello,

In interpolated expression for template literal, it was mentioned any valid expression can be included within the `{}`, however, apart from the things it was mentioned

>including function calls, inline function expression calls, and even other interpolated string literals!

I wonder what else could be used, because when I was trying a spread operator within the literal it behaved quite differently,

````javascript
var name = [1,2]
var msg = `${name}`
// "1,2"
`````

Should not it print the content of array with `[]`? I am little confused that how it is getting printed.

**Comment by getify** [comment]
The `${name}` token in the template literal says, go stringify the `name` value (if it's not already). That's normal array stringification, which (annoyingly) does not include the "[" and "]". This has nothing to do with `...` spread.

**Comment by anirudh-modi** [comment]
Sorry, I was trying it with spread operator, and then discovered same thing is valid for array also..and forgot to change the content.

Thanks, for the explanation.
