### ISSUE TITLE
ES6 & Beyond, Spread/Rest

### ISSUE THREAD

**Issue by anirudh-modi** [getify/You-Dont-Know-JS#772]
I was trying this code below:

````javascript
var name = 'sky';
var f = ...name; //SyntaxError: Unexpected token ..

var g = [...name]; // ["s","k","y"];
````

This leads to the question, where can the spread operator be used, because when I tried using to assign to variable it fails, however when I am using it in `array` it spreads the value across the array.

**Comment by getify** [comment]
The `...` spread operator can only be used in a context that can accept multiple values. AFAIK, there are currently only two such contexts... inside a `[ .. ]` array literal, and inside the `( .. )` arguments list of a function call. `...name` by itself is invalid.

**Comment by anirudh-modi** [comment]
Thanks!

**Comment by anirudh-modi** [comment]
Does these context which can accept multiple values have a specific name of such?
