### ISSUE TITLE
"Predicate" as a reference to 0x, 0b, 0o in Types & Grammar ch2.md

### ISSUE THREAD

**Issue by imrek** [getify/You-Dont-Know-JS#774]
May be this has been discussed before, github's issue search did not return anything related to this, so I'll give it a try:

In *Chapter 2* of **Types & Grammar**, ```0x```, ```0b```, ```0o``` are referred to as *predicate*s (*"Always use the lowercase predicates 0x, 0b, and 0o."*), though I was unable to find any source applying this term to them. On StackOverflow, Github and Wikipedia ```0x```, etc. are commonly called *prefix*es. 

The ECMAScript spec actually uses the more abstract term *code unit* in [18.2.5](http://www.ecma-international.org/ecma-262/6.0/#sec-parseint-string-radix), but in the implementation of ```parseInt()``` a ```stripPrefix``` boolean variable is defined for internal/implementation purposes (Steps 9 and 12), which basically serves as a flag to show whether or not the *code unit* ```0x``` needs to be stripped. So I think the correct terminology to refer to ```0x```, ```0b```, ```0o``` is *prefix*. 

PS. Fantastic book, anyway, I call the books in the series: *Kyle's First[/Second/...] Epistle to the Javascriptians*.

**Comment by getify** [comment]
I'm not sure where I saw "predicate" to refer to those. But I'm also not sure "prefix" actually is definitively more correct, either. For example, MDN uses "leading part" to describe them. Shrugs. I may switch this the next time I make revisions to the text. Thanks.
