### ISSUE TITLE
scope & closures/ch5 - missing foo();?

### ISSUE THREAD

**Issue by casinbee** [getify/You-Dont-Know-JS#781]
In scope & closures/ch5:

```
function foo() {

    var a = 2;

    function baz() {
        console.log( a ); // 2
    }

    bar( baz );
}

function bar(fn) {
    fn(); // look ma, I saw closure!
}
```

I believe there is a `foo();` missing at the end, isn't it?

**Comment by getify** [comment]
Perhaps, but not necessarily. The snippets are not necessarily intended to be full run programs, but OTOH it could be ever so slightly clearer.
