### ISSUE TITLE
Destructuring

### ISSUE THREAD

**Issue by anirudh-modi** [getify/You-Dont-Know-JS#788]
Hello,

https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch2.md#destructuring

> Destructuring symmetrically flips that pattern, so that [a,b,c] on the lefthand side of the = assignment is treated as a kind of "pattern" for decomposing the righthand side array value into separate variable assignments.

It was mentioned that it lefthand side of the = assignment is treated as a kind of "pattern" for decomposing the righthand side.

So does this mean when we assign a value to variable `var a = 10` it is in a way Destructuring?

**Comment by getify** [comment]
well... destructuring is assignment, yes, but destructuring is specifically related to breaking down a compound value (object, array, etc) into its constituent values.

**Comment by anirudh-modi** [comment]
Thanks for the answer.
