### ISSUE TITLE
"ES7" should be changed to a more generic term

### ISSUE THREAD

**Issue by msegado** [getify/You-Dont-Know-JS#789]
There are several references to ES7 or ES7+ features which should be renamed now that ES7 is out (only the exponentiation operator and `Array#includes` made it in as new features; see http://www.2ality.com/2016/01/ecmascript-2016.html).

Going forward, it may be best to use generic references to "future JavaScript versions" or "proposed EcmaScript features" since ES features are now added on a rolling (annual) basis instead of being associated with particular release versions... there are some good thoughts on this over at https://medium.com/@jayphelps/please-stop-referring-to-proposed-javascript-features-as-es7-cad29f9dcc4b.

(Also, these books seem amazing - thank you!!)

**Comment by getify** [comment]
yes this will already be addressed in second edition. thanks. :)
