### ISSUE TITLE
Scope & Closures - Modern Modules - deps[i] = modules[deps[i]]; ?

### ISSUE THREAD

**Issue by kvetoslavnovak** [getify/You-Dont-Know-JS#791]
The Modern Module examole could have more detail explanation regarding what us going on. Take for example this comments:
http://stackoverflow.com/questions/31332645/javascript-module-pattern-from-you-dont-know-js

What I still do not know is why `deps[i] = modules[deps[i]];` does not resolve as undefined?

**Comment by kevcomedia** [comment]
That part also confused me at first.

The only way for `deps[i] = modules[deps[i]];` to resolve to `undefined` is when `modules` doesn't have a property with the name given by `deps[i]` in the first place. You can achieve this by swapping the calls to `MyModules.define()` in the example.
