### ISSUE TITLE
feedback: this & object prototypes > ch 4 > polymorphism

### ISSUE THREAD

**Issue by kaycebasques** [getify/You-Dont-Know-JS#796]
In the first paragraph of this section: 

> ...`Car`s `drive()` method calls `inherited:drive()` ... `SpeedBoat`s `pilot()` method also ...

Having two code literals side-by-side like this is pretty hard to read. You can improve the readability by just shifting words around a little...

The `drive()` method of `Car`... the `pilot()` method of `SpeedBoat`...

**Comment by getify** [comment]
Thanks for the suggestion.
