### ISSUE TITLE
'this & Object Prototypes' Chap 2 minor code fix in 'lexical this' example

### ISSUE THREAD

**Issue by nateq314** [getify/You-Dont-Know-JS#799]
In this code example in chapter 2 of 'this & Object Prototypes', the parameter `a` in the arrow function is unnecessary and never used:

```javascript
function foo() {
    // return an arrow function
    return (a) => {
        // `this` here is lexically adopted from `foo()`
        console.log( this.a );
    };
}

var obj1 = {
    a: 2
};

var obj2 = {
    a: 3
};

var bar = foo.call( obj1 );
bar.call( obj2 ); // 2, not 3!
```

**Comment by getify** [comment]
Yes, I'm aware. The point is to make sure you're aware that the `a` parameter is not in any way connected to the `this.a` reference. That's a very common line of confusion.
