### ISSUE TITLE
'Scopes & Closure': Future Module example incorrect

### ISSUE THREAD

**Issue by unional** [getify/You-Dont-Know-JS#800]
https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch5.md#future-modules

Should be either `export default ...` or `import { ... } form '...'`

**Comment by getify** [comment]
Yes, know issue thay syntax changed after publication. Will be addressed in second edition. See coverage of modules in ES6 & Beyond for more current content.
