### ISSUE TITLE
about translate

### ISSUE THREAD

**Issue by CheshireJCat** [getify/You-Dont-Know-JS#806]
I want to know that If I can fork your great repo and when I read, translate it in Chinese just on github, than when my firends can read your book easily, because ours English is not so good.   
 
I don't have any intention to publish. If you don't agree , I can remove it right now.  
 
Please connect me.  

[Here is my link](https://github.com/CheshireJCat/You-Dont-Know-JS)

**Comment by getify** [comment]
There's already an official published chinese translation. Have you looked for that?

**Comment by CheshireJCat** [comment]
Oh, thank you, I got it just now . And I also want to translate it as the way of improve my English. How do you think?

**Comment by getify** [comment]
Please see the discussion here: https://github.com/getify/You-Dont-Know-JS/issues/9

**Comment by CheshireJCat** [comment]
Got it. I have clear it.
