### ISSUE TITLE
explain "even if it was setTimeout(.., 0)"

### ISSUE THREAD

**Issue by rolandkofler** [getify/You-Dont-Know-JS#808]
>This actually seems obvious on second glance. The timeout function callbacks are all running well after the completion of the loop. In fact, as timers go, even if it was setTimeout(.., 0) on each iteration, all those function callbacks would still run strictly after the completion of the loop, and thus print 6 each time.

Should be explained:
In actuality, setTimeout() re-queues the new JavaScript at the end of the execution queue....

**Comment by getify** [comment]
I don't think your explanation is either accurate (strange use of words) or more helpful than what's written.

**Comment by rolandkofler** [comment]
sorry I know 5 languages barely one of them is English. Most persons understand me perfectly, but you are in a grumpy mood.
