### ISSUE TITLE
On chapter 5 page 50. Example code don't show me nothing

### ISSUE THREAD

**Issue by jhorgint** [getify/You-Dont-Know-JS#809]
function foo() {
    var a = 2;
    function baz() {
        console.log( a ); // 2
    }
    bar( baz );
}
function bar(fn) {
    fn(); // look ma, I saw closure!
}

I don't know what is happening!!!, I have tried on JS Bin, jsfiddle and on Chrome .
Sorry, I'm new on JS and don't figure out what is happening

**Comment by getify** [comment]
The code snippet prints "2". The inner function `baz` closes over the variable `a` that is inside `foo`. That `baz` function reference is passed to the function `bar` which is a different scope. However, the `a` is still accessible by `baz` because of closure.

**Comment by jhorgint** [comment]
Thanks a lot, your argument is right but I don't get it run on my PC, I'm doing something wrong for sure.

**Comment by jhorgint** [comment]
Just need to call the "foo();" function, hahaha....

**Comment by getify** [comment]
Ah... sorry for the confusion.
