### ISSUE TITLE
why `onlyOne` should avoid NaN?

### ISSUE THREAD

**Issue by kangbin** [getify/You-Dont-Know-JS#815]
Hi, Kyle, in the 《types & grammar》"Implicitly: Booleans --> Numbers" section, i read this code

```javascript
function onlyOne() {
    var sum = 0;
    for (var i=0; i < arguments.length; i++) {
        // skip falsy values. same as treating
        // them as 0's, but avoids NaN's.
        if (arguments[i]) {
            sum += arguments[i];
        }
    }
    return sum == 1;
}
```

i don't understand why should avoids NaN's in the comment. Because i try to pass NaN to `onlyOne`, it still works.

Could you help me with this, thank you :)

**Comment by getify** [comment]
The if statement avoids trying to add a NaN into the sum, meaning if you pass them they are ignored/skipped over.

**Comment by kangbin** [comment]
thank you

**Comment by doubleOrt** [comment]
@getify  The wording is really vague and confusing, couldn't it just be "Skips falsy values" ? Why mention both if `NaN` is just one of JavaScript's falsy values.
