### ISSUE TITLE
Fibonacci iterator example

### ISSUE THREAD

**Issue by mahmoudfelfel** [getify/You-Dont-Know-JS#816]
Hi Kyle,
Thanks for the amazing book series.
I'm reading now the "ES6 and Beyond" part, it's amazingly detailed, but I have some questions about the Fibonacci iterator example in ch3:

```
var Fib = {
    [Symbol.iterator]() {
        var n1 = 1, n2 = 1;

        return {
            // make the iterator an iterable
            [Symbol.iterator]() { return this; },

            next() {
                var current = n2;
                n2 = n1;
                n1 = n1 + current;
                return { value: current, done: false };
            },

            return(v) {
                console.log(
                    "Fibonacci sequence abandoned."
                );
                return { value: v, done: true };
            }
        };
    }
};

for (var v of Fib) {
    console.log( v );

    if (v > 50) break;
}
```

Why we need another ```[Symbol.iterator]() ``` inside the first one, we just need ```next()``` to implement an iterator, and the wrapper ```[Symbol.iterator]() ``` is to create an iterable of our object so we can use it with ``` for .. of```.

Another question, isn't it better to stop the loop implicitly inside the implementation instead of ``` if(v>50) break; ```, we can do :

```
           next() {
                var current = n2;
                n2 = n1;
                n1 = n1 + current;
                console.log(current)
                if(current > 50) return this.return(current)
                return { value: current, done: false };
            },
```
So we can avoid the infinity loop, i mean in real life coding, if someone reuses this function, he might forget to add the ```break``` line which will break the code.

Thanks

**Comment by legodude17** [comment]
The `[Symbol.iterator](){ return this; }` is so that the iterator is also iterable. The reason he did `if(v<50)break;` in it is so the iterator can be used for different amounts.

**Comment by getify** [comment]
Yes, that's correct @legodude17. So that you can do:

```js
var it = Fib();

for (var v of it) {
   console.log(v);
   if (v > 50) break;
}
```

The iterator doesn't have its own limit baked into it, as that'd be entirely inappropriate. The consumer (the `for..of` loop) is the place someone should decide how many numbers they want.

**Comment by mahmoudfelfel** [comment]
Thanks @legodude17 @getify for your answers, but ```for .. of``` requires only ```Fib()``` to be an iterable, and we accomplished that with the first ```[Symbol.iterator](){ return .. } ``` so why we need the returned iterator to be an iterable as well, or it is just a good practice to make the iterator an iterable.
This is giving the same result :
```
var Fib = {
    [Symbol.iterator]() {
        var n1 = 1, n2 = 1;

        return {
            next() {
                var current = n2;
                n2 = n1;
                n1 = n1 + current;
                return { value: current, done: false };
            },

            return(v) {
                console.log(
                    "Fibonacci sequence abandoned."
                );
                return { value: v, done: true };
            }
        };
    }
};

for (var v of Fib) {
    console.log( v );

    if (v > 50) break;
}
```

**Comment by legodude17** [comment]
One way you could use it @mahmoudfelfel  is if you had an iterator that you partly wanted to go through and then go through the rest in a `for ... of` loop. Like this:
`var it = Fib[Symbol.iterator]()`
Then you could do:
`it.next() //{value: 1, done: false}`
And then:
`it.next()`
...
After:
```js
for (var v of it) {
    console.log(v);
    if (v > 100) break;
}
```

**Comment by getify** [comment]
Also if you want your iterator function to be able to accept arguments so you want to call it manually, then you want to `for..of` the iterator for that instance.
