### ISSUE TITLE
wront example in: Implicitly: * --> Boolean

### ISSUE THREAD

**Issue by kangbin** [getify/You-Dont-Know-JS#817]
in the types & grammar/ch4.md，section "Implicitly: * --> Boolean" has an example:

```javascript
var a = 42;
var b = "abc";
var c;
var d = null;

if ((a && d) || c) {
    console.log( "yep" );       // yep
}
```

the `(a && d) || c` should return `undefined` and coerce to `false`, which should not print `yep`.

**Comment by getify** [comment]
You've missed that right above that if statement, the c variable is set to "abc", which is truthy.
