### ISSUE TITLE
"up & going": Chapter 2: typeof of null

### ISSUE THREAD

**Issue by bekahsealey** [getify/You-Dont-Know-JS#822]
In the text, NULL is written "null" causing the typeof bug of "object". When NULL is written "NULL", it will properly set the value as NULL and give a ReferenceError NULL type. 

I discovered the difference between null and NULL while learning SQL.

**Comment by getify** [comment]
uhhh... what? `NULL` is not a valid keyword in javascript... the keyword is `null` (all lowercase). If you use `NULL`, that's just asking for a plain ol' normal variable called `NULL`, which I'm guessing you probably haven't defined, hence why you get the ReferenceError.

**Comment by bekahsealey** [comment]
Ahhh. Thank you for the response!

**Comment by getify** [comment]
Cheers!
