### ISSUE TITLE
Up & Going, ch 2, section "Objects" -- possible incorrect object code snippet

### ISSUE THREAD

**Issue by nmspackman** [getify/You-Dont-Know-JS#824]
I don't think obj[b] references var b. 
Also var b should produce "a" not "hello world" since it's not set as var b = obj["a"]

<img width="319" alt="screen shot 2016-07-30 at 8 30 16 am" src="https://cloud.githubusercontent.com/assets/11526734/17271086/03cb07e8-5630-11e6-8953-68f4a3150ed5.png">

**Comment by dtrthi** [comment]
You are correct that the `var b should produce "a" not "hello world"`. But the example was `obj[b]` not just `b`. 
The statement `obj[b]` is equal to `obj["a"]`!!
There's no magic here, it just replaces b by "a", and get the value at property/key "a".

You can see in this example
![image](https://cloud.githubusercontent.com/assets/5228649/17271998/4b0e139a-56b5-11e6-8780-08d64a2365d4.png)

how to get the same value with `dot notation` and `bracket notation`.
```
obj.a ~ obj["a"]
obj.b ~ obj["b"] // "b" is string literal
```
The author wants to show you that we can store the key "a" into a variable (variable b), then use that var to get the value at key "a" (by putting it into the brackets).
Maybe the example use the variable named `b` can cause the confusion with string literal "b".

Hope this help with my bad explanation.

**Comment by nmspackman** [comment]
Oh, I see. I totally missed that. Thanks for the explanation!
