### ISSUE TITLE
Is GitBook version up-to date ?

### ISSUE THREAD

**Issue by antimatter96** [getify/You-Dont-Know-JS#831]
https://www.gitbook.com/book/ydkjs/you-don-t-know-js/details

I feel that this was added without your consent.
Is their a way to get a PDF of the books ?

**Comment by bcallaars** [comment]
Yes, by buying them.

**Comment by getify** [comment]
It is not authorized. Thank you for the heads up. I've asked it be taken down.

O'Reilly sells the PDF format of the books, but that ebook is not available for free (except for the "Up & Going" book, which **is** free).

**Comment by antimatter96** [comment]
Cool.
I instead cloned the repo and then wrote a script to convert all the files
into PDF using markdown-pdf

On Aug 9, 2016 21:55, "Kyle Simpson" <notifications@github.com> wrote:

It is not authorized. Thank you for the heads up. I've asked it be taken
down.

O'Reilly sells the PDF format of the books, but that ebook is not available
for free (except for the "Up & Going" book, which *is* free).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/getify/You-Dont-Know-JS/issues/831#issuecomment-238607829>,
or mute the thread
