### ISSUE TITLE
Boolean coercion misleading

### ISSUE THREAD

**Issue by Activee** [getify/You-Dont-Know-JS#835]
Quote from the book type & grammar 

> Any of these ToBoolean coercions would happen implicitly without the Boolean(..) or !!, if used in a boolean context such as an if (..) .. statement.

I think that is misleading to the reader. Example 
```
var a = new Boolean(false);
if(a){
    console.log("coercion didn't happen");
} //coercion didn't happen, is the output in console because no coercion happened and object is thruty
```

I find as a reader it's not really that clear we are talking about primitive to primitive value here. I think including the example above could be beneficial (even though it was mentioned before).

**Comment by getify** [comment]
In the case of the `a` that is a `new Boolean(..)` object in your example, the `ToBoolean` coercion that's going to happen with the `if` statement is that objects are *always* truthy. That is in fact coercion. I'm confused by why you're trying to assert that it's no coercion.
