### ISSUE TITLE
Template Literals

### ISSUE THREAD

**Issue by rotexhawk** [getify/You-Dont-Know-JS#849]
Your example actually produces the following screenshot, which is a bit confusing for someone like me who doesn't know what raw is.  To get the actual array I had to do `console.log(strings['raw']);` 

```
function foo(strings, ...values) {    
console.log( strings );   
console.log( values );
}
var desc = "awesome";
foo`Everything is ${desc}!`;

// [ "Everything is ", "!"]// [ "awesome" ]
```

![screen shot 2016-09-02 at 2 17 56 pm](https://cloud.githubusercontent.com/assets/12015105/18213936/90836010-7118-11e6-97a1-f84a18acfe38.png)

**Comment by getify** [comment]
The text covers both `strings` and `strings.raw`... they're separate, and in the case where the original string had an escape sequence like `\n` in it. `raw` would have `\` and `n` as separate characters, whereas it'd just be the single new line character in the `strings` version. Both are the "actual" array.

**Comment by rotexhawk** [comment]
Thank you. It took me a while but  `foo`Everything is ${desc}!`;` is not the same as `foo('',`Everything is ${desc}!`);`.

**Comment by getify** [comment]
Right. The ` backtick is not calling the function in the traditional sense, it's letting the function process the separate parts of the template before finalization.
