### ISSUE TITLE
Links in the readme's "Table of content" incorrects

### ISSUE THREAD

**Issue by Tarabass** [getify/You-Dont-Know-JS#859]
Is it me or are the links in the readme incorrect?

To simulate:

1. Go to a book of the series
2. Scroll down to the readme of that serie
3. Click on a link in 'The table of content'

If you need any help fixing this just give me a shout :)

**Comment by getify** [comment]
This appears to be a bug or change in behavior from github. These links have always works.

**Comment by getify** [comment]
Looks like github fixed their bug. Links working fine now for me.
