### ISSUE TITLE
Free Online Reading book Link's are not working

### ISSUE THREAD

**Issue by husain100b** [getify/You-Dont-Know-JS#860]
When I click free online reading book link none of those link are working. It took me 404 page. Please check.

**Comment by getify** [comment]
What links are you talking about?

**Comment by getify** [comment]
This appears to be a bug or change in behavior from github. These links have always worked.

**Comment by husain100b** [comment]
I mean when I click any link from the book title
https://github.com/getify/You-Dont-Know-JS see the image below

it took me to 404 page. See this link
https://github.com/getify/scope%20&%20closures/README.md#you-dont-know-js-scope--closureas
and see the image below


​

**Comment by getify** [comment]
Looks like github fixed their bug. Links working fine now for me.

**Comment by husain100b** [comment]
Now it's okay. Thanks
