### ISSUE TITLE
Types & Grammar Ch 4 - Abstract Relational Comparison

### ISSUE THREAD

**Issue by MJGwater** [getify/You-Dont-Know-JS#863]
> it's important nonetheless to think about what happens with a < b comparisons... The algorithm first calls ToPrimitive coercion on both values, and if the return result of either call is not a string, then both values are coerced to number values using the ToNumber operation rules, and compared numerically.

>For example: **(Problem is with this example)**
```
var a = [ 42 ];
var b = [ "43" ];
a < b;  // true
b < a;  // false
```
However, if both values are strings for the < comparison, simple lexicographic (natural alphabetic) comparison on the characters is performed:
```
var a = [ "42" ];
var b = [ "043" ];
a < b;  // false
```
a and b are not coerced to numbers, because both of them end up as strings after the ToPrimitive coercion on the two arrays. So, "42" is compared character by character to "043", starting with the first characters "4" and "0", respectively. Since "0" is lexicographically less than than "4", the comparison returns false.
>

The wording implies, at least to me, that both values are coerced to numbers in the first example. However in actuality, a is coerced to "42" and b is coerced to "43" and those two values are compared. https://repl.it/D9qS/1 

```
var a = [42];
console.log(a.valueOf()); //[ 42 ]
console.log(a.toString()); //"42"
console.log(typeof a.toString()); //string

var b = ["43"];
console.log(b.valueOf()); //[ '43' ]
console.log(b.toString()); //"43"
console.log(typeof b.toString()); //string

console.log(a < b) //true
```
In case this helps, if you changed a from [42] to [10] and b from ["43"] to ["2"] then it'd say a < b is true. https://repl.it/D9r1 

As long as only strings and objects are compared via <, wouldn't 2 strings always be compared? (unless its the rare object w/o a toString method)

I think the best change to make would be to simply change [ 42 ] to 42 in the first example above so there is an example where both values are coerced to numbers.

**Comment by getify** [comment]
Known issue. #755.
