### ISSUE TITLE
Up & Going Chapter 1: small typo in Constants example code

### ISSUE THREAD

**Issue by jacklj** [getify/You-Dont-Know-JS#867]
In the code after "Here's a silly example:"

console.log( amount );              // 215.9784
console.log( amount.toFixed( 2 ) ); // "215.98"

One commented number have no speech marks, and the other does.

Sorry if this is a pointless issue.

**Comment by getify** [comment]
That's because the first one is a number and the second one is a string (the output of `toFixed(..)` is a string).

**Comment by jacklj** [comment]
Also in chapter 1, in the Loops section, in the second code example, after the line "Let's illustrate:", in the first comment in the code, it says:

// a `while..true` loop would run forever, right?

'while..true' uses the same notation that is established for 'do..while' loops - maybe confusing. Could be rewritten as 'while(true)'?

**Comment by jacklj** [comment]
In the Scope section, swapping these two sentences around would make for slightly more clarity? 

"In JavaScript, each function gets its own scope. Scope is basically a collection of variables as well as the rules for how those variables are accessed by name. "

Then in the following sentence, which says 'that function', it's clearer which function we are referring to, rather than perhaps implying that scope is a type of function.

**Comment by getify** [comment]
Closing since "Up & Going" was replaced with the new "Get Started" book for second edition, so this issue is no longer applicable.
