### ISSUE TITLE
Possible codeblock issue. YDKJS: Async & Performance>Ch1: Asynchrony: Now & Later

### ISSUE THREAD

**Issue by gunrugger** [getify/You-Dont-Know-JS#868]
https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch1.md

Right after the paragraph that starts with "Other examples where the compiler reordering could create observable side effects", there is the following code inside a codeblock:

```
function foo() {
    console.log( b );
    return 1;
}

var a, b, c;

// ES5.1 getter literal syntax
c = {
    get bar() {
        console.log( a );
        return 1;
    }
};

a = 10;
b = 30;

a += foo();             // 30
b += c.bar;             // 11

console.log( a + b );   // 42
```

I beleive lines 18 and 19 should be:
```
a += foo();             // 11
b += c.bar;             // 31
```

**Comment by getify** [comment]
those comments are the result of the console.log messages not the variables themselves.

**Comment by gunrugger** [comment]
Ah. I see. Thank you.
