### ISSUE TITLE
Hello, getify

### ISSUE THREAD

**Issue by aleen42** [getify/You-Dont-Know-JS#869]
Hi, getify,
      Since it's a book, why not publish it onto [Gitbook](https://www.gitbook.com)?

**Comment by nushydude** [comment]
@aleen42

The link is slightly wrong. It should be www.gitbook.com, not gitbook.com. Just saying.

**Comment by aleen42** [comment]
@nushydude Check it!!!!

**Comment by nushydude** [comment]
@aleen42 Works now.

**Comment by getify** [comment]
No, this book is not being distributed on gitbook, due to contract specifications with the publisher.

**Comment by ziolau** [comment]
I perfer the github markdown style, though
