### ISSUE TITLE
Up & Going: Clarification between coercion and casting

### ISSUE THREAD

**Issue by divyanshu013** [getify/You-Dont-Know-JS#870]
It might be very helpful for beginners if you could include a section clarifying how coercion is different from casting.

**Comment by venelinpetrov** [comment]
https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch4.md#converting-values

> Converting a value from one type to another is often called "type casting," when done explicitly, and "coercion" when done implicitly (forced by the rules of how a value is used).

**Comment by getify** [comment]
Yeah, that's a detail I cover in the more in-depth book but I leave out of the beginner/intro "up & going" book.

**Comment by divyanshu013** [comment]
@getify, quite often people have heard of the term 'casting' so perhaps a small paragraph about the difference would help clarify some doubts; just a suggestion.

**Comment by getify** [comment]
Thank you for the feedback. I'm not going to make any changes for now, but I'll keep an eye on this topic in general.

**Comment by divyanshu013** [comment]
Its alright @getify :smile:
