### ISSUE TITLE
scope & closures / ch4

### ISSUE THREAD

**Issue by dblboy** [getify/You-Dont-Know-JS#872]
Hello there
https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch4.md#functions-first

`foo(); // "b"

var a = true;
if (a) {
   function foo() { console.log( "a" ); }
}
else {
   function foo() { console.log( "b" ); }
}`

**Comment by viniciuskneves** [comment]
It will hoist both functions so the second one will override the first one when hoisted.

**Comment by venelinpetrov** [comment]
What's the question?

**Comment by getify** [comment]
This issue is already known.
