### ISSUE TITLE
Types and Grammer > Chapter 4 > Abstract Relational Comparison

### ISSUE THREAD

**Issue by naveed-fida** [getify/You-Dont-Know-JS#874]
Hello. I'd like to report an problem with the first example in this section:
```js
var a = [ 42 ];
var b = [ "43" ];
a < b;  // true
b < a;  // false
```
The paragraph just above this example says:
>The algorithm first calls `ToPrimitive` coercion on both values, and if the return result of either call is not a string, then both values are coerced to number values using the `ToNumber` operation rules, and compared numerically.

This seems to suggest that in this example, `[42]` is coerced to a number and as a result `b` is also coerced to a number and the two values are compared numerically. However I find that that's not the case. To prove that, if we change the value of `b` to `["043"]`, the comparisons would yield opposite results. That's because a `ToPrimitive` operation (or the [[DefaultValue]] internal method) on an array never results in a number (unless of course the array has a `valueOf` method defined that returns a number).

**Comment by getify** [comment]
https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=is%3Aissue%20abstract%20relational%20comparison%20
