### ISSUE TITLE
this & object prototypes: inheritance or polymorphism

### ISSUE THREAD

**Issue by zonzujiro** [getify/You-Dont-Know-JS#875]
I think maybe polymorphism part must be more specific? Because after reading it, I have impression that, author, mixed polymorphism and inheritance. But I'm not sure, maybe I only one who has such impression? So I created this issue.
> When classes are inherited, there is a way for the classes themselves (not the object instances created from them!) to relatively reference the class inherited from, and this relative reference is usually called super.
Conceptually, it would seem a child class Bar can access behavior in its parent class Foo using a relative polymorphic reference (aka, super). However, in reality, the child class is merely given a copy of the inherited behavior from its parent class. If the child "overrides" a method it inherits, both the original and overridden versions of the method are actually maintained, so that they are both accessible.
Don't let polymorphism confuse you into thinking a child class is linked to its parent class. A child class instead gets a copy of what it needs from the parent class. Class inheritance implies copies.

All quoted text, and especially this part:
>Class inheritance implies copies.

could be reason of unnecessary misunderstanding, because it's tells, that children always make copies of all methods of his ancestors. So, basically, number of drive() methods will be equal to number of classes, which was inherited from Vehicle class and it's wrong.
I meet this statement before and not only in this book, so I wan't clarify what I mean.
As example, in C++ methods stored in code segment, and not in class itself. In it's turn, class have links to it's methods. So when RedCar will be inherited from Vehicle, RedCar will not make copies of Vehicle's methods, RedCar will only copy Vehicle's addressees of methods and fields.
But if you override inherited method,  you will have another copy of parent-class method.
So class inheritance, by default, **not** implies copies. But in result of overriding of inherited method, we **will have** a copy.
Almost same thing with Java. And with Python either, which has dictionaries.

**Comment by getify** [comment]
My response to this issue is identical to this comment. I appreciate the feedback but I'm not going to make any changes along these lines.

https://github.com/getify/You-Dont-Know-JS/issues/877#issuecomment-252280802

**Comment by zonzujiro** [comment]
I totally understand your position, thank you for your response.

But can you explain, why you insist on copying in class inheritance? I'm asking not because I'm looking for mistakes, etc., but because I'm interested in understanding of this part of the book.
Thank you.
