### ISSUE TITLE
Async & Performance Ch 3 Promise Scheduling Quirks

### ISSUE THREAD

**Issue by MJGwater** [getify/You-Dont-Know-JS#876]
When I run this in Chrome it says B A, although it's A B in Safari and Firefox. I'm confused by the code so I'm not sure what's going on. Is this just a browser error?
```
var p3 = new Promise( function(resolve,reject){
    resolve( "B" );
} );

var p1 = new Promise( function(resolve,reject){
    resolve( p3 );
} );

var p2 = new Promise( function(resolve,reject){
    resolve( "A" );
} );

p1.then( function(v){
    console.log( v );
} );

p2.then( function(v){
    console.log( v );
} );

// A B  <-- not  B A  as you might expect
```

**Comment by getify** [comment]
Inter-promise scheduling is not controlled by the spec, but only implied. The fact that you see these differences is annoying, and I've tried in the past to argue that these semantics should have been clarified, but my concerns were ignored. Sorry.

**Comment by maximivanov** [comment]
Just stumbled upon this - getting different results for Chrome and FF. It would be really nice if there's a mention next to code snippet that behaviour is not controlled by spec.

**Comment by apieceofbart** [comment]
I think this at least needs a comment because it's confusing for a reader.

**Comment by getify** [comment]
Please see this section: https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md#promise-scheduling-quirks

Specifically, quoting:

> ...you should never rely on anything about the ordering/scheduling of callbacks across Promises. In fact, a good practice is not to code in such a way where the ordering of multiple callbacks matters at all. Avoid that if you can.

Is this coverage of inter-promise scheduling insufficient in a way that I can address?

**Comment by apieceofbart** [comment]
At first I was thinking about a comment in the code, e.g. "please note that as of writing this book this specific example did not work correctly in Chrome bla, bla.." but maybe the paragraph you qouted is enough - it's just that it comes after the code example, perhaps rephrase it and move above it?

It's just that I think we are used to things working in Chrome and I think all other examples work fine so it's surprising to see this one not.

great book btw, bought a paper copy last week!

**Comment by supperchong** [comment]
I run this in node it says B A too.

**Comment by shadowkimi520** [comment]
1. According to the latest V8 source code, when inner_promise is resolved,  the **resolve(inner_promsie)** statement will directly resolve the outer_promise. That is a optimization, but it violate the ECMAScript-spec.
2. If you open the devTool in chrome, the optimization will be closed.
3. NodeJS is engined by V8, so 'B A' too.
