### ISSUE TITLE
Part 3: this & Object Prototypes -> Chapter 3: Contents section

### ISSUE THREAD

**Issue by mzwae** [getify/You-Dont-Know-JS#878]
First of all, a big thank you for the books, they are amazing!

It's unclear to me how to use the object name as a key access. For example, if **multiple object names** are used as keys for accessing different properties, how is it possible to retrieve each one of them?

> In objects, property names are always strings. If you use any other value besides a string (primitive) as the property, it will first be converted to a string. This even includes numbers, which are commonly used as array indexes, so be careful not to confuse the use of numbers between objects and arrays.

    var myObject = { };
    var myObject2 = { };
    myObject[true] = "foo";
    myObject[3] = "bar";

    myObject[myObject] = "baz";
    myObject[myObject2] = "jaz";

    myObject["true"];               // "foo"
    myObject["3"];                  // "bar"
    myObject["[object Object]"];    // "baz"
    myObject[???????];  //"jaz"

**Comment by getify** [comment]
You should not try to use an object as a key in another regular object... as shown, the key of a regular object is always a string, so any object is stringified to `"[object Object]"`. It won't keep two separate objects as two separate keys.

If you want to use objects as keys of a hash, you need what's called a `Map(..)` (added in ES6). Bonus: use a `WeakMap` for better GC where if the object-used-as-a-key is eligible for GC, the key is removed from the `WeakMap` too.

I cover these in Chapter 5 of "ES6 & Beyond" title.

**Comment by mzwae** [comment]
Thank you very much for your quick response and your clear explanation :)
It all makes sense now!
