### ISSUE TITLE
Lookup of eval is different with webpack

### ISSUE THREAD

**Issue by bigbassroller** [getify/You-Dont-Know-JS#879]
On page 17 of the printed version of Scopes & Closures...

```
function foo(str, a) {
    eval( str ); // cheating!
    console.log(a, b);
}

var b = 2;

foo( "var b = 3;", 1); //1, 3
```

the webpack script returns `1 2` in the console, but if I run in the console:

```
function foo(str, a) {
    eval( str ); // cheating!
    console.log(a, b);
}

var b = 2;

foo( "var b = 3;", 1); //1, 3
```

it returns  `1 3` 

What is up with that?

**Comment by getify** [comment]
most likely the presence/absence of strict mode.

**Comment by Ryalian** [comment]
It's not about webpack or anything. Console seems to compile line by
line.(or by block). That's why it's not go to try complicated function in
console.

Bests,

Qijun Chen
