### ISSUE TITLE
Part 3: this & Object Prototypes -> Appendix A: ES6 class -> Class Gotchas

### ISSUE THREAD

**Issue by mzwae** [getify/You-Dont-Know-JS#880]
In the **Class Gotchas Section**, when I run the code below, I get the following error message:
"Uncaught SyntaxError: **'super' keyword unexpected here**"

Why is "super"  _not_ expected here?
 
    class P {
    foo() { console.log( "P.foo" ); }
    }

    class C extends P {
    foo() {
        super();
    }
    }

    var c1 = new C();
    c1.foo(); // "P.foo"

    var D = {
    foo: function() { console.log( "D.foo" ); }
    };

    var E = {
    foo: C.prototype.foo
    };

    // Link E to D for delegation
    Object.setPrototypeOf( E, D );

    E.foo(); // "P.foo"

**Comment by zonzujiro** [comment]
It's because 'super' - is not a function, but a keyword. 
In this particular case 'super' is used for calling method 'foo' of class P, so it must be super.foo();

You can also call method of object in prototype like this: `P.prototype.foo.call(this);`, but 'super' more beautiful way to do this.

**Comment by getify** [comment]
`super()` is only valid in subclass constructors. in methods, must be `super.methodName()`.

**Comment by mzwae** [comment]
Thank you for your reply.
Is the code below the correct way to use **super** keyword in the book example?

     class C extends P {
     foo() {
     super.foo();
     }
     }

**Comment by getify** [comment]
looks ok
