### ISSUE TITLE
add a toc/index?

### ISSUE THREAD

**Issue by turtleDev** [getify/You-Dont-Know-JS#890]
It takes way to long to find something that you need to refer by manually weeding through text. It would be nice if there was a hyperlinked toc at the start of each chapter.

**Comment by getify** [comment]
This repo serves primarily to feed content to O'Reilly for publication. I avoid putting in extra things that they'd have to manually remove that make publishing harder. I appreciate the difficulty of reading without xref links, but frankly, the purpose of the repo is not to optimize online reading. If you're looking for a nicer reading experience, consider checking out the ebooks or printed books.

**Comment by turtleDev** [comment]
fair enough.
