### ISSUE TITLE
Is the open parts of book welcome translate to other language like chinese?

### ISSUE THREAD

**Issue by yuanyan** [getify/You-Dont-Know-JS#9]

**Comment by ceoaliongroo** [comment]
Hi @getify, for me the idea is not clear.

You want and could do access to this github repository, to do the translation?

**Comment by getify** [comment]
If you want to do a foreign language translation for free, do so by forking this repo, making all your changes publicly to that repo, then making a PR back here to this repo.

**Comment by ceoaliongroo** [comment]
Great! thanks for the answer.

**Comment by kosson** [comment]
@dandv Sometimes there are facets very difficult cu comprehend, and the best thing to have at hand is some documentation in your own language. That is establishing a context for a quicker apprehension of some red hearing topics. I was bit by the bug of translating YDKJS in our own language... still contemplating.

**Comment by dandv** [comment]
Salut Nicule,

What facets if I may ask? This is software development, not German
philosophy with untranslatable words. The keywords are in English. Most
docs are in English. By translating into other languages, you're not only
wasting your time but depriving others of good motivation to learn English.

**Comment by kosson** [comment]
Salut,
I refer to facets to the many aspects a particular topic would present to the one learning the language. I agree with the full involvement with the learning materials in English, but on the other hand I have some experience with those people who would find it faster if a tough to crack concept would be presented in their own language. I have some experience with evangelizing Open Educational Resources in Romania, and this particular supplementary aid was raised many times. This is the reason I've started the following repo: [JavaScript, învăț eu, înveți și tu](https://github.com/kosson/javascript-invat-eu-inveti-si-tu)

**Comment by hectorip** [comment]
> Salut Nicule,
> 
> What facets if I may ask? This is software development, not German
> philosophy with untranslatable words. The keywords are in English. Most
> docs are in English. By translating into other languages, you're not only
> wasting your time but depriving others of good motivation to learn English.
> 
> On Sat, Jan 30, 2016, 08:26 Nicolaie Constantinescu <
> [notifications@github.com](mailto:notifications@github.com)> wrote:
> 
> > @dandv https://github.com/dandv Sometimes there are facets very
> > difficult cu comprehend, and the best thing to have at hand is some
> > documentation in your own language. That is establishing a context for a
> > quicker apprehension of some red hearing topics. I was bit by the bug of
> > translating YDKJS in our own language... still contemplating.
> > —
> > Reply to this email directly or view it on GitHub
> > [#9 (comment)](https://github.com/getify/You-Dont-Know-JS/issues/9#issuecomment-177228241)
> > .

That is a very short-sighted point of view. I agree that every decent developer should learn an even code in English, but sometimes, there are developers that are struggling enough to learn the basics of something like JS (and don't know English) to add more to their burden, forcing them to study a language they don't know at the same time they are trying to study and learn a programming language.

**Comment by dandv** [comment]
Perhaps they should focus on learning one thing at a time.
