### ISSUE TITLE
Chinese translation is complete.

### ISSUE THREAD

**Issue by JoeHetfield** [getify/You-Dont-Know-JS#900]
Hi, Kyle. By effort about a whole one year, my Chinese translation of your repo will complete soon. 

This is my repo: [https://github.com/JoeHetfield/You-Dont-Know-JS](https://github.com/JoeHetfield/You-Dont-Know-JS)

It's a Chinese mirror of your repo, translated every word you written. And I've followed every change to catch you up. 

How may I contribute to your repo with this translation? Is there anything I can help further?

Please tell me what you think, comment here or email me. and looking forward to the 2nd edition.

**Comment by getify** [comment]
Fantastic! That's an incredible amount of work! :)

Can you tell me what the appropriate ISO language code would be from this list?

http://www.lingoes.net/en/translator/langcode.htm

**Comment by welladamm** [comment]
@getify It should be `zh-CN`.

**Comment by getify** [comment]
OK, created a branch for you:

https://github.com/getify/You-Dont-Know-JS/tree/1ed-zh-CN

Can you submit a PR to this branch with your changes?

**Comment by JoeHetfield** [comment]
Of course! Just one second!

**Comment by JoeHetfield** [comment]
PR submitted ;)

**Comment by solidtext** [comment]
Hey guys, to save your works you may consider to use my professional Chinese translation service at: http://www.actranslation.com/mandarin/mandarin-translation.htm
