### ISSUE TITLE
"this & object prototypes": cover shadowing properties

### ISSUE THREAD

**Issue by getify** [getify/You-Dont-Know-JS#91]
Cover: 
1. Setting a shadowed property:
   
   ``` js
   var o = { a: 2 };
   var f = Object.create( o );
   f.a; // 2 -- accessed via delegation from `f` to `o`
   f.a = 5;
   f.a; // 5 -- created a shadowed property on `f`!
   o.a; // 2 -- still intact
   ```
2. Strangely, shadowing cannot be done in the case of a property having been marked as `writable:false`:
   
   ``` js
   var o = { };
   Object.defineProperty( o, "a", { value:2, writable:false } );
   var f = Object.create( o );
   f.a; // 2 -- accessed via delegation from `f` to `o`
   f.a = 5;
   f.a; // 2 -- wtf!? didn't let us create a shadowed property on `f`?
   o.a; // 2 -- still intact
   ```
3. Also strangely, a getter/setter prevents shadowing too:
   
   ``` js
   var o = { };
   Object.defineProperty( o, "a", { set: function(){}, get: function(){ return 2; } } );
   var f = Object.create( o );
   f.a; // 2 -- accessed via delegation from `f` to `o`
   f.a = 5;
   f.a; // 2 -- wtf!? didn't let us create a shadowed property on `f`?
   o.a; // 2 -- still intact
   ```

To be clear, in cases 2) and 3) above, the `[[Set]]` algorithm consults the descriptor of the `o.a` property and actually uses the `o.a` to attempt the `= 5` assignment, which fails for 2) and has no effect for 3). In neither of those cases does shadowed `f.a` get created.

But in case 1) above, the descriptor for `o.a` isn't special, so `o.a` isn't used at all, and `f.a = 5` creates shadowed `f.a`.

This WTF inconsistency between 1) and 2)/3) here is what's at issue to me.

**Comment by tsu-complete** [comment]
I suppose I'm pretty late to this conversation but if you haven't already seen this, I have found a way to shadow getters.

https://gist.github.com/tsu-complete/674363fa45aac492595d

(It's in coffee, if you need js you can paste it into http://coffeescript.org/ under the "Try Coffeescript" button)

**Comment by kingofwhales** [comment]
```
var o = { };
Object.defineProperty( o, "a", { set: function(){}, get: function(){ return 2; } } );
var f = Object.create( o );
f.a; // 2 -- accessed via delegation from `f` to `o`
f.a = 5;
f.a; // 2 -- wtf!? didn't let us create a shadowed property on `f`?
o.a; // 2 -- still intact

```
Is case 3 actually a result of shadowing? The getter is returning a fixed value of 2, in which case we won't know if the 2 is from f or o?  I have tried the following case with a different setter and getter. The result is that I am able to create a shadowed property on f. 

```
let parentObject = {}
Object.defineProperty(parentObject,"a",{set:function(value){this._a_ = value},get:function(){return this._a_ * 2}})
let childObject = Object.create(parentObject)
parentObject.a = 100
parentObject.a   // output 200
childObject.a = 200
childObject.a   // output 400
parentObject.a // still output 200
```

**Comment by getify** [comment]
The shadowed property you've created is `_a_`, but `a` is still not shadowed, there's only one of them (on `o`). In other words, making it *look* like shadowing doesn't mean it actually *is* shadowing.

**Comment by benawhite** [comment]
What I don't understand is, why is **writable** enforced on **f**, but **configurable** is not.
```
var o = {};
Object.defineProperty(o, 'a', {value: 2, writable: false, configurable: false});
var f = Object.create(o);
f.a; // 2 -- accessed via delegation from 'f' to 'o'
f.a = 5;
f.a; // 2 -- writable enforced from 'o'
Object.defineProperty(f, 'a', {value: 5, writable: false, configurable: false});
f.a; // 5 -- configurable not enforced from 'o'
```

**Comment by getify** [comment]
Probably because they were guarding against the potential accidental case of 'f.a = 5' but if you use 'defineProperty(..)' it's not likely an accident.
