### ISSUE TITLE
Enable Project Pages?

### ISSUE THREAD

**Issue by kennyjacob** [getify/You-Dont-Know-JS#917]
Hey, I think setting up project pages would make this repo into a nice website with almost no clutter.

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by deltaidea** [comment]
This is not a code repo for a website. This is a book. It's in Markdown, and GitHub displays that just fine, so I don't see the point.

**Comment by BenGitsCode** [comment]
I think I see where @kennyjacob  is coming from, separating the work in progress (managed in projects) from the most updated version of the book—but I always got the sense that having the whole thing always be an open sourced work in progress is more in line with Kyles vision for it.

I'm with you ☝️ but just playing Devil's advocate. As someone that uses github projects at work, it does some things well but is just lacking enough that I can't strongly recommend it for much.

**Comment by getify** [comment]
Yeah, I'm not sure I see the benefits. At first glance, it just looks like more process to manage. What am I missing in terms of benefit?

There's no distinction between "work in progress" and "most updated version", these are one in the same. When there is a second edition, the first edition and second edition will be moved into separate branches, and master will simply have a placeholder README to point to each.

**Comment by kennyjacob** [comment]
I meant something like https://kennyjacob.github.io/You-Dont-Know-JS/ where
the github pages just renders the markdown without github's UI around it.
(The links aren't being translated correctly though.)

**Comment by kennyjacob** [comment]
On further inspection I don't think that might be an easy switch, even if you wanted to just enable gh pages.

I'm sorry about wasting your time folks!

Is there a pdf version that's available for offline use? Thanks. :+1:

**Comment by getify** [comment]
The PDF version of the book is the ebook, but it's for sale (through normal booksellers, O'Reilly, etc). My license with O'Reilly only includes "digital distribution" in markdown format here on GH. Every other digital form is in their purview.

**Comment by BenGitsCode** [comment]
@kennyjacob I've gotten used to reading this on github, and this is quite tedious, but in the past for this and other resources I've occasionally used [dillinger.io](http://dillinger.io/) to get a pdf I can easily (mostly) export into ibooks.
```md
1. Get the markdown for each chapter by choosing 'View Raw' on github (this is the tedious part
2. Paste said raw markdown into dillinger
3. export as pdf
```
If you really want to get pdfs from markdown, that works well, but it's so !DRY that I've gone back to just reading markdown 👍 If you really want to have the pdfs and easier, I recommend just buying them for the convenience and creator support. 

@getify please delete this if I'm encouraging something awful/illegal.

**Comment by getify** [comment]
These tools are fine for your own personal use, but please do not distribute the PDFs to anyone else.
