### ISSUE TITLE
"types & grammar": Page 94, code error. 

### ISSUE THREAD

**Issue by Mozar10** [getify/You-Dont-Know-JS#918]
I am just wondering whether there has been a mistake on page 94 of Types and Grammar. The code should not (and does not print "yep" to the console). Check it out:

var a = 42; 
var b = "abc";
var c; 
var d = null;

if ((a && d) || c) {
    console.log( "yep" );       // yep 
   }

**Comment by getify** [comment]
That's not the whole code snippet.
