### ISSUE TITLE
Hoisting of let

### ISSUE THREAD

**Issue by tompazourek** [getify/You-Dont-Know-JS#92]
I read your book and I have to say it is one of the best programming language books I have ever read. I don't know JavaScript well, but use a lot of other programming languages and this is exactly the information I am looking for, the inside detailed information on how is it working internally.

I have one issue regarding the _scope & closure_ part, which is information on hoisting of _let_ declarations in ES6. So far, the book tries to be up-to-date with the latest ES6 concepts, but it is still lacking the explanation of how the _let_ declarations hoist in the block scope. I personally find it a bit incomplete without this, I think it would help to mention how it works.

What do you think?

**Comment by jinbeomhong** [comment]
For record, see his recent answer from here https://github.com/getify/You-Dont-Know-JS/issues/767
