### ISSUE TITLE
this & object prototypes Appendix A: ES6 class

### ISSUE THREAD

**Issue by kingofwhales** [getify/You-Dont-Know-JS#923]
When I tested the example code, super and toMethod don't seem to be working. 

1. 

The example returns with this error: 
`Uncaught SyntaxError: 'super' keyword unexpected here`

```javascript
class P {
    foo() { console.log( "P.foo" ); }
}

class C extends P {
    foo() {
        super();
    }
}
```
Shouldn't it be super.foo() here? 

```javascript
class C extends P {
    foo() {
        super.foo();
    }
}
```

2. toMethod no longer working.
```javascript

E.foo = C.prototype.foo.toMethod( E, "foo" );

E.foo(); // "D.foo"

// Uncaught TypeError: C.prototype.foo.toMethod is not a function
```

toMethod doesn't seem to be a function any more.  As mentioned here [stackoverflow](http://stackoverflow.com/questions/27511704/what-does-function-prototype-tomethod-do) by Bergi

>  the toMethod method was experimental only and did not make it into the standard. The home object is essentially static now, the only way to manipulate super is to change the [[prototype]]:

**Comment by getify** [comment]
This is already a known issue. Check the open "second edition" issues.
