### ISSUE TITLE
Async & Performance: ch. 3 confusing example result in Promise Scheduling Quirks

### ISSUE THREAD

**Issue by kapral18** [getify/You-Dont-Know-JS#924]
Example [here](https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md#promise-scheduling-quirks) says 
```javascript
var p3 = new Promise( function(resolve,reject){
    resolve( "B" );
} );

var p1 = new Promise( function(resolve,reject){
    resolve( p3 );
} );

var p2 = new Promise( function(resolve,reject){
    resolve( "A" );
} );

p1.then( function(v){
    console.log( v );
} );

p2.then( function(v){
    console.log( v );
} );

// A B  <-- not  B A  as you might expect
```

But testing shows:
In Node.js 7.2.0 => `BA`
in Chrome 55 => `BA`
in Firefox 50 => `AB`
in Safari 10 => `AB`

So maybe it's better to point out in the example result that it is a platform dependent result, not exactly `A B` ?

**Comment by getify** [comment]
This is a known issue in that environments are not constrained to do a predictable thing here.
