### ISSUE TITLE
Scope & Closures / Chapter 3: Function vs. Block Scope / let Loops

### ISSUE THREAD

**Issue by tupacko** [getify/You-Dont-Know-JS#926]
The first two examples given in the [let Loops](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch3.md#let-loops) section of the Function vs. Block Scope chapter are not interchangeable. They have utterly different behavior. Interesting enough (of course, with logical explanation), combined with closures like wrapping the `console.log` in a `SetTimeout` would render the two behave the same.

The first example is:
```
for (let i=0; i<10; i++) {
    console.log( i );
}

console.log( i ); // ReferenceError
```

The second example is:
```
{
    let j;
    for (j=0; j<10; j++) {
        let i = j; // re-bound for each iteration!
        console.log( i );
    }
}
```

Nevertheless, it does not tell they _are_ interchangeable. It's just an assumption because of the title of the second code block: _Here's another way of illustrating the per-iteration binding behavior that occurs_.

To see the difference of what really is executed, just switch to `console.log( i++ );`, adding `++`. The first loop will output all even numbers, the second one will output *all* numbers, both even and odd.

Actually, it is contrary to the statement right above it: _making sure to re-assign it the value from the end of the previous loop iteration_. For the example to be what the sentence states, there should be an additional line of code after `console.log( i );`:
```
j = i;
```

It might be only me interpreting it incorrectly. If you consider please make a more explicit statement of what actually happens/change the example and close the issue.

PS: you provide great resources, thank you!

**Comment by legodude17** [comment]
Thank you for pointing that out, I didn't find them very misleading, but I agree that someone might. Maybe if @getify agrees with you you can submit a PR.

**Comment by getify** [comment]
I didn't intend for these to be taken as literally in all possible ways equivalent. I'm saying they are the same **only with respect to the topic at hand**, which is the block scoping of a variable *per iteration*. Thanks for the discussion, though.
