### ISSUE TITLE
this & Object Prototypes: Chapter 1: Its Scope

### ISSUE THREAD

**Issue by xgirma** [getify/You-Dont-Know-JS#932]
Running the below example code snippet 
```js
function foo() {
    var a = 2;
    this.bar();
}

function bar() {
    console.log( this.a );
}

foo(); //undefined
````
did not give me `undefined`. Instead I get the bellow result 

```js
function foo() {
    var a = 2;
    this.bar(); // Error: TypeError: this.bar is not a function
}

function bar() {
    console.log( this.a );
}

foo();
````
if this is a valid observation, you may consider revising the following content. 

> Firstly, an attempt is made to reference the bar() function via this.bar(). It is almost certainly an accident that it works, but we'll explain the how of that shortly.

**Comment by dfparker2002** [comment]
On Chrome@Ubuntu the script above results in "undefined"

**Comment by getify** [comment]
The only way to definitely test this correctly (and get valid results) is to run the code in an actual JS file hosted in a webpage in a browser. Running it in console, or in some online coding tool like jsbin, or even in node, will produce different results, as these are all synthetic JS envs and don't behave strictly according to the core JS environment.

**Comment by legodude17** [comment]
@getify there is no core JS environment, it is the same language everywhere, the difference would be if it has strict mode enabled by default, right?

**Comment by getify** [comment]
There is absolutely a difference between a real JS program (as run in a file loaded in a browser) and the environment that exists in your developer tools console, or in jsbin, or even in node. Each one of those creates an artificial layer on top of the core JS, and that layer changes expectations. This has nothing to do with strict mode.

For example, in node, every file (not just your modules) is wrapped in a sort of IIFE like wrapper, before execution. So when you run a top-level `var x = 2`, you think you're creating an `x` in the global scope, but you're not. In the devtools console, they wrap your code in a `with`, and some even use `eval(..)` on it. These layers are just not the same as what you get when your code legitimately runs as a real browser program. There's no way around that, it's fact.

**Comment by legodude17** [comment]
I agree with you that there are differences, but JS is a scripting language, it can be run in many different places. I would say that the browser is no more of "the core JS environment" than NodeJS, because the spec doesn't define things like `document` or `window`. I can see the argument you are making that node does wrap your code if a IIFE, and that could change the result of some programs, but I disagree with the fact that the browser is the only place to run "true JS".

Back to the issue at hand, when I enter the code in the snippet at the top into the browser console, it gives me undefined. @xgirma can you give me more information?

**Comment by xgirma** [comment]
I was using Node to test the code snippet. Now I can see, entering same snippet in browser console gives undefined. I think my original question is answered.

**Comment by getify** [comment]
Glad we cleared up the confusion. Cheers!
