### ISSUE TITLE
Types & Grammar chapter 4: Coercion

### ISSUE THREAD

**Issue by ChainsOfPower** [getify/You-Dont-Know-JS#938]
In Abstract Relational Comparison there is given an example (the first example) of comparison where is supposed that one of the operands is not of string type when coerced via ToPrimitive. However in example there are two arrays, which both result in string value when coerced via ToPrimitive.

**Comment by getify** [comment]
Thanks, but known issue: https://github.com/getify/You-Dont-Know-JS/pull/755
