### ISSUE TITLE
You Don't Know JS: this & Object Prototypes - "writeable:false" is confusing

### ISSUE THREAD

**Issue by oriprice** [getify/You-Dont-Know-JS#939]
Under **Setting & Shadowing Properties**:
i think "**and it's not marked as read-only (`writable:false`)**" in first section should be changed to **(`writable:true`)**. its a bit confusing when next section is talking about the opposite state (**read-only**) with the same value of **(`writable:false`)**.

should i open a PR?

Reference:
1. If a normal data accessor (see Chapter 3) property named `foo` is found anywhere higher on the `[[Prototype]]` chain, **and it's not marked as read-only (`writable:false`)** ...
2. If a `foo` is found higher on the `[[Prototype]]` chain, but it's marked as **read-only (`writable:false`)**, ....

**Comment by getify** [comment]
Known issue.
