### ISSUE TITLE
this & Obj Prototypes, Ch 3, Types: 'complex primitives' is an unnecessary term

### ISSUE THREAD

**Issue by brianbishop** [getify/You-Dont-Know-JS#945]
In Ch3, Types https://github.com/getify/You-Dont-Know-JS/blob/master/this%20&%20object%20prototypes/ch3.md#type

> By contrast, there are a few special object sub-types, which we can refer to as complex primitives.

The term _'complex primitives_' is not used again after it's definition here. It's probably not necessary and it's a confusing term given that it's used to describe Array for example, which in the next section is described as a built-in object and a built-in function

**Comment by getify** [comment]
Thanks for the suggestion. I may tweak wording at some point.
