### ISSUE TITLE
You-Dont-Know-JS/this & object prototypes/apA.md, Uncaught SyntaxError: 'super' keyword unexpected here

### ISSUE THREAD

**Issue by Joeycz** [getify/You-Dont-Know-JS#947]
I think there is some incorrect in snippet

render($where) {
        super( $where );
        this.$elem.click( this.onClick.bind( this ) );
    }

supper($where) maybe should not be there.

**Comment by getify** [comment]
spec syntax changed after publication. it should now be 'super.render($where)'.

**Comment by Joeycz** [comment]
yeah, I fetched the latest one is 'super.render($where)', tahnks
