### ISSUE TITLE
'this & Object Prototypes', Ch4 - Parasitic Inheritance - new operator on constructor function

### ISSUE THREAD

**Issue by brianbishop** [getify/You-Dont-Know-JS#950]
Minor issue: possibly replace `var myCar = new Car();` with `var myCar = Car();`

In the example of [parasitic inheritance](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20&%20object%20prototypes/ch4.md#parasitic-inheritance), the Car, which inherites in this case from Vehicle constructor, is instantiated using the `new` operator on the `Car` constructor function:

`var myCar = new Car();`

Maybe it's to get around the lint warnings, but using `new` in this case does not make sense as the `Car` constructor returns an object, which means the 'behind the scenes' functionality of the `new` operator is disregarded. The `myCar` object should be created uing a function invocation, as it does the exact same thing, but there is less chance of confusion e.g. if `Car.prototype.stop` was added you would expect `new Car()` to have this function also but it wouldn't

`var myCar = Car();`

**Comment by getify** [comment]
This exact situation is covered immediately after the example in this note:

    Note: when we call new Car(), a new object is created and referenced by Cars this reference
    (see Chapter 2). But since we don't use that object, and instead return our own car object, the
    initially created object is just discarded. So, Car() could be called without the new keyword,
    and the functionality above would be identical, but without the wasted object creation/garbage-
    collection.

**Comment by brianbishop** [comment]
Ah, I see that now. I have the printed version, didn't spot that note on the next page. Thanks. I'll close this.
