### ISSUE TITLE
4 types & grammar ch5 Operator Precedence example bug

### ISSUE THREAD

**Issue by spacegoing** [getify/You-Dont-Know-JS#955]
> Now, recall this example from above:
> ``` javascript
> if (str && (matches = str.match( /[aeiou]/g ))) { // ..
> }
> ```
> We said the ( ) around the assignment is required, but why? Because && has higher precedence than =, so without the ( ) to force the binding, the expression would instead be treated as (str && matches) = str.match... But this would be an error, because the result of (str && matches) isn't going to be a variable, but instead a value (~in this case undefined~), and so it can't be the left-hand side of an = assignment!

In this case, it could be `''` if `str=''`.

**Comment by DRL9** [comment]
Sorry, I don't know what's  your point!
```js
function vowels(str) {
	var matches;

	// pull out all the vowels
	if (str && (matches = str.match( /[aeiou]/g ))) {
		return matches;
	}
}
```
If `str=''`, `vowels` will reutrn `undefined`.

**Comment by getify** [comment]
Eh. Not a particularly relevant case to clutter the text with.
