### ISSUE TITLE
Up and Going: Chapter 1, Practice question

### ISSUE THREAD

**Issue by jpmehta1990** [getify/You-Dont-Know-JS#958]
Hey Kyle,

I first of all would like to thank you for providing this store of knowledge for any human who has an internet connection and a device to access websites. I have really enjoyed reading the books.

The issue is that in the Practice question in Chapter 1 of Up and Going, you say "You will keep purchasing phones (hint: loop!) until you run out of money in your bank account.". If that is what must be done, what is the use of having a spending threshold? One wouldn't spend more than what (s)he has pre-decided on, right? Would putting it along the lines of "Keep buying phones and an accessory for each phone bought so long as you are below the spending threshold." be more appropriate?

Thanks,
Jay.

**Comment by juan-sierra** [comment]
Hi @jpmehta1990 I was having trouble grasping the logic because of that same issue. Thank you for opening this up. I'll write my solution with the logic of keep buying phones as long as it is below the spending threshold.

Thank you Kyle for making these learning resources open!

Cheers!
Juan

**Comment by getify** [comment]
Thanks, but this is a known issue: https://github.com/getify/You-Dont-Know-JS/issues/456

**Comment by jpmehta1990** [comment]
Oh ok @getify . I looked for it using certain keywords and dint find it, hence raised a new issue. Thanks.
