### ISSUE TITLE
"scope & closures"  apB,   need to be update

### ISSUE THREAD

**Issue by WynterDing** [getify/You-Dont-Know-JS#959]
actually, using babel or traceur compile this code 

```js
{
  let a = 2;
  console.log(a);
}
console.log(a);
```
will get 

```js
{
  var _a = 2;
  console.log(_a);
}
  console.log(a);
```
rather than the `try...catch` one.

I think some  supplementary notes should be added .😄 😄 😄

**Comment by getify** [comment]
Known issue for second edition.
