### ISSUE TITLE
You Don't Know JS: Up & Going, Chapter 2: Into JavaScript, 

### ISSUE THREAD

**Issue by suchendra** [getify/You-Dont-Know-JS#962]
> **The return value from the typeof operator is always one of six (seven as of ES6! - the "symbol" type) string values.**

 , What about the typeof(user defined function)? It does return as function. So it should be seven(or eight including symbol)!. I'm new to JavaScript, Correct me If I'm wrong. But when tried in Chrome console typeof  for user defined function returned as function.
![capture](https://cloud.githubusercontent.com/assets/16555061/22962593/c3e1720c-f373-11e6-8753-f6d03caac032.PNG)

**Comment by getify** [comment]
The following are the only return values for `typeof`:

* "undefined"
* "number"
* "string"
* "boolean"
* "object"
* "function"
* "symbol"

There's 7 of them. Technically, `"null"` *should* be the 8th one, but it's a long-known bug that `typeof null` is actually `"object"`.

**Comment by suchendra** [comment]
"function" is not updated in the page!!

**Comment by razouck** [comment]
I think it would be a good idea to remove “is always” from the sentence, or even rephrase it. The book is literally lying to us.
