### ISSUE TITLE
You Don't Know JS: Up & Going  Chapter 2: Into JavaScript, Built-In type Methods Section

### ISSUE THREAD

**Issue by suchendra** [getify/You-Dont-Know-JS#963]
> **When you use a primitive value like "hello world" as an object by referencing a property or method (e.g., a.toUpperCase() in the previous snippet)**

Here giving example of using "hello world" would be good and not confusing!. 

like **"hello world".toUpperCase()**

**Comment by razouck** [comment]
It is not that confusing.

**Comment by getify** [comment]
I wouldn't want to set the precedent of using the value on the literal value. It'd better be:

```js
var val = "hello world";
val.toUpperCase();  // "HELLO WORLD"
```

But that doesn't inline well, and doesn't add much to the discussion I don't think. Thanks for the suggestion!
