### ISSUE TITLE
Translate the book into Spanish

### ISSUE THREAD

**Issue by casanovavitae** [getify/You-Dont-Know-JS#964]
I have many friends and colleagues who have been interested in the book but have no knowledge of  English language. So, I was thinking It would be a good idea to translate the book into Spanish.  Just  Give me the green light and i will start with up & going.

**Comment by getify** [comment]
Please check these threads for more information. :)

https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=label%3A%22foreign%20language%20translations%22

**Comment by EstebanMarin** [comment]
There is an active repo that is doing the translation, came out of this thread

https://github.com/getify/You-Dont-Know-JS/pull/1378
