### ISSUE TITLE
What's wrong with the example in Getter & Setter section in this & Object part?

### ISSUE THREAD

**Issue by Kishan08** [getify/You-Dont-Know-JS#967]
Currently i'm reading part 3(this & object) of YDKJS series.

Head to Chapter 3. Object, now navigate to section **Getter & Setter**, there's this code which is throwing:
_RangeError: Maximum call stack size exceeded_ this error and if i remove the preceding and succeeding underscore from the code. Here's the screenshot for the reference:

![er](https://cloud.githubusercontent.com/assets/9252295/23201200/85cbf72c-f8fe-11e6-97b8-6625b77b88b3.PNG)

And this is your code along with underscore:

![no-er](https://cloud.githubusercontent.com/assets/9252295/23201223/a08fd20e-f8fe-11e6-9282-6c60f95509d9.PNG)

Which is running perfectly.

But you only mentioned that the underscore has no special meaning.

Then what's wrong with the code if i remove the underscore and why it's throwing RangeError??

**Comment by CezaryDanielNowak** [comment]
In the first example both: getter and setter are calling itself in infinite loop.
That's why getters/setters name should be different to acctual variable.

**Comment by Kishan08** [comment]
I can't understand what you are trying to say.
Can you please elaborate?

**Comment by pankajpatel** [comment]
```javascipt
get a(){
  return this.a
}
```

Here is above code a is both a property, and a method as a getter. When `this.a` is called, it will redirect to `this.a()` which will again request `this.a` in the return statement.

And with later example, the _ (underscore) differentiate the property and the getter name, and hence avoids the infinite loop.

**Comment by Kishan08** [comment]
Thanks for the suggestion.
