### ISSUE TITLE
this & object prototypes Chapter 4: Potential inaccuracy on the concept of "data structures"?

### ISSUE THREAD

**Issue by x-ji** [getify/You-Dont-Know-JS#970]
At the beginning of Chapter 4 of *this & object prototypes*, you have 

> OO or class oriented programming stresses that data intrinsically has associated behavior (of course, different depending on the type and nature of the data!) that operates on it, so proper design is to package up (aka, encapsulate) the data and the behavior together. **This is sometimes called "data structures" in formal computer science.**

It seems to me that "data structures" should not be in any way related to OOP... It just describes the data itself and shouldn't entail the "operations that are associated to/packaged with it". In fact, there is a book out there called exactly [*Purely Functional Data Structures*](https://books.google.com/books/about/Purely_Functional_Data_Structures.html?id=SxPzSTcTalAC&redir_esc=y)!

The book series is wonderful, but to state that the idea of packaging data and behavior together is "called data structures in formal computer science" sounded really jarring and probably wrong...

**Comment by getify** [comment]
As far as I'm aware most CS degree programs have a required course called "Data Structures" -- I took it 3 times actually -- which most definitely present the idea of data + behavior.

Also, quoting from wikipedia:

> Data structures can implement one or more particular abstract data types (ADT), which specify the operations that can be performed on a data structure and the computational complexity of those operations.

**Comment by x-ji** [comment]
I mean, I'm not disputing that for any data structures to be useful, you also have to have some operations on them. That's true, and maybe my statement that 'It just describes the data itself and shouldn't entail the "operations that are associated to/packaged with it".' is inaccurate. However, my point is that this is not something intrinsic to OOP, as that paragraph seems to suggest. You can very well separate the data and the behavior totally, just as you can do in functional programming languages such as Haskell, where you define functions in a separate place than the data. Languages such as C and recently, Rust, also don't have classes yet they can perfectly operate on data structures with mainly a `struct` construct. In fact many data structures classes are still taught in C, which clearly isn't OO. So this is where I found the paragraph a bit jarring.

This is my opinion anyways. Thanks for your prompt reply. The book is really great.

**Comment by getify** [comment]
Thanks for the discussion. I think I will leave the text as-is for now.
