### ISSUE TITLE
Type & Grammar Chapter 4: two arrays should be compared alphabetically in Abstract Relational Comparison

### ISSUE THREAD

**Issue by infinnie** [getify/You-Dont-Know-JS#972]
> Note: The algorithm is only defined for a < b. So, a > b is handled as b < a.
The algorithm first calls ToPrimitive coercion on both values, and if the return result of either call is not a string, then both values are coerced to number values using the ToNumber operation rules, and compared numerically.
> For example:
> ```js
> var a = [ 42 ];
> var b = [ "43" ];
>
> a < b;  // true
> b < a;  // false
> ```

However two arrays, though both containing only one value, should be converted to strings by the internal [[ToPrimitive()]] function.

Test:
```js
[42] > [2333]; // returns true
```

**Comment by artin-phares** [comment]
Another way to prove it's indeed alphabetical (not numerical) comparison

```javascript
var a = [ 42 ];
var b = [ "043" ]; // added zero infront

a < b; // false

**Comment by nishutosh** [comment]
yup it should be

```javascript
 var a = 42 ;
 var b = [ "043" ];

 a < b;   //true
```

**Comment by artin-phares** [comment]
@nishutosh 

Or, we can drop arrays at all.

With these conditions:
> The algorithm first calls ToPrimitive coercion on both values, and if the return result of either call is not a string, then both values are coerced to number values using the ToNumber operation rules, and compared numerically.

This should be ok:

```javascript
var a = 42;
var b = "43";

a < b;  // true
b < a;  // false
```

**Comment by getify** [comment]
This is already a known issue to be addressed in second edition. Thanks.
