### ISSUE TITLE
Types & Grammar Chapter 4: onlyOne function

### ISSUE THREAD

**Issue by ruichao-factual** [getify/You-Dont-Know-JS#977]
In << Types & Grammar>>,  `Implicitly: Booleans --> Numbers` section:
```
function onlyOne() {
    var sum = 0;
    for (var i=0; i < arguments.length; i++) {
        // skip falsy values. same as treating
        // them as 0's, but avoids NaN's.
        if (arguments[i]) {
            sum += arguments[i];
        }
    }
    return sum == 1;
}
```

It will fail when we pass truthy string or number, such as `4`, `'4'`.
I think the snippet `sum += arguments[i]` is a complicate implicitly coercion here. It will be more meaningful to the session title if we change it to `sum += !!arguments[i]`.

Ref: https://github.com/getify/You-Dont-Know-JS/issues/206

**Comment by legodude17** [comment]
It is in the `implicitly` section though.

**Comment by dlbooker** [comment]
If you step through this snippet in the chrome console, sum changes from 0 to NaN as soon as the for loop is entered and remains NaN throughout, and sum += arguments[i]; remains NaN. Yet the function call returns the correct Boolean (in fact, before you step through the function!). ???

Just after 0 assigned to sum:

![image](https://user-images.githubusercontent.com/4533542/28628263-2a7dff60-71f2-11e7-8220-bf2647748544.png)

Just after entering for loop:

![image](https://user-images.githubusercontent.com/4533542/28628362-7330bb76-71f2-11e7-978b-bdeecfd6d3fe.png)

**Comment by getify** [comment]
Why do you have that watch expression of `onlyOne(arguments)`? That seems like it could be the problem.

**Comment by getify** [comment]
It works fine in my debugging:

![debugging-onlyone](https://user-images.githubusercontent.com/150330/28629167-870e7a46-71db-11e7-945f-94aa2147c5db.gif)

**Comment by dlbooker** [comment]
It works (NaN does not appear as the value for sum) if I either close the
Watch window (even with all of the expressions as listed) or if I delete
the watch expression

sum += arguments[i]

in the Watch window and leave it open. That is the only expression that
seems to create the problem. Not sure why...


David L Booker MD FCAP
Founder and CEO, BasePath LLC *http://www.basepathllc.com/
<http://www.basepathllc.com/>*
President, Lab Med PC and ULab LLC *http://www.linkedin.com/in/dlbooker/
<http://www.linkedin.com/in/dlbooker/>*

**Comment by dlbooker** [comment]
However if you run the onlyOne() explicit coercion code you can include the
related expression

sum += Number( !!arguments[i] )


in an open Watch window and it does not create a problem. Either way,
though, the calls result in the correct Boolean.


David L Booker MD FCAP
Founder and CEO, BasePath LLC *http://www.basepathllc.com/
<http://www.basepathllc.com/>*
President, Lab Med PC and ULab LLC *http://www.linkedin.com/in/dlbooker/
<http://www.linkedin.com/in/dlbooker/>*

**Comment by getify** [comment]
Watch expressions should neber

**Comment by getify** [comment]
Watch expressions should never create side effects (ie, modify variables) unless you really want to confuse yourself.

**Comment by doubleOrt** [comment]
@getify So, this function won't work if we pass a number, nor will it work if we pass an object or an array, nor will it work when we pass a string, and yet you say that it is more elegant than the later example if we won't be passing `undefined` and `NaN` ? It works when we pass those: 
```
function onlyOne() {
    var sum = 0;
    for (var i=0; i < arguments.length; i++) {
        // skip falsy values. same as treating
        // them as 0's, but avoids NaN's.
        if (arguments[i]) {
            sum += arguments[i];
        }
    }
    return sum == 1;
}

console.log(onlyOne(undefined, true, true)); // false
console.log(onlyOne(undefined, false, true)); // true
console.log(onlyOne(undefined, false, false)); // false
console.log(onlyOne(undefined, false, false, false, false, false, true, false, NaN)); // true
```

I don't get what you mean by this comment: 
```
 // skip falsy values. same as treating
 // them as 0's, but avoids NaN's.
```
`NaN`'s are skipped, and so are falsy values.


If I am missing something obvious, you would be kind to excuse me, I often miss obvious things.
