### ISSUE TITLE
Scope & Closures: Chapter 1 / Review(TL;DR) error ref 

### ISSUE THREAD

**Issue by betasve** [getify/You-Dont-Know-JS#978]
If I'm correct in the last paragraph of `Review (TL;DR)` there's a mistaken error type. For the RHS it should be a `TypeError`, shouldn't it? 

Unfulfilled RHS references result in ~~ReferenceErrors~~ `TypeError` being thrown. Unfulfilled LHS references result in an automatic, implicitly-created global of that name (if not in "Strict Mode" [^note-strictmode]), or a ReferenceError (if in "Strict Mode" [^note-strictmode]).

**Comment by getify** [comment]
![screen shot 2017-03-03 at 7 09 11 am](https://cloud.githubusercontent.com/assets/150330/23556131/57c28d3a-ffe0-11e6-9e42-69c1047ecd54.png)

**Comment by betasve** [comment]
Oh sorry, my bad. Misunderstood the `TypeError` case.

**Comment by getify** [comment]
No worries. :)
