### ISSUE TITLE
What about branches translations?

### ISSUE THREAD

**Issue by sunfreitas** [getify/You-Dont-Know-JS#979]
I would like to translate this series to portuguese from Brazil.

**Yes, I promise I've read the [Contributions Guidelines](CONTRIBUTING.md)** (please feel free to remove this line).

**Comment by getify** [comment]
Please see these for more information: https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=label%3A%22foreign%20language%20translations%22%20
