### ISSUE TITLE
Scope & Closures: Chapter 2 Lexical Scope - possible confusing wording

### ISSUE THREAD

**Issue by knieber** [getify/You-Dont-Know-JS#981]
In Chapter 2 of Scope & Closure under the Lex-time section: it says 

```
 There are three nested scopes inherent in this code example. It may be
helpful to think about these scopes as bubbles inside of each other.
```
 
<img width="373" alt="screen shot 2017-03-10 at 9 56 39 pm" src="https://cloud.githubusercontent.com/assets/8932380/23819958/763c22f6-05dc-11e7-8125-f26879d17eb9.png">

This may be my own ignorance, but global scope isn't considered a `nested scope` correct? Therefore, shouldn't the text say something to the likes of `There are three scopes in this example (the global scope and two nested function scopes)`.

This is an incredible series and I appreciate all the hard work put into this!

**Comment by getify** [comment]
Eh. English is hard even for English speakers.

"three nested scopes" is a short-hand for "three scopes, nested", which is a short-hand for "one scope, with another nested inside it, with a third nested inside the second". The point is, the global scope is a scope, so it's one of the three in the counting (often overlooked).

I don't think this is causing sufficient confusion that it needs to be clarified. The diagram makes it unmistakably clear. Thanks for the question, though. :)
