### ISSUE TITLE
Up & Going: Transpiling- Confusing explaination of ternary operation

### ISSUE THREAD

**Issue by anurag1018** [getify/You-Dont-Know-JS#983]
```
function foo() {
    var a = arguments[0] !== (void 0) ? arguments[0] : 2;
    console.log( a );
}

```

> As you can see, it checks to see if the arguments[0] value is void 0 (aka undefined), and if so provides the 2 default value; otherwise, it assigns whatever was passed.

The explanation could confuse new learners who are not familiar with the operations of the ternary operators.

A simpler and sequential explanation could be:

The code checks to see if the the value in **NOT** undefined.

Also the order should be: 
1. Assigns whatever value was passed.
2. Otherwise provides the 2 default value

**Comment by getify** [comment]
Decent point, thanks, will fix in second edition.

**Comment by getify** [comment]
Closing since "Up & Going" was replaced with the new "Get Started" book for second edition, so this issue is no longer applicable.
