### ISSUE TITLE
Chapter 2 - This Identifier - Global Variable Error

### ISSUE THREAD

**Issue by lleeoo66** [getify/You-Dont-Know-JS#988]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

When reading the example given in this section, I realized that the function foo() is attempting to access the global variable "bar", and the value of this (in non-strict mode) is listed as "global", which is the assigned value of the variable. The value of the global "bar" (when ran through node.js) is "undefined." This was very confusing to me as a beginner. In strict mode, the function foo() does invoke a missing value error, as described.

**Comment by legodude17** [comment]
@lleeoo66 which book are you referring to?

**Comment by lleeoo66** [comment]
The first, "Up and Going." Sorry about that.

**Comment by getify** [comment]
node is not a fully clean environment to try js in... it wraps your code in modules and changes what we expect about the global object vs what seems to be global variables.

the js console is also not reliable.

the only environment you can truly predict your js in is a real js program (.js file) loaded by an html file.

**Comment by lleeoo66** [comment]
Ah, I see. I guess the fact that the book constantly advocates using the developer console threw me off. I will continue practicing in other books using the ol' natural way. 

Thanks for your timely response!

**Comment by getify** [comment]
it's regrettable for sure. if there was as easy and accessible a tool as the devconsole that actually fully and predictably works, i'd recommend it. devconsole is the best we have, and in this case does work better than node. :/
