### ISSUE TITLE
Chinese translation for this book

### ISSUE THREAD

**Issue by maoxiaoke** [getify/You-Dont-Know-JS#994]
I and my friend are going to translate your books to Chinese. We just want to publish it on GitHub for everyone. We will not publish it as print version. Can we do this job?

Hope to hear back.

**Comment by getify** [comment]
Sorry, no.u The books have already been fully translated to Chinese. See this branch:

https://github.com/getify/You-Dont-Know-JS/tree/1ed-zh-CN
