### ISSUE TITLE
ES6 & Beyond: Chapter 2 (Block-scoped Functions just in strict mode) 

### ISSUE THREAD

**Issue by Lahrachtdi** [getify/You-Dont-Know-JS#997]
**Block-scoped Functions**
Starting with ES6, function declarations that occur inside of blocks are now specified to be scoped to that block. Prior to ES6, the specification did not call for this, but many implementations did it anyway. So now the specification meets reality.

Maybe this is been changed function are block scope only in strict mode

**Comment by getify** [comment]
Nope, block-scoped functions is a tricky matter because the spec requires it but browsers violate it for compat sake (not breaking old code) and the spec "allows" this violation via annex B. Already planned to address this in second edition.
